
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_SHUJULEIXING_RG_FBROWSER_TUOYEWEIZHISHUZU_H__
#define __VCLS_RG_FBROWSER_SHUJULEIXING_RG_FBROWSER_TUOYEWEIZHISHUZU_H__

namespace rg_FBrowser_ShuJuLeiXing
{

class rg_FBrowser_TuoYeWeiZhiShuZu : public CVolObject
{
    DECLARE_VOL_CLASS (rg_FBrowser_ShuJuLeiXing, rg_FBrowser_TuoYeWeiZhiShuZu)

public:
    CefRefPtr<FBroDraggableRegion> m_data;
    inline_ rg_FBrowser_TuoYeWeiZhiShuZu (CefRefPtr<FBroDraggableRegion> object) : rg_FBrowser_TuoYeWeiZhiShuZu () { m_data = object; }
    inline_ void _CopySelfFromExtra (const rg_FBrowser_TuoYeWeiZhiShuZu& objCopyFrom) { m_data = objCopyFrom.m_data; }
    inline_ BOOL _IsSelfEqualExtra (const rg_FBrowser_TuoYeWeiZhiShuZu& objCompare) const { return (m_data.get () == objCompare.m_data.get ()); }
    inline_ BOOL_P IsEmpty () const { return m_data.get () == nullptr; }
    inline_ void Set (CefRefPtr<FBroDraggableRegion> object) { m_data = object; }
    ~rg_FBrowser_TuoYeWeiZhiShuZu(){};

public:
    inline_ rg_FBrowser_TuoYeWeiZhiShuZu () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_FBROWSER_SHUJULEIXING_RG_FBROWSER_TUOYEWEIZHISHUZU_H__
