
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_APP_MCPCLEANCACHECALLBACK_H__
#define __VCLS_RG_VOLCANO_APP_MCPCLEANCACHECALLBACK_H__

namespace rg_volcano_app
{

class MCPCleanCacheCallback : public rg_FBrowser_HuiDiao::rg_class_FBrowser_qlhchd
{
    DECLARE_VOL_CLASS (rg_volcano_app, MCPCleanCacheCallback)

public:
    virtual void rg_WanCheng (BOOL IsSuccess);
    inline_ MCPCleanCacheCallback () { }
    inline_ void _VolObjectInitMembers () { }
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

public:
    CVolString TaskID;
};

}

#endif  //__VCLS_RG_VOLCANO_APP_MCPCLEANCACHECALLBACK_H__
