
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_APP_MCPTAMPERFILTER_H__
#define __VCLS_RG_VOLCANO_APP_MCPTAMPERFILTER_H__

namespace rg_volcano_app
{

class MCPTamperFilter : public rg_FBrowser_ShiJianKongZhi::rg_class_FBrowser_zyglq
{
    DECLARE_VOL_CLASS (rg_volcano_app, MCPTamperFilter)

public:
    virtual BOOL rg_ChuShiHuaGuoLuQi (INT64 KeyID);
    virtual void rg_HuoQuShuJu (INT64 KeyID, INT64 DataPtr, INT DataSize);
    virtual INT rg_XiuGaiShuJu (INT64 KeyID, INT64 InputPtr, INT InputSize, rg_volcano_base::rg_ZhengShuLei& InputReadSize, INT64 OutputPtr, INT OutputSize, rg_volcano_base::rg_ZhengShuLei& OutputWriteSize);
    virtual void rg_JieShu1 (INT64 KeyID);
    MCPTamperFilter ();
    void _VolObjectInitMembers ();
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

public:
    CVolString Action;
    CVolString SearchText;
    CVolString ReplaceText;
    CVolString TailText;
    CVolString PendingOutputText;
    BOOL ModifyHasReleaseAbandon;
    INT RowReplaceStart;
    INT RowReplaceEnd;

protected:
    BOOL OutputPendingOutputText (INT64 OutputPtr, INT OutputSize, rg_volcano_base::rg_ZhengShuLei& OutputWriteSize);
    void ToInPassthrough (CVolString& PassthroughText, CVolString& AbandonReason);

protected:
    CVolMem TailByte;
    CVolMem RawDataCache;
    INT CurrentLineNo;
};

}

#endif  //__VCLS_RG_VOLCANO_APP_MCPTAMPERFILTER_H__
