
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_YANGWANG_RG_XXHASHSHUJUZHAIYAOLEI_N_H__
#define __VCLS_RG_VOLCANO_YANGWANG_RG_XXHASHSHUJUZHAIYAOLEI_N_H__

namespace rg_volcano_YangWang
{

class rg_XxHashShuJuZhaiYaoLei_n : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_YangWang, rg_XxHashShuJuZhaiYaoLei_n)

public:
    inline_ rg_XxHashShuJuZhaiYaoLei_n () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_YANGWANG_RG_XXHASHSHUJUZHAIYAOLEI_N_H__
