
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_BASE64BIANMAFANGSHI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_BASE64BIANMAFANGSHI_H__

namespace rg_volcano_base
{

class rg_BASE64BianMaFangShi : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_base, rg_BASE64BianMaFangShi)

public:
    inline_ rg_BASE64BianMaFangShi () { }
    inline_ void _VolObjectInitMembers () { }

public:
    static const INT rg_BiaoZhun;
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_BASE64BIANMAFANGSHI_H__
