
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_YANGWANG_RG_MD5LEI_N_H__
#define __VCLS_RG_VOLCANO_YANGWANG_RG_MD5LEI_N_H__

namespace rg_volcano_YangWang
{

class rg_MD5Lei_n : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_YangWang, rg_MD5Lei_n)

public:
    static CVolString CALLBACK rg_QuShuJuZhaiYao_n (CVolMem& rg_HuanChongOuShuJu, BOOL rg_ShiFouXiaoXie);
    static CVolString CALLBACK rg_QuShuJuZhaiYao3_n (CVolString& rg_WenJianLuJing17, BOOL rg_ShiFouXiaoXie1);
    inline_ rg_MD5Lei_n () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_YANGWANG_RG_MD5LEI_N_H__
