
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

namespace rg_volcano_app
{

BOOL CALLBACK MCPWorkflowDispatch::RequestWorkflowStop ()
{
    BOOL rg_ZhengZaiYunHang;
    WorkflowStateLock.data ().lock (FALSE);
    rg_ZhengZaiYunHang = WorkflowRun;
    if (rg_ZhengZaiYunHang)
    {
        WorkflowShouldStop = TRUE;
    }
    else
    {
        WorkflowShouldStop = FALSE;
    }
    WorkflowStateLock.data ().unlock ();
    return (rg_ZhengZaiYunHang);
}

void CALLBACK MCPWorkflowDispatch::ResetWorkflowState ()
{
    WorkflowStateLock.data ().lock (FALSE);
    WorkflowShouldStop = FALSE;
    WorkflowRun = FALSE;
    CurrentWorkflowName = _T ("");
    WorkflowStartTime = 0;
    WorkflowStateLock.data ().unlock ();
}

void CALLBACK MCPWorkflowDispatch::ForceStopTimeoutWorkflow ()
{
    CVolString rg_ChaoShiMingChen = _T ("");
    WorkflowStateLock.data ().lock (FALSE);
    if (WorkflowRun == FALSE || WorkflowStartTime == 0)
    {
        WorkflowStateLock.data ().unlock ();
        return;
    }
    if (rg_volcano_base::rg_ChangYongGongNengLei::rg_QuQiDongShiJian () - WorkflowStartTime > 1800000)
    {
        rg_ChaoShiMingChen = CurrentWorkflowName;
        WorkflowShouldStop = TRUE;
        WorkflowRun = FALSE;
        CurrentWorkflowName = _T ("");
        WorkflowStartTime = 0;
    }
    WorkflowStateLock.data ().unlock ();
    if (rg_ChaoShiMingChen != _T (""))
    {
        MCPServerTool::ConsoleOutput (CVolString (_CT2 (_T ("[MCP] 工作流运行超时, 强制终止:"))) + CVolString (rg_ChaoShiMingChen));
    }
}

CVolString CALLBACK MCPWorkflowDispatch::DispatchClassWorkflowOp (CVolString& CommandID, CVolString& MethodName, rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei& ParamJSON)
{
    if (MethodName == _T ("workflow.list") || MethodName == _T ("workflow_list"))
    {
        return (HandleWorkflowList (CommandID));
    }
    else if (MethodName == _T ("workflow.get") || MethodName == _T ("workflow_get"))
    {
        CVolString rg_GongZuoLiuMing;
        rg_GongZuoLiuMing = MCPCommandServer::YyjsonGetText (ParamJSON, _CT2 (_T ("name")));
        if (rg_GongZuoLiuMing == _T (""))
        {
            rg_GongZuoLiuMing = MCPCommandServer::YyjsonGetText (ParamJSON, _CT2 (_T ("file")));
        }
        return (HandleWorkflowGet (CommandID, rg_GongZuoLiuMing));
    }
    else if (MethodName == _T ("workflow.run") || MethodName == _T ("workflow_run"))
    {
        return (HandleWorkflowRun (CommandID, ParamJSON));
    }
    else if (MethodName == _T ("workflow.stop") || MethodName == _T ("workflow_stop"))
    {
        CVolString rg_TingZhiShiMingChen;
        BOOL rg_TingZhiShiYunHang;
        WorkflowStateLock.data ().lock (FALSE);
        rg_TingZhiShiYunHang = WorkflowRun;
        if (rg_TingZhiShiYunHang)
        {
            WorkflowShouldStop = TRUE;
            rg_TingZhiShiMingChen = CurrentWorkflowName;
        }
        else
        {
            WorkflowShouldStop = FALSE;
        }
        WorkflowStateLock.data ().unlock ();
        if (rg_TingZhiShiYunHang)
        {
            return (MCPResponseBuilder::CommandSuccess (CommandID, _CT2 (_T ("工作流停止信号已发送 | 当前运行中: ")) + rg_TingZhiShiMingChen));
        }
        return (MCPResponseBuilder::CommandSuccess (CommandID, _CT2 (_T ("没有正在运行的工作流, 无需停止"))));
    }
    return (_T (""));
}

BOOL CALLBACK MCPWorkflowDispatch::DirContainWorkflowJSON (CVolString& Dir)
{
    if (Dir == _T (""))
    {
        return (FALSE);
    }
    rg_volcano_base::rg_WenJianChaZhaoLei rg_ChaZhaoQi1;
    CVolString rg_ZhaoDaoMing1;
    rg_ZhaoDaoMing1 = rg_ChaZhaoQi1.rg_XinZhaoWenJian (Dir + _T ("\\*.json"), -1, FILE_ATTRIBUTE_DIRECTORY);
    return (rg_ZhaoDaoMing1 != _T (""));
}

CVolString CALLBACK MCPWorkflowDispatch::ReadInWorkflowJSONText (CVolString& FilePath)
{
    if (FilePath == _T (""))
    {
        return (_T (""));
    }
    CVolMem rg_WenJianZiJie2;
    rg_WenJianZiJie2 = rg_volcano_base::rg_CiPanCaoZuoLei::rg_DouRuWenJian (FilePath, -1);
    if ((INT)rg_WenJianZiJie2.GetSize () == 0)
    {
        return (_T (""));
    }
    return (rg_volcano_base::rg_WenBenLei::rg_UTF8DaoWenBen (rg_WenJianZiJie2));
}

rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouShuZuLei CALLBACK MCPWorkflowDispatch::FromDefinitionObjectGetStepArray (rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei& DefinitionObject)
{
    if (yyjson_is_null(DefinitionObject.data().GetObject()))
    {
        rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouShuZuLei rg_KongShuZu1;
        return (rg_KongShuZu1);
    }
    return (ParseStepArrayParam (DefinitionObject));
}

CVolString CALLBACK MCPWorkflowDispatch::GetWorkflowDir ()
{
    if (WorkflowDirCache != _T (""))
    {
        return (WorkflowDirCache);
    }
    CVolString rg_HuanJingMuLu;
    rg_HuanJingMuLu = CVolString (_tgetenv (_CT2 (_T ("AI_BROWSER_WORKFLOWS_DIR")).GetText ()));
    if (rg_HuanJingMuLu != _T ("") && DirContainWorkflowJSON (rg_HuanJingMuLu))
    {
        WorkflowDirCache = rg_HuanJingMuLu;
        return (WorkflowDirCache);
    }
    CVolString rg_YunHangMuLu1;
    rg_YunHangMuLu1 = rg_volcano_base::rg_HuanJingCunQuLei::rg_QuYunHangMuLu ();
    CVolString rg_HouXuan2;
    rg_HouXuan2 = rg_YunHangMuLu1 + _T ("\\workflows");
    if (DirContainWorkflowJSON (rg_HouXuan2))
    {
        WorkflowDirCache = rg_HouXuan2;
        return (WorkflowDirCache);
    }
    CVolString rg_HouXuan3;
    rg_HouXuan3 = rg_YunHangMuLu1 + _T ("\\..\\..\\..\\..\\..\\workflows");
    if (DirContainWorkflowJSON (rg_HouXuan3))
    {
        WorkflowDirCache = rg_HouXuan3;
        return (WorkflowDirCache);
    }
    CVolString rg_HouXuan4;
    rg_HouXuan4 = rg_YunHangMuLu1 + _T ("\\..\\workflows");
    if (DirContainWorkflowJSON (rg_HouXuan4))
    {
        WorkflowDirCache = rg_HouXuan4;
        return (WorkflowDirCache);
    }
    WorkflowDirCache = rg_HouXuan2;
    return (WorkflowDirCache);
}

CVolString CALLBACK MCPWorkflowDispatch::NormalizeWorkflowName (CVolString& RawName)
{
    CVolString rg_Ming4;
    rg_Ming4 = CVolString (RawName).TrimAll ();
    if (rg_Ming4 == _T (""))
    {
        return (_T (""));
    }
    rg_Ming4 = CVolString (GetOSFileNameWithoutPath (rg_Ming4.GetText ()));
    if (rg_Ming4.Right (5) == _T (".json"))
    {
        rg_Ming4 = rg_Ming4.Left ((INT)rg_Ming4.GetLength () - 5);
    }
    if ((INT)rg_Ming4.SearchText (_CT2 (_T ("..")).GetText (), 0, FALSE, FALSE) != -1 || (INT)rg_Ming4.SearchText (_CT2 (_T ("\\")).GetText (), 0, FALSE, FALSE) != -1 || (INT)rg_Ming4.SearchText (_CT2 (_T ("/")).GetText (), 0, FALSE, FALSE) != -1 || (INT)rg_Ming4.SearchText (_CT2 (_T (":")).GetText (), 0, FALSE, FALSE) != -1)
    {
        return (_T (""));
    }
    return (rg_Ming4);
}

CVolString CALLBACK MCPWorkflowDispatch::HandleWorkflowList (CVolString& CommandID)
{
    CVolString rg_MuLu;
    rg_MuLu = GetWorkflowDir ();
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONDuiXiangLei rg_LieBiaoDuiXiang;
    rg_LieBiaoDuiXiang.data().CreateFromText(_CT2 (_T ("{}")));
    rg_volcano_base::rg_WenBenShuZuLei rg_MingChenShuZu;
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONShuZuLei rg_GongZuoLiuShuZu;
    rg_GongZuoLiuShuZu.rg_ChuangJianZiWenBenShuJu (MCPCommandServer::GetEmptyTextArray ());
    rg_volcano_base::rg_WenJianChaZhaoLei rg_ChaZhaoQi2;
    CVolString rg_TongPei;
    rg_TongPei = rg_MuLu + _T ("\\*.json");
    CVolString rg_ZhaoDaoMing2;
    rg_ZhaoDaoMing2 = rg_ChaZhaoQi2.rg_XinZhaoWenJian (rg_TongPei, -1, FILE_ATTRIBUTE_DIRECTORY);
    while (rg_ZhaoDaoMing2 != _T (""))
    {
        if (rg_ZhaoDaoMing2.Right (5) == _T (".json"))
        {
            rg_MingChenShuZu.data ().Add4 (NUM_CHARS_OF_TEXT ("S"), (rg_ZhaoDaoMing2.Left ((INT)rg_ZhaoDaoMing2.GetLength () - 5)).GetText ());
        }
        rg_ZhaoDaoMing2 = rg_ChaZhaoQi2.rg_XinZhaoWenJian (_CT2 (_T ("")), -1, FILE_ATTRIBUTE_DIRECTORY);
    }
    INT rg_idx8;
    for (INT_P __vol_counter_index = 0; __vol_counter_index < (INT)rg_MingChenShuZu.data ().GetCount (); __vol_counter_index++)
    {
        rg_idx8 = (INT)__vol_counter_index;
        rg_GongZuoLiuShuZu.rg_JiaRuWenBenChengYuan1 (CVolString (rg_MingChenShuZu.data ().GetAt (rg_idx8)));
    }
    rg_LieBiaoDuiXiang.rg_JiaRuShuZuChengYuan (_CT2 (_T ("workflows")), rg_GongZuoLiuShuZu, FALSE);
    rg_LieBiaoDuiXiang.rg_JiaRuZhengShuChengYuan (_CT2 (_T ("count")), (INT)rg_MingChenShuZu.data ().GetCount ());
    rg_LieBiaoDuiXiang.rg_JiaRuWenBenChengYuan (_CT2 (_T ("directory")), rg_MuLu);
    return (MCPResponseBuilder::CommandSuccessRawJSON (CommandID, rg_LieBiaoDuiXiang.data().ToString(YYJSON_WRITE_NOFLAG), TRUE));
}

CVolString CALLBACK MCPWorkflowDispatch::HandleWorkflowGet (CVolString& CommandID, CVolString& WorkflowName)
{
    CVolString rg_AnQuanMing;
    rg_AnQuanMing = NormalizeWorkflowName (WorkflowName);
    if (rg_AnQuanMing == _T (""))
    {
        return (MCPResponseBuilder::CommandFailure (CommandID, _CT2 (_T ("无效工作流名"))));
    }
    CVolString rg_WenJianLuJing2;
    rg_WenJianLuJing2 = GetWorkflowDir () + _T ("\\") + rg_AnQuanMing + _T (".json");
    CVolString rg_JSONWenBen2;
    rg_JSONWenBen2 = ReadInWorkflowJSONText (rg_WenJianLuJing2);
    if (rg_JSONWenBen2 == _T (""))
    {
        return (MCPResponseBuilder::CommandFailure (CommandID, _CT2 (_T ("工作流不存在: ")) + rg_AnQuanMing + _T (" | 建议: 先用 workflow_list 列出可用工作流名(不含 .json 后缀)")));
    }
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei rg_JiaoYan;
    if (rg_JiaoYan.data().CreateFromText(rg_JSONWenBen2) == FALSE)
    {
        return (MCPResponseBuilder::CommandFailure (CommandID, _CT2 (_T ("工作流 JSON 无效: ")) + rg_AnQuanMing));
    }
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONDuiXiangLei rg_BaoZhuang8;
    rg_BaoZhuang8.data().CreateFromText(_CT2 (_T ("{}")));
    rg_BaoZhuang8.rg_JiaRuWenBenChengYuan (_CT2 (_T ("name")), rg_AnQuanMing);
    rg_BaoZhuang8.rg_JiaRuWenBenChengYuan (_CT2 (_T ("definition")), rg_JSONWenBen2);
    return (MCPResponseBuilder::CommandSuccessRawJSON (CommandID, rg_BaoZhuang8.data().ToString(YYJSON_WRITE_NOFLAG), TRUE));
}

CVolString CALLBACK MCPWorkflowDispatch::LoadWorkflowDefinition (rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei& ParamJSON)
{
    CVolString rg_GongZuoLiuMing1;
    rg_GongZuoLiuMing1 = MCPCommandServer::YyjsonGetText (ParamJSON, _CT2 (_T ("name")));
    if (rg_GongZuoLiuMing1 == _T (""))
    {
        rg_GongZuoLiuMing1 = MCPCommandServer::YyjsonGetText (ParamJSON, _CT2 (_T ("file")));
    }
    CVolString rg_AnQuanMing1;
    rg_AnQuanMing1 = NormalizeWorkflowName (rg_GongZuoLiuMing1);
    if (rg_AnQuanMing1 != _T (""))
    {
        CVolString rg_WenJianLuJing3;
        rg_WenJianLuJing3 = GetWorkflowDir () + _T ("\\") + rg_AnQuanMing1 + _T (".json");
        CVolString rg_WenJianWenBen;
        rg_WenJianWenBen = ReadInWorkflowJSONText (rg_WenJianLuJing3);
        if (rg_WenJianWenBen != _T (""))
        {
            return (rg_WenJianWenBen);
        }
    }
    CVolString rg_DingYiWenBen;
    rg_DingYiWenBen = MCPCommandServer::YyjsonGetText (ParamJSON, _CT2 (_T ("definition")));
    if (rg_DingYiWenBen != _T (""))
    {
        return (rg_DingYiWenBen);
    }
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei rg_defObj;
    rg_defObj = ParamJSON.rg_QuDuiXiang2 (_CT2 (_T ("definition")));
    if (yyjson_is_null(rg_defObj.data().GetObject()) == FALSE && (INT)yyjson_obj_size(rg_defObj.data().GetObject()) > 0)
    {
        return (rg_defObj.data().ToString(YYJSON_WRITE_NOFLAG));
    }
    return (_T (""));
}

CVolString CALLBACK MCPWorkflowDispatch::FromResultExtractTaskID (CVolString& ResultJSON)
{
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei rg_JieXi8;
    if (rg_JieXi8.data().CreateFromText(ResultJSON) == FALSE)
    {
        return (_T (""));
    }
    CVolString rg_taskID1;
    rg_taskID1 = MCPCommandServer::YyjsonGetText (rg_JieXi8, _CT2 (_T ("task_id")));
    if (rg_taskID1 != _T (""))
    {
        return (rg_taskID1);
    }
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei rg_dataObj1;
    rg_dataObj1 = MCPCommandServer::YyjsonGetObjectMember (rg_JieXi8, _CT2 (_T ("data")));
    if (yyjson_is_null(rg_dataObj1.data().GetObject()) == FALSE)
    {
        rg_taskID1 = MCPCommandServer::YyjsonGetText (rg_dataObj1, _CT2 (_T ("task_id")));
        if (rg_taskID1 != _T (""))
        {
            return (rg_taskID1);
        }
    }
    CVolString rg_XiaoXi;
    rg_XiaoXi = MCPCommandServer::YyjsonGetText (rg_JieXi8, _CT2 (_T ("message")));
    CVolString rg_QianZhui3;
    rg_QianZhui3 = _T ("task_id=");
    INT rg_pos;
    rg_pos = (INT)rg_XiaoXi.SearchText (rg_QianZhui3.GetText (), 0, FALSE, FALSE);
    if (rg_pos != -1)
    {
        INT rg_QianZhuiChang1;
        rg_QianZhuiChang1 = (INT)rg_QianZhui3.GetLength ();
        INT rg_ShengYuChang;
        rg_ShengYuChang = (INT)rg_XiaoXi.GetLength () - rg_pos - rg_QianZhuiChang1;
        if (rg_ShengYuChang <= 0)
        {
            return (_T (""));
        }
        INT rg_DiQuChang;
        rg_DiQuChang = rg_ShengYuChang;
        if (rg_DiQuChang > 256)
        {
            rg_DiQuChang = 256;
        }
        CVolString rg_YuanShiDiQu;
        rg_YuanShiDiQu = rg_XiaoXi.Middle ((rg_pos + rg_QianZhuiChang1), rg_DiQuChang);
        INT rg_BianJie;
        rg_BianJie = (INT)rg_YuanShiDiQu.SearchText (_CT2 (_T (" ")).GetText (), 0, FALSE, FALSE);
        if (rg_BianJie == -1)
        {
            rg_BianJie = (INT)rg_YuanShiDiQu.SearchText (_CT2 (_T ("\"")).GetText (), 0, FALSE, FALSE);
        }
        if (rg_BianJie > 0)
        {
            return (rg_YuanShiDiQu.Left (rg_BianJie));
        }
        return (rg_YuanShiDiQu);
    }
    rg_pos = (INT)ResultJSON.SearchText (_CT2 (_T ("task_")).GetText (), 0, FALSE, FALSE);
    if (rg_pos != -1)
    {
        INT rg_JSONShengYu;
        rg_JSONShengYu = (INT)ResultJSON.GetLength () - rg_pos;
        INT rg_PianDuanChang;
        rg_PianDuanChang = 80;
        if (rg_JSONShengYu < rg_PianDuanChang)
        {
            rg_PianDuanChang = rg_JSONShengYu;
        }
        CVolString rg_PianDuan;
        rg_PianDuan = ResultJSON.Middle (rg_pos, rg_PianDuanChang);
        INT rg_JieShu2;
        rg_JieShu2 = (INT)rg_PianDuan.SearchText (_CT2 (_T ("\"")).GetText (), 0, FALSE, FALSE);
        if (rg_JieShu2 == -1)
        {
            rg_JieShu2 = (INT)rg_PianDuan.SearchText (_CT2 (_T (" ")).GetText (), 0, FALSE, FALSE);
        }
        CVolString rg_HouXuanID;
        if (rg_JieShu2 == -1)
        {
            rg_HouXuanID = rg_PianDuan;
        }
        else
        {
            rg_HouXuanID = rg_PianDuan.Left (rg_JieShu2);
        }
        if (MCPCommandServer::IsBy (rg_HouXuanID, _CT2 (_T ("task_"))) && (INT)rg_HouXuanID.GetLength () >= 20 && (INT)rg_HouXuanID.GetLength () <= 64)
        {
            BOOL rg_idValid = TRUE;
            static CVolString rg_idAllowed = _T ("0123456789_");
            CVolString rg_HouZhui;
            rg_HouZhui = rg_HouXuanID.Right ((INT)rg_HouXuanID.GetLength () - 5);
            INT rg_idLen;
            rg_idLen = (INT)rg_HouZhui.GetLength ();
            for (INT_P __vol_counter_index = 0; __vol_counter_index < rg_idLen; __vol_counter_index++)
            {
                CVolString rg_ch;
                rg_ch = rg_HouZhui.Middle ((INT)__vol_counter_index, 1);
                if ((INT)rg_idAllowed.SearchText (rg_ch.GetText (), 0, FALSE, FALSE) == -1)
                {
                    rg_idValid = FALSE;
                    break;
                }
            }
            if (rg_idValid)
            {
                return (rg_HouXuanID);
            }
        }
    }
    return (_T (""));
}

CVolString CALLBACK MCPWorkflowDispatch::WaitStepAsyncDone (CVolString& TaskID, INT MaxMs, CVolString& WorkflowCommandID, CVolString& ToolName)
{
    if (TaskID == _T (""))
    {
        return (MCPResponseBuilder::BuildStandardFailureJSON (_CT2 (_T ("缺少 task_id"))));
    }
    WorkflowStateLock.data ().lock (FALSE);
    BOOL rg_DengDaiYingTingZhi;
    rg_DengDaiYingTingZhi = WorkflowShouldStop;
    WorkflowStateLock.data ().unlock ();
    if (rg_DengDaiYingTingZhi)
    {
        return (MCPResponseBuilder::BuildStandardFailureJSON (_CT2 (_T ("工作流已停止"))));
    }
    if (MCPCommandServer::MCPIsClose)
    {
        return (MCPResponseBuilder::BuildStandardFailureJSON (_CT2 (_T ("MCP 正在关闭"))));
    }
    INT64 rg_KaiShi4;
    rg_KaiShi4 = rg_volcano_base::rg_ChangYongGongNengLei::rg_QuQiDongShiJian ();
    CVolString rg_CunChuJieGuo5;
    MCPCommandServer::MCPExecuteLock.data ().unlock ();
    rg_CunChuJieGuo5 = MCPCommandServer::WaitAsyncTaskDone (TaskID, MaxMs, WorkflowCommandID, ToolName, 50);
    MCPCommandServer::MCPExecuteLock.data ().lock (FALSE);
    if (rg_CunChuJieGuo5 == _T (""))
    {
        if (MCPCommandServer::MCPIsClose)
        {
            return (MCPResponseBuilder::BuildStandardFailureJSON (_CT2 (_T ("MCP 服务正在关闭"))));
        }
        return (MCPResponseBuilder::BuildStandardFailureJSON (_CT2 (_T ("步骤异步超时(")) + CVolString (MaxMs) + _T ("ms), task_id=") + TaskID));
    }
    CVolString rg_ShiJiGongJu;
    rg_ShiJiGongJu = ToolName;
    if (rg_ShiJiGongJu == _T (""))
    {
        rg_ShiJiGongJu = MCPCommandServer::CurrentCommandMethodName;
    }
    return (MCPCommandServer::ConvertAsyncResultToCommandResponse (WorkflowCommandID + _T ("_w"), rg_CunChuJieGuo5, MCPCommandServer::GetToolResultKeyName (rg_ShiJiGongJu), (INT)(rg_volcano_base::rg_ChangYongGongNengLei::rg_QuQiDongShiJian () - rg_KaiShi4), rg_ShiJiGongJu));
}

CVolString CALLBACK MCPWorkflowDispatch::StepJSONFragmentListToArrayText (rg_volcano_base::rg_WenBenShuZuLei& FragmentList)
{
    if ((INT)FragmentList.data ().GetCount () == 0)
    {
        return (_T ("[]"));
    }
    CVolString rg_JieGuo16;
    rg_JieGuo16 = _T ("[");
    INT rg_idx9;
    for (INT_P __vol_counter_index = 0; __vol_counter_index < (INT)FragmentList.data ().GetCount (); __vol_counter_index++)
    {
        rg_idx9 = (INT)__vol_counter_index;
        if (rg_idx9 > 0)
        {
            rg_JieGuo16 = rg_JieGuo16 + _T (",");
        }
        rg_JieGuo16 = rg_JieGuo16 + CVolString (FragmentList.data ().GetAt (rg_idx9));
    }
    rg_JieGuo16 = rg_JieGuo16 + _T ("]");
    return (rg_JieGuo16);
}

void CALLBACK MCPWorkflowDispatch::AppendStepStructureFailureRecord (rg_volcano_base::rg_WenBenShuZuLei& StepResultJSONList, INT StepIndex, CVolString& ToolName, CVolString& ErrorMessage)
{
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONDuiXiangLei rg_BuJiLu;
    rg_BuJiLu.data().CreateFromText(_CT2 (_T ("{}")));
    rg_BuJiLu.rg_JiaRuZhengShuChengYuan (_CT2 (_T ("index")), StepIndex + 1);
    rg_BuJiLu.rg_JiaRuWenBenChengYuan (_CT2 (_T ("tool")), ToolName);
    rg_BuJiLu.rg_JiaRuLuoJiZhiChengYuan (_CT2 (_T ("success")), FALSE);
    rg_BuJiLu.rg_JiaRuWenBenChengYuan (_CT2 (_T ("error")), ErrorMessage);
    rg_BuJiLu.rg_JiaRuWenBenChengYuan (_CT2 (_T ("result")), MCPResponseBuilder::BuildStandardFailureJSON (ErrorMessage));
    StepResultJSONList.data ().Add4 (NUM_CHARS_OF_TEXT ("S"), (rg_BuJiLu.data().ToString(YYJSON_WRITE_NOFLAG)).GetText ());
}

CVolString CALLBACK MCPWorkflowDispatch::ExecuteWorkflowStep (CVolString& CommandID, rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei& Step, INT StepIndex, CVolString& GlobalOnError, rg_volcano_base::rg_WenBenShuZuLei& StepResultJSONList)
{
    if (yyjson_is_null(Step.data().GetObject()))
    {
        AppendStepStructureFailureRecord (StepResultJSONList, StepIndex, _CT2 (_T ("")), _CT2 (_T ("空步骤对象")));
        return (_T ("fail"));
    }
    if (MCPCommandServer::YyjsonGetLogic (Step, _CT2 (_T ("skip"))))
    {
        rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONDuiXiangLei rg_TiaoGuoJiLu;
        rg_TiaoGuoJiLu.data().CreateFromText(_CT2 (_T ("{}")));
        rg_TiaoGuoJiLu.rg_JiaRuZhengShuChengYuan (_CT2 (_T ("index")), StepIndex + 1);
        rg_TiaoGuoJiLu.rg_JiaRuWenBenChengYuan (_CT2 (_T ("tool")), _CT2 (_T ("")));
        rg_TiaoGuoJiLu.rg_JiaRuLuoJiZhiChengYuan (_CT2 (_T ("success")), TRUE);
        rg_TiaoGuoJiLu.rg_JiaRuLuoJiZhiChengYuan (_CT2 (_T ("skipped")), TRUE);
        StepResultJSONList.data ().Add4 (NUM_CHARS_OF_TEXT ("S"), (rg_TiaoGuoJiLu.data().ToString(YYJSON_WRITE_NOFLAG)).GetText ());
        return (_T ("skip"));
    }
    INT rg_YanShiHaoMiao;
    rg_YanShiHaoMiao = MCPCommandServer::YyjsonGetInt (Step, _CT2 (_T ("delay_ms")));
    if (rg_YanShiHaoMiao < 0)
    {
        rg_YanShiHaoMiao = 0;
    }
    if (rg_YanShiHaoMiao > 30000)
    {
        rg_YanShiHaoMiao = 30000;
    }
    if (rg_YanShiHaoMiao > 0)
    {
        MCPCommandServer::MCPCanInterruptDelay (rg_YanShiHaoMiao, 50, TRUE);
        rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONDuiXiangLei rg_YanShiJiLu;
        rg_YanShiJiLu.data().CreateFromText(_CT2 (_T ("{}")));
        rg_YanShiJiLu.rg_JiaRuZhengShuChengYuan (_CT2 (_T ("index")), StepIndex + 1);
        rg_YanShiJiLu.rg_JiaRuWenBenChengYuan (_CT2 (_T ("tool")), _CT2 (_T ("")));
        rg_YanShiJiLu.rg_JiaRuLuoJiZhiChengYuan (_CT2 (_T ("success")), TRUE);
        rg_YanShiJiLu.rg_JiaRuLuoJiZhiChengYuan (_CT2 (_T ("delayed")), TRUE);
        rg_YanShiJiLu.rg_JiaRuZhengShuChengYuan (_CT2 (_T ("delay_ms")), rg_YanShiHaoMiao);
        StepResultJSONList.data ().Add4 (NUM_CHARS_OF_TEXT ("S"), (rg_YanShiJiLu.data().ToString(YYJSON_WRITE_NOFLAG)).GetText ());
        return (_T ("delay"));
    }
    CVolString rg_GongJuMing1;
    rg_GongJuMing1 = MCPCommandServer::YyjsonGetText (Step, _CT2 (_T ("tool")));
    if (rg_GongJuMing1 == _T (""))
    {
        rg_GongJuMing1 = MCPCommandServer::YyjsonGetText (Step, _CT2 (_T ("name")));
    }
    if (rg_GongJuMing1 == _T (""))
    {
        AppendStepStructureFailureRecord (StepResultJSONList, StepIndex, _CT2 (_T ("")), _CT2 (_T ("缺少 tool/name 字段")));
        return (_T ("fail"));
    }
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei rg_GongJuCanShu;
    rg_GongJuCanShu = MCPCommandServer::YyjsonGetObjectMember (Step, _CT2 (_T ("args")));
    if (yyjson_is_null(rg_GongJuCanShu.data().GetObject()))
    {
        rg_GongJuCanShu = MCPCommandServer::YyjsonGetObjectMember (Step, _CT2 (_T ("arguments")));
    }
    if (yyjson_is_null(rg_GongJuCanShu.data().GetObject()))
    {
        rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei rg_KongCanShu;
        rg_KongCanShu.data().CreateFromText(_CT2 (_T ("{}")));
        rg_GongJuCanShu = rg_KongCanShu;
    }
    CVolString rg_BuJieGuo;
    MCPCommandServer::MCPExecuteLock.data ().unlock ();
    rg_BuJieGuo = MCPCommandServer::ExecuteBrowserCommand (CommandID + _T ("_s") + CVolString (StepIndex), rg_GongJuMing1, rg_GongJuCanShu);
    MCPCommandServer::MCPExecuteLock.data ().lock (FALSE);
    BOOL rg_XuDengDai;
    rg_XuDengDai = MCPCommandServer::YyjsonGetLogic (Step, _CT2 (_T ("wait_async")));
    if (rg_XuDengDai == FALSE && (INT)rg_BuJieGuo.SearchText (_CT2 (_T ("task_")).GetText (), 0, FALSE, FALSE) != -1)
    {
        rg_XuDengDai = TRUE;
    }
    if (rg_XuDengDai)
    {
        CVolString rg_YiBuID4;
        rg_YiBuID4 = FromResultExtractTaskID (rg_BuJieGuo);
        if (rg_YiBuID4 != _T (""))
        {
            INT rg_ZuiDaDengDai;
            rg_ZuiDaDengDai = MCPCommandServer::YyjsonGetInt (Step, _CT2 (_T ("max_ms")));
            if (rg_ZuiDaDengDai <= 0)
            {
                rg_ZuiDaDengDai = 15000;
            }
            if (rg_ZuiDaDengDai > 300000)
            {
                rg_ZuiDaDengDai = 300000;
            }
            rg_BuJieGuo = WaitStepAsyncDone (rg_YiBuID4, rg_ZuiDaDengDai, CommandID, rg_GongJuMing1);
        }
    }
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei rg_BuJieXi;
    BOOL rg_BuChengGong = FALSE;
    if (rg_BuJieXi.data().CreateFromText(rg_BuJieGuo))
    {
        rg_BuChengGong = yyjson_get_bool(yyjson_obj_get(rg_BuJieXi.data().GetObject(), (const char *)CU8String(_CT2 (_T ("success")).GetText()).GetText()));
    }
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONDuiXiangLei rg_BuJiLu1;
    rg_BuJiLu1.data().CreateFromText(_CT2 (_T ("{}")));
    rg_BuJiLu1.rg_JiaRuZhengShuChengYuan (_CT2 (_T ("index")), StepIndex + 1);
    rg_BuJiLu1.rg_JiaRuWenBenChengYuan (_CT2 (_T ("tool")), rg_GongJuMing1);
    rg_BuJiLu1.rg_JiaRuLuoJiZhiChengYuan (_CT2 (_T ("success")), rg_BuChengGong);
    rg_BuJiLu1.rg_JiaRuWenBenChengYuan (_CT2 (_T ("result")), rg_BuJieGuo);
    StepResultJSONList.data ().Add4 (NUM_CHARS_OF_TEXT ("S"), (rg_BuJiLu1.data().ToString(YYJSON_WRITE_NOFLAG)).GetText ());
    if (rg_BuChengGong)
    {
        return (_T ("ok"));
    }
    CVolString rg_BuonError;
    rg_BuonError = MCPCommandServer::YyjsonGetText (Step, _CT2 (_T ("on_error")));
    if (rg_BuonError == _T (""))
    {
        rg_BuonError = GlobalOnError;
    }
    if (rg_BuonError == _T ("stop"))
    {
        return (_T ("fail_stop"));
    }
    return (_T ("fail"));
}

BOOL CALLBACK MCPWorkflowDispatch::StepArrayInvalid (rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouShuZuLei& StepArray)
{
    return ((BOOL)StepArray.IsNullObject () || yyjson_arr_size(StepArray.data().GetArray()) == 0);
}

rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouShuZuLei CALLBACK MCPWorkflowDispatch::ParseStepArrayParam (rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei& ParamJSON)
{
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouShuZuLei rg_KongShuZu2;
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouShuZuLei rg_BuZhouShuZu;
    rg_BuZhouShuZu = ParamJSON.rg_QuLuJingShuZu (_CT2 (_T ("/steps")));
    if (StepArrayInvalid (rg_BuZhouShuZu) == FALSE)
    {
        return (rg_BuZhouShuZu);
    }
    rg_BuZhouShuZu = ParamJSON.rg_QuShuZu1 (_CT2 (_T ("steps")));
    if (StepArrayInvalid (rg_BuZhouShuZu) == FALSE)
    {
        return (rg_BuZhouShuZu);
    }
    CVolString rg_stepsJSONWenBen;
    rg_stepsJSONWenBen = MCPCommandServer::YyjsonGetJSONText (ParamJSON, _CT2 (_T ("steps")));
    if (rg_stepsJSONWenBen != _T ("") && MCPCommandServer::IsBy (CVolString (rg_stepsJSONWenBen).TrimLeft (), _CT2 (_T ("["))))
    {
        rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei rg_stepsBaoZhuang;
        if (rg_stepsBaoZhuang.data().CreateFromText(_CT2 (_T ("{\"steps\":")) + rg_stepsJSONWenBen + _T ("}")))
        {
            rg_BuZhouShuZu = rg_stepsBaoZhuang.rg_QuLuJingShuZu (_CT2 (_T ("/steps")));
            if (StepArrayInvalid (rg_BuZhouShuZu) == FALSE)
            {
                return (rg_BuZhouShuZu);
            }
            rg_BuZhouShuZu = rg_stepsBaoZhuang.rg_QuShuZu1 (_CT2 (_T ("steps")));
            if (StepArrayInvalid (rg_BuZhouShuZu) == FALSE)
            {
                return (rg_BuZhouShuZu);
            }
        }
    }
    return (rg_KongShuZu2);
}

CVolString CALLBACK MCPWorkflowDispatch::HandleWorkflowRun (CVolString& CommandID, rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei& ParamJSON)
{
    ForceStopTimeoutWorkflow ();
    WorkflowStateLock.data ().lock (FALSE);
    BOOL rg_YiYouYunHang;
    rg_YiYouYunHang = WorkflowRun;
    WorkflowStateLock.data ().unlock ();
    if (rg_YiYouYunHang)
    {
        return (MCPResponseBuilder::CommandFailure (CommandID, _CT2 (_T ("已有工作流正在运行, 请 workflow_stop 或等待超时(")) + CVolString (1800000 / 60000) + _T ("分钟)后重试")));
    }
    if (MCPCommandServer::MCPIsClose)
    {
        return (MCPResponseBuilder::CommandFailure (CommandID, _CT2 (_T ("MCP 服务正在关闭, 无法运行工作流"))));
    }
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei rg_DingYi;
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouShuZuLei rg_BuZhouShuZu1;
    rg_BuZhouShuZu1 = ParseStepArrayParam (ParamJSON);
    CVolString rg_QuanJuonError;
    rg_QuanJuonError = MCPCommandServer::YyjsonGetText (ParamJSON, _CT2 (_T ("on_error")));
    if (rg_QuanJuonError == _T (""))
    {
        rg_QuanJuonError = _T ("stop");
    }
    CVolString rg_GongZuoLiuMing2;
    rg_GongZuoLiuMing2 = MCPCommandServer::YyjsonGetText (ParamJSON, _CT2 (_T ("name")));
    if (rg_GongZuoLiuMing2 == _T (""))
    {
        rg_GongZuoLiuMing2 = _T ("inline");
    }
    if (StepArrayInvalid (rg_BuZhouShuZu1))
    {
        CVolString rg_DingYiWenBen1;
        rg_DingYiWenBen1 = LoadWorkflowDefinition (ParamJSON);
        if (rg_DingYiWenBen1 == _T (""))
        {
            return (MCPResponseBuilder::CommandFailure (CommandID, _CT2 (_T ("需要 name/file、definition 或 steps 参数"))));
        }
        rg_DingYiWenBen1 = CVolString (rg_DingYiWenBen1).TrimAll ();
        if (rg_DingYi.data().CreateFromText(rg_DingYiWenBen1) == FALSE)
        {
            return (MCPResponseBuilder::CommandFailure (CommandID, _CT2 (_T ("工作流 JSON 解析失败"))));
        }
        rg_BuZhouShuZu1 = FromDefinitionObjectGetStepArray (rg_DingYi);
        CVolString rg_WenJianonError;
        rg_WenJianonError = MCPCommandServer::YyjsonGetText (rg_DingYi, _CT2 (_T ("on_error")));
        if (rg_WenJianonError != _T (""))
        {
            rg_QuanJuonError = rg_WenJianonError;
        }
        CVolString rg_WenJianMing1;
        rg_WenJianMing1 = MCPCommandServer::YyjsonGetText (rg_DingYi, _CT2 (_T ("name")));
        if (rg_WenJianMing1 != _T (""))
        {
            rg_GongZuoLiuMing2 = rg_WenJianMing1;
        }
    }
    if (StepArrayInvalid (rg_BuZhouShuZu1))
    {
        return (MCPResponseBuilder::CommandFailure (CommandID, _CT2 (_T ("工作流缺少 steps 数组 | steps 须为 JSON 数组, 每项形如 {\"tool\":\"browser_navigate\",\"args\":{\"url\":\"https://example.com\"}} | 也可用 name 指向 workflows 目录下的工作流文件"))));
    }
    WorkflowStateLock.data ().lock (FALSE);
    WorkflowShouldStop = FALSE;
    WorkflowRun = TRUE;
    CurrentWorkflowName = rg_GongZuoLiuMing2;
    WorkflowStartTime = rg_volcano_base::rg_ChangYongGongNengLei::rg_QuQiDongShiJian ();
    WorkflowStateLock.data ().unlock ();
    INT rg_ZongBuShu;
    rg_ZongBuShu = (INT)yyjson_arr_size(rg_BuZhouShuZu1.data().GetArray());
    INT rg_ChengGongShu = 0;
    INT rg_ShiBaiShu = 0;
    INT rg_TiaoGuoShu = 0;
    INT rg_YanShiShu = 0;
    rg_volcano_base::rg_WenBenShuZuLei rg_BuZhouJieGuoJSONLieBiao;
    for (INT_P __vol_counter_index = 0; __vol_counter_index < rg_ZongBuShu; __vol_counter_index++)
    {
        BOOL rg_BuChaoShi = FALSE;
        CVolString rg_BuChaoShiMing = _T ("");
        BOOL rg_BuYingTingZhi;
        WorkflowStateLock.data ().lock (FALSE);
        if (WorkflowStartTime > 0 && rg_volcano_base::rg_ChangYongGongNengLei::rg_QuQiDongShiJian () - WorkflowStartTime > 1800000)
        {
            rg_BuChaoShi = TRUE;
            rg_BuChaoShiMing = CurrentWorkflowName;
            WorkflowShouldStop = TRUE;
        }
        rg_BuYingTingZhi = WorkflowShouldStop;
        WorkflowStateLock.data ().unlock ();
        if (rg_BuChaoShi)
        {
            MCPServerTool::ConsoleOutput (CVolString (_CT2 (_T ("[MCP] 工作流运行超时, 强制终止:"))) + CVolString (rg_BuChaoShiMing));
        }
        if (rg_BuYingTingZhi)
        {
            break;
        }
        INT rg_BuSuoYin;
        rg_BuSuoYin = (INT)__vol_counter_index;
        rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei rg_BuZhou;
        rg_BuZhou = rg_BuZhouShuZu1.rg_QuChengYuan55 (rg_BuSuoYin);
        CVolString rg_ChanBuJieGuo;
        rg_ChanBuJieGuo = ExecuteWorkflowStep (CommandID, rg_BuZhou, rg_BuSuoYin, rg_QuanJuonError, rg_BuZhouJieGuoJSONLieBiao);
        if (rg_ChanBuJieGuo == _T ("skip"))
        {
            rg_TiaoGuoShu = rg_TiaoGuoShu + 1;
        }
        else if (rg_ChanBuJieGuo == _T ("delay"))
        {
            rg_YanShiShu = rg_YanShiShu + 1;
        }
        else if (rg_ChanBuJieGuo == _T ("ok"))
        {
            rg_ChengGongShu = rg_ChengGongShu + 1;
        }
        else if (rg_ChanBuJieGuo == _T ("fail"))
        {
            rg_ShiBaiShu = rg_ShiBaiShu + 1;
        }
        else if (rg_ChanBuJieGuo == _T ("fail_stop"))
        {
            rg_ShiBaiShu = rg_ShiBaiShu + 1;
            break;
        }
    }
    BOOL rg_YiTingZhi;
    WorkflowStateLock.data ().lock (FALSE);
    WorkflowRun = FALSE;
    CurrentWorkflowName = _T ("");
    WorkflowStartTime = 0;
    rg_YiTingZhi = WorkflowShouldStop;
    WorkflowShouldStop = FALSE;
    WorkflowStateLock.data ().unlock ();
    BOOL rg_HuiZongChengGong;
    rg_HuiZongChengGong = rg_ShiBaiShu == 0 && (rg_YiTingZhi == FALSE || rg_ChengGongShu + rg_TiaoGuoShu + rg_ShiBaiShu + rg_YanShiShu == rg_ZongBuShu);
    CVolString rg_stepsJSON;
    rg_stepsJSON = StepJSONFragmentListToArrayText (rg_BuZhouJieGuoJSONLieBiao);
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONDuiXiangLei rg_HuiZongDuiXiang1;
    rg_HuiZongDuiXiang1.data().CreateFromText(_CT2 (_T ("{}")));
    rg_HuiZongDuiXiang1.rg_JiaRuWenBenChengYuan (_CT2 (_T ("workflow")), rg_GongZuoLiuMing2);
    rg_HuiZongDuiXiang1.rg_JiaRuLuoJiZhiChengYuan (_CT2 (_T ("success")), rg_HuiZongChengGong);
    rg_HuiZongDuiXiang1.rg_JiaRuLuoJiZhiChengYuan (_CT2 (_T ("stopped")), rg_YiTingZhi);
    rg_HuiZongDuiXiang1.rg_JiaRuZhengShuChengYuan (_CT2 (_T ("total_steps")), rg_ZongBuShu);
    rg_HuiZongDuiXiang1.rg_JiaRuZhengShuChengYuan (_CT2 (_T ("success_count")), rg_ChengGongShu);
    rg_HuiZongDuiXiang1.rg_JiaRuZhengShuChengYuan (_CT2 (_T ("failure_count")), rg_ShiBaiShu);
    rg_HuiZongDuiXiang1.rg_JiaRuZhengShuChengYuan (_CT2 (_T ("skipped_count")), rg_TiaoGuoShu);
    rg_HuiZongDuiXiang1.rg_JiaRuZhengShuChengYuan (_CT2 (_T ("delay_count")), rg_YanShiShu);
    CVolString rg_HuiZongTouJSON;
    rg_HuiZongTouJSON = rg_HuiZongDuiXiang1.data().ToString(YYJSON_WRITE_NOFLAG);
    CVolString rg_HuiZongPianDuan;
    rg_HuiZongPianDuan = rg_HuiZongTouJSON.Left ((INT)rg_HuiZongTouJSON.GetLength () - 1) + _T (",\"steps\":") + rg_stepsJSON + _T ("}");
    return (MCPResponseBuilder::CommandSuccessRawJSON (CommandID, rg_HuiZongPianDuan, rg_HuiZongChengGong));
}

}
