
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

namespace rg_volcano_base
{

rg_HuChiSuoLei::rg_HuChiSuoLei ()
{
    _VolObjectInitMembers ();
}

void rg_HuChiSuoLei::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

rg_HuanCunXianChengLei::rg_HuanCunXianChengLei ()
{
    _VolObjectInitMembers ();
}

void rg_HuanCunXianChengLei::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

rg_HuanCunXianChengLei::~rg_HuanCunXianChengLei ()
{
    OnBeforeObjectCleanup ();
}

BOOL rg_HuanCunXianChengLei::rg_QiDong2 (INT rg_YongHuCanShu8)
{
    rg_TingZhi3 ();
    const HVOLTHREAD hThread = g_objVolApp.GetThreadPool ().StartNewThread ((VOL_POOL_THREAD_FUNC)sThreadFunc, (UINT_P)this, (UINT_P)rg_YongHuCanShu8);
    if (hThread != NULL) {
        data ().init (hThread, this);
        return TRUE;
    }
    return FALSE;
}

void rg_HuanCunXianChengLei::rg_TingZhi3 ()
{
    if (data ().m_hThreadHandle != 0) {
        g_objVolApp.GetThreadPool ().StopThread (data ().m_hThreadHandle);
        data ().init ();
    }
}

void rg_HuanCunXianChengLei::ra_HuanCunXianChengLei_XianChengYunHang1 (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_4.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
}

INT rg_HuanCunXianChengLei::rg_XianChengYunHang1 (INT rg_XianChengGouBing8, INT rg_YongHuCanShu9, INT rg_TuiChuShiJian2)
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_4.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber, INT rg_XianChengGouBing8, INT rg_YongHuCanShu9, INT rg_TuiChuShiJian2))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber, rg_XianChengGouBing8, rg_YongHuCanShu9, rg_TuiChuShiJian2);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}
void rg_HuanCunXianChengLei::_OnBeforeCleanup ()  {
    if (data ().m_hThreadHandle != 0 && data ().m_pOwnerObject == this)  {
        g_objVolApp.GetThreadPool ().StopThread (data ().m_hThreadHandle);
        data ().init ();
    }
}

}
