
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VPKG_RG_VOLCANO_BASE_W_RES_H__
#define __VPKG_RG_VOLCANO_BASE_W_RES_H__

typedef enum
{
    GOADT_NOT = 0,
    GOADT_DELETE_OBJECT,
    GOADT_DESTORY_ICON,
    GOADT_DESTORY_CURSOR,
    GOADT_DESTROY_IMAGELIST,
}
GDI_OBJ_AUTO_DELETE_TYPE;
class CGDIObjectHandle : public CRefObject
{
    DECLARE_DERIVED_CLASS (CGDIObjectHandle)
public:
    inline_ CGDIObjectHandle (const HGDIOBJ hGDIObject, const GDI_OBJ_AUTO_DELETE_TYPE enAutoDeleteType) :
            m_hGDIObject (hGDIObject),
            m_enAutoDeleteType (enAutoDeleteType)
    {
    }
    virtual ~CGDIObjectHandle ()
    {
        if (m_hGDIObject != NULL)
        {
            switch (m_enAutoDeleteType)
            {
            case GOADT_DESTORY_ICON:
                VERIFY (::DestroyIcon ((HICON)m_hGDIObject));
                break;
            case GOADT_DESTORY_CURSOR:
                VERIFY (::DestroyCursor ((HCURSOR)m_hGDIObject));
                break;
            case GOADT_DESTROY_IMAGELIST:
                VERIFY (::ImageList_Destroy ((HIMAGELIST)m_hGDIObject));
                break;
            case GOADT_DELETE_OBJECT:
                VERIFY (::DeleteObject (m_hGDIObject));
                break;
            }
        }
    }
    inline_ HGDIOBJ SafeGetGDIHandle () const
    {
        return (this == NULL ? NULL : m_hGDIObject);
    }
    inline_ HGDIOBJ DetachGDIHandle ()
    {
        const HGDIOBJ hGDIObject = m_hGDIObject;
        m_hGDIObject = NULL;
        return hGDIObject;
    }
protected:
    HGDIOBJ m_hGDIObject;
    const GDI_OBJ_AUTO_DELETE_TYPE m_enAutoDeleteType;
};

#endif  // __VPKG_RG_VOLCANO_BASE_W_RES_H__
