
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

namespace rg_FBrowser_value
{

BOOL FBroBinaryValue::_IsSelfEqual (const FBroBinaryValue& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void FBroBinaryValue::_CopySelfFrom (const FBroBinaryValue& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

BOOL FBroBinaryValue::rg_ShiFouWeiKong156 ()
{
    return IsEmpty();
}

INT FBroBinaryValue::rg_QuDaXiao ()
{
    if(IsEmpty ()) return 0;
    return FBroHsBinaryValue_GetSize(m_class);
}

void FBroBinaryValue::rg_QuZhi26 (INT rg_HuanCunZhiZhen2, INT rg_HuanCunDaXiao, INT rg_PianYiLiang1)
{
    if(IsEmpty ()) return;
    FBroHsBinaryValue_GetData(m_class,(void *)rg_HuanCunZhiZhen2,rg_HuanCunDaXiao,rg_PianYiLiang1);
}

CVolString FBroBinaryValue::rg_QuWenBen7 ()
{
    if(!IsEmpty ()) return FBroUnit::FBroStringToCWString(FBroHsBinaryValue_GetString(m_class));
}

CVolMem FBroBinaryValue::rg_QuZiJieJi21 ()
{
    if(IsEmpty ()) return CVolMem();
    INT rg_size4;
    INT rg_datapoint;
    CVolMem rg_tempret4;
    rg_size4 = rg_QuDaXiao ();
    if (rg_size4 > 0)
    {
        rg_datapoint = (INT_P)malloc ((size_t)rg_size4);
        rg_QuZhi26 (rg_datapoint, rg_size4, 0);
        rg_tempret4 = CVolMem ((void*)rg_datapoint, rg_size4);
        free ((void*)rg_datapoint);
    }
    return (rg_tempret4);
}

BOOL FBroListValue::_IsSelfEqual (const FBroListValue& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void FBroListValue::_CopySelfFrom (const FBroListValue& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

BOOL FBroListValue::rg_ShiFouWeiKong158 ()
{
    return IsEmpty();
}

BOOL FBroListValue::rg_ShiFouYouXiao8 ()
{
    if(IsEmpty ()) return false;
    return FBroHsListValue_IsValid(m_class);
}

INT FBroListValue::rg_QuDaXiao1 ()
{
    if(IsEmpty ()) return 0;
    return FBroHsListValue_GetSize(m_class);
}

INT FBroListValue::rg_QuLeiXing6 (INT rg_SuoYin28)
{
    if(IsEmpty ()) return 0;
    return FBroHsListValue_GetType(m_class,rg_SuoYin28);
}

BOOL FBroListValue::rg_QuLuoJiZhi (INT rg_SuoYin29)
{
    if(IsEmpty ()) return false;
    return FBroHsListValue_GetBool(m_class,rg_SuoYin29);
}

INT FBroListValue::rg_QuZhengShuZhi (INT rg_SuoYin30)
{
    if(IsEmpty ()) return 0;
    return FBroHsListValue_GetInt(m_class,rg_SuoYin30);
}

DOUBLE FBroListValue::rg_QuShuangJingDuXiaoShuZhi (INT rg_SuoYin31)
{
    if(IsEmpty ()) return 0;
    return FBroHsListValue_GetDouble(m_class,rg_SuoYin31);
}

CVolString FBroListValue::rg_QuWenBenZhi (INT rg_SuoYin32)
{
    if(IsEmpty()) return CVolString();
    CefRefPtr<FBroString> fbrostring = FBroHsListValue_GetString(m_class,rg_SuoYin32);
    return FBroUnit::FBroStringToCWString(fbrostring);
}

BOOL FBroValue::_IsSelfEqual (const FBroValue& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void FBroValue::_CopySelfFrom (const FBroValue& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

BOOL FBroValue::rg_ShiFouWeiKong159 ()
{
    return IsEmpty();
}

void FBroValue::rg_ChuangJian22 ()
{
    Set(FBroHsValue_Create());
}

BOOL FBroValue::rg_ZhiLuoJiZhi1 (BOOL rg_bool_value4)
{
    if(IsEmpty()) return false;
    return FBroHsValue_SetBool(m_class,rg_bool_value4);
}

BOOL FBroValue::rg_ZhiZhengShuZhi1 (INT rg_ZhengShuZhi4)
{
    if(IsEmpty()) return false;
    return FBroHsValue_SetInt(m_class,rg_ZhengShuZhi4);
}

BOOL FBroValue::rg_ZhiWenBenZhi1 (CVolString& rg_string18)
{
    if(IsEmpty()) return false;
    return FBroHsValue_SetString(m_class,rg_string18.GetText());
}

FBroDictionaryValue FBroValue::rg_QuZiDianZhi2 ()
{
    FBroDictionaryValue rg_tempdata2;
    if(!IsEmpty()) { rg_tempdata2.Set(FBroHsValue_GetDictionary(m_class));}
    return (rg_tempdata2);
}

BOOL FBroDictionaryValue::_IsSelfEqual (const FBroDictionaryValue& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void FBroDictionaryValue::_CopySelfFrom (const FBroDictionaryValue& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

BOOL FBroDictionaryValue::rg_ShiFouWeiKong160 ()
{
    return IsEmpty();
}

void FBroDictionaryValue::rg_ChuangJian23 ()
{
    Set(FBroHsDictionaryValue_Create());
}

rg_FBrowser_ShuJuLeiXing::rg_FBrowser_WenBenShuZu FBroDictionaryValue::rg_QuGuanJianZi ()
{
    if(!IsEmpty()) return rg_FBrowser_ShuJuLeiXing::rg_FBrowser_WenBenShuZu(FBroHsDictionaryValue_GetKeys(m_class));
    return rg_FBrowser_ShuJuLeiXing::rg_FBrowser_WenBenShuZu();
}

BOOL FBroDictionaryValue::rg_YiChu2 (CVolString& rg_GuanJianZi95)
{
    if(IsEmpty()) return false;
    return FBroHsDictionaryValue_Remove(m_class,rg_GuanJianZi95.GetText());
}

INT FBroDictionaryValue::rg_QuZhengShuZhi2 (CVolString& rg_GuanJianZi98)
{
    if(IsEmpty ()) return 0;
    return FBroHsDictionaryValue_GetInt(m_class,rg_GuanJianZi98.GetText());
}

CVolString FBroDictionaryValue::rg_QuWenBenZhi2 (CVolString& rg_GuanJianZi100)
{
    if(IsEmpty()) return CVolString();
    CefRefPtr<FBroString> fbrostring = FBroHsDictionaryValue_GetString(m_class,rg_GuanJianZi100.GetText());
    return FBroUnit::FBroStringToCWString(fbrostring);
}

BOOL FBroDictionaryValue::rg_ZhiZhengShuZhi2 (CVolString& rg_GuanJianZi104, INT rg_ZhengShuZhi5)
{
    if(IsEmpty()) return false;
    return FBroHsDictionaryValue_SetInt(m_class,rg_GuanJianZi104.GetText(),rg_ZhengShuZhi5);
}

BOOL FBroDictionaryValue::rg_ZhiWenBenZhi2 (CVolString& rg_GuanJianZi106, CVolString& rg_string19)
{
    if(IsEmpty()) return false;
    return FBroHsDictionaryValue_SetString(m_class,rg_GuanJianZi106.GetText(),rg_string19.GetText());
}

BOOL FBroPostDataElementVector::_IsSelfEqual (const FBroPostDataElementVector& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void FBroPostDataElementVector::_CopySelfFrom (const FBroPostDataElementVector& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

BOOL FBroPostDataElementVector::rg_ShiFouWeiKong161 ()
{
    return IsEmpty();
}

INT FBroPostDataElementVector::rg_QuGeShu6 ()
{
    return FBroPostDataList_Size(m_class);
}

void FBroPostDataElementVector::rg_DaoShuZuShou6 ()
{
    if(!IsEmpty()) FBroPostDataList_ToBegin(m_class);
}

BOOL FBroPostDataElementVector::rg_DaoXiaYiGe6 ()
{
    if(!IsEmpty()) return FBroPostDataList_ToNext(m_class);
    return (FALSE);
}

rg_FBrowser_LiuLanQi::FBroHsPostDataElement FBroPostDataElementVector::rg_QuDangQianWeiZhiShuJu6 ()
{
    return IsEmpty()? rg_FBrowser_LiuLanQi::FBroHsPostDataElement() : rg_FBrowser_LiuLanQi::FBroHsPostDataElement(FBroPostDataList_GetCurrentData(m_class));
}

BOOL rg_class_FBrowser_X509zhshshz::_IsSelfEqual (const rg_class_FBrowser_X509zhshshz& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_class_FBrowser_X509zhshshz::_CopySelfFrom (const rg_class_FBrowser_X509zhshshz& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

BOOL FBroDragData::_IsSelfEqual (const FBroDragData& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void FBroDragData::_CopySelfFrom (const FBroDragData& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

}
