
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_LIULANQI_FBROSSLINFO_H__
#define __VCLS_RG_FBROWSER_LIULANQI_FBROSSLINFO_H__

namespace rg_FBrowser_LiuLanQi
{

class FBroSSLInfo : public CVolObject
{
    DECLARE_VOL_CLASS (rg_FBrowser_LiuLanQi, FBroSSLInfo)

public:
    CefRefPtr<CefSSLInfo> m_class;
    inline_ FBroSSLInfo (CefRefPtr<CefSSLInfo> object) : FBroSSLInfo () { m_class = object; }
    inline_ void _CopySelfFromExtra (const FBroSSLInfo& objCopyFrom) { m_class = objCopyFrom.m_class; }
    inline_ BOOL _IsSelfEqualExtra (const FBroSSLInfo& objCompare) const { return (m_class.get () == objCompare.m_class.get ()); }
    inline_ BOOL IsEmpty () const { return m_class.get () == nullptr; }
    inline_ void Set (CefRefPtr<CefSSLInfo> object) { m_class = object; }
    ~FBroSSLInfo(){};

public:
    inline_ FBroSSLInfo () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_FBROWSER_LIULANQI_FBROSSLINFO_H__
