
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_APP_RG_MCP_TIANBIAOFENPA_H__
#define __VCLS_RG_VOLCANO_APP_RG_MCP_TIANBIAOFENPA_H__

namespace rg_volcano_app
{

class rg_MCP_TianBiaoFenPa : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_app, rg_MCP_TianBiaoFenPa)

public:
    static CVolString CALLBACK rg_FenLeiFenPa_TianBiaoCaoZuo (CVolString& rg_MingLingID31, CVolString& rg_FangFaMing9, rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei& rg_CanShuJSON17);
    inline_ rg_MCP_TianBiaoFenPa () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_APP_RG_MCP_TIANBIAOFENPA_H__
