
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_APP_RG_MCP_NIXIANGFENPA_H__
#define __VCLS_RG_VOLCANO_APP_RG_MCP_NIXIANGFENPA_H__

namespace rg_volcano_app
{

class rg_MCP_NiXiangFenPa : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_app, rg_MCP_NiXiangFenPa)

public:
    static CVolString CALLBACK rg_FenLeiFenPa_NiXiangCaoZuo (CVolString& rg_MingLingID31, CVolString& rg_FangFaMing10, rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei& rg_CanShuJSON19);
    inline_ rg_MCP_NiXiangFenPa () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_APP_RG_MCP_NIXIANGFENPA_H__
