
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_SUANSHUYUNSUANLEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_SUANSHUYUNSUANLEI_H__

namespace rg_volcano_base
{

class rg_SuanShuYunSuanLei : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_base, rg_SuanShuYunSuanLei)

public:
    inline_ rg_SuanShuYunSuanLei () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_SUANSHUYUNSUANLEI_H__
