
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_WINDOWS_SQLITESHJK_RG_SQLITEJILUJILEI_H__
#define __VCLS_RG_VOLCANO_WINDOWS_SQLITESHJK_RG_SQLITEJILUJILEI_H__

namespace rg_volcano_windows_SQLiteshjk
{

class rg_SQLiteJiLuJiLei : public CVolObject
{
    DECLARE_VOL_CLASS (rg_volcano_windows_SQLiteshjk, rg_SQLiteJiLuJiLei)

protected:
    inline_ void _OnInitExtra ()  {  m_pRefObject = new CRefObjectWithData<CSqliteStmtWraper>; }
    inline_ void _OnCleanupExtra ()  { if (m_pRefObject != NULL)  m_pRefObject->Release (); }
    inline_ void _CopySelfFromExtra (const rg_SQLiteJiLuJiLei& objCopyFrom)  { SetRefObject (objCopyFrom.m_pRefObject); }
    inline_ BOOL _IsSelfEqualExtra (const rg_SQLiteJiLuJiLei& objCompare) const  { return (m_pRefObject == objCompare.m_pRefObject); }
    CRefObject* m_pRefObject;
public:
    void SetRefObject (CRefObject* pRefObject);
    void TakeOverNewRefObject (CRefObject* pNewRefObject);
    inline_ CRefObject* GetRefObject ()  {  return m_pRefObject;  }
public:
    inline_ CSqliteStmtWraper& data ()  { return ((CRefObjectWithData<CSqliteStmtWraper>*)m_pRefObject)->m_data; }
    inline_ CSqliteStmtWraper* pdata ()  { return &((CRefObjectWithData<CSqliteStmtWraper>*)m_pRefObject)->m_data; }
inline_ rg_SQLiteJiLuJiLei (INT_P ptr) : rg_SQLiteJiLuJiLei()
{
    data().SetData(ptr);
}
inline_ sqlite3_stmt* GetStmt () { return data().GetData(); }

public:
    INT rg_ZhiHangYuGou ();
    INT rg_ZhiZhengShuCanShuShuJu (INT rg_CanShuSuoYin2, INT rg_value114);
    INT rg_ZhiChangZhengShuCanShuShuJu (INT rg_CanShuSuoYin3, INT64 rg_value115);
    INT rg_ZhiWenBenCanShuShuJu (INT rg_CanShuSuoYin4, CVolString& rg_value116);
    INT rg_DouZhengShuShuJu (INT rg_LieSuoYin24);
    CVolString rg_DouWenBenShuJu (INT rg_LieSuoYin26);
    void rg_ShiFang2 ();
    rg_SQLiteJiLuJiLei ();
    void _VolObjectInitMembers ();
    virtual ~rg_SQLiteJiLuJiLei ();
};

}

#endif  //__VCLS_RG_VOLCANO_WINDOWS_SQLITESHJK_RG_SQLITEJILUJILEI_H__
