
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_HUIDIAO_RG_CLASS_FBROWSER_ZFCHHD_H__
#define __VCLS_RG_FBROWSER_HUIDIAO_RG_CLASS_FBROWSER_ZFCHHD_H__

namespace rg_FBrowser_HuiDiao
{

class rg_class_FBrowser_zfchhd : public CVolObject, public FBroHsStringVisitor
{
    DECLARE_EMPTY_VOL_CLASS (rg_FBrowser_HuiDiao, rg_class_FBrowser_zfchhd)

public:
        _FBRO_NEW_DELETE_OVERRIDE();
    public:
        virtual void Visit(const CefString& string) override;

public:
    virtual void rg_HuiDiao4 (CVolString& rg_string5);
    rg_class_FBrowser_zfchhd ();
    void _VolObjectInitMembers ();
    virtual ~rg_class_FBrowser_zfchhd ();

protected:
    void rg_class_FBrowser_zfchhd_class_chshh ();
    void rg_class_FBrowser_zfchhd_class_ql ();
};

}

#endif  //__VCLS_RG_FBROWSER_HUIDIAO_RG_CLASS_FBROWSER_ZFCHHD_H__
