
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_CHANGYONGGONGNENGLEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_CHANGYONGGONGNENGLEI_H__

namespace rg_volcano_base
{

class rg_ChangYongGongNengLei : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_base, rg_ChangYongGongNengLei)

public:
    static INT64 CALLBACK rg_QuQiDongShiJian ();
    inline_ rg_ChangYongGongNengLei () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_CHANGYONGGONGNENGLEI_H__
