
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_SHUJULEIXING_RG_FBROWSER_WENBENSHUZU_H__
#define __VCLS_RG_FBROWSER_SHUJULEIXING_RG_FBROWSER_WENBENSHUZU_H__

namespace rg_FBrowser_ShuJuLeiXing
{

class rg_FBrowser_WenBenShuZu : public CVolObject
{
    DECLARE_VOL_CLASS (rg_FBrowser_ShuJuLeiXing, rg_FBrowser_WenBenShuZu)

public:
    CefRefPtr<FBroCefStringList> m_data;
    inline_ rg_FBrowser_WenBenShuZu (CefRefPtr<FBroCefStringList> object) : rg_FBrowser_WenBenShuZu () { m_data = object; }
    inline_ void _CopySelfFromExtra (const rg_FBrowser_WenBenShuZu& objCopyFrom) { m_data = objCopyFrom.m_data; }
    inline_ BOOL _IsSelfEqualExtra (const rg_FBrowser_WenBenShuZu& objCompare) const { return (m_data.get () == objCompare.m_data.get ()); }
    inline_ BOOL_P IsEmpty () const { return m_data.get () == nullptr; }
    inline_ void Set (CefRefPtr<FBroCefStringList> object) { m_data = object; }
    ~rg_FBrowser_WenBenShuZu(){};

public:
    void rg_ChuangJian9 ();
    INT rg_QuGeShu3 ();
    void rg_JiaRuChengYuan36 (CVolString& rg_member3);
    CVolString rg_QuShuJu3 (INT rg_SuoYin3);
    inline_ rg_FBrowser_WenBenShuZu () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_FBROWSER_SHUJULEIXING_RG_FBROWSER_WENBENSHUZU_H__
