
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_SHIJIANKONGZHI_RG_CLASS_FBROWSER_YINGYONGSHIJIAN_H__
#define __VCLS_RG_FBROWSER_SHIJIANKONGZHI_RG_CLASS_FBROWSER_YINGYONGSHIJIAN_H__

namespace rg_FBrowser_ShiJianKongZhi
{

class rg_class_FBrowser_YingYongShiJian : public CVolObject, public FBroHsInitEvent
{
    DECLARE_EMPTY_VOL_CLASS (rg_FBrowser_ShiJianKongZhi, rg_class_FBrowser_YingYongShiJian)

public:
        _FBRO_NEW_DELETE_OVERRIDE();
    public:
        virtual void OnBeforeCommandLineProcessing(const CefString& process_type,CefRefPtr<CefCommandLine> command_line) override;
        virtual void OnRegisterCustomSchemes(CefRawPtr<CefSchemeRegistrar> registrar) override;
        virtual void OnContextInitialized() override;
        virtual void OnBeforeChildProcessLaunch(CefRefPtr<CefCommandLine> command_line) override;
        virtual void OnScheduleMessagePumpWork(int64_t delay_ms) override;
        virtual void OnWebKitInitialized()override;
        virtual void OnBrowserCreated(CefRefPtr<CefBrowser> browser, CefRefPtr<CefDictionaryValue> extra_info)override;
        virtual void OnBrowserDestroyed(CefRefPtr<CefBrowser> browser) override;
        virtual void OnContextCreated(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefRefPtr<CefV8Context> context) override;
        virtual void OnContextReleased(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefRefPtr<CefV8Context> context) override;
        virtual void OnUncaughtException(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefRefPtr<CefV8Context> context,CefRefPtr<CefV8Exception> exception,CefRefPtr<CefV8StackTrace> stackTrace)override;
        virtual void OnFocusedNodeChanged(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefRefPtr<CefDOMNode> node) override;
        virtual bool OnProcessMessageReceived(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefProcessId source_process,CefRefPtr<CefProcessMessage> message)override;
        virtual void OnLoadingStateChange(CefRefPtr<CefBrowser> browser,bool isLoading,bool canGoBack,bool canGoForward)override ;
        virtual void OnLoadStart(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefLoadHandler::TransitionType transition_type)override ;
        virtual void OnLoadEnd(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,int httpStatusCode)override ;
        virtual void OnLoadError(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefLoadHandler::ErrorCode errorCode,const CefString& errorText,const CefString& failedUrl)override ;
        virtual void ReceiveMainProcessMessage(CefRefPtr<CefBrowser> browser,const CefString& name,char* message, int size) override;
        virtual void OnWebSocketClientCreate(CefRefPtr<CefBrowser> browser, CefRefPtr<CefFrame> frame, CefRefPtr<FBroDOMWssClient> websocket) override;
        virtual void OnWebSocketClientClose(CefRefPtr<CefBrowser> browser, CefRefPtr<CefFrame> frame, CefRefPtr<FBroDOMWssClient> websocket) override;
        virtual bool OnWebSocketClientMessage(CefRefPtr<CefBrowser> browser, CefRefPtr<CefFrame> frame, CefRefPtr<FBroDOMWssClient> websocket, int type, HANDLE& data, int& size)override;
        virtual void OnWebSocketClientConnect(CefRefPtr<CefBrowser> browser, CefRefPtr<CefFrame> frame, CefRefPtr<FBroDOMWssClient> websocket, HANDLE& returl, HANDLE& protocols) override;
        virtual bool OnWebSocketClientSend(CefRefPtr<CefBrowser> browser, CefRefPtr<CefFrame> frame, CefRefPtr<FBroDOMWssClient> websocket, int type, HANDLE& retdata, int offsize, int& size) override;
        virtual void GetDefaultClient(CefRefPtr<CefBrowser> browser,const CefString& url,CefRefPtr<FBroUseExtraData> user_settings) override;
        virtual void ClearData(HANDLE data) override{ if(data) delete[] data; }
        virtual void FinishShutdown(BOOL& shutdown) override;
        virtual void OnCreateExtension(CefRefPtr<CefRequestContext> requestContext,const CefString& extensionID) override;
        virtual void OnCreateExtensionError(CefRefPtr<CefRequestContext> requestContext,const CefString& extensionID,const CefString& path,const CefString& error) override;
        virtual void OnAddExtension(CefRefPtr<CefRequestContext> requestContext,const CefString& extensionID) override;
        virtual void OnRemoveExtension(CefRefPtr<CefRequestContext> requestContext,const CefString& extensionID) override;
        virtual void OnRequestContextInitialized(CefRefPtr<CefRequestContext> requestContext) override;

public:
    virtual void rg_QingQiuHuanJingChuShiHuaWanBi (rg_FBrowser_LiuLanQi::FBroRequestContext& rg_QingQiuHuanJing);
    virtual void rg_KuoZhanChaJian_ChuangJianChengGong (rg_FBrowser_LiuLanQi::FBroRequestContext& rg_QingQiuHuanJing1, CVolString& rg_ChaJianID);
    virtual void rg_KuoZhanChaJian_ChuangJianShiBai (rg_FBrowser_LiuLanQi::FBroRequestContext& rg_QingQiuHuanJing2, CVolString& rg_ChaJianID1, CVolString& rg_ChaJianLuJing, CVolString& rg_CuoWuXinXi);
    virtual void rg_KuoZhanChaJian_ZaiRuChengGong (rg_FBrowser_LiuLanQi::FBroRequestContext& rg_QingQiuHuanJing3, CVolString& rg_ChaJianID2);
    virtual void rg_KuoZhanChaJian_XieZaiChengGong (rg_FBrowser_LiuLanQi::FBroRequestContext& rg_QingQiuHuanJing4, CVolString& rg_ChaJianID3);
    virtual void rg_HuoQuMoRenShiJian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi54, CVolString& rg_DeZhi3, rg_FBrowser_LiuLanQi::rg_class_FBrowser_yhewpzh& rg_YongHuEWaiPeiZhi1);
    virtual void rg_ZhiHangGuanBiWanBi (rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouJieShuChengXu1);
    virtual void rg_JiJiangChuLiMingLingHang (CVolString& rg_JinChengLeiXing1, rg_FBrowser_LiuLanQi::FBroCommandLine& rg_MingLingHang);
    virtual void rg_ZhuCeZiDingYiFangAn (rg_FBrowser_LiuLanQi::FBroSchemeRegistrar& rg_FangAn);
    virtual void rg_LiuLanQi_ChuShiHuaWanBi ();
    virtual void rg_LiuLanQi_JiJiangQiDongZiJinCheng (rg_FBrowser_LiuLanQi::FBroCommandLine& rg_MingLingHang1);
    virtual void rg_LiuLanQi_JiJiangQiDongXiaoXiDiaoDu (INT64 rg_YanChiShiJian);
    virtual void rg_XuanRan_JiJiangChuShiHuaWebKit ();
    virtual void rg_XuanRan_LiuLanQiChuangJian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi55, rg_FBrowser_value::FBroDictionaryValue& rg_EWaiXinXi3);
    virtual void rg_XuanRan_JiJiangXiaoHuiLiuLanQi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi56);
    virtual void rg_XuanRan_JiJiangChuangJianV8HuanJing (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi57, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia20, rg_FBrowser_LiuLanQi::FBroV8Context& rg_V8HuanJing2);
    virtual void rg_XuanRan_JiJiangShiFangV8HuanJing (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi58, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia21, rg_FBrowser_LiuLanQi::FBroV8Context& rg_V8HuanJing3);
    virtual void rg_XuanRan_JiJiangBuHuoYiChang (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi59, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia22, rg_FBrowser_LiuLanQi::FBroV8Context& rg_V8HuanJing4, rg_FBrowser_LiuLanQi::FBroV8Exception& rg_V8YiChang1, rg_FBrowser_LiuLanQi::FBroV8StackTrace& rg_V8DuiZhanZongJi1);
    virtual void rg_XuanRan_JiaoDianJieDianGaiBian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi60, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia23, rg_FBrowser_LiuLanQi::FBroDOMNode& rg_DOMJieDian1);
    virtual BOOL rg_XuanRan_ShouDaoXiaoXi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi61, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia24, INT rg_YuanJinCheng, rg_FBrowser_LiuLanQi::FBroProcessMessage& rg_XiaoXi13);
    virtual void rg_XuanRan_ZaiRuZhuangTaiBeiGaiBian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi62, BOOL rg_ShiFouDouQuZhong, BOOL rg_KeHouTui, BOOL rg_KeQianJin);
    virtual void rg_XuanRan_ZaiRuKaiShi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi63, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia25, INT rg_GuoDuLeiXing2);
    virtual void rg_XuanRan_ZaiRuJieShu (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi64, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia26, INT rg_ZhuangTaiMa5);
    virtual void rg_XuanRan_ZaiRuCuoWu (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi65, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia27, INT rg_CuoWuDaiMa2, CVolString& rg_CuoWuWenBen6, CVolString& rg_ShiBaiDeZhi2);
    virtual void rg_JinChengJianXiaoXi_ShouDaoZhuJinChengXiaoXi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi66, CVolString& rg_XiaoXiMing, CVolMem& rg_XiaoXiNeiRong);
    virtual void rg_xr_VIP_WebSocketkhd_chj (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi67, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia28, rg_LiuLanQi_VIP::rg_class_FBrowserVIP_WebSocketkhd& rg_websocketKeHuDuan);
    virtual void rg_xr_VIP_WebSocketkhd_gb (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi68, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia29, rg_LiuLanQi_VIP::rg_class_FBrowserVIP_WebSocketkhd& rg_websocketKeHuDuan1);
    virtual void rg_xr_VIP_WebSocketkhd_ljfwq (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi69, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia30, rg_LiuLanQi_VIP::rg_class_FBrowserVIP_WebSocketkhd& rg_websocketKeHuDuan2, CVolString& rg_url11, CVolString& rg_protocols);
    virtual BOOL rg_xr_VIP_WebSocketkhd_jshshj (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi70, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia31, rg_LiuLanQi_VIP::rg_class_FBrowserVIP_WebSocketkhd& rg_websocketKeHuDuan3, INT rg_ShuJuLeiXing, CVolMem& rg_ShuJu11);
    virtual BOOL rg_xr_VIP_WebSocketkhd_fsshj (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi71, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia32, rg_LiuLanQi_VIP::rg_class_FBrowserVIP_WebSocketkhd& rg_websocketKeHuDuan4, INT rg_ShuJuLeiXing1, CVolMem& rg_ShuJu12);
    rg_class_FBrowser_YingYongShiJian ();
    void _VolObjectInitMembers ();
    virtual ~rg_class_FBrowser_YingYongShiJian ();

protected:
    void rg_class_FBrowser_yyshj_class_chshh ();
    void rg_class_FBrowser_yyshj_class_ql ();
};

}

#endif  //__VCLS_RG_FBROWSER_SHIJIANKONGZHI_RG_CLASS_FBROWSER_YINGYONGSHIJIAN_H__
