
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_SHUJULEIXING_RG_FBROWSER_CHUSHIHUAPEIZHI_H__
#define __VCLS_RG_FBROWSER_SHUJULEIXING_RG_FBROWSER_CHUSHIHUAPEIZHI_H__

namespace rg_FBrowser_ShuJuLeiXing
{

class rg_FBrowser_ChuShiHuaPeiZhi : public CVolObject
{
    DECLARE_VOL_CLASS (rg_FBrowser_ShuJuLeiXing, rg_FBrowser_ChuShiHuaPeiZhi)

public:
     ~rg_FBrowser_ChuShiHuaPeiZhi(){ Release();};
    FBroInitSettings* ToFBroData();
    void Release();
    FBroInitSettings tempdata;

public:
    rg_FBrowser_ChuShiHuaPeiZhi ();
    void _VolObjectInitMembers ();
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

public:
    BOOL rg_MoShaXiang;
    CVolString rg_ZhiHangJinCheng;
    CVolString rg_KuangJiaWenJianMuLu;
    CVolString rg_ZhubundleLuJing;
    BOOL rg_QiYongJiTongXiaoXiXunHuan;
    BOOL rg_QiYongWaiBuXiaoXi;
    BOOL rg_QiYongLiBingXuanRan;
    BOOL rg_JinYongMingLingCanShu;
    CVolString rg_HuanCunMuLu;
    BOOL rg_BaoLiuSession;
    CVolString rg_LiuLanQiBiaoShi;
    CVolString rg_LiuLanQiBiaoShiBanBen;
    CVolString rg_BenDeHuaYuYan;
    CVolString rg_RiZhiMuLu;
    INT rg_RiZhiMoShi;
    INT rg_RiZhiYuanSu;
    CVolString rg_javascript_flags;
    CVolString rg_ZiYuanLuJing;
    CVolString rg_BenDeYuYanLuJing;
    INT rg_YuanChengDuanKou;
    INT rg_uncaught_exception_stack_size;
    INT rg_BeiJingYanSe;
    CVolString rg_JieShouYuYanQingChan;
    CVolString rg_QiYongcookieJiHuaQingChanCanShu;
    BOOL rg_QiYongcookieJiHua_PaiChuMoRenCanShu;
    CVolString rg_ChromeCeLueid;
    INT rg_ChromeYingYongTuBiaoid;
    INT rg_JinYongXinHaoChuLiChengXu;
    BOOL rg_QiYongZiDongDuoLiMoShi;
};

}

#endif  //__VCLS_RG_FBROWSER_SHUJULEIXING_RG_FBROWSER_CHUSHIHUAPEIZHI_H__
