
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_VALUE_FBROVALUE_H__
#define __VCLS_RG_FBROWSER_VALUE_FBROVALUE_H__

namespace rg_FBrowser_value
{

class FBroValue : public CVolObject
{
    DECLARE_VOL_CLASS (rg_FBrowser_value, FBroValue)

public:
    CefRefPtr<CefValue> m_class;
    inline_ FBroValue (CefRefPtr<CefValue> object) : FBroValue () { m_class = object; }
    inline_ void _CopySelfFromExtra (const FBroValue& objCopyFrom) { m_class = objCopyFrom.m_class; }
    inline_ BOOL _IsSelfEqualExtra (const FBroValue& objCompare) const { return (m_class.get () == objCompare.m_class.get ()); }
    inline_ BOOL_P IsEmpty () const { return m_class.get () == nullptr; }
    inline_ void Set(CefRefPtr<CefValue> object) { m_class = object; }
    ~FBroValue(){};

public:
    BOOL rg_ShiFouWeiKong159 ();
    void rg_ChuangJian22 ();
    BOOL rg_ZhiLuoJiZhi1 (BOOL rg_bool_value4);
    BOOL rg_ZhiZhengShuZhi1 (INT rg_ZhengShuZhi5);
    BOOL rg_ZhiWenBenZhi1 (CVolString& rg_string19);
    FBroDictionaryValue rg_QuZiDianZhi2 ();
    inline_ FBroValue () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_FBROWSER_VALUE_FBROVALUE_H__
