
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_LIULANQI_VIP_RG_CLASS_FBROWSERVIP_UASHJ_H__
#define __VCLS_RG_LIULANQI_VIP_RG_CLASS_FBROWSERVIP_UASHJ_H__

namespace rg_LiuLanQi_VIP
{

class rg_class_FBrowserVIP_UAshj : public CVolObject
{
    DECLARE_VOL_CLASS (rg_LiuLanQi_VIP, rg_class_FBrowserVIP_UAshj)

public:
    CefRefPtr<FBroVIPUserAgentData> m_class;
    inline_ rg_class_FBrowserVIP_UAshj (CefRefPtr<FBroVIPUserAgentData> object) : rg_class_FBrowserVIP_UAshj () { m_class = object; }
    inline_ void _CopySelfFromExtra (const rg_class_FBrowserVIP_UAshj& objCopyFrom) { m_class = objCopyFrom.m_class; }
    inline_ BOOL _IsSelfEqualExtra (const rg_class_FBrowserVIP_UAshj& objCompare) const { return (m_class.get () == objCompare.m_class.get ()); }
    inline_ BOOL_P IsEmpty () const { return m_class.get () == nullptr; }
    inline_ void Set(CefRefPtr<FBroVIPUserAgentData> object) { m_class = object; }
    ~rg_class_FBrowserVIP_UAshj(){};

public:
    void rg_ChuangJian27 ();
    void rg_ZhiUserAgent (CVolString& rg_userAgent1);
    void rg_ZhiAcceptLanguage (CVolString& rg_acceptLanguage);
    void rg_ZhiPlatform (CVolString& rg_platform);
    void rg_ZhiHighPlatform (CVolString& rg_platform1);
    void rg_ZhiArchitecture (CVolString& rg_architecture);
    void rg_ZhiModel (CVolString& rg_model);
    void rg_ZhiMobile (BOOL rg_mobile);
    void rg_ZhiBitness (CVolString& rg_bitness);
    void rg_ZhiWow (BOOL rg_wow);
    inline_ rg_class_FBrowserVIP_UAshj () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_LIULANQI_VIP_RG_CLASS_FBROWSERVIP_UASHJ_H__
