
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_LIULANQI_RG_CLASS_FBROWSER_LIULANQI_H__
#define __VCLS_RG_FBROWSER_LIULANQI_RG_CLASS_FBROWSER_LIULANQI_H__

namespace rg_FBrowser_LiuLanQi
{

class rg_class_FBrowser_LiuLanQi : public CVolObject
{
    DECLARE_VOL_CLASS (rg_FBrowser_LiuLanQi, rg_class_FBrowser_LiuLanQi)

public:
    CefRefPtr<CefBrowser> m_class;
    inline_ rg_class_FBrowser_LiuLanQi (CefRefPtr<CefBrowser> object) : rg_class_FBrowser_LiuLanQi () { m_class = object; }
    inline_ void _CopySelfFromExtra (const rg_class_FBrowser_LiuLanQi& objCopyFrom) { m_class = objCopyFrom.m_class; }
    inline_ BOOL _IsSelfEqualExtra (const rg_class_FBrowser_LiuLanQi& objCompare) const { return (m_class.get () == objCompare.m_class.get ()); }
    inline_ BOOL IsEmpty () const { return m_class.get () == nullptr; }
    inline_ void Set (CefRefPtr<CefBrowser> object) { m_class = object; }

public:
    static BOOL CALLBACK rg_FBrowser_ChuangJianLiuLanQi (CVolString& rg_LianJieDeZhi, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_ChuangKouXinXi& rg_ChuangKouXinXi4, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_LiuLanQiPeiZhi& rg_LiuLanQiSheZhi3, FBroRequestContext& rg_QingQiuHuanJing6, rg_FBrowser_value::FBroDictionaryValue& rg_EWaiXinXi5, rg_class_FBrowser_shjzhnzhzh& rg_LiuLanQiShiJian2, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_JinYongShiJian& rg_JinYongShiJian, CVolString& rg_BiaoShi11);
    BOOL rg_ShiFouWeiKong127 ();
    BOOL rg_ShiFouYiGuanBi ();
    CVolString rg_QuYongHuBiaoShi ();
    BOOL rg_KeFouHouTui ();
    void rg_HouTui ();
    BOOL rg_KeFouQianJin ();
    void rg_QianJin ();
    BOOL rg_ShiFouDouQuZhong1 ();
    void rg_ChongXinZaiRu ();
    void rg_ChongXinZaiRu_HuLueHuanCun ();
    void rg_TingZhiZaiRu ();
    INT rg_QuID ();
    BOOL rg_ShiFouXiangTong (rg_class_FBrowser_LiuLanQi& rg_DuiBiLiuLanQi);
    BOOL rg_ShiFouWeiDanChuang ();
    BOOL rg_ShiFouYouWenDang ();
    FBroFrame rg_QuZhuKuangJia ();
    FBroFrame rg_QuDangQianJiaoDianKuangJia ();
    FBroFrame rg_QuKuangJia_MingChen (CVolString& rg_MingChen2);
    rg_FBrowser_ShuJuLeiXing::rg_FBrowser_WenBenShuZu rg_QuKuangJiaID ();
    rg_FBrowser_ShuJuLeiXing::rg_FBrowser_WenBenShuZu rg_QuKuangJiaMingChen ();
    void rg_GuanBiLiuLanQi (BOOL rg_LiJiGuanBi, BOOL rg_ShiFouZhiKong);
    void rg_ZhiJiaoDian (BOOL rg_JiaoDian2);
    INT rg_QuChuangKouGouBing ();
    INT rg_QuDaKaiZheChuangKouGouBing ();
    BOOL rg_ShiFouLiuLanQiShiTu ();
    DOUBLE rg_QuSuFangJiBie ();
    void rg_ZhiSuFangJiBie (DOUBLE rg_JiBie);
    void rg_KaiShiXiaZai (CVolString& rg_DeZhi7);
    void rg_XiaZaiTuPian (CVolString& rg_DeZhi8, BOOL rg_ShiFouWeiTuBiao, INT rg_ZuiDaCheCun1, BOOL rg_HuLueHuanCun1, rg_class_FBrowser_shjzhnzhzh& rg_XiaZaiTuPianHuiDiao1);
    void rg_DaKaiDuiHuaKuang (INT rg_MoShi2, CVolString& rg_BiaoTi4, CVolString& rg_MoRenWenJianMing, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_WenBenShuZu& rg_GuoLuQi3, rg_class_FBrowser_shjzhnzhzh& rg_DaKaiWenJianDuiHuaKuangHuiDiao1);
    void rg_DaYin ();
    void rg_DaYinWeiPDF (CVolString& rg_BaoCunWenJianLuJing, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_PDFDaYinSheZhi& rg_PDFDaYinSheZhi, rg_class_FBrowser_shjzhnzhzh& rg_DaYinWeiPDFHuiDiao1);
    void rg_ChaZhao (CVolString& rg_ChaZhaoWenBen, BOOL rg_XiangQian, BOOL rg_ShiFouOuFenDaXiao, BOOL rg_ChaZhaoXiaYiGe);
    void rg_TingZhiChaZhao (BOOL rg_QingChuXuanXiang);
    void rg_DaKaiKaiFaZheGongJu (CVolString& rg_BiaoTi5, INT rg_FuChuangKou, INT rg_HengZuoBiao10, INT rg_ZongZuoBiao10, INT rg_KuanDu13, INT rg_GaoDu13, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_LiuLanQiPeiZhi& rg_LiuLanQiSheZhi7, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_WeiZhi& rg_YuanSuZuoBiao, rg_class_FBrowser_shjzhnzhzh& rg_LiuLanQiShiJian6, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_JinYongShiJian& rg_JinYongShiJian4);
    void rg_GuanBiKaiFaZheGongJu ();
    BOOL rg_ShiFouWeiKaiFaZhe ();
    BOOL rg_ShiFouCunZaiKaiFaZheGongJu ();
    void rg_FaSongAnJianShiJian (rg_FBrowser_ShuJuLeiXing::rg_FBrowser_AnJianShiJian& rg_AnJianShiJian5);
    void rg_FaSongShuBiaoDianJiShiJian (INT rg_AnJianLeiXing1, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_ShuBiaoShiJian& rg_ShuBiaoShiJian3, BOOL rg_DianJi, INT rg_DianJiCiShu);
    void rg_FaSongShuBiaoYiDongShiJian (rg_FBrowser_ShuJuLeiXing::rg_FBrowser_ShuBiaoShiJian& rg_ShuBiaoShiJian4, BOOL rg_ShuBiaoLiKai);
    void rg_FaSongShuBiaoGunLunShiJian (rg_FBrowser_ShuJuLeiXing::rg_FBrowser_ShuBiaoShiJian& rg_ShuBiaoShiJian5, INT rg_HengXiangGunLun, INT rg_ZongXiangGunLun);
    void rg_ZhiYeMianJingYin (BOOL rg_JingYin2);
    BOOL rg_ShiFouYeMianJingYin ();
    FBroRequestContext rg_QuQingQiuHuanJing ();
    INT rg_QuFuChuangKouGouBing ();
    void rg_ZhiFuChuangKou (INT rg_FuChuangKouGouBing9);
    void rg_ZhiChuangKouShuXing (INT rg_FengGeLeiXing, INT rg_FengGe2);
    INT rg_QuChuangKouShuXing (INT rg_FengGeLeiXing1);
    CVolString rg_QuChuangKouBiaoTi ();
    BOOL rg_JinChengJianXiaoXi_FaSongShuJu_DaoQuanBuXuanRanJinCheng (CVolString& rg_XiaoXiMing2, CVolMem& rg_XiaoXi16);
    BOOL rg_JinChengJianXiaoXi_FaSongShuJu_DaoZhiDingXuanRanJinCheng (INT rg_XuanRanJinChengID1, CVolString& rg_XiaoXiMing3, CVolMem& rg_XiaoXi17);
    rg_volcano_base::rg_ZhengShuShuZuLei rg_JinChengJianXiaoXi_QuXuanRanJinChengIDQingChan ();
    BOOL rg_JinChengJianXiaoXi_FaSongShuJu_DaoZhuJinCheng (CVolString& rg_XiaoXiMing4, CVolMem& rg_XiaoXi18);
    void rg_QingLiHuanCun1 (CVolString& rg_YuanDeZhi4, INT64 rg_QingLiDuiXiang1, INT64 rg_CunChuLeiXing1, rg_class_FBrowser_shjzhnzhzh& rg_JieGuoHuiDiao1);
    void rg_SheZhiDaiLi (CVolString& rg_DaiLiDeZhi, CVolString& rg_DaiLiZhangHao, CVolString& rg_DaiLiMiMa);
    void rg_QingKongDaiLi ();
    rg_class_FBrowser_TianBiaoKuangJia rg_QuZhuTianBiaoKuangJia ();
    rg_LiuLanQi_VIP::rg_class_FBrowserVIP_kfzhDOM rg_QuKaiFaZheDOM ();
    rg_FBrowser_value::FBroDictionaryValue rg_QuEWaiShuJu ();
    rg_LiuLanQi_VIP::rg_class_FBrowserVIP_kzhq rg_QuVIPKongZhiQi1 ();
    inline_ rg_class_FBrowser_LiuLanQi () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_FBROWSER_LIULANQI_RG_CLASS_FBROWSER_LIULANQI_H__
