
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_APP_RG_CLASS_MCP_DEVTOOLSGCHZH_H__
#define __VCLS_RG_VOLCANO_APP_RG_CLASS_MCP_DEVTOOLSGCHZH_H__

namespace rg_volcano_app
{

class rg_class_MCP_DevToolsgchzh : public rg_FBrowser_ShiJianKongZhi::rg_class_FBrowser_kfzhxxshj
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_app, rg_class_MCP_DevToolsgchzh)

public:
    virtual BOOL rg_KaiFaZheXiaoXi_VIP_ShouDaoXiaoXi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi45, INT rg_XiaoXiZhiZhen, INT rg_XiaoXiDaXiao);
    virtual void rg_KaiFaZheXiaoXi_VIP_ZhiHangWanCheng (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi46, INT rg_XiaoXiID, BOOL rg_ChengGong1, INT rg_JieGuoZhiZhen, INT rg_JieGuoDaXiao);
    virtual void rg_KaiFaZheXiaoXi_VIP_ShouDaoShiJian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi47, CVolString& rg_FangFaMing, INT rg_CanShuZhiZhen, INT rg_CanShuDaXiao);
    inline_ rg_class_MCP_DevToolsgchzh () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_APP_RG_CLASS_MCP_DEVTOOLSGCHZH_H__
