
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_APP_RG_CLASS_MCP_FANGANZIYUANCHULIQI_H__
#define __VCLS_RG_VOLCANO_APP_RG_CLASS_MCP_FANGANZIYUANCHULIQI_H__

namespace rg_volcano_app
{

class rg_class_MCP_FangAnZiYuanChuLiQi : public rg_FBrowser_ShiJianKongZhi::rg_class_FBrowser_zychlq
{
    DECLARE_VOL_CLASS (rg_volcano_app, rg_class_MCP_FangAnZiYuanChuLiQi)

public:
    virtual BOOL rg_DaKai (INT64 rg_BiaoShiID11, rg_FBrowser_LiuLanQi::FBroRequest& rg_QingQiu7, rg_volcano_base::rg_LuoJiXingLei& rg_ChuLiQingQiu, rg_FBrowser_HuiDiao::rg_class_FBrowser_HuiDiao& rg_HuiDiao6);
    virtual BOOL rg_ChuLiQingQiu1 (INT64 rg_BiaoShiID12, rg_FBrowser_LiuLanQi::FBroRequest& rg_QingQiu8, rg_FBrowser_HuiDiao::rg_class_FBrowser_HuiDiao& rg_HuiDiao7);
    virtual void rg_QuXiangYingTou (INT64 rg_BiaoShiID13, rg_FBrowser_LiuLanQi::rg_class_FBrowser_XiangYing& rg_XiangYing4, rg_volcano_base::rg_ChangZhengShuLei& rg_XiangYingChangDu, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_string& rg_ChongDingXiangDeZhi);
    virtual BOOL rg_HuLue (INT64 rg_BiaoShiID14, INT64 rg_KeHuLueDaXiao, rg_volcano_base::rg_ChangZhengShuLei& rg_BeiHuLueDaXiao, rg_FBrowser_HuiDiao::rg_class_FBrowser_zyhlhd& rg_ZiYuanHuLueHuiDiao);
    virtual BOOL rg_DouQu (INT64 rg_BiaoShiID15, INT rg_ShuChuShuJuZhiZhen, INT rg_DouQuDaXiao, rg_volcano_base::rg_ZhengShuLei& rg_DouRuDaXiao, rg_FBrowser_HuiDiao::rg_class_FBrowser_zydqhd& rg_ZiYuanDouQuHuiDiao);
    virtual void rg_TuiChu (INT64 rg_BiaoShiID16);
    inline_ rg_class_MCP_FangAnZiYuanChuLiQi () { }
    inline_ void _VolObjectInitMembers () { }
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

protected:
    CVolMem rg_XiangYingZiJieJi;
    CVolString rg_DangQianMIME;
};

}

#endif  //__VCLS_RG_VOLCANO_APP_RG_CLASS_MCP_FANGANZIYUANCHULIQI_H__
