
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_HUIDIAO_RG_CLASS_FBROWSER_SHOUQUANHUIDIAO_H__
#define __VCLS_RG_FBROWSER_HUIDIAO_RG_CLASS_FBROWSER_SHOUQUANHUIDIAO_H__

namespace rg_FBrowser_HuiDiao
{

class rg_class_FBrowser_ShouQuanHuiDiao : public CVolObject
{
    DECLARE_VOL_CLASS (rg_FBrowser_HuiDiao, rg_class_FBrowser_ShouQuanHuiDiao)

public:
    CefRefPtr<CefAuthCallback> m_class;
    inline_ rg_class_FBrowser_ShouQuanHuiDiao (CefRefPtr<CefAuthCallback> object) : rg_class_FBrowser_ShouQuanHuiDiao () { m_class = object; }
    inline_ void _CopySelfFromExtra (const rg_class_FBrowser_ShouQuanHuiDiao& objCopyFrom) { m_class = objCopyFrom.m_class; }
    inline_ BOOL _IsSelfEqualExtra (const rg_class_FBrowser_ShouQuanHuiDiao& objCompare) const { return (m_class.get () == objCompare.m_class.get ()); }
    inline_ BOOL_P IsEmpty () const { return m_class.get () == nullptr; }
    inline_ void Set (CefRefPtr<CefAuthCallback> object) { m_class = object; }
    ~rg_class_FBrowser_ShouQuanHuiDiao(){};

public:
    inline_ rg_class_FBrowser_ShouQuanHuiDiao () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_FBROWSER_HUIDIAO_RG_CLASS_FBROWSER_SHOUQUANHUIDIAO_H__
