
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_SHIJIANKONGZHI_RG_CLASS_FBROWSER_LLQSHJ_H__
#define __VCLS_RG_FBROWSER_SHIJIANKONGZHI_RG_CLASS_FBROWSER_LLQSHJ_H__

namespace rg_FBrowser_ShiJianKongZhi
{

class rg_class_FBrowser_llqshj : public CVolObject, public FBroHsBroEvent
{
    DECLARE_EMPTY_VOL_CLASS (rg_FBrowser_ShiJianKongZhi, rg_class_FBrowser_llqshj)

public:
        _FBRO_NEW_DELETE_OVERRIDE();
    public:
        virtual bool OnProcessMessageReceived(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefProcessId source_process,CefRefPtr<CefProcessMessage> message)override;
        virtual bool OnBeforeBrowse(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefRefPtr<CefRequest> request,bool user_gesture,bool is_redirect)override;
        virtual bool OnOpenURLFromTab(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,const CefString& target_url,CefRequestHandler::WindowOpenDisposition target_disposition,bool user_gesture)override;
        virtual bool OnCertificateError(CefRefPtr<CefBrowser> browser,cef_errorcode_t cert_error,const CefString& request_url,CefRefPtr<CefSSLInfo> ssl_info,CefRefPtr<CefCallback> callback) override;
        virtual bool OnSelectClientCertificate(CefRefPtr<CefBrowser> browser,bool isProxy,const CefString& host,int port, CefRefPtr<FBroX509CertificateList> certificates,CefRefPtr<CefSelectClientCertificateCallback> callback)override;
        virtual void OnRenderViewReady(CefRefPtr<CefBrowser> browser)override;
        virtual void OnRenderProcessTerminated(CefRefPtr<CefBrowser> browser,CefRequestHandler::TerminationStatus status, int error_code,const CefString& error_string)override;
        virtual bool GetAuthCredentials(CefRefPtr<CefBrowser> browser,const CefString& origin_url,bool isProxy,const CefString& host,int port,const CefString& realm,const CefString& scheme,CefRefPtr<CefAuthCallback> callback)override;
        virtual void OnAfterCreated(CefRefPtr<CefBrowser> browser,CefRefPtr<CefDictionaryValue> extrainfo)override;
        virtual bool OnBeforePopup(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,int popup_id,const CefString& target_url,const CefString& target_frame_name,
            CefLifeSpanHandler::WindowOpenDisposition target_disposition,bool user_gesture,const CefPopupFeatures& popupFeatures,CefWindowInfo& windowInfo,
            CefBrowserSettings& settings,bool* no_javascript_access,CefRefPtr<FBroUseExtraData> user_settings) override;
        virtual void OnBeforePopupAborted(CefRefPtr<CefBrowser> browser,int popup_id) override;
        virtual void OnBeforeDevToolsPopup(CefRefPtr<CefBrowser> browser,CefWindowInfo& windowInfo,
            CefBrowserSettings& settings,bool* use_default_window,CefRefPtr<FBroUseExtraData> user_settings) override;
        virtual bool DoClose(CefRefPtr<CefBrowser> browser) override;
        virtual void OnBeforeClose(CefRefPtr<CefBrowser> browser) override;
        virtual void OnAddressChange(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,const CefString& url)override;
        virtual void OnTitleChange(CefRefPtr<CefBrowser> browser,const CefString& title)override;
        virtual void OnFaviconURLChange(CefRefPtr<CefBrowser> browser,CefRefPtr<CefListValue> icon_urls) override;
        virtual void OnFullscreenModeChange(CefRefPtr<CefBrowser> browser,bool fullscreen)override;
        virtual bool OnTooltip(CefRefPtr<CefBrowser> browser,CefRefPtr<FBroString> text) override;
        virtual void OnStatusMessage(CefRefPtr<CefBrowser> browser,const CefString& value)override;
        virtual bool OnConsoleMessage(CefRefPtr<CefBrowser> browser,cef_log_severity_t level,const CefString& message,const CefString& source,int line)override;
        virtual bool OnAutoResize(CefRefPtr<CefBrowser> browser,const CefSize& new_size)override;
        virtual void OnLoadingProgressChange(CefRefPtr<CefBrowser> browser,double progress)override;
        virtual bool OnCursorChange(CefRefPtr<CefBrowser> browser,CefCursorHandle cursor,cef_cursor_type_t type,const CefCursorInfo& custom_cursor_info) override;
        virtual void OnMediaAccessChange(CefRefPtr<CefBrowser> browser,bool has_video_access,bool has_audio_access) override;
        virtual CefResourceRequestHandler::ReturnValue OnBeforeResourceLoad(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefRefPtr<CefRequest> request,CefRefPtr<CefCallback> callback)override;
        virtual CefRefPtr<CefResourceHandler> GetResourceHandler(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefRefPtr<CefRequest> request)override;
        virtual void OnResourceRedirect(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefRefPtr<CefRequest> request,CefRefPtr<CefResponse> response,CefRefPtr<FBroString> new_url)override;
        virtual bool OnResourceResponse(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefRefPtr<CefRequest> request,CefRefPtr<CefResponse> response)override;
        virtual CefRefPtr<CefResponseFilter> GetResourceResponseFilter(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefRefPtr<CefRequest> request,CefRefPtr<CefResponse> response)override;
        virtual void OnResourceLoadComplete(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefRefPtr<CefRequest> request,CefRefPtr<CefResponse> response,CefResourceRequestHandler::URLRequestStatus status,int64_t received_content_length)override;
        virtual void OnProtocolExecution(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefRefPtr<CefRequest> request,bool& allow_os_execution)override;
        virtual void OnLoadingStateChange(CefRefPtr<CefBrowser> browser,bool isLoading,bool canGoBack,bool canGoForward)override;
        virtual void OnLoadStart(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefLoadHandler::TransitionType transition_type) override;
        virtual void OnLoadEnd(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,int httpStatusCode)override;
        virtual void OnLoadError(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefLoadHandler::ErrorCode errorCode,const CefString& errorText,const CefString& failedUrl) override;
        virtual void OnBeforeContextMenu(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefRefPtr<CefContextMenuParams> params,CefRefPtr<CefMenuModel> model)override;
        virtual bool RunContextMenu(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefRefPtr<CefContextMenuParams> params,CefRefPtr<CefMenuModel> model,CefRefPtr<CefRunContextMenuCallback> callback)override;
        virtual bool OnContextMenuCommand(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,CefRefPtr<CefContextMenuParams> params,int command_id,CefContextMenuHandler::EventFlags event_flags)override;
        virtual void OnContextMenuDismissed(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame) override;
        virtual bool RunQuickMenu(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,PTELIB_ELEMENT_AT location,POINT_SIZE size,int edit_state_flags,CefRefPtr<CefRunQuickMenuCallback> callback) override;
        virtual bool OnQuickMenuCommand(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,int command_id,int event_flags) override;
        virtual void OnQuickMenuDismissed(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame) override;
        virtual bool CanDownload(CefRefPtr<CefBrowser> browser,const CefString& url,const CefString& request_method) override;
        virtual bool OnBeforeDownload(CefRefPtr<CefBrowser> browser,CefRefPtr<CefDownloadItem> download_item,const CefString& suggested_name,CefRefPtr<CefBeforeDownloadCallback> callback)override;
        virtual void OnDownloadUpdated(CefRefPtr<CefBrowser> browser,CefRefPtr<CefDownloadItem> download_item,CefRefPtr<CefDownloadItemCallback> callback)override;
        virtual bool OnPreKeyEvent(CefRefPtr<CefBrowser> browser,PTELIB_KEYEVENT event,POINT_OSEVENT os_event,bool* is_keyboard_shortcut)override;
        virtual bool OnKeyEvent(CefRefPtr<CefBrowser> browser,PTELIB_KEYEVENT event,POINT_OSEVENT os_event) override;
        virtual bool OnFileDialog(CefRefPtr<CefBrowser> browser,CefDialogHandler::FileDialogMode mode,const CefString& title,const CefString& default_file_path,
    CefRefPtr<FBroCefStringList> accept_filters,CefRefPtr<FBroCefStringList> accept_extensions,CefRefPtr<FBroCefStringList> accept_descriptions,CefRefPtr<CefFileDialogCallback> callback) override;
        virtual bool OnJSDialog(CefRefPtr<CefBrowser> browser,const CefString& origin_url,CefJSDialogHandler::JSDialogType dialog_type,const CefString& message_text,const CefString& default_prompt_text,CefRefPtr<CefJSDialogCallback> callback,bool& suppress_message)override;
        virtual bool OnBeforeUnloadDialog(CefRefPtr<CefBrowser> browser,const CefString& message_text,bool is_reload,CefRefPtr<CefJSDialogCallback> callback) override;
        virtual void OnResetDialogState(CefRefPtr<CefBrowser> browser)override;
        virtual void OnDialogClosed(CefRefPtr<CefBrowser> browser)override;
        virtual void OnTakeFocus(CefRefPtr<CefBrowser> browser, bool next) override;
        virtual bool OnSetFocus(CefRefPtr<CefBrowser> browser, CefFocusHandler::FocusSource source) override;
        virtual void OnGotFocus(CefRefPtr<CefBrowser> browser) override;
        virtual void OnFindResult(CefRefPtr<CefBrowser> browser,int identifier,int count,POINT_RECT selectionRect,int activeMatchOrdinal,bool finalUpdate) override;
        virtual bool OnDragEnter(CefRefPtr<CefBrowser> browser,CefRefPtr<CefDragData> dragData,CefDragHandler::DragOperationsMask mask) override;
        virtual void OnDraggableRegionsChanged(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,const CefRefPtr<FBroDraggableRegion> regions)override;
        virtual void ReceiveRenderProcessMessage(CefRefPtr<CefBrowser> browser,INT64 processid,const CefString& name,char* message, int size) override;
        virtual bool GetRootScreenRect(CefRefPtr<CefBrowser> browser, CefRect& rect) override;
        virtual void GetViewRect(CefRefPtr<CefBrowser> browser, CefRect& rect) override;
        virtual bool GetScreenPoint(CefRefPtr<CefBrowser> browser,int viewX,int viewY,int& screenX,int& screenY)override;
        virtual bool GetScreenInfo(CefRefPtr<CefBrowser> browser,CefScreenInfo& screen_info)override;
        virtual void OnPopupShow(CefRefPtr<CefBrowser> browser, bool show) override;
        virtual void OnPopupSize(CefRefPtr<CefBrowser> browser, const CefRect& rect) override;
        virtual void OnPaint(CefRefPtr<CefBrowser> browser,CefRenderHandler::PaintElementType type,CefRefPtr<FBroRectValueList> dirtyRects,const void* buffer,int width,int height) override;
        virtual void OnAcceleratedPaint(CefRefPtr<CefBrowser> browser,CefRenderHandler::PaintElementType type,CefRefPtr<FBroRectValueList> dirtyRects,const CefAcceleratedPaintInfo& info)override;
        virtual bool StartDragging(CefRefPtr<CefBrowser> browser,CefRefPtr<CefDragData> drag_data,CefRenderHandler::DragOperationsMask allowed_ops,int x,int y)override;
        virtual void UpdateDragCursor(CefRefPtr<CefBrowser> browser,CefRenderHandler::DragOperation operation) override;
        virtual void OnScrollOffsetChanged(CefRefPtr<CefBrowser> browser,double x,double y) override;
        virtual void OnImeCompositionRangeChanged(CefRefPtr<CefBrowser> browser,const CefRange& selected_range,CefRefPtr<FBroRectValueList> character_bounds)override;
        virtual void OnTextSelectionChanged(CefRefPtr<CefBrowser> browser,const CefString& selected_text,const CefRange& selected_range)override;
        virtual void OnVirtualKeyboardRequested(CefRefPtr<CefBrowser> browser,CefRenderHandler::TextInputMode input_mode) override;
        virtual void OnDocumentAvailableInMainFrame(CefRefPtr<CefBrowser> browser) override;
        virtual bool GetAudioParameters(CefRefPtr<CefBrowser> browser,CefAudioParameters& params) override;
        virtual void OnAudioStreamStarted(CefRefPtr<CefBrowser> browser,const CefAudioParameters& params,int channels) override;
        virtual void OnAudioStreamPacket(CefRefPtr<CefBrowser> browser,const float** data,int frames,int64_t pts) override;
        virtual void OnAudioStreamStopped(CefRefPtr<CefBrowser> browser) override;
        virtual void OnAudioStreamError(CefRefPtr<CefBrowser> browser,const CefString& message) override;
        virtual bool OnChromeCommand(CefRefPtr<CefBrowser> browser,int command_id,cef_window_open_disposition_t disposition) override;
        virtual void OnFrameCreated(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame) override;
        virtual void OnFrameAttached(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,bool reattached) override;
        virtual void OnFrameDetached(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame) override;
        virtual void OnMainFrameChanged(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> old_frame,CefRefPtr<CefFrame> new_frame) override;
        virtual bool OnRequestMediaAccessPermission(CefRefPtr<CefBrowser> browser,CefRefPtr<CefFrame> frame,const CefString& requesting_origin,uint32_t requested_permissions,CefRefPtr<CefMediaAccessCallback> callback) override;
        virtual bool OnShowPermissionPrompt(CefRefPtr<CefBrowser> browser,uint64_t prompt_id,const CefString& requesting_origin,uint32_t requested_permissions,CefRefPtr<CefPermissionPromptCallback> callback) override;
        virtual void OnDismissPermissionPrompt(CefRefPtr<CefBrowser> browser,uint64_t prompt_id,cef_permission_request_result_t result) override;

public:
    virtual BOOL rg_LiuLanQi_ShouDaoXiaoXi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi72, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia33, INT rg_YuanJinCheng1, rg_FBrowser_LiuLanQi::FBroProcessMessage& rg_XiaoXi14);
    virtual BOOL rg_LiuLanQi_JiJiangDaoHang (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi73, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia34, rg_FBrowser_LiuLanQi::FBroRequest& rg_QingQiu13, BOOL rg_YongHuDongZuo1, BOOL rg_ShiFouChongDingXiang1);
    virtual BOOL rg_LiuLanQi_CongBiaoQianDaKaiDeZhi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi74, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia35, CVolString& rg_MuDeDeZhi, INT rg_MuDePeiZhi, BOOL rg_YongHuHangWei);
    virtual BOOL rg_LiuLanQi_QingQiuZhengShuCuoWu (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi75, INT rg_CuoWuDaiMa3, CVolString& rg_MuBiaoDeZhi1, rg_FBrowser_LiuLanQi::FBroSSLInfo& rg_SSLXinXi, rg_FBrowser_HuiDiao::rg_class_FBrowser_HuiDiao& rg_QingQiuHuiDiao);
    virtual BOOL rg_LiuLanQi_XuanZeKeHuDuanZhengShu (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi76, BOOL rg_ShiFouWeiDaiLi, CVolString& rg_ZhuJiDeZhi1, INT rg_DuanKou6, rg_FBrowser_value::rg_class_FBrowser_X509zhshshz& rg_X509ZhengShuQingChan, rg_FBrowser_HuiDiao::rg_class_FBrowser_xzzhshhd& rg_XuanZeZhengShuHuiDiao);
    virtual void rg_LiuLanQi_XuanRanShiTu (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi77);
    virtual void rg_LiuLanQi_XuanRanYiWaiZhongZhi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi78, INT rg_ZhuangTai2, INT rg_CuoWuMa5, CVolString& rg_CuoWuWenBen7);
    virtual BOOL rg_LiuLanQi_HuoDeXuShouQuanZhengShu (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi79, CVolString& rg_YuanDeZhi1, BOOL rg_ShiFouWeiDaiLi1, CVolString& rg_ZhuJi, INT rg_DuanKou7, CVolString& rg_YuMing, CVolString& rg_RenZhengFangAn, rg_FBrowser_HuiDiao::rg_class_FBrowser_ShouQuanHuiDiao& rg_ShouQuanHuiDiao);
    virtual void rg_LiuLanQi_ChuangJianWanBi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi80, rg_FBrowser_value::FBroDictionaryValue& rg_EWaiXinXi4);
    virtual BOOL rg_LiuLanQi_JiJiangDaKaiXinChuangKou (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi81, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia36, INT rg_DanChuangID2, CVolString& rg_DeZhi4, CVolString& rg_MuBiaoKuangJiaMingChen1, INT rg_MuBiaoLeiXing1, BOOL rg_YongHuShouShi1, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_DanChuGongNeng& rg_DanChuGongNeng1, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_ChuangKouXinXi& rg_ChuangKouXinXi2, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_LiuLanQiPeiZhi& rg_LiuLanQiSheZhi1, rg_volcano_base::rg_LuoJiXingLei& rg_MoJSFangWen1, rg_FBrowser_LiuLanQi::rg_class_FBrowser_yhewpzh& rg_YongHuEWaiPeiZhi2);
    virtual void rg_LiuLanQi_DaKaiXinChuangKouShiBai (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi82, INT rg_DanChuangID3);
    virtual void rg_LiuLanQi_JiJiangDaKaiKaiFaZheChuangKou (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi83, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_ChuangKouXinXi& rg_ChuangKouXinXi3, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_LiuLanQiPeiZhi& rg_LiuLanQiSheZhi2, rg_volcano_base::rg_LuoJiXingLei& rg_ShiYongMoRenChuangKou, rg_FBrowser_LiuLanQi::rg_class_FBrowser_yhewpzh& rg_YongHuEWaiPeiZhi3);
    virtual BOOL rg_LiuLanQi_ZhiHangGuanBi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi84);
    virtual void rg_LiuLanQi_JiJiangGuanBi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi85);
    virtual void rg_LiuLanQi_DeZhiBeiGaiBian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi86, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia37, CVolString& rg_DeZhi5);
    virtual void rg_LiuLanQi_BiaoTiBeiGaiBian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi87, CVolString& rg_BiaoTi2);
    virtual void rg_LiuLanQi_WangYeTuBiaoBeiGaiBian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi88, rg_FBrowser_value::FBroListValue& rg_TuBiaoDeZhiLieBiao1);
    virtual void rg_LiuLanQi_QuanBingMoShiBeiGaiBian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi89, BOOL rg_QuanBing1);
    virtual BOOL rg_LiuLanQi_GongJuLanBeiGaiBian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi90, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_string& rg_NeiRong3);
    virtual void rg_LiuLanQi_ZhuangTaiLanBeiGaiBian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi91, CVolString& rg_NeiRong4);
    virtual BOOL rg_LiuLanQi_KongZhiTaiXiaoXi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi92, INT rg_RiZhiJiBie3, CVolString& rg_XiaoXi15, CVolString& rg_NeiRong5, INT rg_Hang1);
    virtual BOOL rg_LiuLanQi_ZiDongDiaoZhengCheCun (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi93, INT rg_GaoDu11, INT rg_KuanDu11);
    virtual void rg_LiuLanQi_JiaZaiJinDuBeiGaiBian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi94, INT rg_JinDu3);
    virtual BOOL rg_LiuLanQi_GuangBiaoBeiGaiBian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi95, INT rg_GuangBiaoGouBing, INT rg_LeiXing5, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_GuangBiaoXinXi& rg_GuangBiaoXinXi);
    virtual void rg_LiuLanQi_JiJiangGaiBianMeiTiFangWen (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi96, BOOL rg_BaoHanShiPinFangWen, BOOL rg_BaoHanYinPinFangWen);
    virtual BOOL rg_LiuLanQi_JiJiangJiaZaiZiYuan (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi97, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia38, rg_FBrowser_LiuLanQi::FBroRequest& rg_QingQiu14, rg_FBrowser_HuiDiao::rg_class_FBrowser_HuiDiao& rg_QingQiuHuiDiao1);
    virtual void rg_LiuLanQi_HuoQuZiYuanChuLiQi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi98, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia39, rg_FBrowser_LiuLanQi::FBroRequest& rg_QingQiu15, rg_FBrowser_FuZhu::rg_class_FBrowser_shzhzychlq& rg_SheZhiZiYuanChuLiQi1);
    virtual void rg_LiuLanQi_ChongDingXiangZiYuan (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi99, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia40, rg_FBrowser_LiuLanQi::FBroRequest& rg_QingQiu16, rg_FBrowser_LiuLanQi::rg_class_FBrowser_XiangYing& rg_XiangYing6, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_string& rg_XinDeZhi2);
    virtual BOOL rg_LiuLanQi_XiangYingZiYuan (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi100, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia41, rg_FBrowser_LiuLanQi::FBroRequest& rg_QingQiu17, rg_FBrowser_LiuLanQi::rg_class_FBrowser_XiangYing& rg_XiangYing7);
    virtual void rg_LiuLanQi_HuoQuZiYuanGuoLuQi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi101, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia42, rg_FBrowser_LiuLanQi::FBroRequest& rg_QingQiu18, rg_FBrowser_LiuLanQi::rg_class_FBrowser_XiangYing& rg_XiangYing8, rg_FBrowser_FuZhu::rg_class_FBrowser_shzhzyglq& rg_SheZhiZiYuanGuoLuQi1);
    virtual void rg_LiuLanQi_ZiYuanJiaZaiWanBi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi102, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia43, rg_FBrowser_LiuLanQi::FBroRequest& rg_QingQiu19, rg_FBrowser_LiuLanQi::rg_class_FBrowser_XiangYing& rg_XiangYing9, INT rg_ZhuangTai3, INT64 rg_ZiYuanDaXiao);
    virtual void rg_LiuLanQi_ChuLiXieYiQingQiu (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi103, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia44, rg_FBrowser_LiuLanQi::FBroRequest& rg_QingQiu20, rg_volcano_base::rg_LuoJiXingLei& rg_YunXuCaoZuoJiTongZhiHang);
    virtual void rg_LiuLanQi_ZaiRuZhuangTaiBeiGaiBian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi104, BOOL rg_ZaiRuZhong1, BOOL rg_ShiFouNengHouTui1, BOOL rg_ShiFouNengQianJin1);
    virtual void rg_LiuLanQi_ZaiRuKaiShi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi105, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia45, INT rg_GuoDuLeiXing3);
    virtual void rg_LiuLanQi_ZaiRuJieShu (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi106, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia46, INT rg_ZhuangTaiMa6);
    virtual void rg_LiuLanQi_ZaiRuCuoWu (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi107, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia47, INT rg_CuoWuMa6, CVolString& rg_CuoWuWenBen8, CVolString& rg_ShiBaiDeZhi3);
    virtual void rg_LiuLanQi_JiJiangDaKaiCaiChan (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi108, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia48, rg_FBrowser_LiuLanQi::FBroContextMenuParams& rg_CaiChanHuanJing, rg_FBrowser_LiuLanQi::FBroMenuModel& rg_CaiChanMoShi);
    virtual BOOL rg_LiuLanQi_CaiChanBeiDiaoYong (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi109, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia49, rg_FBrowser_LiuLanQi::FBroContextMenuParams& rg_CaiChanHuanJing1, rg_FBrowser_LiuLanQi::FBroMenuModel& rg_CaiChanMoShi1, rg_FBrowser_HuiDiao::rg_class_FBrowser_yhmlcchhd& rg_YunHangMingLingCaiChanHuiDiao);
    virtual BOOL rg_LiuLanQi_CaiChanBeiDianJi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi110, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia50, rg_FBrowser_LiuLanQi::FBroContextMenuParams& rg_CaiChanHuanJing2, INT rg_MingLingID41, INT rg_ShiJianBiaoShi3);
    virtual void rg_LiuLanQi_CaiChanBeiGuanBi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi111, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia51);
    virtual BOOL rg_LiuLanQi_JiJiangYunHangKuaiJieCaiChan (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi112, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia52, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_WeiZhi& rg_WeiZhi19, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_CheCun& rg_CheCun10, INT rg_BianJiZhuangTaiBiaoShi, rg_FBrowser_HuiDiao::rg_class_FBrowser_kjcchhd& rg_HuiDiao7);
    virtual BOOL rg_LiuLanQi_JiJiangYunHangKuaiJieCaiChanMingLing (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi113, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia53, INT rg_MingLingID42, INT rg_ShiJianBiaoShi4);
    virtual void rg_LiuLanQi_JiJiangQuXiaoKuaiJieCaiChan (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi114, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia54);
    virtual BOOL rg_LiuLanQi_KeXiaZai (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi115, CVolString& rg_DeZhi6, CVolString& rg_QingQiuFangFa3);
    virtual BOOL rg_LiuLanQi_JiJiangXiaZai (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi116, rg_FBrowser_LiuLanQi::FBroDownloadItem& rg_XiaZai2, CVolString& rg_TuiJianMing1, rg_FBrowser_HuiDiao::rg_class_FBrowser_jjxzhd& rg_XiaZaiHuiDiao3);
    virtual void rg_LiuLanQi_ZhengZaiXiaZai (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi117, rg_FBrowser_LiuLanQi::FBroDownloadItem& rg_XiaZai3, rg_FBrowser_HuiDiao::rg_class_FBrowser_zhzxzhd& rg_XiaZaiHuiDiao4);
    virtual BOOL rg_LiuLanQi_AnXiaMouJian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi118, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_AnJianShiJian& rg_AnJianShiJian3, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_JiTongShiJian& rg_JiTongShiJian1, BOOL rg_ShiFouKuaiJieJian1);
    virtual BOOL rg_LiuLanQi_AnXiaMouJianHou (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi119, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_AnJianShiJian& rg_AnJianShiJian4, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_JiTongShiJian& rg_JiTongShiJian2);
    virtual BOOL rg_LiuLanQi_JiJiangDaKaiDuiHuaKuang (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi120, INT rg_MoShi1, CVolString& rg_BiaoTi3, CVolString& rg_MoRenLuJing1, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_WenBenShuZu& rg_GuoLuQi2, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_WenBenShuZu& rg_KuoZhanMing2, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_WenBenShuZu& rg_JieShouLeiXing1, rg_FBrowser_HuiDiao::rg_class_FBrowser_dhkhd& rg_DuiHuaKuangHuiDiao2);
    virtual BOOL rg_LiuLanQi_JSJiJiangDaKaiDuiHuaKuang (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi121, CVolString& rg_YuanDeZhi2, INT rg_DuiHuaKuangLeiXing1, CVolString& rg_XiaoXiWenBen4, CVolString& rg_MoRenDiShiWenBen1, rg_FBrowser_HuiDiao::rg_class_FBrowser_JSdhkhd& rg_HuiDiao8, rg_volcano_base::rg_LuoJiXingLei& rg_JinZhiXiaoXi);
    virtual BOOL rg_LiuLanQi_JSJiJiangDaKaiLiKaiDuiHuaKuang (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi122, CVolString& rg_XiaoXiWenBen5, BOOL rg_ChongZai1, rg_FBrowser_HuiDiao::rg_class_FBrowser_JSdhkhd& rg_HuiDiao9);
    virtual void rg_LiuLanQi_JSChongZhiDuiHuaKuang (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi123);
    virtual void rg_LiuLanQi_JSDuiHuaKuangGuanBi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi124);
    virtual void rg_LiuLanQi_JiJiangShiQuJiaoDian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi125, BOOL rg_XiaYiGe1);
    virtual BOOL rg_LiuLanQi_QingQiuJiaoDian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi126, INT rg_YuanLeiXing);
    virtual void rg_LiuLanQi_ShouDaoJiaoDian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi127);
    virtual void rg_LiuLanQi_ChaZhaoFanKui (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi128, INT rg_ID9, INT rg_ShuLiang1, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_JuXingWeiZhi& rg_XuanZeWeiZhi1, INT rg_ShunXu1, BOOL rg_ZuiHouGengXin1);
    virtual BOOL rg_LiuLanQi_TuoYeJinRu (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi129, rg_FBrowser_value::FBroDragData& rg_TuoYeShuJu, INT rg_TuoDongLeiXing);
    virtual void rg_LiuLanQi_TuoYeOuYuGaiBian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi130, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia55, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_TuoYeWeiZhiShuZu& rg_TuoYeWeiZhi);
    virtual void rg_JinChengJianXiaoXi_ShouDaoXuanRanJinChengXiaoXi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi131, INT rg_XuanRanJinChengID, CVolString& rg_XiaoXiMing1, CVolMem& rg_XiaoXiNeiRong1);
    virtual BOOL rg_LiBingXuanRan_HuoQuGenBingMuJuXing (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi132, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_JuXingWeiZhi& rg_JuXing);
    virtual void rg_LiBingXuanRan_HuoQuShiTuJuXing (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi133, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_JuXingWeiZhi& rg_JuXing1);
    virtual BOOL rg_LiBingXuanRan_HuoQuBingMuDian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi134, INT rg_ShiTuHengZuoBiao, INT rg_ShiTuZongZuoBiao, rg_volcano_base::rg_ZhengShuLei& rg_BingMuHengZuoBiao, rg_volcano_base::rg_ZhengShuLei& rg_BingMuZongZuoBiao);
    virtual BOOL rg_LiBingXuanRan_HuoQuChuangKouXinXi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi135, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_BingMuXinXi& rg_BingMuXinXi);
    virtual void rg_LiBingXuanRan_JiJiangXianShiDanChuang (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi136, BOOL rg_XianShi);
    virtual void rg_LiBingXuanRan_YiDongDiaoZhengDanChuang (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi137, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_JuXingWeiZhi& rg_JuXing2);
    virtual void rg_LiBingXuanRan_JiangBeiHuiZhi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi138, INT rg_LeiXing6, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_JuXingWeiZhiShuZu& rg_JuXingQingChan, INT rg_HuanCunZhiZhen1, INT rg_KuanDu12, INT rg_GaoDu12);
    virtual void rg_LiBingXuanRan_JiangBeiJiaSuHuiZhi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi139, INT rg_LeiXing7, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_JuXingWeiZhiShuZu& rg_JuXingQingChan1, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_JiaSuHuiZhiXinXi& rg_JiaSuHuiZhiXinXi);
    virtual BOOL rg_LiBingXuanRan_KaiShiTuoYe (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi140, rg_FBrowser_value::FBroDragData& rg_TuoYeShuJu1, INT rg_TuoYeCaoZuoLeiXing, INT rg_HengZuoBiao8, INT rg_ZongZuoBiao8);
    virtual void rg_LiBingXuanRan_GengXinTuoDongGuangBiao (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi141, INT rg_TuoYeCaoZuoLeiXing1);
    virtual void rg_LiBingXuanRan_GunDongPianYiLiangGaiBian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi142, DOUBLE rg_HengZuoBiao9, DOUBLE rg_ZongZuoBiao9);
    virtual void rg_LiBingXuanRan_IMEFanWeiGaiBian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi143, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_FanWei& rg_XuanZeFanWei, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_JuXingWeiZhiShuZu& rg_ZiFuFanWei);
    virtual void rg_LiBingXuanRan_WenBenXuanZeGaiBian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi144, CVolString& rg_XuanZeWenBen, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_FanWei& rg_XuanZeFanWei1);
    virtual void rg_LiBingXuanRan_XuNiJianPanQingQiu (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi145, INT rg_ShuRuLeiXing);
    virtual void rg_LiuLanQi_JiJiangChuangJianZhuKuangJiaDocument (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi146);
    virtual BOOL rg_LiuLanQi_HuoQuYinPinCanShu (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi147, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_YinPinCanShu& rg_param20);
    virtual void rg_LiuLanQi_JiJiangQiDongYinPinLiu (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi148, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_YinPinCanShu& rg_param21, INT rg_TongDao);
    virtual void rg_LiuLanQi_ShouDaoYinPinLiuBao (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi149, INT rg_ShuJuZhiZhen13, INT rg_ZhengShu2, INT64 rg_pts);
    virtual void rg_LiuLanQi_JiJiangJieShuYinPinLiu (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi150);
    virtual void rg_LiuLanQi_YinPinLiuChuXianCuoWu (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi151, CVolString& rg_CuoWuXinXi1);
    virtual BOOL rg_LiuLanQi_JiJiangZhiHangChromeMingLing (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi152, INT rg_MingLingID43, INT rg_PeiZhi);
    virtual void rg_LiuLanQi_JiJiangChuangJianKuangJia (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi153, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia56);
    virtual void rg_LiuLanQi_JiJiangLianJieKuangJia (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi154, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia57, BOOL rg_ZaiCiLianJie);
    virtual void rg_LiuLanQi_JiJiangCaLiKuangJia (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi155, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia58);
    virtual void rg_LiuLanQi_JiJiangGaiBianZhuKuangJia (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi156, rg_FBrowser_LiuLanQi::FBroFrame& rg_JiuKuangJia1, rg_FBrowser_LiuLanQi::FBroFrame& rg_XinKuangJia1);
    virtual BOOL rg_LiuLanQi_JiJiangQingQiuMeiTiFangWenXuKe (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi157, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia59, CVolString& rg_QingQiuYuan, INT rg_QingQiuXuKe, rg_FBrowser_HuiDiao::rg_class_FBrowser_mtjrhd& rg_HuiDiao10);
    virtual BOOL rg_LiuLanQi_JiJiangXianShiXuKeDiShi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi158, INT64 rg_DiShiID, CVolString& rg_QingQiuYuan1, INT rg_QingQiuXuKe1, rg_FBrowser_HuiDiao::rg_class_FBrowser_qxdshhd& rg_HuiDiao11);
    virtual void rg_LiuLanQi_JiJiangGuanBiXuKeDiShi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi159, INT64 rg_DiShiID1, INT rg_JieGuoBiaoShi1);
    rg_class_FBrowser_llqshj ();
    void _VolObjectInitMembers ();
    virtual ~rg_class_FBrowser_llqshj ();

protected:
    void rg_class_FBrowser_llqshj_class_chshh ();
    void rg_class_FBrowser_llqshj_class_ql ();
};

}

#endif  //__VCLS_RG_FBROWSER_SHIJIANKONGZHI_RG_CLASS_FBROWSER_LLQSHJ_H__
