
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_RG_CONST_RG_JSONJIEXI_H__
#define __VCLS_RG_FBROWSER_RG_CONST_RG_JSONJIEXI_H__

namespace rg_FBrowser_rg_const
{

class rg_JSONJieXi : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_FBrowser_rg_const, rg_JSONJieXi)

public:
    inline_ rg_JSONJieXi () { }
    inline_ void _VolObjectInitMembers () { }

public:
    static const INT rg_RFC;
};

}

#endif  //__VCLS_RG_FBROWSER_RG_CONST_RG_JSONJIEXI_H__
