
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_LIULANQI_FBROV8CONTEXT_H__
#define __VCLS_RG_FBROWSER_LIULANQI_FBROV8CONTEXT_H__

namespace rg_FBrowser_LiuLanQi
{

class FBroV8Context : public CVolObject
{
    DECLARE_VOL_CLASS (rg_FBrowser_LiuLanQi, FBroV8Context)

public:
    CefRefPtr<CefV8Context> m_class;
    inline_ FBroV8Context (CefRefPtr<CefV8Context> object) : FBroV8Context () { m_class = object; }
    inline_ void _CopySelfFromExtra (const FBroV8Context& objCopyFrom) { m_class = objCopyFrom.m_class; }
    inline_ BOOL _IsSelfEqualExtra (const FBroV8Context& objCompare) const { return (m_class.get () == objCompare.m_class.get ()); }
    inline_ BOOL IsEmpty () const { return m_class.get () == nullptr; }
    inline_ void Set (CefRefPtr<CefV8Context> object) { m_class = object; }
    ~FBroV8Context(){};

public:
    inline_ FBroV8Context () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_FBROWSER_LIULANQI_FBROV8CONTEXT_H__
