
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_APP_RG_MCP_JITONGFENPA_H__
#define __VCLS_RG_VOLCANO_APP_RG_MCP_JITONGFENPA_H__

namespace rg_volcano_app
{

class rg_MCP_JiTongFenPa : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_app, rg_MCP_JiTongFenPa)

public:
    static CVolString CALLBACK rg_FenLeiFenPa_JiTongCaoZuo (CVolString& rg_MingLingID32, CVolString& rg_FangFaMing11, rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei& rg_CanShuJSON20);
    inline_ rg_MCP_JiTongFenPa () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_APP_RG_MCP_JITONGFENPA_H__
