
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HUOSHANSHICHUANG_JSONZHICHI_RG_YYJSONSHUZULEI_H__
#define __VCLS_RG_HUOSHANSHICHUANG_JSONZHICHI_RG_YYJSONSHUZULEI_H__

namespace rg_HuoShanShiChuang_JSONZhiChi
{

class rg_YYJSONShuZuLei : public rg_volcano_base::rg_KuoZhanDuiXiangLei
{
    DECLARE_VOL_CLASS (rg_HuoShanShiChuang_JSONZhiChi, rg_YYJSONShuZuLei)

protected:
    inline_ void _OnInitExtra ()  {  m_pRefObject = new CRefObjectWithData<CVolJsonMutArray>; }
    inline_ void _OnCleanupExtra ()  { if (m_pRefObject != NULL)  m_pRefObject->Release (); }
    inline_ void _CopySelfFromExtra (const rg_YYJSONShuZuLei& objCopyFrom)  { SetRefObject (objCopyFrom.m_pRefObject); }
    inline_ BOOL _IsSelfEqualExtra (const rg_YYJSONShuZuLei& objCompare) const  { return (m_pRefObject == objCompare.m_pRefObject); }
    CRefObject* m_pRefObject;
public:
    void SetRefObject (CRefObject* pRefObject);
    void TakeOverNewRefObject (CRefObject* pNewRefObject);
    inline_ CRefObject* GetRefObject ()  {  return m_pRefObject;  }
public:
    inline_ CVolJsonMutArray& data ()  { return ((CRefObjectWithData<CVolJsonMutArray>*)m_pRefObject)->m_data; }
    inline_ CVolJsonMutArray* pdata ()  { return &((CRefObjectWithData<CVolJsonMutArray>*)m_pRefObject)->m_data; }
inline_ rg_YYJSONShuZuLei (yyjson_mut_val* arr, CRefJsonMutObjectPtrWithData* pRefObject) : rg_YYJSONShuZuLei()  { data().SetArray(arr, pRefObject); }

public:
    BOOL rg_ChuangJianZiWenBenShuJu (rg_volcano_base::rg_WenBenShuZuLei& rg_member15);
    BOOL rg_JiaRuChengYuan44 (rg_YYJSONDuiXiangLei& rg_TianJiaZhi4);
    BOOL rg_JiaRuZhengShuChengYuan1 (INT rg_value138);
    BOOL rg_JiaRuXiaoShuChengYuan1 (DOUBLE rg_value139);
    BOOL rg_JiaRuWenBenChengYuan1 (CVolString& rg_value140);
    virtual void GetDumpString (CVolString& rg_ZhanShiNeiRong91, INT rg_ZuiDaZhanShiShuJuCheCun91);
    rg_YYJSONShuZuLei ();
    void _VolObjectInitMembers ();
    virtual ~rg_YYJSONShuZuLei ();
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

protected:
    CVolObjectArray rg_ChengYuanShuZu1;
};

}

#endif  //__VCLS_RG_HUOSHANSHICHUANG_JSONZHICHI_RG_YYJSONSHUZULEI_H__
