
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_RG_CONST_RG_ANJIANSHIJIAN2_H__
#define __VCLS_RG_FBROWSER_RG_CONST_RG_ANJIANSHIJIAN2_H__

namespace rg_FBrowser_rg_const
{

class rg_AnJianShiJian2 : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_FBrowser_rg_const, rg_AnJianShiJian2)

public:
    inline_ rg_AnJianShiJian2 () { }
    inline_ void _VolObjectInitMembers () { }

public:
    static const INT rg_ChanJi;
    static const INT rg_AnXia;
    static const INT rg_FangKai;
};

}

#endif  //__VCLS_RG_FBROWSER_RG_CONST_RG_ANJIANSHIJIAN2_H__
