
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_WENBENLEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_WENBENLEI_H__

namespace rg_volcano_base
{

class rg_WenBenLei : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_base, rg_WenBenLei)

public:
    static CVolMem CALLBACK rg_WenBenDaoUTF (CVolString& rg_SuoYuCaoZuoDeWenBen5, BOOL rg_ShiFouBaoGuaJieShuLingZiFu);
    static CVolString CALLBACK rg_UTF8DaoWenBen (CVolMem& rg_SuoYuZhuaiHuanDeUTF8WenBenShuJu);
    static CVolString CALLBACK rg_ZiJieJiDaoWenBen (CVolMem& rg_SuoYuZhuaiHuanDeWenBenShuJu1);
    inline_ rg_WenBenLei () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_WENBENLEI_H__
