
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_VALUE_FBRODRAGDATA_H__
#define __VCLS_RG_FBROWSER_VALUE_FBRODRAGDATA_H__

namespace rg_FBrowser_value
{

class FBroDragData : public CVolObject
{
    DECLARE_VOL_CLASS (rg_FBrowser_value, FBroDragData)

public:
    CefRefPtr<CefDragData> m_class;
    inline_ FBroDragData (CefRefPtr<CefDragData> object) : FBroDragData () { m_class = object; }
    inline_ void _CopySelfFromExtra (const FBroDragData& objCopyFrom) { m_class = objCopyFrom.m_class; }
    inline_ BOOL _IsSelfEqualExtra (const FBroDragData& objCompare) const { return (m_class.get () == objCompare.m_class.get ()); }
    inline_ BOOL_P IsEmpty () const { return m_class.get () == nullptr; }
    inline_ void Set(CefRefPtr<CefDragData> object) { m_class = object; }
    ~FBroDragData(){};

public:
    inline_ FBroDragData () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_FBROWSER_VALUE_FBRODRAGDATA_H__
