
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_SHUJULEIXING_RG_FBROWSER_JITONGSHIJIAN_H__
#define __VCLS_RG_FBROWSER_SHUJULEIXING_RG_FBROWSER_JITONGSHIJIAN_H__

namespace rg_FBrowser_ShuJuLeiXing
{

class rg_FBrowser_JiTongShiJian : public CVolObject
{
    DECLARE_VOL_CLASS (rg_FBrowser_ShuJuLeiXing, rg_FBrowser_JiTongShiJian)

public:
    ~rg_FBrowser_JiTongShiJian(){}
    rg_FBrowser_JiTongShiJian (E_OSEVENT data) : rg_FBrowser_JiTongShiJian () {
      m_data = data;
      ToHsData();
    }
    POINT_OSEVENT ToFBroData();
    void ToHsData();
    E_OSEVENT m_data;

public:
    rg_FBrowser_JiTongShiJian ();
    void _VolObjectInitMembers ();
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

public:
    INT rg_GouBing;
    INT rg_XiaoXi12;
    INT64 rg_wParam;
    INT64 rg_lParam;
    INT rg_ShiJian2;
    rg_FBrowser_WeiZhi rg_WeiZhi18;
};

}

#endif  //__VCLS_RG_FBROWSER_SHUJULEIXING_RG_FBROWSER_JITONGSHIJIAN_H__
