
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_SHUJULEIXING_RG_FBROWSER_COOKIESHUJU_H__
#define __VCLS_RG_FBROWSER_SHUJULEIXING_RG_FBROWSER_COOKIESHUJU_H__

namespace rg_FBrowser_ShuJuLeiXing
{

class rg_FBrowser_CookieShuJu : public CVolObject
{
    DECLARE_VOL_CLASS (rg_FBrowser_ShuJuLeiXing, rg_FBrowser_CookieShuJu)

public:
    rg_FBrowser_CookieShuJu (E_COOKIEDATA data) : rg_FBrowser_CookieShuJu () { FBroUnit::CopyFBroData(data,&m_data);ToHsData();}
    ~rg_FBrowser_CookieShuJu(){release();}
    POINT_COOKIEDATA ToFBroData();
    void ToHsData();
    void release();
    E_COOKIEDATA m_data;

public:
    rg_FBrowser_CookieShuJu ();
    void _VolObjectInitMembers ();
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

public:
    CVolString rg_Ming10;
    CVolString rg_value91;
    CVolString rg_Yu;
    CVolString rg_LuJing4;
    BOOL rg_ShiFouZhiYouhttp;
    BOOL rg_ShiFouYouGuoJiShiJian;
    rg_FBrowser_ShiJianLeiXing rg_GuoJiShiJian1;
    rg_FBrowser_ShiJianLeiXing rg_FangWenShiJian;
    BOOL rg_AnQuanChuanShu;
    INT rg_TongZhan;
    INT rg_YouXianJi2;
};

}

#endif  //__VCLS_RG_FBROWSER_SHUJULEIXING_RG_FBROWSER_COOKIESHUJU_H__
