
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

namespace rg_volcano_windows_SQLiteshjk
{

rg_SQLiteShuJuKuLei::rg_SQLiteShuJuKuLei ()
{
    _VolObjectInitMembers ();
}

void rg_SQLiteShuJuKuLei::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

BOOL rg_SQLiteShuJuKuLei::_IsSelfEqual (const rg_SQLiteShuJuKuLei& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_SQLiteShuJuKuLei::_CopySelfFrom (const rg_SQLiteShuJuKuLei& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

rg_SQLiteShuJuKuLei::~rg_SQLiteShuJuKuLei ()
{
    OnBeforeObjectCleanup ();
    _OnCleanupExtra ();
}
void rg_SQLiteShuJuKuLei::SetRefObject (CRefObject* pRefObject)
{
    ASSERT_R_DATA_OR_NULL (pRefObject);
    if (pRefObject != NULL)  pRefObject->AddRef ();
    if (m_pRefObject != NULL)  m_pRefObject->Release ();
    m_pRefObject = pRefObject;
}
void rg_SQLiteShuJuKuLei::TakeOverNewRefObject (CRefObject* pNewRefObject)
{
    ASSERT (pNewRefObject != m_pRefObject);
    ASSERT_R_DATA_OR_NULL (pNewRefObject);
    if (m_pRefObject != NULL)  m_pRefObject->Release ();
    m_pRefObject = pNewRefObject;
}

BOOL rg_SQLiteShuJuKuLei::rg_DaKai10 (CVolString& rg_WenJianMing12, INT rg_XuanXiangWei, CVolString& rg_VFSDuiXiang)
{
    CU8String str(rg_VFSDuiXiang.GetText ());
    const char* vfs = (rg_VFSDuiXiang.IsEmpty() ? NULL : str.GetText());
    sqlite3* mSqlite3 = NULL;
    if (sqlite3_open_v2((const char*)CU8String(rg_WenJianMing12.GetText ()).GetText(), &mSqlite3, rg_XuanXiangWei == -1 ? (SQLITE_OPEN_CREATE | SQLITE_OPEN_READWRITE) : rg_XuanXiangWei, vfs) == SQLITE_OK)
    {
        data().Close();
        data().SetData(mSqlite3);
        return TRUE;
    }
    return FALSE;
}

INT rg_SQLiteShuJuKuLei::rg_ZhiHangSQLYuGou (CVolString& rg_YuGouNeiRong, CVolString& rg_CuoWuNeiRong)
{
    if (GetSqlite () == NULL) return -100;
    char *ErrMsg = 0;
    int result = sqlite3_exec(GetSqlite(), (const char*)CU8String(rg_YuGouNeiRong.GetText ()).GetText(), NULL, NULL, &ErrMsg);
    if (ErrMsg) rg_CuoWuNeiRong.SetText(ErrMsg);
    sqlite3_free(ErrMsg);
    return result;
}

rg_SQLiteJiLuJiLei rg_SQLiteShuJuKuLei::rg_QuJiLuJi (CVolString& rg_YuGouNeiRong1, INT rg_NeiRongPianYi)
{
    sqlite3_stmt* pStmt = NULL;
    if (GetSqlite()){
        sqlite3_prepare_v2(GetSqlite(), (const char*)CU8String(rg_YuGouNeiRong1.GetText ()).GetText(), rg_NeiRongPianYi, &pStmt, NULL);
    }
    return rg_SQLiteJiLuJiLei((INT_P)pStmt);
}

void rg_SQLiteShuJuKuLei::ra_SQLiteShuJuKuLei_DengDaiShuJuKuShiFangSuo (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_42.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
}

INT rg_SQLiteShuJuKuLei::rg_DengDaiShuJuKuShiFangSuo (INT rg_DengDaiCiShu1)
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_42.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber, INT rg_DengDaiCiShu1))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber, rg_DengDaiCiShu1);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

rg_SQLiteJiLuJiLei::rg_SQLiteJiLuJiLei ()
{
    _VolObjectInitMembers ();
}

void rg_SQLiteJiLuJiLei::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

BOOL rg_SQLiteJiLuJiLei::_IsSelfEqual (const rg_SQLiteJiLuJiLei& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_SQLiteJiLuJiLei::_CopySelfFrom (const rg_SQLiteJiLuJiLei& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

rg_SQLiteJiLuJiLei::~rg_SQLiteJiLuJiLei ()
{
    OnBeforeObjectCleanup ();
    _OnCleanupExtra ();
}
void rg_SQLiteJiLuJiLei::SetRefObject (CRefObject* pRefObject)
{
    ASSERT_R_DATA_OR_NULL (pRefObject);
    if (pRefObject != NULL)  pRefObject->AddRef ();
    if (m_pRefObject != NULL)  m_pRefObject->Release ();
    m_pRefObject = pRefObject;
}
void rg_SQLiteJiLuJiLei::TakeOverNewRefObject (CRefObject* pNewRefObject)
{
    ASSERT (pNewRefObject != m_pRefObject);
    ASSERT_R_DATA_OR_NULL (pNewRefObject);
    if (m_pRefObject != NULL)  m_pRefObject->Release ();
    m_pRefObject = pNewRefObject;
}

INT rg_SQLiteJiLuJiLei::rg_ZhiHangYuGou ()
{
    if (GetStmt()) return sqlite3_step(GetStmt());
    return SQLITE_ERROR;
}

INT rg_SQLiteJiLuJiLei::rg_ZhiZhengShuCanShuShuJu (INT rg_CanShuSuoYin2, INT rg_value114)
{
    if (GetStmt()) return sqlite3_bind_int(GetStmt(), rg_CanShuSuoYin2, rg_value114);
    return SQLITE_ERROR;
}

INT rg_SQLiteJiLuJiLei::rg_ZhiChangZhengShuCanShuShuJu (INT rg_CanShuSuoYin3, INT64 rg_value115)
{
    if (GetStmt()) return sqlite3_bind_int64(GetStmt(), rg_CanShuSuoYin3, rg_value115);
    return SQLITE_ERROR;
}

INT rg_SQLiteJiLuJiLei::rg_ZhiWenBenCanShuShuJu (INT rg_CanShuSuoYin4, CVolString& rg_value116)
{
    CU8String u8str (rg_value116.GetText ());
    const U8CHAR* ps = u8str.GetText ();
    if (GetStmt()) return sqlite3_bind_text(GetStmt(), rg_CanShuSuoYin4, ps, (INT)strlen(ps), SQLITE_TRANSIENT);
    return SQLITE_ERROR;
}

INT rg_SQLiteJiLuJiLei::rg_DouZhengShuShuJu (INT rg_LieSuoYin24)
{
    if (GetStmt()) return sqlite3_column_int(GetStmt(), rg_LieSuoYin24);
    return 0;
}

CVolString rg_SQLiteJiLuJiLei::rg_DouWenBenShuJu (INT rg_LieSuoYin26)
{
    if (GetStmt())
    {
        const char* result = (const char *)sqlite3_column_text(GetStmt(), rg_LieSuoYin26);
        if (result != NULL) return result;
    }
    return _T("");
}

void rg_SQLiteJiLuJiLei::rg_ShiFang2 ()
{
    if (GetStmt()) data().Close();
}

}
