
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

namespace rg_FBrowser_ShuJuLeiXing
{

rg_FBrowser_ChuShiHuaPeiZhi::rg_FBrowser_ChuShiHuaPeiZhi ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_ChuShiHuaPeiZhi::_VolObjectInitMembers ()
{
    rg_MoShaXiang = FALSE;
    rg_QiYongJiTongXiaoXiXunHuan = FALSE;
    rg_QiYongWaiBuXiaoXi = FALSE;
    rg_QiYongLiBingXuanRan = FALSE;
    rg_JinYongMingLingCanShu = FALSE;
    rg_BaoLiuSession = FALSE;
    rg_RiZhiMoShi = 0;
    rg_RiZhiYuanSu = 0;
    rg_YuanChengDuanKou = 0;
    rg_uncaught_exception_stack_size = 0;
    rg_BeiJingYanSe = 0;
    rg_QiYongcookieJiHua_PaiChuMoRenCanShu = FALSE;
    rg_ChromeYingYongTuBiaoid = 0;
    rg_JinYongXinHaoChuLiChengXu = 0;
    rg_QiYongZiDongDuoLiMoShi = FALSE;
}

BOOL rg_FBrowser_ChuShiHuaPeiZhi::_IsSelfEqual (const rg_FBrowser_ChuShiHuaPeiZhi& objCompare) const
{
    if (rg_MoShaXiang != objCompare.rg_MoShaXiang)  return FALSE;
    if (rg_ZhiHangJinCheng != objCompare.rg_ZhiHangJinCheng)  return FALSE;
    if (rg_KuangJiaWenJianMuLu != objCompare.rg_KuangJiaWenJianMuLu)  return FALSE;
    if (rg_ZhubundleLuJing != objCompare.rg_ZhubundleLuJing)  return FALSE;
    if (rg_QiYongJiTongXiaoXiXunHuan != objCompare.rg_QiYongJiTongXiaoXiXunHuan)  return FALSE;
    if (rg_QiYongWaiBuXiaoXi != objCompare.rg_QiYongWaiBuXiaoXi)  return FALSE;
    if (rg_QiYongLiBingXuanRan != objCompare.rg_QiYongLiBingXuanRan)  return FALSE;
    if (rg_JinYongMingLingCanShu != objCompare.rg_JinYongMingLingCanShu)  return FALSE;
    if (rg_HuanCunMuLu != objCompare.rg_HuanCunMuLu)  return FALSE;
    if (rg_BaoLiuSession != objCompare.rg_BaoLiuSession)  return FALSE;
    if (rg_LiuLanQiBiaoShi != objCompare.rg_LiuLanQiBiaoShi)  return FALSE;
    if (rg_LiuLanQiBiaoShiBanBen != objCompare.rg_LiuLanQiBiaoShiBanBen)  return FALSE;
    if (rg_BenDeHuaYuYan != objCompare.rg_BenDeHuaYuYan)  return FALSE;
    if (rg_RiZhiMuLu != objCompare.rg_RiZhiMuLu)  return FALSE;
    if (rg_RiZhiMoShi != objCompare.rg_RiZhiMoShi)  return FALSE;
    if (rg_RiZhiYuanSu != objCompare.rg_RiZhiYuanSu)  return FALSE;
    if (rg_javascript_flags != objCompare.rg_javascript_flags)  return FALSE;
    if (rg_ZiYuanLuJing != objCompare.rg_ZiYuanLuJing)  return FALSE;
    if (rg_BenDeYuYanLuJing != objCompare.rg_BenDeYuYanLuJing)  return FALSE;
    if (rg_YuanChengDuanKou != objCompare.rg_YuanChengDuanKou)  return FALSE;
    if (rg_uncaught_exception_stack_size != objCompare.rg_uncaught_exception_stack_size)  return FALSE;
    if (rg_BeiJingYanSe != objCompare.rg_BeiJingYanSe)  return FALSE;
    if (rg_JieShouYuYanQingChan != objCompare.rg_JieShouYuYanQingChan)  return FALSE;
    if (rg_QiYongcookieJiHuaQingChanCanShu != objCompare.rg_QiYongcookieJiHuaQingChanCanShu)  return FALSE;
    if (rg_QiYongcookieJiHua_PaiChuMoRenCanShu != objCompare.rg_QiYongcookieJiHua_PaiChuMoRenCanShu)  return FALSE;
    if (rg_ChromeCeLueid != objCompare.rg_ChromeCeLueid)  return FALSE;
    if (rg_ChromeYingYongTuBiaoid != objCompare.rg_ChromeYingYongTuBiaoid)  return FALSE;
    if (rg_JinYongXinHaoChuLiChengXu != objCompare.rg_JinYongXinHaoChuLiChengXu)  return FALSE;
    if (rg_QiYongZiDongDuoLiMoShi != objCompare.rg_QiYongZiDongDuoLiMoShi)  return FALSE;
    return TRUE;
}

void rg_FBrowser_ChuShiHuaPeiZhi::_CopySelfFrom (const rg_FBrowser_ChuShiHuaPeiZhi& objCopyFrom)
{
    rg_MoShaXiang = objCopyFrom.rg_MoShaXiang;
    rg_ZhiHangJinCheng = objCopyFrom.rg_ZhiHangJinCheng;
    rg_KuangJiaWenJianMuLu = objCopyFrom.rg_KuangJiaWenJianMuLu;
    rg_ZhubundleLuJing = objCopyFrom.rg_ZhubundleLuJing;
    rg_QiYongJiTongXiaoXiXunHuan = objCopyFrom.rg_QiYongJiTongXiaoXiXunHuan;
    rg_QiYongWaiBuXiaoXi = objCopyFrom.rg_QiYongWaiBuXiaoXi;
    rg_QiYongLiBingXuanRan = objCopyFrom.rg_QiYongLiBingXuanRan;
    rg_JinYongMingLingCanShu = objCopyFrom.rg_JinYongMingLingCanShu;
    rg_HuanCunMuLu = objCopyFrom.rg_HuanCunMuLu;
    rg_BaoLiuSession = objCopyFrom.rg_BaoLiuSession;
    rg_LiuLanQiBiaoShi = objCopyFrom.rg_LiuLanQiBiaoShi;
    rg_LiuLanQiBiaoShiBanBen = objCopyFrom.rg_LiuLanQiBiaoShiBanBen;
    rg_BenDeHuaYuYan = objCopyFrom.rg_BenDeHuaYuYan;
    rg_RiZhiMuLu = objCopyFrom.rg_RiZhiMuLu;
    rg_RiZhiMoShi = objCopyFrom.rg_RiZhiMoShi;
    rg_RiZhiYuanSu = objCopyFrom.rg_RiZhiYuanSu;
    rg_javascript_flags = objCopyFrom.rg_javascript_flags;
    rg_ZiYuanLuJing = objCopyFrom.rg_ZiYuanLuJing;
    rg_BenDeYuYanLuJing = objCopyFrom.rg_BenDeYuYanLuJing;
    rg_YuanChengDuanKou = objCopyFrom.rg_YuanChengDuanKou;
    rg_uncaught_exception_stack_size = objCopyFrom.rg_uncaught_exception_stack_size;
    rg_BeiJingYanSe = objCopyFrom.rg_BeiJingYanSe;
    rg_JieShouYuYanQingChan = objCopyFrom.rg_JieShouYuYanQingChan;
    rg_QiYongcookieJiHuaQingChanCanShu = objCopyFrom.rg_QiYongcookieJiHuaQingChanCanShu;
    rg_QiYongcookieJiHua_PaiChuMoRenCanShu = objCopyFrom.rg_QiYongcookieJiHua_PaiChuMoRenCanShu;
    rg_ChromeCeLueid = objCopyFrom.rg_ChromeCeLueid;
    rg_ChromeYingYongTuBiaoid = objCopyFrom.rg_ChromeYingYongTuBiaoid;
    rg_JinYongXinHaoChuLiChengXu = objCopyFrom.rg_JinYongXinHaoChuLiChengXu;
    rg_QiYongZiDongDuoLiMoShi = objCopyFrom.rg_QiYongZiDongDuoLiMoShi;
}

void rg_FBrowser_ChuShiHuaPeiZhi::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_MoShaXiang, sizeof (BOOL));
    rg_ZhiHangJinCheng.LoadFromStream (stream);
    rg_KuangJiaWenJianMuLu.LoadFromStream (stream);
    rg_ZhubundleLuJing.LoadFromStream (stream);
    stream.ReadExact (&rg_QiYongJiTongXiaoXiXunHuan, sizeof (BOOL));
    stream.ReadExact (&rg_QiYongWaiBuXiaoXi, sizeof (BOOL));
    stream.ReadExact (&rg_QiYongLiBingXuanRan, sizeof (BOOL));
    stream.ReadExact (&rg_JinYongMingLingCanShu, sizeof (BOOL));
    rg_HuanCunMuLu.LoadFromStream (stream);
    stream.ReadExact (&rg_BaoLiuSession, sizeof (BOOL));
    rg_LiuLanQiBiaoShi.LoadFromStream (stream);
    rg_LiuLanQiBiaoShiBanBen.LoadFromStream (stream);
    rg_BenDeHuaYuYan.LoadFromStream (stream);
    rg_RiZhiMuLu.LoadFromStream (stream);
    stream.ReadExact (&rg_RiZhiMoShi, sizeof (INT));
    stream.ReadExact (&rg_RiZhiYuanSu, sizeof (INT));
    rg_javascript_flags.LoadFromStream (stream);
    rg_ZiYuanLuJing.LoadFromStream (stream);
    rg_BenDeYuYanLuJing.LoadFromStream (stream);
    stream.ReadExact (&rg_YuanChengDuanKou, sizeof (INT));
    stream.ReadExact (&rg_uncaught_exception_stack_size, sizeof (INT));
    stream.ReadExact (&rg_BeiJingYanSe, sizeof (INT));
    rg_JieShouYuYanQingChan.LoadFromStream (stream);
    rg_QiYongcookieJiHuaQingChanCanShu.LoadFromStream (stream);
    stream.ReadExact (&rg_QiYongcookieJiHua_PaiChuMoRenCanShu, sizeof (BOOL));
    rg_ChromeCeLueid.LoadFromStream (stream);
    stream.ReadExact (&rg_ChromeYingYongTuBiaoid, sizeof (INT));
    stream.ReadExact (&rg_JinYongXinHaoChuLiChengXu, sizeof (INT));
    stream.ReadExact (&rg_QiYongZiDongDuoLiMoShi, sizeof (BOOL));
}

void rg_FBrowser_ChuShiHuaPeiZhi::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_MoShaXiang, sizeof (BOOL));
    rg_ZhiHangJinCheng.SaveIntoStream (stream);
    rg_KuangJiaWenJianMuLu.SaveIntoStream (stream);
    rg_ZhubundleLuJing.SaveIntoStream (stream);
    stream.write (&rg_QiYongJiTongXiaoXiXunHuan, sizeof (BOOL));
    stream.write (&rg_QiYongWaiBuXiaoXi, sizeof (BOOL));
    stream.write (&rg_QiYongLiBingXuanRan, sizeof (BOOL));
    stream.write (&rg_JinYongMingLingCanShu, sizeof (BOOL));
    rg_HuanCunMuLu.SaveIntoStream (stream);
    stream.write (&rg_BaoLiuSession, sizeof (BOOL));
    rg_LiuLanQiBiaoShi.SaveIntoStream (stream);
    rg_LiuLanQiBiaoShiBanBen.SaveIntoStream (stream);
    rg_BenDeHuaYuYan.SaveIntoStream (stream);
    rg_RiZhiMuLu.SaveIntoStream (stream);
    stream.write (&rg_RiZhiMoShi, sizeof (INT));
    stream.write (&rg_RiZhiYuanSu, sizeof (INT));
    rg_javascript_flags.SaveIntoStream (stream);
    rg_ZiYuanLuJing.SaveIntoStream (stream);
    rg_BenDeYuYanLuJing.SaveIntoStream (stream);
    stream.write (&rg_YuanChengDuanKou, sizeof (INT));
    stream.write (&rg_uncaught_exception_stack_size, sizeof (INT));
    stream.write (&rg_BeiJingYanSe, sizeof (INT));
    rg_JieShouYuYanQingChan.SaveIntoStream (stream);
    rg_QiYongcookieJiHuaQingChanCanShu.SaveIntoStream (stream);
    stream.write (&rg_QiYongcookieJiHua_PaiChuMoRenCanShu, sizeof (BOOL));
    rg_ChromeCeLueid.SaveIntoStream (stream);
    stream.write (&rg_ChromeYingYongTuBiaoid, sizeof (INT));
    stream.write (&rg_JinYongXinHaoChuLiChengXu, sizeof (INT));
    stream.write (&rg_QiYongZiDongDuoLiMoShi, sizeof (BOOL));
}
FBroInitSettings* rg_FBrowser_ChuShiHuaPeiZhi::ToFBroData(){
  Release();
  tempdata.no_sandbox=rg_MoShaXiang;
  tempdata.browser_subprocess_path=FBroUnit::UnicodeToAnsi(rg_ZhiHangJinCheng.GetText());
  tempdata.framework_dir_path=FBroUnit::UnicodeToAnsi(rg_KuangJiaWenJianMuLu.GetText());
  tempdata.main_bundle_path=FBroUnit::UnicodeToAnsi(rg_ZhubundleLuJing.GetText());
  tempdata.multi_threaded_message_loop=rg_QiYongJiTongXiaoXiXunHuan;
  tempdata.external_message_pump=rg_QiYongWaiBuXiaoXi;
  tempdata.windowless_rendering_enabled=rg_QiYongLiBingXuanRan;
  tempdata.command_line_args_disabled=rg_JinYongMingLingCanShu;
  tempdata.cache_path=FBroUnit::UnicodeToAnsi(rg_HuanCunMuLu.GetText());
  tempdata.persist_session_cookies=rg_BaoLiuSession;
  tempdata.user_agent=FBroUnit::UnicodeToAnsi(rg_LiuLanQiBiaoShi.GetText());
  tempdata.user_agent_product=FBroUnit::UnicodeToAnsi(rg_LiuLanQiBiaoShiBanBen.GetText());
  tempdata.locale=FBroUnit::UnicodeToAnsi(rg_BenDeHuaYuYan.GetText());
  tempdata.log_file=FBroUnit::UnicodeToAnsi(rg_RiZhiMuLu.GetText());
  tempdata.log_severity=rg_RiZhiMoShi;
  tempdata.log_items=rg_RiZhiYuanSu;
  tempdata.javascript_flags=FBroUnit::UnicodeToAnsi(rg_javascript_flags.GetText());
  tempdata.resources_dir_path=FBroUnit::UnicodeToAnsi(rg_ZiYuanLuJing.GetText());
  tempdata.locales_dir_path=FBroUnit::UnicodeToAnsi(rg_BenDeYuYanLuJing.GetText());
  tempdata.remote_debugging_port=rg_YuanChengDuanKou;
  tempdata.uncaught_exception_stack_size=rg_uncaught_exception_stack_size;
  tempdata.background_color=rg_BeiJingYanSe;
  tempdata.accept_language_list=FBroUnit::UnicodeToAnsi(rg_JieShouYuYanQingChan.GetText());
  tempdata.cookieable_schemes_list=FBroUnit::UnicodeToAnsi(rg_QiYongcookieJiHuaQingChanCanShu.GetText());
  tempdata.cookieable_schemes_exclude_defaults=rg_QiYongcookieJiHua_PaiChuMoRenCanShu;
  tempdata.chrome_policy_id=FBroUnit::UnicodeToAnsi(rg_ChromeCeLueid.GetText());
  tempdata.chrome_app_icon_id=rg_ChromeYingYongTuBiaoid;
  tempdata.disable_signal_handlers=rg_JinYongXinHaoChuLiChengXu;
  tempdata.enable_auto_multiple=rg_QiYongZiDongDuoLiMoShi;
  return &tempdata;
}
void rg_FBrowser_ChuShiHuaPeiZhi::Release(){
   FBroUnit::FreeCharArray(tempdata.browser_subprocess_path);
   FBroUnit::FreeCharArray(tempdata.framework_dir_path);
   FBroUnit::FreeCharArray(tempdata.main_bundle_path);
   FBroUnit::FreeCharArray(tempdata.cache_path);
   FBroUnit::FreeCharArray(tempdata.user_agent_product);
   FBroUnit::FreeCharArray(tempdata.user_agent);
   FBroUnit::FreeCharArray(tempdata.locale);
   FBroUnit::FreeCharArray(tempdata.log_file);
   FBroUnit::FreeCharArray(tempdata.javascript_flags);
   FBroUnit::FreeCharArray(tempdata.resources_dir_path);
   FBroUnit::FreeCharArray(tempdata.locales_dir_path);
   FBroUnit::FreeCharArray(tempdata.accept_language_list);
   FBroUnit::FreeCharArray(tempdata.cookieable_schemes_list);
   FBroUnit::FreeCharArray(tempdata.chrome_policy_id);
}

rg_FBrowser_DanChuGongNeng::rg_FBrowser_DanChuGongNeng ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_DanChuGongNeng::_VolObjectInitMembers ()
{
    rg_x4 = 0;
    rg_xSet = 0;
    rg_y3 = 0;
    rg_ySet = 0;
    rg_width = 0;
    rg_widthSet = 0;
    rg_height = 0;
    rg_heightSet = 0;
    rg_isPopup = 0;
}

BOOL rg_FBrowser_DanChuGongNeng::_IsSelfEqual (const rg_FBrowser_DanChuGongNeng& objCompare) const
{
    if (rg_x4 != objCompare.rg_x4)  return FALSE;
    if (rg_xSet != objCompare.rg_xSet)  return FALSE;
    if (rg_y3 != objCompare.rg_y3)  return FALSE;
    if (rg_ySet != objCompare.rg_ySet)  return FALSE;
    if (rg_width != objCompare.rg_width)  return FALSE;
    if (rg_widthSet != objCompare.rg_widthSet)  return FALSE;
    if (rg_height != objCompare.rg_height)  return FALSE;
    if (rg_heightSet != objCompare.rg_heightSet)  return FALSE;
    if (rg_isPopup != objCompare.rg_isPopup)  return FALSE;
    return TRUE;
}

void rg_FBrowser_DanChuGongNeng::_CopySelfFrom (const rg_FBrowser_DanChuGongNeng& objCopyFrom)
{
    rg_x4 = objCopyFrom.rg_x4;
    rg_xSet = objCopyFrom.rg_xSet;
    rg_y3 = objCopyFrom.rg_y3;
    rg_ySet = objCopyFrom.rg_ySet;
    rg_width = objCopyFrom.rg_width;
    rg_widthSet = objCopyFrom.rg_widthSet;
    rg_height = objCopyFrom.rg_height;
    rg_heightSet = objCopyFrom.rg_heightSet;
    rg_isPopup = objCopyFrom.rg_isPopup;
}

void rg_FBrowser_DanChuGongNeng::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_x4, sizeof (INT));
    stream.ReadExact (&rg_xSet, sizeof (INT));
    stream.ReadExact (&rg_y3, sizeof (INT));
    stream.ReadExact (&rg_ySet, sizeof (INT));
    stream.ReadExact (&rg_width, sizeof (INT));
    stream.ReadExact (&rg_widthSet, sizeof (INT));
    stream.ReadExact (&rg_height, sizeof (INT));
    stream.ReadExact (&rg_heightSet, sizeof (INT));
    stream.ReadExact (&rg_isPopup, sizeof (INT));
}

void rg_FBrowser_DanChuGongNeng::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_x4, sizeof (INT));
    stream.write (&rg_xSet, sizeof (INT));
    stream.write (&rg_y3, sizeof (INT));
    stream.write (&rg_ySet, sizeof (INT));
    stream.write (&rg_width, sizeof (INT));
    stream.write (&rg_widthSet, sizeof (INT));
    stream.write (&rg_height, sizeof (INT));
    stream.write (&rg_heightSet, sizeof (INT));
    stream.write (&rg_isPopup, sizeof (INT));
}
cef_popup_features_t* rg_FBrowser_DanChuGongNeng::ToFBroData(){
  release();
  m_data.x=rg_x4;
  m_data.xSet=rg_xSet;
  m_data.y=rg_y3;
  m_data.ySet=rg_ySet;
  m_data.width=rg_width;
  m_data.widthSet=rg_widthSet;
  m_data.height=rg_height;
  m_data.heightSet=rg_heightSet;
  m_data.isPopup=rg_isPopup;
  return &m_data;
}
void rg_FBrowser_DanChuGongNeng::ToHsData(){
  rg_x4=m_data.x;
  rg_xSet=m_data.xSet;
  rg_y3=m_data.y;
  rg_ySet=m_data.ySet;
  rg_width=m_data.width;
  rg_widthSet= m_data.widthSet;
  rg_height=m_data.height;
  rg_heightSet=m_data.heightSet;
  rg_isPopup=m_data.isPopup;
}
void rg_FBrowser_DanChuGongNeng::release(){}

rg_FBrowser_ChuangKouXinXi::rg_FBrowser_ChuangKouXinXi ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_ChuangKouXinXi::_VolObjectInitMembers ()
{
    rg_EWaiFengGe = 0;
    rg_FengGe1 = 0;
    rg_HengZuoBiao1 = 0;
    rg_ZongZuoBiao1 = 0;
    rg_KuanDu7 = 0;
    rg_GaoDu7 = 0;
    rg_FuChuangKouGouBing8 = 0;
    rg_CaiChanGouBing = 0;
    rg_QiYongLiBingXuanRanMoShi = FALSE;
    rg_QiYongGongXiangJieGou = FALSE;
    rg_QiYongWaiBuKuangJia = FALSE;
    rg_ChuangKouGouBing4 = 0;
    rg_YunHangFengGe = 0;
}

BOOL rg_FBrowser_ChuangKouXinXi::_IsSelfEqual (const rg_FBrowser_ChuangKouXinXi& objCompare) const
{
    if (rg_EWaiFengGe != objCompare.rg_EWaiFengGe)  return FALSE;
    if (rg_ChuangKouMing != objCompare.rg_ChuangKouMing)  return FALSE;
    if (rg_FengGe1 != objCompare.rg_FengGe1)  return FALSE;
    if (rg_HengZuoBiao1 != objCompare.rg_HengZuoBiao1)  return FALSE;
    if (rg_ZongZuoBiao1 != objCompare.rg_ZongZuoBiao1)  return FALSE;
    if (rg_KuanDu7 != objCompare.rg_KuanDu7)  return FALSE;
    if (rg_GaoDu7 != objCompare.rg_GaoDu7)  return FALSE;
    if (rg_FuChuangKouGouBing8 != objCompare.rg_FuChuangKouGouBing8)  return FALSE;
    if (rg_CaiChanGouBing != objCompare.rg_CaiChanGouBing)  return FALSE;
    if (rg_QiYongLiBingXuanRanMoShi != objCompare.rg_QiYongLiBingXuanRanMoShi)  return FALSE;
    if (rg_QiYongGongXiangJieGou != objCompare.rg_QiYongGongXiangJieGou)  return FALSE;
    if (rg_QiYongWaiBuKuangJia != objCompare.rg_QiYongWaiBuKuangJia)  return FALSE;
    if (rg_ChuangKouGouBing4 != objCompare.rg_ChuangKouGouBing4)  return FALSE;
    if (rg_FuChuangKouMing != objCompare.rg_FuChuangKouMing)  return FALSE;
    if (rg_YunHangFengGe != objCompare.rg_YunHangFengGe)  return FALSE;
    return TRUE;
}

void rg_FBrowser_ChuangKouXinXi::_CopySelfFrom (const rg_FBrowser_ChuangKouXinXi& objCopyFrom)
{
    rg_EWaiFengGe = objCopyFrom.rg_EWaiFengGe;
    rg_ChuangKouMing = objCopyFrom.rg_ChuangKouMing;
    rg_FengGe1 = objCopyFrom.rg_FengGe1;
    rg_HengZuoBiao1 = objCopyFrom.rg_HengZuoBiao1;
    rg_ZongZuoBiao1 = objCopyFrom.rg_ZongZuoBiao1;
    rg_KuanDu7 = objCopyFrom.rg_KuanDu7;
    rg_GaoDu7 = objCopyFrom.rg_GaoDu7;
    rg_FuChuangKouGouBing8 = objCopyFrom.rg_FuChuangKouGouBing8;
    rg_CaiChanGouBing = objCopyFrom.rg_CaiChanGouBing;
    rg_QiYongLiBingXuanRanMoShi = objCopyFrom.rg_QiYongLiBingXuanRanMoShi;
    rg_QiYongGongXiangJieGou = objCopyFrom.rg_QiYongGongXiangJieGou;
    rg_QiYongWaiBuKuangJia = objCopyFrom.rg_QiYongWaiBuKuangJia;
    rg_ChuangKouGouBing4 = objCopyFrom.rg_ChuangKouGouBing4;
    rg_FuChuangKouMing = objCopyFrom.rg_FuChuangKouMing;
    rg_YunHangFengGe = objCopyFrom.rg_YunHangFengGe;
}

void rg_FBrowser_ChuangKouXinXi::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_EWaiFengGe, sizeof (INT));
    rg_ChuangKouMing.LoadFromStream (stream);
    stream.ReadExact (&rg_FengGe1, sizeof (INT));
    stream.ReadExact (&rg_HengZuoBiao1, sizeof (INT));
    stream.ReadExact (&rg_ZongZuoBiao1, sizeof (INT));
    stream.ReadExact (&rg_KuanDu7, sizeof (INT));
    stream.ReadExact (&rg_GaoDu7, sizeof (INT));
    stream.ReadExact (&rg_FuChuangKouGouBing8, sizeof (INT));
    stream.ReadExact (&rg_CaiChanGouBing, sizeof (INT));
    stream.ReadExact (&rg_QiYongLiBingXuanRanMoShi, sizeof (BOOL));
    stream.ReadExact (&rg_QiYongGongXiangJieGou, sizeof (BOOL));
    stream.ReadExact (&rg_QiYongWaiBuKuangJia, sizeof (BOOL));
    stream.ReadExact (&rg_ChuangKouGouBing4, sizeof (INT));
    rg_FuChuangKouMing.LoadFromStream (stream);
    stream.ReadExact (&rg_YunHangFengGe, sizeof (INT));
}

void rg_FBrowser_ChuangKouXinXi::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_EWaiFengGe, sizeof (INT));
    rg_ChuangKouMing.SaveIntoStream (stream);
    stream.write (&rg_FengGe1, sizeof (INT));
    stream.write (&rg_HengZuoBiao1, sizeof (INT));
    stream.write (&rg_ZongZuoBiao1, sizeof (INT));
    stream.write (&rg_KuanDu7, sizeof (INT));
    stream.write (&rg_GaoDu7, sizeof (INT));
    stream.write (&rg_FuChuangKouGouBing8, sizeof (INT));
    stream.write (&rg_CaiChanGouBing, sizeof (INT));
    stream.write (&rg_QiYongLiBingXuanRanMoShi, sizeof (BOOL));
    stream.write (&rg_QiYongGongXiangJieGou, sizeof (BOOL));
    stream.write (&rg_QiYongWaiBuKuangJia, sizeof (BOOL));
    stream.write (&rg_ChuangKouGouBing4, sizeof (INT));
    rg_FuChuangKouMing.SaveIntoStream (stream);
    stream.write (&rg_YunHangFengGe, sizeof (INT));
}
PTELIB_WINDOWS_INFO rg_FBrowser_ChuangKouXinXi::ToFBroData(){
  release();
   m_data.is_null=false;
   m_data.ex_style=rg_EWaiFengGe;
   m_data.window_name=FBroUnit::UnicodeToAnsi(rg_ChuangKouMing.GetText());
   m_data.style=rg_FengGe1;
   m_data.x=rg_HengZuoBiao1;
   m_data.y=rg_ZongZuoBiao1;
   m_data.width=rg_KuanDu7;
   m_data.height=rg_GaoDu7;
   m_data.parent_window=(HWND)rg_FuChuangKouGouBing8;
   m_data.menu=(HMENU)rg_CaiChanGouBing;
   m_data.windowless_rendering_enabled=rg_QiYongLiBingXuanRanMoShi;
   m_data.shared_texture_enabled=rg_QiYongGongXiangJieGou;
   m_data.external_begin_frame_enabled=rg_QiYongWaiBuKuangJia;
   m_data.window=(HWND)rg_ChuangKouGouBing4;
   m_data.parent_window_name=FBroUnit::UnicodeToAnsi(rg_FuChuangKouMing);
   m_data.runtime_style=rg_YunHangFengGe;
  return &m_data;
}
void rg_FBrowser_ChuangKouXinXi::release(){
  FBroUnit::FreeCharArray(m_data.window_name);
  FBroUnit::FreeCharArray(m_data.parent_window_name);
}

rg_FBrowser_LiuLanQiPeiZhi::rg_FBrowser_LiuLanQiPeiZhi ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_LiuLanQiPeiZhi::_VolObjectInitMembers ()
{
    rg_LiBingXuanRanZhengLu = 0;
    rg_MoRenZiTiDaXiao = 0;
    rg_MoRenGuDingZiTiDaXiao = 0;
    rg_ZuiXiaoZiTiDaXiao = 0;
    rg_ZuiXiaoLuoJiZiTiDaXiao = 0;
    rg_YuanChengZiTi = 0;
    rg_QiYongJS = 0;
    rg_QiYongJSGuanBiChuangKou = 0;
    rg_QiYongJSFangWenJianQieBan = 0;
    rg_QiYongJSDOMNianTie = 0;
    rg_QiYongTuPianJiaZai = 0;
    rg_QiYongTuPianZiKuoGe = 0;
    rg_QiYongWenBenOuYuDiaoZheng = 0;
    rg_QiYongXuanXiangKaLianJie = 0;
    rg_QiYongBenDeCunChu = 0;
    rg_QiYongShuJuKu = 0;
    rg_QiYongWebGL = 0;
    rg_BeiJingYanSe1 = 0;
    rg_ZhuangTaiQiPao = 0;
    rg_SuFangQiPao = 0;
}

BOOL rg_FBrowser_LiuLanQiPeiZhi::_IsSelfEqual (const rg_FBrowser_LiuLanQiPeiZhi& objCompare) const
{
    if (rg_LiBingXuanRanZhengLu != objCompare.rg_LiBingXuanRanZhengLu)  return FALSE;
    if (rg_BiaoZhunZiTiLeiXing != objCompare.rg_BiaoZhunZiTiLeiXing)  return FALSE;
    if (rg_GuDingZiTiLeiXing != objCompare.rg_GuDingZiTiLeiXing)  return FALSE;
    if (rg_ChenXianZiTiLeiXing != objCompare.rg_ChenXianZiTiLeiXing)  return FALSE;
    if (rg_MoChenXianZiTiLeiXing != objCompare.rg_MoChenXianZiTiLeiXing)  return FALSE;
    if (rg_CaoShuZiTiLeiXing != objCompare.rg_CaoShuZiTiLeiXing)  return FALSE;
    if (rg_HuanXiangZiTiLeiXing != objCompare.rg_HuanXiangZiTiLeiXing)  return FALSE;
    if (rg_MoRenZiTiDaXiao != objCompare.rg_MoRenZiTiDaXiao)  return FALSE;
    if (rg_MoRenGuDingZiTiDaXiao != objCompare.rg_MoRenGuDingZiTiDaXiao)  return FALSE;
    if (rg_ZuiXiaoZiTiDaXiao != objCompare.rg_ZuiXiaoZiTiDaXiao)  return FALSE;
    if (rg_ZuiXiaoLuoJiZiTiDaXiao != objCompare.rg_ZuiXiaoLuoJiZiTiDaXiao)  return FALSE;
    if (rg_MoRenBianMa != objCompare.rg_MoRenBianMa)  return FALSE;
    if (rg_YuanChengZiTi != objCompare.rg_YuanChengZiTi)  return FALSE;
    if (rg_QiYongJS != objCompare.rg_QiYongJS)  return FALSE;
    if (rg_QiYongJSGuanBiChuangKou != objCompare.rg_QiYongJSGuanBiChuangKou)  return FALSE;
    if (rg_QiYongJSFangWenJianQieBan != objCompare.rg_QiYongJSFangWenJianQieBan)  return FALSE;
    if (rg_QiYongJSDOMNianTie != objCompare.rg_QiYongJSDOMNianTie)  return FALSE;
    if (rg_QiYongTuPianJiaZai != objCompare.rg_QiYongTuPianJiaZai)  return FALSE;
    if (rg_QiYongTuPianZiKuoGe != objCompare.rg_QiYongTuPianZiKuoGe)  return FALSE;
    if (rg_QiYongWenBenOuYuDiaoZheng != objCompare.rg_QiYongWenBenOuYuDiaoZheng)  return FALSE;
    if (rg_QiYongXuanXiangKaLianJie != objCompare.rg_QiYongXuanXiangKaLianJie)  return FALSE;
    if (rg_QiYongBenDeCunChu != objCompare.rg_QiYongBenDeCunChu)  return FALSE;
    if (rg_QiYongShuJuKu != objCompare.rg_QiYongShuJuKu)  return FALSE;
    if (rg_QiYongWebGL != objCompare.rg_QiYongWebGL)  return FALSE;
    if (rg_BeiJingYanSe1 != objCompare.rg_BeiJingYanSe1)  return FALSE;
    if (rg_ZhuangTaiQiPao != objCompare.rg_ZhuangTaiQiPao)  return FALSE;
    if (rg_SuFangQiPao != objCompare.rg_SuFangQiPao)  return FALSE;
    return TRUE;
}

void rg_FBrowser_LiuLanQiPeiZhi::_CopySelfFrom (const rg_FBrowser_LiuLanQiPeiZhi& objCopyFrom)
{
    rg_LiBingXuanRanZhengLu = objCopyFrom.rg_LiBingXuanRanZhengLu;
    rg_BiaoZhunZiTiLeiXing = objCopyFrom.rg_BiaoZhunZiTiLeiXing;
    rg_GuDingZiTiLeiXing = objCopyFrom.rg_GuDingZiTiLeiXing;
    rg_ChenXianZiTiLeiXing = objCopyFrom.rg_ChenXianZiTiLeiXing;
    rg_MoChenXianZiTiLeiXing = objCopyFrom.rg_MoChenXianZiTiLeiXing;
    rg_CaoShuZiTiLeiXing = objCopyFrom.rg_CaoShuZiTiLeiXing;
    rg_HuanXiangZiTiLeiXing = objCopyFrom.rg_HuanXiangZiTiLeiXing;
    rg_MoRenZiTiDaXiao = objCopyFrom.rg_MoRenZiTiDaXiao;
    rg_MoRenGuDingZiTiDaXiao = objCopyFrom.rg_MoRenGuDingZiTiDaXiao;
    rg_ZuiXiaoZiTiDaXiao = objCopyFrom.rg_ZuiXiaoZiTiDaXiao;
    rg_ZuiXiaoLuoJiZiTiDaXiao = objCopyFrom.rg_ZuiXiaoLuoJiZiTiDaXiao;
    rg_MoRenBianMa = objCopyFrom.rg_MoRenBianMa;
    rg_YuanChengZiTi = objCopyFrom.rg_YuanChengZiTi;
    rg_QiYongJS = objCopyFrom.rg_QiYongJS;
    rg_QiYongJSGuanBiChuangKou = objCopyFrom.rg_QiYongJSGuanBiChuangKou;
    rg_QiYongJSFangWenJianQieBan = objCopyFrom.rg_QiYongJSFangWenJianQieBan;
    rg_QiYongJSDOMNianTie = objCopyFrom.rg_QiYongJSDOMNianTie;
    rg_QiYongTuPianJiaZai = objCopyFrom.rg_QiYongTuPianJiaZai;
    rg_QiYongTuPianZiKuoGe = objCopyFrom.rg_QiYongTuPianZiKuoGe;
    rg_QiYongWenBenOuYuDiaoZheng = objCopyFrom.rg_QiYongWenBenOuYuDiaoZheng;
    rg_QiYongXuanXiangKaLianJie = objCopyFrom.rg_QiYongXuanXiangKaLianJie;
    rg_QiYongBenDeCunChu = objCopyFrom.rg_QiYongBenDeCunChu;
    rg_QiYongShuJuKu = objCopyFrom.rg_QiYongShuJuKu;
    rg_QiYongWebGL = objCopyFrom.rg_QiYongWebGL;
    rg_BeiJingYanSe1 = objCopyFrom.rg_BeiJingYanSe1;
    rg_ZhuangTaiQiPao = objCopyFrom.rg_ZhuangTaiQiPao;
    rg_SuFangQiPao = objCopyFrom.rg_SuFangQiPao;
}

void rg_FBrowser_LiuLanQiPeiZhi::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_LiBingXuanRanZhengLu, sizeof (INT));
    rg_BiaoZhunZiTiLeiXing.LoadFromStream (stream);
    rg_GuDingZiTiLeiXing.LoadFromStream (stream);
    rg_ChenXianZiTiLeiXing.LoadFromStream (stream);
    rg_MoChenXianZiTiLeiXing.LoadFromStream (stream);
    rg_CaoShuZiTiLeiXing.LoadFromStream (stream);
    rg_HuanXiangZiTiLeiXing.LoadFromStream (stream);
    stream.ReadExact (&rg_MoRenZiTiDaXiao, sizeof (INT));
    stream.ReadExact (&rg_MoRenGuDingZiTiDaXiao, sizeof (INT));
    stream.ReadExact (&rg_ZuiXiaoZiTiDaXiao, sizeof (INT));
    stream.ReadExact (&rg_ZuiXiaoLuoJiZiTiDaXiao, sizeof (INT));
    rg_MoRenBianMa.LoadFromStream (stream);
    stream.ReadExact (&rg_YuanChengZiTi, sizeof (INT));
    stream.ReadExact (&rg_QiYongJS, sizeof (INT));
    stream.ReadExact (&rg_QiYongJSGuanBiChuangKou, sizeof (INT));
    stream.ReadExact (&rg_QiYongJSFangWenJianQieBan, sizeof (INT));
    stream.ReadExact (&rg_QiYongJSDOMNianTie, sizeof (INT));
    stream.ReadExact (&rg_QiYongTuPianJiaZai, sizeof (INT));
    stream.ReadExact (&rg_QiYongTuPianZiKuoGe, sizeof (INT));
    stream.ReadExact (&rg_QiYongWenBenOuYuDiaoZheng, sizeof (INT));
    stream.ReadExact (&rg_QiYongXuanXiangKaLianJie, sizeof (INT));
    stream.ReadExact (&rg_QiYongBenDeCunChu, sizeof (INT));
    stream.ReadExact (&rg_QiYongShuJuKu, sizeof (INT));
    stream.ReadExact (&rg_QiYongWebGL, sizeof (INT));
    stream.ReadExact (&rg_BeiJingYanSe1, sizeof (INT));
    stream.ReadExact (&rg_ZhuangTaiQiPao, sizeof (INT));
    stream.ReadExact (&rg_SuFangQiPao, sizeof (INT));
}

void rg_FBrowser_LiuLanQiPeiZhi::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_LiBingXuanRanZhengLu, sizeof (INT));
    rg_BiaoZhunZiTiLeiXing.SaveIntoStream (stream);
    rg_GuDingZiTiLeiXing.SaveIntoStream (stream);
    rg_ChenXianZiTiLeiXing.SaveIntoStream (stream);
    rg_MoChenXianZiTiLeiXing.SaveIntoStream (stream);
    rg_CaoShuZiTiLeiXing.SaveIntoStream (stream);
    rg_HuanXiangZiTiLeiXing.SaveIntoStream (stream);
    stream.write (&rg_MoRenZiTiDaXiao, sizeof (INT));
    stream.write (&rg_MoRenGuDingZiTiDaXiao, sizeof (INT));
    stream.write (&rg_ZuiXiaoZiTiDaXiao, sizeof (INT));
    stream.write (&rg_ZuiXiaoLuoJiZiTiDaXiao, sizeof (INT));
    rg_MoRenBianMa.SaveIntoStream (stream);
    stream.write (&rg_YuanChengZiTi, sizeof (INT));
    stream.write (&rg_QiYongJS, sizeof (INT));
    stream.write (&rg_QiYongJSGuanBiChuangKou, sizeof (INT));
    stream.write (&rg_QiYongJSFangWenJianQieBan, sizeof (INT));
    stream.write (&rg_QiYongJSDOMNianTie, sizeof (INT));
    stream.write (&rg_QiYongTuPianJiaZai, sizeof (INT));
    stream.write (&rg_QiYongTuPianZiKuoGe, sizeof (INT));
    stream.write (&rg_QiYongWenBenOuYuDiaoZheng, sizeof (INT));
    stream.write (&rg_QiYongXuanXiangKaLianJie, sizeof (INT));
    stream.write (&rg_QiYongBenDeCunChu, sizeof (INT));
    stream.write (&rg_QiYongShuJuKu, sizeof (INT));
    stream.write (&rg_QiYongWebGL, sizeof (INT));
    stream.write (&rg_BeiJingYanSe1, sizeof (INT));
    stream.write (&rg_ZhuangTaiQiPao, sizeof (INT));
    stream.write (&rg_SuFangQiPao, sizeof (INT));
}
FBroBrowserSetting* rg_FBrowser_LiuLanQiPeiZhi::ToFBroData(){
  release();
   m_data.is_null=false;
   m_data.windowless_frame_rate=rg_LiBingXuanRanZhengLu;
   m_data.standard_font_family=FBroUnit::UnicodeToAnsi(rg_BiaoZhunZiTiLeiXing);
   m_data.fixed_font_family=FBroUnit::UnicodeToAnsi(rg_GuDingZiTiLeiXing);
   m_data.serif_font_family=FBroUnit::UnicodeToAnsi(rg_ChenXianZiTiLeiXing);
   m_data.sans_serif_font_family=FBroUnit::UnicodeToAnsi(rg_MoChenXianZiTiLeiXing);
   m_data.cursive_font_family=FBroUnit::UnicodeToAnsi(rg_CaoShuZiTiLeiXing);
   m_data.fantasy_font_family=FBroUnit::UnicodeToAnsi(rg_HuanXiangZiTiLeiXing);
   m_data.default_font_size=rg_MoRenZiTiDaXiao;
   m_data.default_fixed_font_size=rg_MoRenGuDingZiTiDaXiao;
   m_data.minimum_font_size=rg_ZuiXiaoZiTiDaXiao;
   m_data.minimum_logical_font_size=rg_ZuiXiaoLuoJiZiTiDaXiao;
   m_data.default_encoding=FBroUnit::UnicodeToAnsi(rg_MoRenBianMa);
   m_data.remote_fonts=rg_YuanChengZiTi;
   m_data.javascript=rg_QiYongJS;
   m_data.javascript_close_windows=rg_QiYongJSGuanBiChuangKou;
   m_data.javascript_access_clipboard=rg_QiYongJSFangWenJianQieBan;
   m_data.javascript_dom_paste=rg_QiYongJSDOMNianTie;
   m_data.image_loading=rg_QiYongTuPianJiaZai;
   m_data.image_shrink_standalone_to_fit=rg_QiYongTuPianZiKuoGe;
   m_data.text_area_resize=rg_QiYongWenBenOuYuDiaoZheng;
   m_data.tab_to_links=rg_QiYongXuanXiangKaLianJie;
   m_data.local_storage=rg_QiYongBenDeCunChu;
   m_data.databases=rg_QiYongShuJuKu;
   m_data.webgl=rg_QiYongWebGL;
   m_data.background_color=rg_BeiJingYanSe1;
   m_data.chrome_status_bubble=rg_ZhuangTaiQiPao;
   m_data.chrome_zoom_bubble=rg_SuFangQiPao;
  return &m_data;
}
void rg_FBrowser_LiuLanQiPeiZhi::release(){
   FBroUnit::FreeCharArray(m_data.standard_font_family);
   FBroUnit::FreeCharArray(m_data.fixed_font_family);
   FBroUnit::FreeCharArray(m_data.serif_font_family);
   FBroUnit::FreeCharArray(m_data.sans_serif_font_family);
   FBroUnit::FreeCharArray(m_data.cursive_font_family);
   FBroUnit::FreeCharArray(m_data.fantasy_font_family);
   FBroUnit::FreeCharArray(m_data.default_encoding);
}

rg_FBrowser_WeiZhi::rg_FBrowser_WeiZhi ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_WeiZhi::_VolObjectInitMembers ()
{
    rg_X5 = 0;
    rg_Y4 = 0;
}

BOOL rg_FBrowser_WeiZhi::_IsSelfEqual (const rg_FBrowser_WeiZhi& objCompare) const
{
    if (rg_X5 != objCompare.rg_X5)  return FALSE;
    if (rg_Y4 != objCompare.rg_Y4)  return FALSE;
    return TRUE;
}

void rg_FBrowser_WeiZhi::_CopySelfFrom (const rg_FBrowser_WeiZhi& objCopyFrom)
{
    rg_X5 = objCopyFrom.rg_X5;
    rg_Y4 = objCopyFrom.rg_Y4;
}

void rg_FBrowser_WeiZhi::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_X5, sizeof (INT));
    stream.ReadExact (&rg_Y4, sizeof (INT));
}

void rg_FBrowser_WeiZhi::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_X5, sizeof (INT));
    stream.write (&rg_Y4, sizeof (INT));
}
void rg_FBrowser_WeiZhi::ToFBroData(PTELIB_ELEMENT_AT inData){
   m_data.x=inData->x;
   m_data.y=inData->y;
}
PTELIB_ELEMENT_AT rg_FBrowser_WeiZhi::ToFBroData(){
   m_data.x=rg_X5;
   m_data.y=rg_Y4;
  return &m_data;
}
void rg_FBrowser_WeiZhi::ToHsData(){
  rg_X5=m_data.x;
  rg_Y4=m_data.y;
}

rg_FBrowser_CheCun::rg_FBrowser_CheCun ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_CheCun::_VolObjectInitMembers ()
{
    rg_GaoDu8 = 0;
    rg_KuanDu8 = 0;
}

BOOL rg_FBrowser_CheCun::_IsSelfEqual (const rg_FBrowser_CheCun& objCompare) const
{
    if (rg_GaoDu8 != objCompare.rg_GaoDu8)  return FALSE;
    if (rg_KuanDu8 != objCompare.rg_KuanDu8)  return FALSE;
    return TRUE;
}

void rg_FBrowser_CheCun::_CopySelfFrom (const rg_FBrowser_CheCun& objCopyFrom)
{
    rg_GaoDu8 = objCopyFrom.rg_GaoDu8;
    rg_KuanDu8 = objCopyFrom.rg_KuanDu8;
}

void rg_FBrowser_CheCun::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_GaoDu8, sizeof (INT));
    stream.ReadExact (&rg_KuanDu8, sizeof (INT));
}

void rg_FBrowser_CheCun::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_GaoDu8, sizeof (INT));
    stream.write (&rg_KuanDu8, sizeof (INT));
}
POINT_SIZE rg_FBrowser_CheCun::ToFBroData(){
    m_data.height = rg_GaoDu8;
    m_data.width = rg_KuanDu8;
    return &m_data;
}
void rg_FBrowser_CheCun::ToHsData(){
    rg_GaoDu8 = m_data.height;
    rg_KuanDu8 = m_data.width;
}

rg_FBrowser_JuXingWeiZhi::rg_FBrowser_JuXingWeiZhi ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_JuXingWeiZhi::_VolObjectInitMembers ()
{
    rg_HengZuoBiao2 = 0;
    rg_ZongZuoBiao2 = 0;
    rg_KuanDu9 = 0;
    rg_GaoDu9 = 0;
}

BOOL rg_FBrowser_JuXingWeiZhi::_IsSelfEqual (const rg_FBrowser_JuXingWeiZhi& objCompare) const
{
    if (rg_HengZuoBiao2 != objCompare.rg_HengZuoBiao2)  return FALSE;
    if (rg_ZongZuoBiao2 != objCompare.rg_ZongZuoBiao2)  return FALSE;
    if (rg_KuanDu9 != objCompare.rg_KuanDu9)  return FALSE;
    if (rg_GaoDu9 != objCompare.rg_GaoDu9)  return FALSE;
    return TRUE;
}

void rg_FBrowser_JuXingWeiZhi::_CopySelfFrom (const rg_FBrowser_JuXingWeiZhi& objCopyFrom)
{
    rg_HengZuoBiao2 = objCopyFrom.rg_HengZuoBiao2;
    rg_ZongZuoBiao2 = objCopyFrom.rg_ZongZuoBiao2;
    rg_KuanDu9 = objCopyFrom.rg_KuanDu9;
    rg_GaoDu9 = objCopyFrom.rg_GaoDu9;
}

void rg_FBrowser_JuXingWeiZhi::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_HengZuoBiao2, sizeof (INT));
    stream.ReadExact (&rg_ZongZuoBiao2, sizeof (INT));
    stream.ReadExact (&rg_KuanDu9, sizeof (INT));
    stream.ReadExact (&rg_GaoDu9, sizeof (INT));
}

void rg_FBrowser_JuXingWeiZhi::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_HengZuoBiao2, sizeof (INT));
    stream.write (&rg_ZongZuoBiao2, sizeof (INT));
    stream.write (&rg_KuanDu9, sizeof (INT));
    stream.write (&rg_GaoDu9, sizeof (INT));
}
POINT_RECT rg_FBrowser_JuXingWeiZhi::ToFBroData(){
  m_data.x=rg_HengZuoBiao2;
  m_data.y=rg_ZongZuoBiao2;
  m_data.width=rg_KuanDu9;
  m_data.height=rg_GaoDu9;
  return &m_data;
}
void rg_FBrowser_JuXingWeiZhi::ToHsData(){
  rg_HengZuoBiao2=m_data.x;
  rg_ZongZuoBiao2=m_data.y;
  rg_KuanDu9=m_data.width;
  rg_GaoDu9=m_data.height;
}

BOOL rg_FBrowser_JuXingWeiZhiShuZu::_IsSelfEqual (const rg_FBrowser_JuXingWeiZhiShuZu& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_FBrowser_JuXingWeiZhiShuZu::_CopySelfFrom (const rg_FBrowser_JuXingWeiZhiShuZu& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

BOOL rg_FBrowser_TuoYeWeiZhiShuZu::_IsSelfEqual (const rg_FBrowser_TuoYeWeiZhiShuZu& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_FBrowser_TuoYeWeiZhiShuZu::_CopySelfFrom (const rg_FBrowser_TuoYeWeiZhiShuZu& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

rg_FBrowser_AnJianShiJian::rg_FBrowser_AnJianShiJian ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_AnJianShiJian::_VolObjectInitMembers ()
{
    rg_LeiXing2 = 0;
    rg_XiuShiWei1 = 0;
    rg_JiTongAnJian = 0;
    rg_JiQiAnJian = 0;
    rg_ShiFouJiTongAnJian = 0;
    rg_ZiFuZhi = 0;
    rg_XiuGaiZiFu = 0;
    rg_ShiFouKeBianJi = 0;
}

BOOL rg_FBrowser_AnJianShiJian::_IsSelfEqual (const rg_FBrowser_AnJianShiJian& objCompare) const
{
    if (rg_LeiXing2 != objCompare.rg_LeiXing2)  return FALSE;
    if (rg_XiuShiWei1 != objCompare.rg_XiuShiWei1)  return FALSE;
    if (rg_JiTongAnJian != objCompare.rg_JiTongAnJian)  return FALSE;
    if (rg_JiQiAnJian != objCompare.rg_JiQiAnJian)  return FALSE;
    if (rg_ShiFouJiTongAnJian != objCompare.rg_ShiFouJiTongAnJian)  return FALSE;
    if (rg_ZiFuZhi != objCompare.rg_ZiFuZhi)  return FALSE;
    if (rg_XiuGaiZiFu != objCompare.rg_XiuGaiZiFu)  return FALSE;
    if (rg_ShiFouKeBianJi != objCompare.rg_ShiFouKeBianJi)  return FALSE;
    return TRUE;
}

void rg_FBrowser_AnJianShiJian::_CopySelfFrom (const rg_FBrowser_AnJianShiJian& objCopyFrom)
{
    rg_LeiXing2 = objCopyFrom.rg_LeiXing2;
    rg_XiuShiWei1 = objCopyFrom.rg_XiuShiWei1;
    rg_JiTongAnJian = objCopyFrom.rg_JiTongAnJian;
    rg_JiQiAnJian = objCopyFrom.rg_JiQiAnJian;
    rg_ShiFouJiTongAnJian = objCopyFrom.rg_ShiFouJiTongAnJian;
    rg_ZiFuZhi = objCopyFrom.rg_ZiFuZhi;
    rg_XiuGaiZiFu = objCopyFrom.rg_XiuGaiZiFu;
    rg_ShiFouKeBianJi = objCopyFrom.rg_ShiFouKeBianJi;
}

void rg_FBrowser_AnJianShiJian::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_LeiXing2, sizeof (INT));
    stream.ReadExact (&rg_XiuShiWei1, sizeof (INT));
    stream.ReadExact (&rg_JiTongAnJian, sizeof (INT));
    stream.ReadExact (&rg_JiQiAnJian, sizeof (INT));
    stream.ReadExact (&rg_ShiFouJiTongAnJian, sizeof (INT));
    stream.ReadExact (&rg_ZiFuZhi, sizeof (TCHAR));
    stream.ReadExact (&rg_XiuGaiZiFu, sizeof (TCHAR));
    stream.ReadExact (&rg_ShiFouKeBianJi, sizeof (INT));
}

void rg_FBrowser_AnJianShiJian::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_LeiXing2, sizeof (INT));
    stream.write (&rg_XiuShiWei1, sizeof (INT));
    stream.write (&rg_JiTongAnJian, sizeof (INT));
    stream.write (&rg_JiQiAnJian, sizeof (INT));
    stream.write (&rg_ShiFouJiTongAnJian, sizeof (INT));
    stream.write (&rg_ZiFuZhi, sizeof (TCHAR));
    stream.write (&rg_XiuGaiZiFu, sizeof (TCHAR));
    stream.write (&rg_ShiFouKeBianJi, sizeof (INT));
}
PTELIB_KEYEVENT rg_FBrowser_AnJianShiJian::ToFBroData(){
  m_data.type=rg_LeiXing2;
  m_data.modifiers=rg_XiuShiWei1;
  m_data.windows_key_code=rg_JiTongAnJian;
  m_data.native_key_code=rg_JiQiAnJian;
  m_data.is_system_key=rg_ShiFouJiTongAnJian;
  m_data.h_character= rg_ZiFuZhi >> 8;
  m_data.character=rg_ZiFuZhi & 0xff ;
  m_data.h_unmodified_character=rg_XiuGaiZiFu >> 8;
  m_data.unmodified_character=rg_XiuGaiZiFu & 0xff;
  m_data.focus_on_editable_field=rg_ShiFouKeBianJi;
  return &m_data;
}
void rg_FBrowser_AnJianShiJian::ToHsData(){
  rg_LeiXing2= m_data.type;
  rg_XiuShiWei1=m_data.modifiers;
  rg_JiTongAnJian=m_data.windows_key_code;
  rg_JiQiAnJian=m_data.native_key_code;
  rg_ShiFouJiTongAnJian=m_data.is_system_key;
  rg_ZiFuZhi=(m_data.h_character << 8) | (m_data.character & 0xff);
  rg_XiuGaiZiFu=(m_data.h_unmodified_character << 8) | (m_data.unmodified_character & 0xff);
  rg_ShiFouKeBianJi=m_data.focus_on_editable_field;
}

rg_FBrowser_JiTongShiJian::rg_FBrowser_JiTongShiJian ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_JiTongShiJian::_VolObjectInitMembers ()
{
    rg_GouBing = 0;
    rg_XiaoXi9 = 0;
    rg_wParam = 0;
    rg_lParam = 0;
    rg_ShiJian2 = 0;
}

BOOL rg_FBrowser_JiTongShiJian::_IsSelfEqual (const rg_FBrowser_JiTongShiJian& objCompare) const
{
    if (rg_GouBing != objCompare.rg_GouBing)  return FALSE;
    if (rg_XiaoXi9 != objCompare.rg_XiaoXi9)  return FALSE;
    if (rg_wParam != objCompare.rg_wParam)  return FALSE;
    if (rg_lParam != objCompare.rg_lParam)  return FALSE;
    if (rg_ShiJian2 != objCompare.rg_ShiJian2)  return FALSE;
    if (rg_WeiZhi18 != objCompare.rg_WeiZhi18)  return FALSE;
    return TRUE;
}

void rg_FBrowser_JiTongShiJian::_CopySelfFrom (const rg_FBrowser_JiTongShiJian& objCopyFrom)
{
    rg_GouBing = objCopyFrom.rg_GouBing;
    rg_XiaoXi9 = objCopyFrom.rg_XiaoXi9;
    rg_wParam = objCopyFrom.rg_wParam;
    rg_lParam = objCopyFrom.rg_lParam;
    rg_ShiJian2 = objCopyFrom.rg_ShiJian2;
    rg_WeiZhi18 = objCopyFrom.rg_WeiZhi18;
}

void rg_FBrowser_JiTongShiJian::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_GouBing, sizeof (INT));
    stream.ReadExact (&rg_XiaoXi9, sizeof (INT));
    stream.ReadExact (&rg_wParam, sizeof (INT64));
    stream.ReadExact (&rg_lParam, sizeof (INT64));
    stream.ReadExact (&rg_ShiJian2, sizeof (INT));
    rg_WeiZhi18.LoadFromStream (stream);
}

void rg_FBrowser_JiTongShiJian::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_GouBing, sizeof (INT));
    stream.write (&rg_XiaoXi9, sizeof (INT));
    stream.write (&rg_wParam, sizeof (INT64));
    stream.write (&rg_lParam, sizeof (INT64));
    stream.write (&rg_ShiJian2, sizeof (INT));
    rg_WeiZhi18.SaveIntoStream (stream);
}
POINT_OSEVENT rg_FBrowser_JiTongShiJian::ToFBroData(){
  m_data.hwnd=(HWND)rg_GouBing;
  m_data.message=rg_XiaoXi9;
  m_data.wParam=(WPARAM)rg_wParam;
  m_data.lParam=(LPARAM)rg_lParam;
  m_data.time=rg_ShiJian2;
  m_data.point.x=rg_WeiZhi18.rg_X5;
  m_data.point.y=rg_WeiZhi18.rg_Y4;
  return &m_data;
}
void rg_FBrowser_JiTongShiJian::ToHsData(){
  rg_GouBing=(INT)m_data.hwnd;
  rg_XiaoXi9=m_data.message;
  rg_wParam=m_data.wParam;
  rg_lParam=m_data.lParam;
  rg_ShiJian2=m_data.time;
  rg_WeiZhi18.rg_X5=m_data.point.x;
  rg_WeiZhi18.rg_Y4=m_data.point.y;
}

rg_FBrowser_ShuBiaoShiJian::rg_FBrowser_ShuBiaoShiJian ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_ShuBiaoShiJian::_VolObjectInitMembers ()
{
    rg_HengZuoBiao3 = 0;
    rg_ZongZuoBiao3 = 0;
    rg_XiuShiJian = 0;
}

BOOL rg_FBrowser_ShuBiaoShiJian::_IsSelfEqual (const rg_FBrowser_ShuBiaoShiJian& objCompare) const
{
    if (rg_HengZuoBiao3 != objCompare.rg_HengZuoBiao3)  return FALSE;
    if (rg_ZongZuoBiao3 != objCompare.rg_ZongZuoBiao3)  return FALSE;
    if (rg_XiuShiJian != objCompare.rg_XiuShiJian)  return FALSE;
    return TRUE;
}

void rg_FBrowser_ShuBiaoShiJian::_CopySelfFrom (const rg_FBrowser_ShuBiaoShiJian& objCopyFrom)
{
    rg_HengZuoBiao3 = objCopyFrom.rg_HengZuoBiao3;
    rg_ZongZuoBiao3 = objCopyFrom.rg_ZongZuoBiao3;
    rg_XiuShiJian = objCopyFrom.rg_XiuShiJian;
}

void rg_FBrowser_ShuBiaoShiJian::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_HengZuoBiao3, sizeof (INT));
    stream.ReadExact (&rg_ZongZuoBiao3, sizeof (INT));
    stream.ReadExact (&rg_XiuShiJian, sizeof (INT));
}

void rg_FBrowser_ShuBiaoShiJian::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_HengZuoBiao3, sizeof (INT));
    stream.write (&rg_ZongZuoBiao3, sizeof (INT));
    stream.write (&rg_XiuShiJian, sizeof (INT));
}
POINT_MOUSEEVENT rg_FBrowser_ShuBiaoShiJian::ToFBroData(){
  m_data.x=rg_HengZuoBiao3;
  m_data.y=rg_ZongZuoBiao3;
  m_data.modifiers=rg_XiuShiJian;
  return &m_data;
}

BOOL rg_FBrowser_ShuangWenBen::_IsSelfEqual (const rg_FBrowser_ShuangWenBen& objCompare) const
{
    if (rg_name1 != objCompare.rg_name1)  return FALSE;
    if (rg_value85 != objCompare.rg_value85)  return FALSE;
    return TRUE;
}

void rg_FBrowser_ShuangWenBen::_CopySelfFrom (const rg_FBrowser_ShuangWenBen& objCopyFrom)
{
    rg_name1 = objCopyFrom.rg_name1;
    rg_value85 = objCopyFrom.rg_value85;
}

void rg_FBrowser_ShuangWenBen::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    rg_name1.LoadFromStream (stream);
    rg_value85.LoadFromStream (stream);
}

void rg_FBrowser_ShuangWenBen::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    rg_name1.SaveIntoStream (stream);
    rg_value85.SaveIntoStream (stream);
}
PTELIB_STRING_STRING rg_FBrowser_ShuangWenBen::ToFBroData(){
  release();
  m_data.first=FBroUnit::UnicodeToAnsi(rg_name1);
  m_data.second=FBroUnit::UnicodeToAnsi(rg_value85);
  return &m_data;
}
void rg_FBrowser_ShuangWenBen::release(){
  FBroUnit::FreeCharArray(m_data.first);
  FBroUnit::FreeCharArray(m_data.second);
}

BOOL rg_FBrowser_ShuangWenBenShuZu::_IsSelfEqual (const rg_FBrowser_ShuangWenBenShuZu& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_FBrowser_ShuangWenBenShuZu::_CopySelfFrom (const rg_FBrowser_ShuangWenBenShuZu& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

BOOL rg_FBrowser_ShuangWenBenShuZu::rg_ShiFouWeiKong122 ()
{
    return BOOL(IsEmpty());
}

void rg_FBrowser_ShuangWenBenShuZu::rg_ChuangJian7 ()
{
    m_data=FBroDoubleString_Creat();
}

INT rg_FBrowser_ShuangWenBenShuZu::rg_QuGeShu2 ()
{
    return IsEmpty()?0:FBroDoubleString_Size(m_data);
}

void rg_FBrowser_ShuangWenBenShuZu::rg_JiaRuChengYuan35 (rg_FBrowser_ShuangWenBen& rg_member2)
{
    if(!IsEmpty()) FBroDoubleString_Add(m_data,rg_member2.rg_name1.GetText(), rg_member2.rg_value85.GetText());
}

void rg_FBrowser_ShuangWenBenShuZu::rg_DaoShuZuShou2 ()
{
    if(!IsEmpty()) FBroDoubleString_ToBegin(m_data);
}

BOOL rg_FBrowser_ShuangWenBenShuZu::rg_DaoXiaYiGe2 ()
{
    if(!IsEmpty()) return FBroDoubleString_ToNext(m_data);
    return (FALSE);
}

rg_FBrowser_ShuangWenBen rg_FBrowser_ShuangWenBenShuZu::rg_QuDangQianWeiZhiShuJu2 ()
{
    rg_FBrowser_ShuangWenBen rg_temp3;
    rg_temp3.rg_name1 = rg_QuDangQianWeiZhiShuJu_GuanJianZi ();
    rg_temp3.rg_value85 = rg_QuDangQianWeiZhiShuJu_ShuJu ();
    return (rg_temp3);
}

CVolString rg_FBrowser_ShuangWenBenShuZu::rg_QuDangQianWeiZhiShuJu_GuanJianZi ()
{
    if(IsEmpty()) return CVolString();
    CefRefPtr<FBroString> fbrostring = FBroDoubleString_GetCurrentData_Key(m_data);
    return FBroUnit::FBroStringToCWString(fbrostring);
}

CVolString rg_FBrowser_ShuangWenBenShuZu::rg_QuDangQianWeiZhiShuJu_ShuJu ()
{
    if(IsEmpty()) return CVolString();
    CefRefPtr<FBroString> fbrostring = FBroDoubleString_GetCurrentData_Value(m_data);
    return FBroUnit::FBroStringToCWString(fbrostring);
}

BOOL rg_FBrowser_string::_IsSelfEqual (const rg_FBrowser_string& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_FBrowser_string::_CopySelfFrom (const rg_FBrowser_string& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

CVolString rg_FBrowser_string::rg_QuZhi24 ()
{
    if(!IsEmpty()) return FBroUnit::FBroStringToCWString(m_data);
    return (_T (""));
}

BOOL rg_FBrowser_WenBenShuZu::_IsSelfEqual (const rg_FBrowser_WenBenShuZu& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_FBrowser_WenBenShuZu::_CopySelfFrom (const rg_FBrowser_WenBenShuZu& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

void rg_FBrowser_WenBenShuZu::rg_ChuangJian9 ()
{
    m_data=FBroCefStringList_Creat();
}

INT rg_FBrowser_WenBenShuZu::rg_QuGeShu3 ()
{
    return FBroCefStringList_Size(m_data);
}

void rg_FBrowser_WenBenShuZu::rg_JiaRuChengYuan36 (CVolString& rg_member3)
{
    if(!IsEmpty()) FBroCefStringList_Add(m_data, rg_member3.GetText());
}

CVolString rg_FBrowser_WenBenShuZu::rg_QuShuJu3 (INT rg_SuoYin3)
{
    if(IsEmpty()) return CVolString();
    CefRefPtr<FBroString> fbrostring = FBroCefStringList_GetValue(m_data,rg_SuoYin3);
    return FBroUnit::FBroStringToCWString(fbrostring);
}

rg_FBrowser_GuangBiaoXinXi::rg_FBrowser_GuangBiaoXinXi ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_GuangBiaoXinXi::_VolObjectInitMembers ()
{
    rg_HengZuoBiao5 = 0;
    rg_ZongZuoBiao5 = 0;
    rg_TuXiangBiLiYinZi = 0;
    rg_HuanCunZhiZhen = 0;
    rg_CheCunKuanDu = 0;
    rg_CheCunGaoDu = 0;
}

BOOL rg_FBrowser_GuangBiaoXinXi::_IsSelfEqual (const rg_FBrowser_GuangBiaoXinXi& objCompare) const
{
    if (rg_HengZuoBiao5 != objCompare.rg_HengZuoBiao5)  return FALSE;
    if (rg_ZongZuoBiao5 != objCompare.rg_ZongZuoBiao5)  return FALSE;
    if (IsDoubleEqual (rg_TuXiangBiLiYinZi, objCompare.rg_TuXiangBiLiYinZi) == FALSE)  return FALSE;
    if (rg_HuanCunZhiZhen != objCompare.rg_HuanCunZhiZhen)  return FALSE;
    if (rg_CheCunKuanDu != objCompare.rg_CheCunKuanDu)  return FALSE;
    if (rg_CheCunGaoDu != objCompare.rg_CheCunGaoDu)  return FALSE;
    return TRUE;
}

void rg_FBrowser_GuangBiaoXinXi::_CopySelfFrom (const rg_FBrowser_GuangBiaoXinXi& objCopyFrom)
{
    rg_HengZuoBiao5 = objCopyFrom.rg_HengZuoBiao5;
    rg_ZongZuoBiao5 = objCopyFrom.rg_ZongZuoBiao5;
    rg_TuXiangBiLiYinZi = objCopyFrom.rg_TuXiangBiLiYinZi;
    rg_HuanCunZhiZhen = objCopyFrom.rg_HuanCunZhiZhen;
    rg_CheCunKuanDu = objCopyFrom.rg_CheCunKuanDu;
    rg_CheCunGaoDu = objCopyFrom.rg_CheCunGaoDu;
}

void rg_FBrowser_GuangBiaoXinXi::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_HengZuoBiao5, sizeof (INT));
    stream.ReadExact (&rg_ZongZuoBiao5, sizeof (INT));
    stream.ReadExact (&rg_TuXiangBiLiYinZi, sizeof (DOUBLE));
    stream.ReadExact (&rg_HuanCunZhiZhen, sizeof (INT));
    stream.ReadExact (&rg_CheCunKuanDu, sizeof (INT));
    stream.ReadExact (&rg_CheCunGaoDu, sizeof (INT));
}

void rg_FBrowser_GuangBiaoXinXi::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_HengZuoBiao5, sizeof (INT));
    stream.write (&rg_ZongZuoBiao5, sizeof (INT));
    stream.write (&rg_TuXiangBiLiYinZi, sizeof (DOUBLE));
    stream.write (&rg_HuanCunZhiZhen, sizeof (INT));
    stream.write (&rg_CheCunKuanDu, sizeof (INT));
    stream.write (&rg_CheCunGaoDu, sizeof (INT));
}
CefCursorInfo* rg_FBrowser_GuangBiaoXinXi::ToFBroData(){
  release();
  m_data.hotspot.x=rg_HengZuoBiao5;
  m_data.hotspot.y=rg_ZongZuoBiao5;
  m_data.image_scale_factor=(float)rg_TuXiangBiLiYinZi;
  m_data.buffer=(void *)rg_HuanCunZhiZhen;
  m_data.size.width=rg_CheCunKuanDu;
  m_data.size.height=rg_CheCunGaoDu;
  return &m_data;
}
void rg_FBrowser_GuangBiaoXinXi::release(){
}

rg_FBrowser_ShiJianLeiXing::rg_FBrowser_ShiJianLeiXing ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_ShiJianLeiXing::_VolObjectInitMembers ()
{
    rg_Nian1 = 0;
    rg_Yue1 = 0;
    rg_Ri3 = 0;
    rg_Shi = 0;
    rg_Fen = 0;
    rg_Miao3 = 0;
    rg_HaoMiao2 = 0;
}

BOOL rg_FBrowser_ShiJianLeiXing::_IsSelfEqual (const rg_FBrowser_ShiJianLeiXing& objCompare) const
{
    if (rg_Nian1 != objCompare.rg_Nian1)  return FALSE;
    if (rg_Yue1 != objCompare.rg_Yue1)  return FALSE;
    if (rg_Ri3 != objCompare.rg_Ri3)  return FALSE;
    if (rg_Shi != objCompare.rg_Shi)  return FALSE;
    if (rg_Fen != objCompare.rg_Fen)  return FALSE;
    if (rg_Miao3 != objCompare.rg_Miao3)  return FALSE;
    if (rg_HaoMiao2 != objCompare.rg_HaoMiao2)  return FALSE;
    return TRUE;
}

void rg_FBrowser_ShiJianLeiXing::_CopySelfFrom (const rg_FBrowser_ShiJianLeiXing& objCopyFrom)
{
    rg_Nian1 = objCopyFrom.rg_Nian1;
    rg_Yue1 = objCopyFrom.rg_Yue1;
    rg_Ri3 = objCopyFrom.rg_Ri3;
    rg_Shi = objCopyFrom.rg_Shi;
    rg_Fen = objCopyFrom.rg_Fen;
    rg_Miao3 = objCopyFrom.rg_Miao3;
    rg_HaoMiao2 = objCopyFrom.rg_HaoMiao2;
}

void rg_FBrowser_ShiJianLeiXing::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_Nian1, sizeof (INT));
    stream.ReadExact (&rg_Yue1, sizeof (INT));
    stream.ReadExact (&rg_Ri3, sizeof (INT));
    stream.ReadExact (&rg_Shi, sizeof (INT));
    stream.ReadExact (&rg_Fen, sizeof (INT));
    stream.ReadExact (&rg_Miao3, sizeof (INT));
    stream.ReadExact (&rg_HaoMiao2, sizeof (INT));
}

void rg_FBrowser_ShiJianLeiXing::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_Nian1, sizeof (INT));
    stream.write (&rg_Yue1, sizeof (INT));
    stream.write (&rg_Ri3, sizeof (INT));
    stream.write (&rg_Shi, sizeof (INT));
    stream.write (&rg_Fen, sizeof (INT));
    stream.write (&rg_Miao3, sizeof (INT));
    stream.write (&rg_HaoMiao2, sizeof (INT));
}
POINT_TIMEDATA rg_FBrowser_ShiJianLeiXing::ToFBroData(){
  release();
  m_data.year=rg_Nian1;
  m_data.month=rg_Yue1;
  m_data.day=rg_Ri3;
  m_data.hour=rg_Shi;
  m_data.minute=rg_Fen;
  m_data.second=rg_Miao3;
  m_data.millisecond=rg_HaoMiao2;
  return &m_data;
}
void rg_FBrowser_ShiJianLeiXing::ToHsData(E_TIMEDATA data){
  m_data=data;
  rg_Nian1=m_data.year;
  rg_Yue1=m_data.month;
  rg_Ri3=m_data.day;
  rg_Shi=m_data.hour;
  rg_Fen=m_data.minute;
  rg_Miao3=m_data.second;
  rg_HaoMiao2=m_data.millisecond;
}
void rg_FBrowser_ShiJianLeiXing::release(){
}

rg_FBrowser_CookieShuJu::rg_FBrowser_CookieShuJu ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_CookieShuJu::_VolObjectInitMembers ()
{
    rg_ShiFouZhiYouhttp = FALSE;
    rg_ShiFouYouGuoJiShiJian = FALSE;
    rg_AnQuanChuanShu = FALSE;
    rg_TongZhan = 0;
    rg_YouXianJi2 = 0;
}

BOOL rg_FBrowser_CookieShuJu::_IsSelfEqual (const rg_FBrowser_CookieShuJu& objCompare) const
{
    if (rg_Ming10 != objCompare.rg_Ming10)  return FALSE;
    if (rg_value91 != objCompare.rg_value91)  return FALSE;
    if (rg_Yu != objCompare.rg_Yu)  return FALSE;
    if (rg_LuJing4 != objCompare.rg_LuJing4)  return FALSE;
    if (rg_ShiFouZhiYouhttp != objCompare.rg_ShiFouZhiYouhttp)  return FALSE;
    if (rg_ShiFouYouGuoJiShiJian != objCompare.rg_ShiFouYouGuoJiShiJian)  return FALSE;
    if (rg_GuoJiShiJian1 != objCompare.rg_GuoJiShiJian1)  return FALSE;
    if (rg_FangWenShiJian != objCompare.rg_FangWenShiJian)  return FALSE;
    if (rg_AnQuanChuanShu != objCompare.rg_AnQuanChuanShu)  return FALSE;
    if (rg_TongZhan != objCompare.rg_TongZhan)  return FALSE;
    if (rg_YouXianJi2 != objCompare.rg_YouXianJi2)  return FALSE;
    return TRUE;
}

void rg_FBrowser_CookieShuJu::_CopySelfFrom (const rg_FBrowser_CookieShuJu& objCopyFrom)
{
    rg_Ming10 = objCopyFrom.rg_Ming10;
    rg_value91 = objCopyFrom.rg_value91;
    rg_Yu = objCopyFrom.rg_Yu;
    rg_LuJing4 = objCopyFrom.rg_LuJing4;
    rg_ShiFouZhiYouhttp = objCopyFrom.rg_ShiFouZhiYouhttp;
    rg_ShiFouYouGuoJiShiJian = objCopyFrom.rg_ShiFouYouGuoJiShiJian;
    rg_GuoJiShiJian1 = objCopyFrom.rg_GuoJiShiJian1;
    rg_FangWenShiJian = objCopyFrom.rg_FangWenShiJian;
    rg_AnQuanChuanShu = objCopyFrom.rg_AnQuanChuanShu;
    rg_TongZhan = objCopyFrom.rg_TongZhan;
    rg_YouXianJi2 = objCopyFrom.rg_YouXianJi2;
}

void rg_FBrowser_CookieShuJu::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    rg_Ming10.LoadFromStream (stream);
    rg_value91.LoadFromStream (stream);
    rg_Yu.LoadFromStream (stream);
    rg_LuJing4.LoadFromStream (stream);
    stream.ReadExact (&rg_ShiFouZhiYouhttp, sizeof (BOOL));
    stream.ReadExact (&rg_ShiFouYouGuoJiShiJian, sizeof (BOOL));
    rg_GuoJiShiJian1.LoadFromStream (stream);
    rg_FangWenShiJian.LoadFromStream (stream);
    stream.ReadExact (&rg_AnQuanChuanShu, sizeof (BOOL));
    stream.ReadExact (&rg_TongZhan, sizeof (INT));
    stream.ReadExact (&rg_YouXianJi2, sizeof (INT));
}

void rg_FBrowser_CookieShuJu::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    rg_Ming10.SaveIntoStream (stream);
    rg_value91.SaveIntoStream (stream);
    rg_Yu.SaveIntoStream (stream);
    rg_LuJing4.SaveIntoStream (stream);
    stream.write (&rg_ShiFouZhiYouhttp, sizeof (BOOL));
    stream.write (&rg_ShiFouYouGuoJiShiJian, sizeof (BOOL));
    rg_GuoJiShiJian1.SaveIntoStream (stream);
    rg_FangWenShiJian.SaveIntoStream (stream);
    stream.write (&rg_AnQuanChuanShu, sizeof (BOOL));
    stream.write (&rg_TongZhan, sizeof (INT));
    stream.write (&rg_YouXianJi2, sizeof (INT));
}
POINT_COOKIEDATA rg_FBrowser_CookieShuJu::ToFBroData(){
  release();
  m_data.name = FBroUnit::UnicodeToAnsi(rg_Ming10.GetText());
  m_data.value = FBroUnit::UnicodeToAnsi(rg_value91.GetText());
  m_data.domain = FBroUnit::UnicodeToAnsi(rg_Yu.GetText());
  m_data.path = FBroUnit::UnicodeToAnsi(rg_LuJing4.GetText());
  m_data.httponly = rg_ShiFouZhiYouhttp;
  m_data.has_expires = rg_ShiFouYouGuoJiShiJian;
  rg_GuoJiShiJian1.ToFBroData();
  m_data.expires_time = rg_GuoJiShiJian1.m_data;
  rg_FangWenShiJian.ToFBroData();
  m_data.last_access_time = rg_FangWenShiJian.m_data;
  m_data.secure=rg_AnQuanChuanShu;
  m_data.same_site=rg_TongZhan;
  m_data.priority=rg_YouXianJi2;
  return &m_data;
}
void rg_FBrowser_CookieShuJu::ToHsData(){
  rg_Ming10=FBroUnit::ToCWString(m_data.name);
  rg_value91=FBroUnit::ToCWString(m_data.value);
  rg_Yu=FBroUnit::ToCWString(m_data.domain);
  rg_LuJing4=FBroUnit::ToCWString(m_data.path);
  rg_ShiFouZhiYouhttp = m_data.httponly;
  rg_ShiFouYouGuoJiShiJian = m_data.has_expires;
  rg_GuoJiShiJian1.ToHsData(m_data.expires_time);
  rg_FangWenShiJian.ToHsData(m_data.last_access_time);
  rg_AnQuanChuanShu = m_data.secure;
  rg_TongZhan = m_data.same_site;
  rg_YouXianJi2 = m_data.priority;
}
void rg_FBrowser_CookieShuJu::release(){
  FBroUnit::FreeCharArray(m_data.name);
  FBroUnit::FreeCharArray(m_data.value);
  FBroUnit::FreeCharArray(m_data.domain);
  FBroUnit::FreeCharArray(m_data.path);
}

rg_FBrowser_BingMuXinXi::rg_FBrowser_BingMuXinXi ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_BingMuXinXi::_VolObjectInitMembers ()
{
    rg_SheBeiBiLiYinZi = 0;
    rg_ShenDu = 0;
    rg_ShenDuHuoZuJian = 0;
    rg_is_monochrome = 0;
}

BOOL rg_FBrowser_BingMuXinXi::_IsSelfEqual (const rg_FBrowser_BingMuXinXi& objCompare) const
{
    if (IsDoubleEqual (rg_SheBeiBiLiYinZi, objCompare.rg_SheBeiBiLiYinZi) == FALSE)  return FALSE;
    if (rg_ShenDu != objCompare.rg_ShenDu)  return FALSE;
    if (rg_ShenDuHuoZuJian != objCompare.rg_ShenDuHuoZuJian)  return FALSE;
    if (rg_is_monochrome != objCompare.rg_is_monochrome)  return FALSE;
    if (rg_JuXingWeiZhi1 != objCompare.rg_JuXingWeiZhi1)  return FALSE;
    if (rg_KeYongJuXing != objCompare.rg_KeYongJuXing)  return FALSE;
    return TRUE;
}

void rg_FBrowser_BingMuXinXi::_CopySelfFrom (const rg_FBrowser_BingMuXinXi& objCopyFrom)
{
    rg_SheBeiBiLiYinZi = objCopyFrom.rg_SheBeiBiLiYinZi;
    rg_ShenDu = objCopyFrom.rg_ShenDu;
    rg_ShenDuHuoZuJian = objCopyFrom.rg_ShenDuHuoZuJian;
    rg_is_monochrome = objCopyFrom.rg_is_monochrome;
    rg_JuXingWeiZhi1 = objCopyFrom.rg_JuXingWeiZhi1;
    rg_KeYongJuXing = objCopyFrom.rg_KeYongJuXing;
}

void rg_FBrowser_BingMuXinXi::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_SheBeiBiLiYinZi, sizeof (DOUBLE));
    stream.ReadExact (&rg_ShenDu, sizeof (INT));
    stream.ReadExact (&rg_ShenDuHuoZuJian, sizeof (INT));
    stream.ReadExact (&rg_is_monochrome, sizeof (INT));
    rg_JuXingWeiZhi1.LoadFromStream (stream);
    rg_KeYongJuXing.LoadFromStream (stream);
}

void rg_FBrowser_BingMuXinXi::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_SheBeiBiLiYinZi, sizeof (DOUBLE));
    stream.write (&rg_ShenDu, sizeof (INT));
    stream.write (&rg_ShenDuHuoZuJian, sizeof (INT));
    stream.write (&rg_is_monochrome, sizeof (INT));
    rg_JuXingWeiZhi1.SaveIntoStream (stream);
    rg_KeYongJuXing.SaveIntoStream (stream);
}
POINT_SCREENINFO rg_FBrowser_BingMuXinXi::ToFBroData(){
     m_data.device_scale_factor=(float)rg_SheBeiBiLiYinZi;
     m_data.depth=rg_ShenDu;
     m_data.depth_per_component=rg_ShenDuHuoZuJian;
     m_data.is_monochrome=rg_is_monochrome;
     m_data.rect.x=rg_JuXingWeiZhi1.rg_HengZuoBiao2;
     m_data.rect.y=rg_JuXingWeiZhi1.rg_ZongZuoBiao2;
     m_data.rect.width=rg_JuXingWeiZhi1.rg_KuanDu9;
     m_data.rect.height=rg_JuXingWeiZhi1.rg_GaoDu9;
     m_data.available_rect.x=rg_KeYongJuXing.rg_HengZuoBiao2;
     m_data.available_rect.y=rg_KeYongJuXing.rg_ZongZuoBiao2;
     m_data.available_rect.width=rg_KeYongJuXing.rg_KuanDu9;
     m_data.available_rect.height=rg_KeYongJuXing.rg_GaoDu9;
     return &m_data;
}
void rg_FBrowser_BingMuXinXi::ToHsData(){
    rg_SheBeiBiLiYinZi = m_data.device_scale_factor;
    rg_ShenDu = m_data.depth;
    rg_ShenDuHuoZuJian = m_data.depth_per_component;
    rg_is_monochrome = m_data.is_monochrome;
    rg_JuXingWeiZhi1.rg_HengZuoBiao2 = m_data.rect.x;
    rg_JuXingWeiZhi1.rg_ZongZuoBiao2 = m_data.rect.y;
    rg_JuXingWeiZhi1.rg_KuanDu9 = m_data.rect.width;
    rg_JuXingWeiZhi1.rg_GaoDu9 = m_data.rect.height;
    rg_KeYongJuXing.rg_HengZuoBiao2 = m_data.available_rect.x;
    rg_KeYongJuXing.rg_ZongZuoBiao2 = m_data.available_rect.y;
    rg_KeYongJuXing.rg_KuanDu9 = m_data.available_rect.width;
    rg_KeYongJuXing.rg_GaoDu9 = m_data.available_rect.height;
}

rg_FBrowser_FanWei::rg_FBrowser_FanWei ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_FanWei::_VolObjectInitMembers ()
{
    rg_LaiYuan = 0;
    rg_MuBiao = 0;
}

BOOL rg_FBrowser_FanWei::_IsSelfEqual (const rg_FBrowser_FanWei& objCompare) const
{
    if (rg_LaiYuan != objCompare.rg_LaiYuan)  return FALSE;
    if (rg_MuBiao != objCompare.rg_MuBiao)  return FALSE;
    return TRUE;
}

void rg_FBrowser_FanWei::_CopySelfFrom (const rg_FBrowser_FanWei& objCopyFrom)
{
    rg_LaiYuan = objCopyFrom.rg_LaiYuan;
    rg_MuBiao = objCopyFrom.rg_MuBiao;
}

void rg_FBrowser_FanWei::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_LaiYuan, sizeof (INT));
    stream.ReadExact (&rg_MuBiao, sizeof (INT));
}

void rg_FBrowser_FanWei::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_LaiYuan, sizeof (INT));
    stream.write (&rg_MuBiao, sizeof (INT));
}
POINT_RANGE rg_FBrowser_FanWei::ToFBroData(){
     m_data.from=rg_LaiYuan;
     m_data.to=rg_MuBiao;
     return &m_data;
}
void rg_FBrowser_FanWei::ToHsData(){
    rg_LaiYuan = m_data.from;
    rg_MuBiao = m_data.to;
}

rg_FBrowser_JieTuBianKuangShuJu::rg_FBrowser_JieTuBianKuangShuJu ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_JieTuBianKuangShuJu::_VolObjectInitMembers ()
{
    rg_HengZuoBiao6 = 0;
    rg_ZongZuoBiao6 = 0;
    rg_KuanDu10 = 0;
    rg_GaoDu10 = 0;
    rg_SuFang = 0;
}

BOOL rg_FBrowser_JieTuBianKuangShuJu::_IsSelfEqual (const rg_FBrowser_JieTuBianKuangShuJu& objCompare) const
{
    if (rg_HengZuoBiao6 != objCompare.rg_HengZuoBiao6)  return FALSE;
    if (rg_ZongZuoBiao6 != objCompare.rg_ZongZuoBiao6)  return FALSE;
    if (rg_KuanDu10 != objCompare.rg_KuanDu10)  return FALSE;
    if (rg_GaoDu10 != objCompare.rg_GaoDu10)  return FALSE;
    if (rg_SuFang != objCompare.rg_SuFang)  return FALSE;
    return TRUE;
}

void rg_FBrowser_JieTuBianKuangShuJu::_CopySelfFrom (const rg_FBrowser_JieTuBianKuangShuJu& objCopyFrom)
{
    rg_HengZuoBiao6 = objCopyFrom.rg_HengZuoBiao6;
    rg_ZongZuoBiao6 = objCopyFrom.rg_ZongZuoBiao6;
    rg_KuanDu10 = objCopyFrom.rg_KuanDu10;
    rg_GaoDu10 = objCopyFrom.rg_GaoDu10;
    rg_SuFang = objCopyFrom.rg_SuFang;
}

void rg_FBrowser_JieTuBianKuangShuJu::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_HengZuoBiao6, sizeof (INT));
    stream.ReadExact (&rg_ZongZuoBiao6, sizeof (INT));
    stream.ReadExact (&rg_KuanDu10, sizeof (INT));
    stream.ReadExact (&rg_GaoDu10, sizeof (INT));
    stream.ReadExact (&rg_SuFang, sizeof (INT));
}

void rg_FBrowser_JieTuBianKuangShuJu::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_HengZuoBiao6, sizeof (INT));
    stream.write (&rg_ZongZuoBiao6, sizeof (INT));
    stream.write (&rg_KuanDu10, sizeof (INT));
    stream.write (&rg_GaoDu10, sizeof (INT));
    stream.write (&rg_SuFang, sizeof (INT));
}
VIEWPORT_POINT rg_FBrowser_JieTuBianKuangShuJu::ToFBroData(){
    m_data.x = rg_HengZuoBiao6;
    m_data.y = rg_ZongZuoBiao6;
    m_data.width = rg_KuanDu10;
    m_data.height = rg_GaoDu10;
    m_data.scale = rg_SuFang;
    return &m_data;
}
void rg_FBrowser_JieTuBianKuangShuJu::ToHsData(){
     rg_HengZuoBiao6 = m_data.x;
     rg_ZongZuoBiao6 = m_data.y;
     rg_KuanDu10 = m_data.width;
     rg_GaoDu10 = m_data.height;
     rg_SuFang = m_data.scale;
}

rg_FBrowser_VIPChuMoShiJian::rg_FBrowser_VIPChuMoShiJian ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_VIPChuMoShiJian::_VolObjectInitMembers ()
{
    rg_HengZuoBiao7 = 0;
    rg_ZongZuoBiao7 = 0;
    rg_HengBanJing = 1;
    rg_ZongBanJing = 1;
    rg_XuanZhuaiJiaoDu2 = 0;
    rg_YaLi1 = 1;
    rg_id4 = 0;
}

BOOL rg_FBrowser_VIPChuMoShiJian::_IsSelfEqual (const rg_FBrowser_VIPChuMoShiJian& objCompare) const
{
    if (rg_HengZuoBiao7 != objCompare.rg_HengZuoBiao7)  return FALSE;
    if (rg_ZongZuoBiao7 != objCompare.rg_ZongZuoBiao7)  return FALSE;
    if (rg_HengBanJing != objCompare.rg_HengBanJing)  return FALSE;
    if (rg_ZongBanJing != objCompare.rg_ZongBanJing)  return FALSE;
    if (rg_XuanZhuaiJiaoDu2 != objCompare.rg_XuanZhuaiJiaoDu2)  return FALSE;
    if (rg_YaLi1 != objCompare.rg_YaLi1)  return FALSE;
    if (rg_id4 != objCompare.rg_id4)  return FALSE;
    return TRUE;
}

void rg_FBrowser_VIPChuMoShiJian::_CopySelfFrom (const rg_FBrowser_VIPChuMoShiJian& objCopyFrom)
{
    rg_HengZuoBiao7 = objCopyFrom.rg_HengZuoBiao7;
    rg_ZongZuoBiao7 = objCopyFrom.rg_ZongZuoBiao7;
    rg_HengBanJing = objCopyFrom.rg_HengBanJing;
    rg_ZongBanJing = objCopyFrom.rg_ZongBanJing;
    rg_XuanZhuaiJiaoDu2 = objCopyFrom.rg_XuanZhuaiJiaoDu2;
    rg_YaLi1 = objCopyFrom.rg_YaLi1;
    rg_id4 = objCopyFrom.rg_id4;
}

void rg_FBrowser_VIPChuMoShiJian::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_HengZuoBiao7, sizeof (INT));
    stream.ReadExact (&rg_ZongZuoBiao7, sizeof (INT));
    stream.ReadExact (&rg_HengBanJing, sizeof (INT));
    stream.ReadExact (&rg_ZongBanJing, sizeof (INT));
    stream.ReadExact (&rg_XuanZhuaiJiaoDu2, sizeof (INT));
    stream.ReadExact (&rg_YaLi1, sizeof (INT));
    stream.ReadExact (&rg_id4, sizeof (INT));
}

void rg_FBrowser_VIPChuMoShiJian::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_HengZuoBiao7, sizeof (INT));
    stream.write (&rg_ZongZuoBiao7, sizeof (INT));
    stream.write (&rg_HengBanJing, sizeof (INT));
    stream.write (&rg_ZongBanJing, sizeof (INT));
    stream.write (&rg_XuanZhuaiJiaoDu2, sizeof (INT));
    stream.write (&rg_YaLi1, sizeof (INT));
    stream.write (&rg_id4, sizeof (INT));
}
E_DEV_TOUCHPOINT* rg_FBrowser_VIPChuMoShiJian::ToFBroData(){
     m_data.x=rg_HengZuoBiao7;
     m_data.y=rg_ZongZuoBiao7;
     m_data.radiusX=rg_HengBanJing;
     m_data.radiusY=rg_ZongBanJing;
     m_data.rotationAngle=rg_XuanZhuaiJiaoDu2;
     m_data.force=rg_YaLi1;
     m_data.id=rg_id4;
    return &m_data;
}
void rg_FBrowser_VIPChuMoShiJian::ToHsData(){
     rg_HengZuoBiao7=m_data.x;
     rg_ZongZuoBiao7=m_data.y;
     rg_HengBanJing=m_data.radiusX;
     rg_ZongBanJing=m_data.radiusY;
     rg_XuanZhuaiJiaoDu2=m_data.rotationAngle;
     rg_YaLi1=m_data.force;
     rg_id4=m_data.id;
}

rg_FBrowser_JinYongShiJian::rg_FBrowser_JinYongShiJian ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_JinYongShiJian::_VolObjectInitMembers ()
{
    rg_JinYongYinPinHuoQuShiJian = FALSE;
    rg_JinYongMingLingShiJian = FALSE;
    rg_JinYongCaiChanShiJian = FALSE;
    rg_JinYongDuiHuaKuangShiJian = FALSE;
    rg_JinYongXianShiShiJian = FALSE;
    rg_JinYongXiaZaiShiJian = FALSE;
    rg_JinYongChuMoShiJian = FALSE;
    rg_JinYongChaZhaoShiJian = FALSE;
    rg_JinYongJiaoDianShiJian = FALSE;
    rg_JinYongKuangJiaShiJian = FALSE;
    rg_JinYongMeiTiXuKeShiJian = FALSE;
    rg_JinYongJSDuiHuaKuangShiJian = FALSE;
    rg_JinYongJianPanShiJian = FALSE;
    rg_JinYongShengMingZhouJiShiJian = FALSE;
    rg_JinYongJiaZaiShiJian = FALSE;
    rg_JinYongDaYinShiJian = FALSE;
    rg_JinYongLiBingXuanRanShiJian = FALSE;
    rg_JinYongQingQiuShiJian = FALSE;
}

BOOL rg_FBrowser_JinYongShiJian::_IsSelfEqual (const rg_FBrowser_JinYongShiJian& objCompare) const
{
    if (rg_JinYongYinPinHuoQuShiJian != objCompare.rg_JinYongYinPinHuoQuShiJian)  return FALSE;
    if (rg_JinYongMingLingShiJian != objCompare.rg_JinYongMingLingShiJian)  return FALSE;
    if (rg_JinYongCaiChanShiJian != objCompare.rg_JinYongCaiChanShiJian)  return FALSE;
    if (rg_JinYongDuiHuaKuangShiJian != objCompare.rg_JinYongDuiHuaKuangShiJian)  return FALSE;
    if (rg_JinYongXianShiShiJian != objCompare.rg_JinYongXianShiShiJian)  return FALSE;
    if (rg_JinYongXiaZaiShiJian != objCompare.rg_JinYongXiaZaiShiJian)  return FALSE;
    if (rg_JinYongChuMoShiJian != objCompare.rg_JinYongChuMoShiJian)  return FALSE;
    if (rg_JinYongChaZhaoShiJian != objCompare.rg_JinYongChaZhaoShiJian)  return FALSE;
    if (rg_JinYongJiaoDianShiJian != objCompare.rg_JinYongJiaoDianShiJian)  return FALSE;
    if (rg_JinYongKuangJiaShiJian != objCompare.rg_JinYongKuangJiaShiJian)  return FALSE;
    if (rg_JinYongMeiTiXuKeShiJian != objCompare.rg_JinYongMeiTiXuKeShiJian)  return FALSE;
    if (rg_JinYongJSDuiHuaKuangShiJian != objCompare.rg_JinYongJSDuiHuaKuangShiJian)  return FALSE;
    if (rg_JinYongJianPanShiJian != objCompare.rg_JinYongJianPanShiJian)  return FALSE;
    if (rg_JinYongShengMingZhouJiShiJian != objCompare.rg_JinYongShengMingZhouJiShiJian)  return FALSE;
    if (rg_JinYongJiaZaiShiJian != objCompare.rg_JinYongJiaZaiShiJian)  return FALSE;
    if (rg_JinYongDaYinShiJian != objCompare.rg_JinYongDaYinShiJian)  return FALSE;
    if (rg_JinYongLiBingXuanRanShiJian != objCompare.rg_JinYongLiBingXuanRanShiJian)  return FALSE;
    if (rg_JinYongQingQiuShiJian != objCompare.rg_JinYongQingQiuShiJian)  return FALSE;
    return TRUE;
}

void rg_FBrowser_JinYongShiJian::_CopySelfFrom (const rg_FBrowser_JinYongShiJian& objCopyFrom)
{
    rg_JinYongYinPinHuoQuShiJian = objCopyFrom.rg_JinYongYinPinHuoQuShiJian;
    rg_JinYongMingLingShiJian = objCopyFrom.rg_JinYongMingLingShiJian;
    rg_JinYongCaiChanShiJian = objCopyFrom.rg_JinYongCaiChanShiJian;
    rg_JinYongDuiHuaKuangShiJian = objCopyFrom.rg_JinYongDuiHuaKuangShiJian;
    rg_JinYongXianShiShiJian = objCopyFrom.rg_JinYongXianShiShiJian;
    rg_JinYongXiaZaiShiJian = objCopyFrom.rg_JinYongXiaZaiShiJian;
    rg_JinYongChuMoShiJian = objCopyFrom.rg_JinYongChuMoShiJian;
    rg_JinYongChaZhaoShiJian = objCopyFrom.rg_JinYongChaZhaoShiJian;
    rg_JinYongJiaoDianShiJian = objCopyFrom.rg_JinYongJiaoDianShiJian;
    rg_JinYongKuangJiaShiJian = objCopyFrom.rg_JinYongKuangJiaShiJian;
    rg_JinYongMeiTiXuKeShiJian = objCopyFrom.rg_JinYongMeiTiXuKeShiJian;
    rg_JinYongJSDuiHuaKuangShiJian = objCopyFrom.rg_JinYongJSDuiHuaKuangShiJian;
    rg_JinYongJianPanShiJian = objCopyFrom.rg_JinYongJianPanShiJian;
    rg_JinYongShengMingZhouJiShiJian = objCopyFrom.rg_JinYongShengMingZhouJiShiJian;
    rg_JinYongJiaZaiShiJian = objCopyFrom.rg_JinYongJiaZaiShiJian;
    rg_JinYongDaYinShiJian = objCopyFrom.rg_JinYongDaYinShiJian;
    rg_JinYongLiBingXuanRanShiJian = objCopyFrom.rg_JinYongLiBingXuanRanShiJian;
    rg_JinYongQingQiuShiJian = objCopyFrom.rg_JinYongQingQiuShiJian;
}

void rg_FBrowser_JinYongShiJian::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_JinYongYinPinHuoQuShiJian, sizeof (BOOL));
    stream.ReadExact (&rg_JinYongMingLingShiJian, sizeof (BOOL));
    stream.ReadExact (&rg_JinYongCaiChanShiJian, sizeof (BOOL));
    stream.ReadExact (&rg_JinYongDuiHuaKuangShiJian, sizeof (BOOL));
    stream.ReadExact (&rg_JinYongXianShiShiJian, sizeof (BOOL));
    stream.ReadExact (&rg_JinYongXiaZaiShiJian, sizeof (BOOL));
    stream.ReadExact (&rg_JinYongChuMoShiJian, sizeof (BOOL));
    stream.ReadExact (&rg_JinYongChaZhaoShiJian, sizeof (BOOL));
    stream.ReadExact (&rg_JinYongJiaoDianShiJian, sizeof (BOOL));
    stream.ReadExact (&rg_JinYongKuangJiaShiJian, sizeof (BOOL));
    stream.ReadExact (&rg_JinYongMeiTiXuKeShiJian, sizeof (BOOL));
    stream.ReadExact (&rg_JinYongJSDuiHuaKuangShiJian, sizeof (BOOL));
    stream.ReadExact (&rg_JinYongJianPanShiJian, sizeof (BOOL));
    stream.ReadExact (&rg_JinYongShengMingZhouJiShiJian, sizeof (BOOL));
    stream.ReadExact (&rg_JinYongJiaZaiShiJian, sizeof (BOOL));
    stream.ReadExact (&rg_JinYongDaYinShiJian, sizeof (BOOL));
    stream.ReadExact (&rg_JinYongLiBingXuanRanShiJian, sizeof (BOOL));
    stream.ReadExact (&rg_JinYongQingQiuShiJian, sizeof (BOOL));
}

void rg_FBrowser_JinYongShiJian::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_JinYongYinPinHuoQuShiJian, sizeof (BOOL));
    stream.write (&rg_JinYongMingLingShiJian, sizeof (BOOL));
    stream.write (&rg_JinYongCaiChanShiJian, sizeof (BOOL));
    stream.write (&rg_JinYongDuiHuaKuangShiJian, sizeof (BOOL));
    stream.write (&rg_JinYongXianShiShiJian, sizeof (BOOL));
    stream.write (&rg_JinYongXiaZaiShiJian, sizeof (BOOL));
    stream.write (&rg_JinYongChuMoShiJian, sizeof (BOOL));
    stream.write (&rg_JinYongChaZhaoShiJian, sizeof (BOOL));
    stream.write (&rg_JinYongJiaoDianShiJian, sizeof (BOOL));
    stream.write (&rg_JinYongKuangJiaShiJian, sizeof (BOOL));
    stream.write (&rg_JinYongMeiTiXuKeShiJian, sizeof (BOOL));
    stream.write (&rg_JinYongJSDuiHuaKuangShiJian, sizeof (BOOL));
    stream.write (&rg_JinYongJianPanShiJian, sizeof (BOOL));
    stream.write (&rg_JinYongShengMingZhouJiShiJian, sizeof (BOOL));
    stream.write (&rg_JinYongJiaZaiShiJian, sizeof (BOOL));
    stream.write (&rg_JinYongDaYinShiJian, sizeof (BOOL));
    stream.write (&rg_JinYongLiBingXuanRanShiJian, sizeof (BOOL));
    stream.write (&rg_JinYongQingQiuShiJian, sizeof (BOOL));
}
Event_Disable_Control* rg_FBrowser_JinYongShiJian::ToFBroData(){
    m_data.disableGetAudioHandler = rg_JinYongYinPinHuoQuShiJian;
    m_data.disableGetCommandHandler = rg_JinYongMingLingShiJian;
    m_data.disableGetContextMenuHandler = rg_JinYongCaiChanShiJian;
    m_data.disableGetDialogHandler = rg_JinYongDuiHuaKuangShiJian;
    m_data.disableGetDisplayHandler = rg_JinYongXianShiShiJian;
    m_data.disableGetDownloadHandler = rg_JinYongXiaZaiShiJian;
    m_data.disableGetDragHandler = rg_JinYongChuMoShiJian;
    m_data.disableGetFindHandler = rg_JinYongChaZhaoShiJian;
    m_data.disableGetFocusHandler = rg_JinYongJiaoDianShiJian;
    m_data.disableGetFrameHandler = rg_JinYongKuangJiaShiJian;
    m_data.disableGetPermissionHandler = rg_JinYongMeiTiXuKeShiJian;
    m_data.disableGetJSDialogHandler = rg_JinYongJSDuiHuaKuangShiJian;
    m_data.disableGetKeyboardHandler = rg_JinYongJianPanShiJian;
    m_data.disableGetLifeSpanHandler = rg_JinYongShengMingZhouJiShiJian;
    m_data.disableGetLoadHandler = rg_JinYongJiaZaiShiJian;
    m_data.disableGetPrintHandler = rg_JinYongDaYinShiJian;
    m_data.disableGetRenderHandler = rg_JinYongLiBingXuanRanShiJian;
    m_data.disableGetRequestHandler = rg_JinYongQingQiuShiJian;
    return &m_data;
}
void rg_FBrowser_JinYongShiJian::ToHsData(){
    rg_JinYongYinPinHuoQuShiJian = m_data.disableGetAudioHandler;
    rg_JinYongMingLingShiJian = m_data.disableGetCommandHandler;
    rg_JinYongCaiChanShiJian = m_data.disableGetContextMenuHandler;
    rg_JinYongDuiHuaKuangShiJian = m_data.disableGetDialogHandler;
    rg_JinYongXianShiShiJian = m_data.disableGetDisplayHandler;
    rg_JinYongXiaZaiShiJian = m_data.disableGetDownloadHandler;
    rg_JinYongChuMoShiJian = m_data.disableGetDragHandler;
    rg_JinYongChaZhaoShiJian = m_data.disableGetFindHandler;
    rg_JinYongJiaoDianShiJian = m_data.disableGetFocusHandler;
    rg_JinYongKuangJiaShiJian = m_data.disableGetFrameHandler;
    rg_JinYongMeiTiXuKeShiJian = m_data.disableGetPermissionHandler;
    rg_JinYongJSDuiHuaKuangShiJian = m_data.disableGetJSDialogHandler;
    rg_JinYongJianPanShiJian = m_data.disableGetKeyboardHandler;
    rg_JinYongShengMingZhouJiShiJian = m_data.disableGetLifeSpanHandler;
    rg_JinYongJiaZaiShiJian = m_data.disableGetLoadHandler;
    rg_JinYongDaYinShiJian = m_data.disableGetPrintHandler;
    rg_JinYongLiBingXuanRanShiJian = m_data.disableGetRenderHandler;
    rg_JinYongQingQiuShiJian = m_data.disableGetRequestHandler;
}

rg_FBrowser_YinPinCanShu::rg_FBrowser_YinPinCanShu ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_YinPinCanShu::_VolObjectInitMembers ()
{
    rg_TongDaoBuJu = 0;
    rg_CaiYangPinLu = 0;
    rg_ZhengHuanChong = 0;
}

BOOL rg_FBrowser_YinPinCanShu::_IsSelfEqual (const rg_FBrowser_YinPinCanShu& objCompare) const
{
    if (rg_TongDaoBuJu != objCompare.rg_TongDaoBuJu)  return FALSE;
    if (rg_CaiYangPinLu != objCompare.rg_CaiYangPinLu)  return FALSE;
    if (rg_ZhengHuanChong != objCompare.rg_ZhengHuanChong)  return FALSE;
    return TRUE;
}

void rg_FBrowser_YinPinCanShu::_CopySelfFrom (const rg_FBrowser_YinPinCanShu& objCopyFrom)
{
    rg_TongDaoBuJu = objCopyFrom.rg_TongDaoBuJu;
    rg_CaiYangPinLu = objCopyFrom.rg_CaiYangPinLu;
    rg_ZhengHuanChong = objCopyFrom.rg_ZhengHuanChong;
}

void rg_FBrowser_YinPinCanShu::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_TongDaoBuJu, sizeof (INT));
    stream.ReadExact (&rg_CaiYangPinLu, sizeof (INT));
    stream.ReadExact (&rg_ZhengHuanChong, sizeof (INT));
}

void rg_FBrowser_YinPinCanShu::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_TongDaoBuJu, sizeof (INT));
    stream.write (&rg_CaiYangPinLu, sizeof (INT));
    stream.write (&rg_ZhengHuanChong, sizeof (INT));
}
void rg_FBrowser_YinPinCanShu::ToFBroData(E_AudioParameters* data){
     m_data.channel_layout=data->channel_layout;
     m_data.sample_rate=data->sample_rate;
     m_data.frames_per_buffer=data->frames_per_buffer;
}
E_AudioParameters* rg_FBrowser_YinPinCanShu::ToFBroData(){
     m_data.channel_layout=rg_TongDaoBuJu;
     m_data.sample_rate=rg_CaiYangPinLu;
     m_data.frames_per_buffer=rg_ZhengHuanChong;
    return &m_data;
}
void rg_FBrowser_YinPinCanShu::ToHsData(){
     rg_TongDaoBuJu=m_data.channel_layout;
     rg_CaiYangPinLu=m_data.sample_rate;
     rg_ZhengHuanChong=m_data.frames_per_buffer;
}

INT rg_FBrowser_MeiTiYingJianShuZu::rg_JiaRuShuJu (CVolString& rg_QuDongID, CVolString& rg_YingJianMing, CVolString& rg_FenZuID)
{
    return AddItem(rg_QuDongID.GetText(),rg_YingJianMing.GetText(),rg_FenZuID.GetText());
}

rg_FBrowser_PDFDaYinSheZhi::rg_FBrowser_PDFDaYinSheZhi ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_PDFDaYinSheZhi::_VolObjectInitMembers ()
{
    rg_HengXiangMoShi = FALSE;
    rg_DaYinBeiJing = FALSE;
    rg_SuFangBiLi = 0;
    rg_YeMianKuanDu = 0;
    rg_YeMianGaoDu = 0;
    rg_ShouXuanCSSYeMianDaXiao = FALSE;
    rg_BianKuangLeiXing = 0;
    rg_BianKuangDingDian = 0;
    rg_BianKuangYouBian = 0;
    rg_BianKuangDeBu = 0;
    rg_BianKuangZuoBian = 0;
    rg_XianShiYeMeiYeJiao = FALSE;
    rg_ShengChengDaiBiaoQianDePDF = FALSE;
    rg_ShengChengWenDangDaGang = FALSE;
}

BOOL rg_FBrowser_PDFDaYinSheZhi::_IsSelfEqual (const rg_FBrowser_PDFDaYinSheZhi& objCompare) const
{
    if (rg_HengXiangMoShi != objCompare.rg_HengXiangMoShi)  return FALSE;
    if (rg_DaYinBeiJing != objCompare.rg_DaYinBeiJing)  return FALSE;
    if (IsDoubleEqual (rg_SuFangBiLi, objCompare.rg_SuFangBiLi) == FALSE)  return FALSE;
    if (IsDoubleEqual (rg_YeMianKuanDu, objCompare.rg_YeMianKuanDu) == FALSE)  return FALSE;
    if (IsDoubleEqual (rg_YeMianGaoDu, objCompare.rg_YeMianGaoDu) == FALSE)  return FALSE;
    if (rg_ShouXuanCSSYeMianDaXiao != objCompare.rg_ShouXuanCSSYeMianDaXiao)  return FALSE;
    if (rg_BianKuangLeiXing != objCompare.rg_BianKuangLeiXing)  return FALSE;
    if (IsDoubleEqual (rg_BianKuangDingDian, objCompare.rg_BianKuangDingDian) == FALSE)  return FALSE;
    if (IsDoubleEqual (rg_BianKuangYouBian, objCompare.rg_BianKuangYouBian) == FALSE)  return FALSE;
    if (IsDoubleEqual (rg_BianKuangDeBu, objCompare.rg_BianKuangDeBu) == FALSE)  return FALSE;
    if (IsDoubleEqual (rg_BianKuangZuoBian, objCompare.rg_BianKuangZuoBian) == FALSE)  return FALSE;
    if (rg_YeMianFanWei != objCompare.rg_YeMianFanWei)  return FALSE;
    if (rg_XianShiYeMeiYeJiao != objCompare.rg_XianShiYeMeiYeJiao)  return FALSE;
    if (rg_TouMoBan != objCompare.rg_TouMoBan)  return FALSE;
    if (rg_YeJiaoMoBan != objCompare.rg_YeJiaoMoBan)  return FALSE;
    if (rg_ShengChengDaiBiaoQianDePDF != objCompare.rg_ShengChengDaiBiaoQianDePDF)  return FALSE;
    if (rg_ShengChengWenDangDaGang != objCompare.rg_ShengChengWenDangDaGang)  return FALSE;
    return TRUE;
}

void rg_FBrowser_PDFDaYinSheZhi::_CopySelfFrom (const rg_FBrowser_PDFDaYinSheZhi& objCopyFrom)
{
    rg_HengXiangMoShi = objCopyFrom.rg_HengXiangMoShi;
    rg_DaYinBeiJing = objCopyFrom.rg_DaYinBeiJing;
    rg_SuFangBiLi = objCopyFrom.rg_SuFangBiLi;
    rg_YeMianKuanDu = objCopyFrom.rg_YeMianKuanDu;
    rg_YeMianGaoDu = objCopyFrom.rg_YeMianGaoDu;
    rg_ShouXuanCSSYeMianDaXiao = objCopyFrom.rg_ShouXuanCSSYeMianDaXiao;
    rg_BianKuangLeiXing = objCopyFrom.rg_BianKuangLeiXing;
    rg_BianKuangDingDian = objCopyFrom.rg_BianKuangDingDian;
    rg_BianKuangYouBian = objCopyFrom.rg_BianKuangYouBian;
    rg_BianKuangDeBu = objCopyFrom.rg_BianKuangDeBu;
    rg_BianKuangZuoBian = objCopyFrom.rg_BianKuangZuoBian;
    rg_YeMianFanWei = objCopyFrom.rg_YeMianFanWei;
    rg_XianShiYeMeiYeJiao = objCopyFrom.rg_XianShiYeMeiYeJiao;
    rg_TouMoBan = objCopyFrom.rg_TouMoBan;
    rg_YeJiaoMoBan = objCopyFrom.rg_YeJiaoMoBan;
    rg_ShengChengDaiBiaoQianDePDF = objCopyFrom.rg_ShengChengDaiBiaoQianDePDF;
    rg_ShengChengWenDangDaGang = objCopyFrom.rg_ShengChengWenDangDaGang;
}

void rg_FBrowser_PDFDaYinSheZhi::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_HengXiangMoShi, sizeof (BOOL));
    stream.ReadExact (&rg_DaYinBeiJing, sizeof (BOOL));
    stream.ReadExact (&rg_SuFangBiLi, sizeof (DOUBLE));
    stream.ReadExact (&rg_YeMianKuanDu, sizeof (DOUBLE));
    stream.ReadExact (&rg_YeMianGaoDu, sizeof (DOUBLE));
    stream.ReadExact (&rg_ShouXuanCSSYeMianDaXiao, sizeof (BOOL));
    stream.ReadExact (&rg_BianKuangLeiXing, sizeof (INT));
    stream.ReadExact (&rg_BianKuangDingDian, sizeof (DOUBLE));
    stream.ReadExact (&rg_BianKuangYouBian, sizeof (DOUBLE));
    stream.ReadExact (&rg_BianKuangDeBu, sizeof (DOUBLE));
    stream.ReadExact (&rg_BianKuangZuoBian, sizeof (DOUBLE));
    rg_YeMianFanWei.LoadFromStream (stream);
    stream.ReadExact (&rg_XianShiYeMeiYeJiao, sizeof (BOOL));
    rg_TouMoBan.LoadFromStream (stream);
    rg_YeJiaoMoBan.LoadFromStream (stream);
    stream.ReadExact (&rg_ShengChengDaiBiaoQianDePDF, sizeof (BOOL));
    stream.ReadExact (&rg_ShengChengWenDangDaGang, sizeof (BOOL));
}

void rg_FBrowser_PDFDaYinSheZhi::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_HengXiangMoShi, sizeof (BOOL));
    stream.write (&rg_DaYinBeiJing, sizeof (BOOL));
    stream.write (&rg_SuFangBiLi, sizeof (DOUBLE));
    stream.write (&rg_YeMianKuanDu, sizeof (DOUBLE));
    stream.write (&rg_YeMianGaoDu, sizeof (DOUBLE));
    stream.write (&rg_ShouXuanCSSYeMianDaXiao, sizeof (BOOL));
    stream.write (&rg_BianKuangLeiXing, sizeof (INT));
    stream.write (&rg_BianKuangDingDian, sizeof (DOUBLE));
    stream.write (&rg_BianKuangYouBian, sizeof (DOUBLE));
    stream.write (&rg_BianKuangDeBu, sizeof (DOUBLE));
    stream.write (&rg_BianKuangZuoBian, sizeof (DOUBLE));
    rg_YeMianFanWei.SaveIntoStream (stream);
    stream.write (&rg_XianShiYeMeiYeJiao, sizeof (BOOL));
    rg_TouMoBan.SaveIntoStream (stream);
    rg_YeJiaoMoBan.SaveIntoStream (stream);
    stream.write (&rg_ShengChengDaiBiaoQianDePDF, sizeof (BOOL));
    stream.write (&rg_ShengChengWenDangDaGang, sizeof (BOOL));
}
FBroPdfPrintSettings* rg_FBrowser_PDFDaYinSheZhi::ToFBroData(){
    m_data.landscape;
    m_data.print_background;
    m_data.scale;
    m_data.paper_width;
    m_data.paper_height;
    m_data.prefer_css_page_size;
    m_data.margin_type;
    m_data.margin_top;
    m_data.margin_right;
    m_data.margin_bottom;
    m_data.margin_left;
    m_data.page_ranges=FBroUnit::UnicodeToAnsi(rg_YeMianFanWei.GetText());
    m_data. display_header_footer;
    m_data.header_template=FBroUnit::UnicodeToAnsi(rg_TouMoBan.GetText());
    m_data.footer_template=FBroUnit::UnicodeToAnsi(rg_YeJiaoMoBan.GetText());
    m_data.generate_tagged_pdf;
    m_data.generate_document_outline;
    return &m_data;
}
void rg_FBrowser_PDFDaYinSheZhi::ToHsData(){
    rg_HengXiangMoShi = m_data.landscape;
    rg_DaYinBeiJing = m_data.print_background;
    rg_SuFangBiLi = m_data.scale;
    rg_YeMianKuanDu = m_data.paper_width;
    rg_YeMianGaoDu = m_data.paper_height;
    rg_ShouXuanCSSYeMianDaXiao = m_data.prefer_css_page_size;
    rg_BianKuangLeiXing = m_data.margin_type;
    rg_BianKuangDingDian = m_data.margin_top;
    rg_BianKuangYouBian = m_data.margin_right;
    rg_BianKuangDeBu = m_data.margin_bottom;
    rg_BianKuangZuoBian = m_data.margin_left;
    rg_YeMianFanWei = FBroUnit::ToCWString(m_data.page_ranges);
    rg_XianShiYeMeiYeJiao = m_data.display_header_footer;
    rg_TouMoBan = FBroUnit::ToCWString(m_data.header_template);
    rg_YeJiaoMoBan = FBroUnit::ToCWString(m_data.footer_template);
    rg_ShengChengDaiBiaoQianDePDF = m_data.generate_tagged_pdf;
    rg_ShengChengWenDangDaGang = m_data.generate_document_outline;
}
void rg_FBrowser_PDFDaYinSheZhi::release(){
  FBroUnit::FreeCharArray(m_data.page_ranges);
  FBroUnit::FreeCharArray(m_data.header_template);
  FBroUnit::FreeCharArray(m_data.footer_template);
}

rg_FBrowser_JiaSuHuiZhiEWaiXinXi::rg_FBrowser_JiaSuHuiZhiEWaiXinXi ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_JiaSuHuiZhiEWaiXinXi::_VolObjectInitMembers ()
{
    rg_timestamp = 0;
    rg_capture_counter = 0;
    rg_has_capture_update_rect = 0;
    rg_has_region_capture_rect = 0;
    rg_has_source_size = 0;
    rg_has_capture_counter = 0;
}

BOOL rg_FBrowser_JiaSuHuiZhiEWaiXinXi::_IsSelfEqual (const rg_FBrowser_JiaSuHuiZhiEWaiXinXi& objCompare) const
{
    if (rg_timestamp != objCompare.rg_timestamp)  return FALSE;
    if (rg_coded_size != objCompare.rg_coded_size)  return FALSE;
    if (rg_visible_rect != objCompare.rg_visible_rect)  return FALSE;
    if (rg_content_rect != objCompare.rg_content_rect)  return FALSE;
    if (rg_source_size != objCompare.rg_source_size)  return FALSE;
    if (rg_capture_update_rect != objCompare.rg_capture_update_rect)  return FALSE;
    if (rg_region_capture_rect != objCompare.rg_region_capture_rect)  return FALSE;
    if (rg_capture_counter != objCompare.rg_capture_counter)  return FALSE;
    if (rg_has_capture_update_rect != objCompare.rg_has_capture_update_rect)  return FALSE;
    if (rg_has_region_capture_rect != objCompare.rg_has_region_capture_rect)  return FALSE;
    if (rg_has_source_size != objCompare.rg_has_source_size)  return FALSE;
    if (rg_has_capture_counter != objCompare.rg_has_capture_counter)  return FALSE;
    return TRUE;
}

void rg_FBrowser_JiaSuHuiZhiEWaiXinXi::_CopySelfFrom (const rg_FBrowser_JiaSuHuiZhiEWaiXinXi& objCopyFrom)
{
    rg_timestamp = objCopyFrom.rg_timestamp;
    rg_coded_size = objCopyFrom.rg_coded_size;
    rg_visible_rect = objCopyFrom.rg_visible_rect;
    rg_content_rect = objCopyFrom.rg_content_rect;
    rg_source_size = objCopyFrom.rg_source_size;
    rg_capture_update_rect = objCopyFrom.rg_capture_update_rect;
    rg_region_capture_rect = objCopyFrom.rg_region_capture_rect;
    rg_capture_counter = objCopyFrom.rg_capture_counter;
    rg_has_capture_update_rect = objCopyFrom.rg_has_capture_update_rect;
    rg_has_region_capture_rect = objCopyFrom.rg_has_region_capture_rect;
    rg_has_source_size = objCopyFrom.rg_has_source_size;
    rg_has_capture_counter = objCopyFrom.rg_has_capture_counter;
}

void rg_FBrowser_JiaSuHuiZhiEWaiXinXi::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_timestamp, sizeof (INT64));
    rg_coded_size.LoadFromStream (stream);
    rg_visible_rect.LoadFromStream (stream);
    rg_content_rect.LoadFromStream (stream);
    rg_source_size.LoadFromStream (stream);
    rg_capture_update_rect.LoadFromStream (stream);
    rg_region_capture_rect.LoadFromStream (stream);
    stream.ReadExact (&rg_capture_counter, sizeof (INT64));
    stream.ReadExact (&rg_has_capture_update_rect, sizeof (INT));
    stream.ReadExact (&rg_has_region_capture_rect, sizeof (INT));
    stream.ReadExact (&rg_has_source_size, sizeof (INT));
    stream.ReadExact (&rg_has_capture_counter, sizeof (INT));
}

void rg_FBrowser_JiaSuHuiZhiEWaiXinXi::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_timestamp, sizeof (INT64));
    rg_coded_size.SaveIntoStream (stream);
    rg_visible_rect.SaveIntoStream (stream);
    rg_content_rect.SaveIntoStream (stream);
    rg_source_size.SaveIntoStream (stream);
    rg_capture_update_rect.SaveIntoStream (stream);
    rg_region_capture_rect.SaveIntoStream (stream);
    stream.write (&rg_capture_counter, sizeof (INT64));
    stream.write (&rg_has_capture_update_rect, sizeof (INT));
    stream.write (&rg_has_region_capture_rect, sizeof (INT));
    stream.write (&rg_has_source_size, sizeof (INT));
    stream.write (&rg_has_capture_counter, sizeof (INT));
}
void rg_FBrowser_JiaSuHuiZhiEWaiXinXi::ToHsData(){
     rg_timestamp = m_data.timestamp;
     rg_coded_size = rg_FBrowser_CheCun(m_data.coded_size);
     rg_visible_rect = rg_FBrowser_JuXingWeiZhi(m_data.visible_rect);
     rg_content_rect = rg_FBrowser_JuXingWeiZhi(m_data.content_rect);
     rg_source_size = rg_FBrowser_CheCun(m_data.source_size);
     rg_capture_update_rect = rg_FBrowser_JuXingWeiZhi(m_data.capture_update_rect);
     rg_region_capture_rect = rg_FBrowser_JuXingWeiZhi(m_data.region_capture_rect);
     rg_capture_counter = m_data.capture_counter;
     rg_has_capture_update_rect = m_data.has_capture_update_rect;
     rg_has_region_capture_rect = m_data.has_region_capture_rect;
     rg_has_source_size = m_data.has_source_size;
     rg_has_capture_counter = m_data.has_capture_counter;
}

rg_FBrowser_JiaSuHuiZhiXinXi::rg_FBrowser_JiaSuHuiZhiXinXi ()
{
    _VolObjectInitMembers ();
}

void rg_FBrowser_JiaSuHuiZhiXinXi::_VolObjectInitMembers ()
{
    rg_GongXiangWenLiGouBing = 0;
    rg_YanSeLeiXing1 = 0;
}

BOOL rg_FBrowser_JiaSuHuiZhiXinXi::_IsSelfEqual (const rg_FBrowser_JiaSuHuiZhiXinXi& objCompare) const
{
    if (rg_GongXiangWenLiGouBing != objCompare.rg_GongXiangWenLiGouBing)  return FALSE;
    if (rg_YanSeLeiXing1 != objCompare.rg_YanSeLeiXing1)  return FALSE;
    if (rg_EWaiXinXi2 != objCompare.rg_EWaiXinXi2)  return FALSE;
    return TRUE;
}

void rg_FBrowser_JiaSuHuiZhiXinXi::_CopySelfFrom (const rg_FBrowser_JiaSuHuiZhiXinXi& objCopyFrom)
{
    rg_GongXiangWenLiGouBing = objCopyFrom.rg_GongXiangWenLiGouBing;
    rg_YanSeLeiXing1 = objCopyFrom.rg_YanSeLeiXing1;
    rg_EWaiXinXi2 = objCopyFrom.rg_EWaiXinXi2;
}

void rg_FBrowser_JiaSuHuiZhiXinXi::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    stream.ReadExact (&rg_GongXiangWenLiGouBing, sizeof (INT));
    stream.ReadExact (&rg_YanSeLeiXing1, sizeof (INT));
    rg_EWaiXinXi2.LoadFromStream (stream);
}

void rg_FBrowser_JiaSuHuiZhiXinXi::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    stream.write (&rg_GongXiangWenLiGouBing, sizeof (INT));
    stream.write (&rg_YanSeLeiXing1, sizeof (INT));
    rg_EWaiXinXi2.SaveIntoStream (stream);
}
void rg_FBrowser_JiaSuHuiZhiXinXi::ToHsData(){
     rg_GongXiangWenLiGouBing = INT(m_data.shared_texture_handle);
     rg_YanSeLeiXing1 = m_data.format;
     rg_EWaiXinXi2 = rg_FBrowser_JiaSuHuiZhiEWaiXinXi(m_data.extra);
}

}
