import json, sys, time, urllib.request
import os as _os, sys as _sys
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
import _console  # noqa: F401  控制台 UTF-8 兜底(见 _console.py)
sys.path.insert(0,'.')
spec=__import__("importlib.util",fromlist=["x"]).spec_from_file_location("v4","verify_round4.py")
v4=__import__("importlib.util",fromlist=["x"]).module_from_spec(spec); spec.loader.exec_module(v4)
v4.call("browser_navigate", {"url":"https://example.com/?s=%d"%int(time.time()),"wait_for_load":True}, 45)
time.sleep(0.5)
v4.call("browser_execute_js", {"code":"document.body.insertAdjacentHTML('beforeend','<input id=\"snapin\" value=\"SNAPVAL\"><p id=\"snapp\">SNAPTEXT</p>');'ok'"}, 30)
time.sleep(0.3)
e,t,_ = v4.call("browser_snapshot", {}, 40)
print("=== browser_snapshot err=%s (长度 %d) ===" % (e, len(t)))
print(t[:1400])
print()
e2,t2,_ = v4.call("browser_get_forms", {}, 40)
print("=== browser_get_forms err=%s (长度 %d) ===" % (e2, len(t2)))
print(t2[:600])
