import json,re,urllib.request,io,sys
import os as _os, sys as _sys
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
import _console  # noqa: F401  控制台 UTF-8 兜底(见 _console.py)
src=open("src/MCP_Server.wsv",encoding="utf-8",errors="replace").read()
reg=set()
for m in re.finditer(r'注册命令双变体 \("([a-z0-9_]+)"',src): reg.add("browser_"+m.group(1))
for m in re.finditer(r'置整数值 \("(browser_[a-z0-9_]+)"',src): reg.add(m.group(1))
tools=set(re.findall(r'添加工具JSON \("([a-z0-9_]+)"',src))
r=urllib.request.Request("http://127.0.0.1:9222/mcp",data=json.dumps({"jsonrpc":"2.0","id":1,"method":"tools/list"}).encode(),headers={"Content-Type":"application/json"})
live=set(t["name"] for t in json.loads(urllib.request.urlopen(r,timeout=20).read().decode())["result"]["tools"])
print("源码注册表=%d  源码添加工具JSON=%d  服务实际=%d"%(len(reg),len(tools),len(live)))
print("A) 注册表有 / 无工具定义(=幽灵注册):",len(reg-tools))
gh=sorted(reg-tools)
for i in range(0,len(gh),6): print("   ",' '.join(x.replace("browser_","") for x in gh[i:i+6]))
print("B) 有工具定义 / 注册表无:",len(tools-reg))
print("C) 服务实际 vs 源码定义 差异:",len(live^tools))
print("   仅在服务:",sorted(live-tools)[:10]); print("   仅在源码:",sorted(tools-live)[:10])
