# -*- coding: utf-8 -*-
import importlib.util,sys,time
import os as _os, sys as _sys
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
import _console  # noqa: F401  控制台 UTF-8 兜底(见 _console.py)
sys.path.insert(0,'.')
spec=importlib.util.spec_from_file_location("pw","probe_writes.py")
pw=importlib.util.module_from_spec(spec); spec.loader.exec_module(pw)
pw.call("browser_navigate",{"url":"https://example.com/?v=%d"%int(time.time()),"wait_for_load":True},60); time.sleep(1.0)
print("页面就绪 h1 =", pw.oracle("document.querySelector('h1').textContent"))
print()
print("--- 断言A: browser_dom_get_html {selector:h1} 是主路径无CDP, 返回真HTML还是 'null'? ---")
e,t = pw.resolve("browser_dom_get_html",{"selector":"h1"})
print("   err=%s resp=%s" % (e, t[:260]))
print()
print("--- 断言B: browser_fill_attr_get 省略 attribute (attr=='' 时 CDP 被跳过) ---")
e,t = pw.resolve("browser_fill_attr_get",{"selector":"h1"})
print("   err=%s resp=%s" % (e, t[:260]))
print()
print("--- 断言C: browser_fill_attr_get 带 attribute (上轮已修, 回归) ---")
e,t = pw.resolve("browser_fill_attr_get",{"selector":"a","attribute":"href"})
print("   err=%s resp=%s" % (e, t[:200]))
print()
print("--- 断言D: browser_fill_exists 不存在元素 (应为 false) ---")
e,t = pw.resolve("browser_fill_exists",{"selector":"#nonexistent-xyz"})
print("   err=%s resp=%s" % (e, t[:220]))
print()
print("--- 断言E: browser_fill_exists 存在元素 (应为 true) ---")
e,t = pw.resolve("browser_fill_exists",{"selector":"h1"})
print("   err=%s resp=%s" % (e, t[:220]))
