
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_LIULANQI_FBROV8EXCEPTION_H__
#define __VCLS_RG_FBROWSER_LIULANQI_FBROV8EXCEPTION_H__

namespace rg_FBrowser_LiuLanQi
{

class FBroV8Exception : public CVolObject
{
    DECLARE_VOL_CLASS (rg_FBrowser_LiuLanQi, FBroV8Exception)

public:
    CefRefPtr<CefV8Exception> m_class;
    inline_ FBroV8Exception (CefRefPtr<CefV8Exception> object) : FBroV8Exception () { m_class = object; }
    inline_ void _CopySelfFromExtra (const FBroV8Exception& objCopyFrom) { m_class = objCopyFrom.m_class; }
    inline_ BOOL _IsSelfEqualExtra (const FBroV8Exception& objCompare) const { return (m_class.get () == objCompare.m_class.get ()); }
    inline_ BOOL IsEmpty () const { return m_class.get () == nullptr; }
    inline_ void Set (CefRefPtr<CefV8Exception> object) { m_class = object; }
    ~FBroV8Exception(){};

public:
    BOOL rg_ShiFouWeiKong144 ();
    CVolString rg_QuXiaoXi ();
    inline_ FBroV8Exception () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_FBROWSER_LIULANQI_FBROV8EXCEPTION_H__
