
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_APP_MCPCOOKIECOLLECTCALLBACK_H__
#define __VCLS_RG_VOLCANO_APP_MCPCOOKIECOLLECTCALLBACK_H__

namespace rg_volcano_app
{

class MCPCookieCollectCallback : public rg_FBrowser_HuiDiao::rg_class_FBrowser_Cookiehd
{
    DECLARE_VOL_CLASS (rg_volcano_app, MCPCookieCollectCallback)

public:
    virtual void rg_KaiShi ();
    virtual BOOL rg_FangWen (rg_FBrowser_ShuJuLeiXing::rg_FBrowser_CookieShuJu& CookieData, INT CurrentItem, INT Total, rg_volcano_base::rg_LuoJiXingLei& DeleteCurrentCookie);
    virtual void rg_JieShu ();
    MCPCookieCollectCallback ();
    void _VolObjectInitMembers ();
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

public:
    INT MaxItemCount;
    CVolString AsyncTaskID;

protected:
    CVolString CookieListJSON;
    BOOL FirstItem;
    INT CurrentTotal;
};

}

#endif  //__VCLS_RG_VOLCANO_APP_MCPCOOKIECOLLECTCALLBACK_H__
