
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_HUIDIAO_RG_CLASS_FBROWSER_MTJRHD_H__
#define __VCLS_RG_FBROWSER_HUIDIAO_RG_CLASS_FBROWSER_MTJRHD_H__

namespace rg_FBrowser_HuiDiao
{

class rg_class_FBrowser_mtjrhd : public CVolObject
{
    DECLARE_VOL_CLASS (rg_FBrowser_HuiDiao, rg_class_FBrowser_mtjrhd)

public:
    CefRefPtr<CefMediaAccessCallback> m_class;
    inline_ rg_class_FBrowser_mtjrhd (CefRefPtr<CefMediaAccessCallback> object) : rg_class_FBrowser_mtjrhd () { m_class = object; }
    inline_ void _CopySelfFromExtra (const rg_class_FBrowser_mtjrhd& objCopyFrom) { m_class = objCopyFrom.m_class; }
    inline_ BOOL _IsSelfEqualExtra (const rg_class_FBrowser_mtjrhd& objCompare) const { return (m_class == objCompare.m_class); }
    inline_ BOOL_P IsEmpty () const { return m_class == nullptr; }
    inline_ void Set (CefRefPtr<CefMediaAccessCallback> object) { m_class = object; }
    ~rg_class_FBrowser_mtjrhd(){};

public:
    inline_ rg_class_FBrowser_mtjrhd () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_FBROWSER_HUIDIAO_RG_CLASS_FBROWSER_MTJRHD_H__
