
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_SHIJIANKONGZHI_RG_CLASS_FBROWSER_FWQSHJ_H__
#define __VCLS_RG_FBROWSER_SHIJIANKONGZHI_RG_CLASS_FBROWSER_FWQSHJ_H__

namespace rg_FBrowser_ShiJianKongZhi
{

class rg_class_FBrowser_fwqshj : public CVolObject, public FBroHsServerHandle
{
    DECLARE_EMPTY_VOL_CLASS (rg_FBrowser_ShiJianKongZhi, rg_class_FBrowser_fwqshj)

public:
        _FBRO_NEW_DELETE_OVERRIDE();
    public:
        virtual void OnServerCreated(CefRefPtr<CefServer> server) override;
        virtual void OnServerDestroyed(CefRefPtr<CefServer> server) override;
        virtual void OnClientConnected(CefRefPtr<CefServer> server,int connection_id) override;
        virtual void OnClientDisconnected(CefRefPtr<CefServer> server,int connection_id) override;
        virtual void OnHttpRequest(CefRefPtr<CefServer> server,int connection_id,const CefString& client_address, CefRefPtr<CefRequest> request) override;
        virtual void OnWebSocketRequest(CefRefPtr<CefServer> server,int connection_id,const CefString& client_address,CefRefPtr<CefRequest> request,CefRefPtr<CefCallback> callback) override;
        virtual void OnWebSocketConnected(CefRefPtr<CefServer> server,int connection_id) override;
        virtual void OnWebSocketMessage(CefRefPtr<CefServer> server,int connection_id,const void* data,size_t data_size) override;

public:
    virtual void rg_FuWuQiJiJiangChuangJian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_FuWuQi& rg_FuWuQi2);
    virtual void rg_FuWuQiJiJiangXiaoHui (rg_FBrowser_LiuLanQi::rg_class_FBrowser_FuWuQi& rg_FuWuQi3);
    virtual void rg_ShouDaoKeHuDuanLianJie (rg_FBrowser_LiuLanQi::rg_class_FBrowser_FuWuQi& rg_FuWuQi4, INT rg_LianJieID);
    virtual void rg_ShouDaoKeHuDuanDuanKaiLianJie (rg_FBrowser_LiuLanQi::rg_class_FBrowser_FuWuQi& rg_FuWuQi5, INT rg_LianJieID1);
    virtual void rg_ShouDaoHTTPQingQiu (rg_FBrowser_LiuLanQi::rg_class_FBrowser_FuWuQi& rg_FuWuQi6, INT rg_LianJieID2, CVolString& rg_KeHuDuanDeZhi, rg_FBrowser_LiuLanQi::FBroRequest& rg_QingQiu12);
    virtual void rg_ShouDaoWebSocketQingQiu (rg_FBrowser_LiuLanQi::rg_class_FBrowser_FuWuQi& rg_FuWuQi7, INT rg_LianJieID3, CVolString& rg_KeHuDuanDeZhi1, rg_FBrowser_LiuLanQi::FBroRequest& rg_QingQiu13, rg_FBrowser_HuiDiao::rg_class_FBrowser_HuiDiao& rg_HuiDiao10);
    virtual void rg_ShouDaoWebSocketLianJie (rg_FBrowser_LiuLanQi::rg_class_FBrowser_FuWuQi& rg_FuWuQi8, INT rg_LianJieID4);
    virtual void rg_ShouDaoWebSocketXiaoXi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_FuWuQi& rg_FuWuQi9, INT rg_LianJieID5, INT rg_ShuJuZhiZhen10, INT rg_ShuJuChangDu);
    rg_class_FBrowser_fwqshj ();
    void _VolObjectInitMembers ();
    virtual ~rg_class_FBrowser_fwqshj ();

protected:
    void rg_class_FBrowser_fwqshj_class_chshh ();
    void rg_class_FBrowser_fwqshj_class_ql ();
};

}

#endif  //__VCLS_RG_FBROWSER_SHIJIANKONGZHI_RG_CLASS_FBROWSER_FWQSHJ_H__
