
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_APP_MCPSCHEMERESOURCEHANDLER_H__
#define __VCLS_RG_VOLCANO_APP_MCPSCHEMERESOURCEHANDLER_H__

namespace rg_volcano_app
{

class MCPSchemeResourceHandler : public rg_FBrowser_ShiJianKongZhi::rg_class_FBrowser_zychlq
{
    DECLARE_VOL_CLASS (rg_volcano_app, MCPSchemeResourceHandler)

public:
    virtual BOOL rg_DaKai (INT64 KeyID, rg_FBrowser_LiuLanQi::FBroRequest& Request, rg_volcano_base::rg_LuoJiXingLei& HandleRequest, rg_FBrowser_HuiDiao::rg_class_FBrowser_HuiDiao& Callback);
    virtual BOOL rg_ChuLiQingQiu (INT64 KeyID, rg_FBrowser_LiuLanQi::FBroRequest& Request, rg_FBrowser_HuiDiao::rg_class_FBrowser_HuiDiao& Callback);
    virtual void rg_QuXiangYingTou (INT64 KeyID, rg_FBrowser_LiuLanQi::rg_class_FBrowser_XiangYing& Response, rg_volcano_base::rg_ChangZhengShuLei& ResponseLength, rg_FBrowser_ShuJuLeiXing::rg_FBrowser_string& RedirectUrl);
    virtual BOOL rg_HuLue (INT64 KeyID, INT64 CanIgnoreSize, rg_volcano_base::rg_ChangZhengShuLei& IgnoredSize, rg_FBrowser_HuiDiao::rg_class_FBrowser_zyhlhd& ResourceIgnoreCallback);
    virtual BOOL rg_DouQu (INT64 KeyID, INT OutputDataPtr, INT ReadSize, rg_volcano_base::rg_ZhengShuLei& ReadInSize, rg_FBrowser_HuiDiao::rg_class_FBrowser_zydqhd& ResourceReadCallback);
    virtual void rg_TuiChu (INT64 KeyID);
    inline_ MCPSchemeResourceHandler () { }
    inline_ void _VolObjectInitMembers () { }
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

protected:
    CVolMem ResponseBytes;
    CVolString CurrentMIME;
};

}

#endif  //__VCLS_RG_VOLCANO_APP_MCPSCHEMERESOURCEHANDLER_H__
