
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_WENJIANCHAZHAOLEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_WENJIANCHAZHAOLEI_H__

namespace rg_volcano_base
{

class rg_WenJianChaZhaoLei : public CVolRefObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_base, rg_WenJianChaZhaoLei)

public:
    rg_WenJianChaZhaoGouBingLei& GetData ();
    void SetData (const rg_WenJianChaZhaoGouBingLei& data);

public:
    INT rg_ZhaoDaoWenJian (INT rg_YuXinZhaoWenJianDeShuXing, CVolString& rg_DangQianWenJianMingChen, INT rg_DangQianWenJianShuXing);
    CVolString rg_XinZhaoWenJian (CVolString& rg_YuXinZhaoWenJian, INT rg_YuXinZhaoWenJianDeShuXing1, INT rg_YuTiaoGuoWenJianDeShuXing);
    rg_WenJianChaZhaoLei ();
    void _VolObjectInitMembers ();

public:
    void ra_WenJianChaZhaoLei_ZhaoDaoWenJian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);

protected:
    void rg_WenJianChaZhaoLei_class_ChuShiHua ();

protected:
    CVolEventReceiver rw_3;
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_WENJIANCHAZHAOLEI_H__
