
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_APP_MCPVIPDISPATCH_H__
#define __VCLS_RG_VOLCANO_APP_MCPVIPDISPATCH_H__

namespace rg_volcano_app
{

class MCPVIPDispatch : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_app, MCPVIPDispatch)

public:
    static CVolString CALLBACK DispatchClassVIPOp (CVolString& CommandID, CVolString& MethodName, rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei& ParamJSON);
    inline_ MCPVIPDispatch () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_APP_MCPVIPDISPATCH_H__
