
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_YANGWANG_RG_CRCJIAOYANLEI_N_H__
#define __VCLS_RG_VOLCANO_YANGWANG_RG_CRCJIAOYANLEI_N_H__

namespace rg_volcano_YangWang
{

class rg_CRCJiaoYanLei_n : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_YangWang, rg_CRCJiaoYanLei_n)

public:
    static INT CALLBACK rg_QuShuJuZhaiYao_CRC (CVolMem& rg_ShuJuYuan, INT rg_CRCZhi);
    inline_ rg_CRCJiaoYanLei_n () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_YANGWANG_RG_CRCJIAOYANLEI_N_H__
