
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_YANGWANG_RG_CRCAPI_H__
#define __VCLS_RG_VOLCANO_YANGWANG_RG_CRCAPI_H__

namespace rg_volcano_YangWang
{

class rg_CRCapi : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_YangWang, rg_CRCapi)

public:
    static INT CALLBACK RtlComputeCrc32 (INT rg_CRCZhi1, INT rg_HuanCunShuJu, INT rg_ShuJuChangDu85);
    inline_ rg_CRCapi () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_YANGWANG_RG_CRCAPI_H__
