
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

namespace rg_volcano_YangWang
{
void rg_WenBenChuLiLei_n::SuperReplaceSubText(CVolString* src, INT_P argNum, ...)
{
    va_list argList;
    va_start (argList, argNum);
    for (INT_P npIndex = 1; npIndex < argNum; npIndex+=2)
    {
        const CVolString* str1 = va_arg (argList, const CVolString*);
        const CVolString* str2 = va_arg (argList, const CVolString*);
        src->ReplaceSubText(*str1, *str2, 0, -1, FALSE);
    }
    va_end(argList);
}
void rg_WenBenChuLiLei_n::TextSplicing(CVolString* src, CVolString* fuhao, INT_P argNum, ...)
{
    src->Empty();
    va_list argList;
    va_start (argList, argNum);
    for (INT_P npIndex = 2; npIndex < argNum; npIndex++)
    {
        const CVolString* str1 = va_arg (argList, const CVolString*);
        if(npIndex < argNum-1){
            src->AddText (*str1+ *fuhao);
        }
        else{
            src->AddText (*str1);
       }
    }
    va_end(argList);
}

}
