
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VPKG_RG_VOLCANO_APP_MAIN_H__
#define __VPKG_RG_VOLCANO_APP_MAIN_H__

extern EXTERN_FUNC_ITEM rw_1 [];

#endif  // __VPKG_RG_VOLCANO_APP_MAIN_H__
