
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_APP_RG_CLASS_MCP_QINGLIHUANCUNHUIDIAO_H__
#define __VCLS_RG_VOLCANO_APP_RG_CLASS_MCP_QINGLIHUANCUNHUIDIAO_H__

namespace rg_volcano_app
{

class rg_class_MCP_QingLiHuanCunHuiDiao : public rg_FBrowser_HuiDiao::rg_class_FBrowser_qlhchd
{
    DECLARE_VOL_CLASS (rg_volcano_app, rg_class_MCP_QingLiHuanCunHuiDiao)

public:
    virtual void rg_WanCheng (BOOL rg_ShiFouChengGong1);
    inline_ rg_class_MCP_QingLiHuanCunHuiDiao () { }
    inline_ void _VolObjectInitMembers () { }
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

public:
    CVolString rg_RenWuID8;
};

}

#endif  //__VCLS_RG_VOLCANO_APP_RG_CLASS_MCP_QINGLIHUANCUNHUIDIAO_H__
