
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_RG_CONST_RG_XIANCHENGID_H__
#define __VCLS_RG_FBROWSER_RG_CONST_RG_XIANCHENGID_H__

namespace rg_FBrowser_rg_const
{

class rg_XianChengID : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_FBrowser_rg_const, rg_XianChengID)

public:
    inline_ rg_XianChengID () { }
    inline_ void _VolObjectInitMembers () { }

public:
    static const INT rg_UI;
};

}

#endif  //__VCLS_RG_FBROWSER_RG_CONST_RG_XIANCHENGID_H__
