
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_LIULANQI_RG_CLASS_FBROWSER_TIANBIAOKUANGJIA_H__
#define __VCLS_RG_FBROWSER_LIULANQI_RG_CLASS_FBROWSER_TIANBIAOKUANGJIA_H__

namespace rg_FBrowser_LiuLanQi
{

class rg_class_FBrowser_TianBiaoKuangJia : public FBroBaseFrame
{
    DECLARE_EMPTY_VOL_CLASS (rg_FBrowser_LiuLanQi, rg_class_FBrowser_TianBiaoKuangJia)

public:
    rg_class_FBrowser_TianBiaoKuangJia (CefRefPtr<CefFrame> object): FBroBaseFrame(object){rg_class_FBrowser_TianBiaoKuangJia ();}

public:
    void rg_DianJiYuanSu (CVolString& rg_XuanZeQi, INT rg_SuoYin5);
    void rg_GunDongDaoYuanSu (CVolString& rg_XuanZeQi1, INT rg_SuoYin6, BOOL rg_ShiFouDingDuanDuiJi);
    void rg_ZhiYuanSuXuanZeKuang (CVolString& rg_XuanZeQi2, INT rg_SuoYin7, BOOL rg_XuanZe2);
    void rg_ZhiYuanSuJiaoDian (CVolString& rg_XuanZeQi6, INT rg_SuoYin11, BOOL rg_ShiFouJiaoDian);
    void rg_ZhiYuanSuNeiRong (CVolString& rg_XuanZeQi7, INT rg_SuoYin12, CVolString& rg_NeiRong6);
    void rg_ZhiYuanSuShuXing (CVolString& rg_XuanZeQi17, INT rg_SuoYin22, CVolString& rg_YuanSuMing, CVolString& rg_value98);
    void rg_QuYuanSuShuXing (CVolString& rg_XuanZeQi18, INT rg_SuoYin23, CVolString& rg_YuanSuMing1, rg_class_FBrowser_shjzhnzhzh& rg_JieGuoHuiDiao10);
    void rg_YuanSuShiFouCunZai (CVolString& rg_XuanZeQi19, INT rg_SuoYin24, rg_class_FBrowser_shjzhnzhzh& rg_JieGuoHuiDiao11);
    void rg_ChuFaYuanSuShiJian (CVolString& rg_XuanZeQi21, INT rg_SuoYin26, CVolString& rg_ShiJianMing5, INT rg_AnJianDaiMa);
    inline_ rg_class_FBrowser_TianBiaoKuangJia () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_FBROWSER_LIULANQI_RG_CLASS_FBROWSER_TIANBIAOKUANGJIA_H__
