
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_APP_RG_CLASS_MCP_STDIOFUWUXIANCHENG_H__
#define __VCLS_RG_VOLCANO_APP_RG_CLASS_MCP_STDIOFUWUXIANCHENG_H__

namespace rg_volcano_app
{

class rg_class_MCP_StdioFuWuXianCheng : public rg_volcano_base::rg_HuanCunXianChengLei
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_app, rg_class_MCP_StdioFuWuXianCheng)

public:
    rg_class_MCP_StdioFuWuXianCheng ();
    void _VolObjectInitMembers ();
    virtual ~rg_class_MCP_StdioFuWuXianCheng ();

public:
    static INT re_class_MCP_StdioFuWuXianCheng_HuanCunXianChengLei_XianChengYunHang (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber, INT64 rg_XianChengGouBing2, INT64 rg_YongHuCanShu, INT64 rg_TuiChuShiJian)
    {
        return ((rg_class_MCP_StdioFuWuXianCheng*)pobjEventReceiver)->rg_HuanCunXianChengLei_XianChengYunHang ((rg_volcano_base::rg_HuanCunXianChengLei&)*pobjEventSource, nTagNumber, rg_XianChengGouBing2, rg_YongHuCanShu, rg_TuiChuShiJian);
    }

protected:
    INT rg_HuanCunXianChengLei_XianChengYunHang (rg_volcano_base::rg_HuanCunXianChengLei& rg_LaiYuanDuiXiang12, INT rg_BiaoJiZhi12, INT64 rg_XianChengGouBing2, INT64 rg_YongHuCanShu, INT64 rg_TuiChuShiJian);

protected:
    CVolEventObjectPointer* rw_2;
};

}

#endif  //__VCLS_RG_VOLCANO_APP_RG_CLASS_MCP_STDIOFUWUXIANCHENG_H__
