
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_LIULANQI_FBROV8STACKTRACE_H__
#define __VCLS_RG_FBROWSER_LIULANQI_FBROV8STACKTRACE_H__

namespace rg_FBrowser_LiuLanQi
{

class FBroV8StackTrace : public CVolObject
{
    DECLARE_VOL_CLASS (rg_FBrowser_LiuLanQi, FBroV8StackTrace)

public:
    CefRefPtr<CefV8StackTrace> m_class;
    inline_ FBroV8StackTrace (CefRefPtr<CefV8StackTrace> object) : FBroV8StackTrace () { m_class = object; }
    inline_ void _CopySelfFromExtra (const FBroV8StackTrace& objCopyFrom) { m_class = objCopyFrom.m_class; }
    inline_ BOOL _IsSelfEqualExtra (const FBroV8StackTrace& objCompare) const { return (m_class.get () == objCompare.m_class.get ()); }
    inline_ BOOL IsEmpty () const { return m_class.get () == nullptr; }
    inline_ void Set (CefRefPtr<CefV8StackTrace> object) { m_class = object; }
    ~FBroV8StackTrace(){};

public:
    inline_ FBroV8StackTrace () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_FBROWSER_LIULANQI_FBROV8STACKTRACE_H__
