
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_HUIDIAO_RG_CLASS_FBROWSER_QXDSHHD_H__
#define __VCLS_RG_FBROWSER_HUIDIAO_RG_CLASS_FBROWSER_QXDSHHD_H__

namespace rg_FBrowser_HuiDiao
{

class rg_class_FBrowser_qxdshhd : public CVolObject
{
    DECLARE_VOL_CLASS (rg_FBrowser_HuiDiao, rg_class_FBrowser_qxdshhd)

public:
    CefRefPtr<CefPermissionPromptCallback> m_class;
    inline_ rg_class_FBrowser_qxdshhd (CefRefPtr<CefPermissionPromptCallback> object) : rg_class_FBrowser_qxdshhd () { m_class = object; }
    inline_ void _CopySelfFromExtra (const rg_class_FBrowser_qxdshhd& objCopyFrom) { m_class = objCopyFrom.m_class; }
    inline_ BOOL _IsSelfEqualExtra (const rg_class_FBrowser_qxdshhd& objCompare) const { return (m_class == objCompare.m_class); }
    inline_ BOOL_P IsEmpty () const { return m_class == nullptr; }
    inline_ void Set (CefRefPtr<CefPermissionPromptCallback> object) { m_class = object; }
    ~rg_class_FBrowser_qxdshhd(){};

public:
    inline_ rg_class_FBrowser_qxdshhd () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_FBROWSER_HUIDIAO_RG_CLASS_FBROWSER_QXDSHHD_H__
