
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

namespace rg_volcano_MFCJieMian_base
{

rg_ZuJianBuJuQi::rg_ZuJianBuJuQi ()
{
    _VolObjectInitMembers ();
}

void rg_ZuJianBuJuQi::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

rg_ZuJianBuJuQi::~rg_ZuJianBuJuQi ()
{
    OnBeforeObjectCleanup ();
    _OnCleanupExtra ();
}
void rg_ZuJianBuJuQi::_OnInitExtra ()
{
    CMfcWndObject* pMfcWndObject = new CMfcWndObject (new CVWnd_Container (), FALSE);
    pMfcWndObject->m_dwAttrInitialStyle = (pMfcWndObject->m_dwAttrInitialStyle & ~(0)) | 0;
    pMfcWndObject->m_dwAttrInitialExStyle = (pMfcWndObject->m_dwAttrInitialExStyle & ~(0)) | 0;
    TakeOverNewRefObject (pMfcWndObject);
    _OnInitControl ();
}
BOOL rg_ZuJianBuJuQi::CreateMfcControl (CVolNativeWndCreateParam* pCreateParam)
{
    ASSERT (pCreateParam != NULL);
    CVWnd_Container* pWnd = (CVWnd_Container*)GetMfcWndPtr ();
    ASSERT (pWnd != NULL);
    pWnd->m_nGroupNumber = pCreateParam->m_nGroupNumber;
    if (pWnd->m_hWnd == NULL)
    {
        OnBeforeNativeWndCreate (pCreateParam);
        OnCalcNativeWndPos (pCreateParam);
        if (pWnd->CreateControl (pCreateParam))
        {
            if (pWnd->m_hWnd != NULL)
                OnAfterNativeWndCreate (pWnd, pCreateParam);
            return TRUE;
        }
    }
    return FALSE;
}
void rg_ZuJianBuJuQi::AttachEventListener ()
{
    ((CVWnd_Container*)GetMfcWndPtr ())->m_pEventListener = (IContainerEventListener*)this;
}
void rg_ZuJianBuJuQi::DetachEventListener ()
{
    CVWnd_Container* pwndControl = (CVWnd_Container*)GetMfcWndPtr ();
    if (pwndControl->m_pEventListener == (IContainerEventListener*)this)
        pwndControl->m_pEventListener = NULL;
}
BOOL_P rg_ZuJianBuJuQi::IsEventAttached ()
{
    return (((CVWnd_Container*)GetMfcWndPtr ())->m_pEventListener != NULL);
}

void rg_ZuJianBuJuQi::ra_ZuJianBuJuQi_ChuangJianWanBi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_5.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT rg_ZuJianBuJuQi::rg_ChuangJianWanBi ()
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_5.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

void rg_ZuJianBuJuQi::ra_ZuJianBuJuQi_JiangBeiXiaoHui (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_6.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT rg_ZuJianBuJuQi::rg_JiangBeiXiaoHui ()
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_6.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

void rg_ZuJianBuJuQi::ra_ZuJianBuJuQi_YiBeiXiaoHui (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_7.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT rg_ZuJianBuJuQi::rg_YiBeiXiaoHui ()
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_7.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

void rg_ZuJianBuJuQi::ra_ZuJianBuJuQi_WeiZhiBeiGaiBian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_8.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT rg_ZuJianBuJuQi::rg_WeiZhiBeiGaiBian ()
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_8.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

void rg_ZuJianBuJuQi::ra_ZuJianBuJuQi_CheCunBeiGaiBian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_9.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT rg_ZuJianBuJuQi::rg_CheCunBeiGaiBian ()
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_9.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

void rg_ZuJianBuJuQi::ra_ZuJianBuJuQi_BeiXianShi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_10.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT rg_ZuJianBuJuQi::rg_BeiXianShi ()
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_10.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

void rg_ZuJianBuJuQi::ra_ZuJianBuJuQi_BeiYinCang (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_11.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT rg_ZuJianBuJuQi::rg_BeiYinCang ()
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_11.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

void rg_ZuJianBuJuQi::ra_ZuJianBuJuQi_JieShouDaoZiZuJianMingLing (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_12.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT rg_ZuJianBuJuQi::rg_JieShouDaoZiZuJianMingLing (INT rg_MingLingDaiMa)
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_12.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber, INT rg_MingLingDaiMa))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber, rg_MingLingDaiMa);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

BOOL rg_ChuangKouWeiZhiXianZhiXinXi::_IsSelfEqual (const rg_ChuangKouWeiZhiXianZhiXinXi& objCompare) const
{
    if (rg_ZuiDaCheCun12 != objCompare.rg_ZuiDaCheCun12)  return FALSE;
    if (rg_ZuiDaWeiZhi != objCompare.rg_ZuiDaWeiZhi)  return FALSE;
    if (rg_ZuiXiaoDiaoJieCheCun != objCompare.rg_ZuiXiaoDiaoJieCheCun)  return FALSE;
    if (rg_ZuiDaDiaoJieCheCun != objCompare.rg_ZuiDaDiaoJieCheCun)  return FALSE;
    return TRUE;
}

void rg_ChuangKouWeiZhiXianZhiXinXi::_CopySelfFrom (const rg_ChuangKouWeiZhiXianZhiXinXi& objCopyFrom)
{
    rg_ZuiDaCheCun12 = objCopyFrom.rg_ZuiDaCheCun12;
    rg_ZuiDaWeiZhi = objCopyFrom.rg_ZuiDaWeiZhi;
    rg_ZuiXiaoDiaoJieCheCun = objCopyFrom.rg_ZuiXiaoDiaoJieCheCun;
    rg_ZuiDaDiaoJieCheCun = objCopyFrom.rg_ZuiDaDiaoJieCheCun;
}

void rg_ChuangKouWeiZhiXianZhiXinXi::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    rg_ZuiDaCheCun12.LoadFromStream (stream);
    rg_ZuiDaWeiZhi.LoadFromStream (stream);
    rg_ZuiXiaoDiaoJieCheCun.LoadFromStream (stream);
    rg_ZuiDaDiaoJieCheCun.LoadFromStream (stream);
}

void rg_ChuangKouWeiZhiXianZhiXinXi::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    rg_ZuiDaCheCun12.SaveIntoStream (stream);
    rg_ZuiDaWeiZhi.SaveIntoStream (stream);
    rg_ZuiXiaoDiaoJieCheCun.SaveIntoStream (stream);
    rg_ZuiDaDiaoJieCheCun.SaveIntoStream (stream);
}
void rg_ChuangKouWeiZhiXianZhiXinXi::Copy (const MINMAXINFO* lpMMI)
{
    rg_ZuiDaCheCun12.Copy ((const SIZE*)&lpMMI->ptMaxSize);
    rg_ZuiDaWeiZhi.Copy (&lpMMI->ptMaxPosition);
    rg_ZuiXiaoDiaoJieCheCun.Copy ((const SIZE*)&lpMMI->ptMinTrackSize);
    rg_ZuiDaDiaoJieCheCun.Copy ((const SIZE*)&lpMMI->ptMaxTrackSize);
}
void rg_ChuangKouWeiZhiXianZhiXinXi::Out (MINMAXINFO* lpMMI) const
{
    rg_ZuiDaCheCun12.Out ((SIZE*)&lpMMI->ptMaxSize);
    rg_ZuiDaWeiZhi.Out (&lpMMI->ptMaxPosition);
    rg_ZuiXiaoDiaoJieCheCun.Out ((SIZE*)&lpMMI->ptMinTrackSize);
    rg_ZuiDaDiaoJieCheCun.Out ((SIZE*)&lpMMI->ptMaxTrackSize);
}

CVolWinForm::CVolWinForm ()
{
    _VolObjectInitMembers ();
}

void CVolWinForm::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

CVolWinForm::~CVolWinForm ()
{
    OnBeforeObjectCleanup ();
    _OnCleanupExtra ();
}
void CVolWinForm::_OnInitExtra ()
{
    CMfcWndObject* pMfcWndObject = new CMfcWndObject (new CVWnd_WinForm (), FALSE);
    pMfcWndObject->m_dwAttrInitialStyle = (pMfcWndObject->m_dwAttrInitialStyle & ~(0)) | 0;
    pMfcWndObject->m_dwAttrInitialExStyle = (pMfcWndObject->m_dwAttrInitialExStyle & ~(0)) | 0;
    TakeOverNewRefObject (pMfcWndObject);
    _OnInitControl ();
}
BOOL CVolWinForm::CreateMfcControl (CVolNativeWndCreateParam* pCreateParam)
{
    ASSERT (pCreateParam != NULL);
    CVWnd_WinForm* pWnd = (CVWnd_WinForm*)GetMfcWndPtr ();
    ASSERT (pWnd != NULL);
    pWnd->m_nGroupNumber = pCreateParam->m_nGroupNumber;
    if (pWnd->m_hWnd == NULL)
    {
        OnBeforeNativeWndCreate (pCreateParam);
        OnCalcNativeWndPos (pCreateParam);
        if (pWnd->CreateControl (pCreateParam))
        {
            if (pWnd->m_hWnd != NULL)
                OnAfterNativeWndCreate (pWnd, pCreateParam);
            return TRUE;
        }
    }
    return FALSE;
}
void CVolWinForm::AttachEventListener ()
{
    ((CVWnd_WinForm*)GetMfcWndPtr ())->m_pEventListener = (IWinFormEventListener*)this;
}
void CVolWinForm::DetachEventListener ()
{
    CVWnd_WinForm* pwndControl = (CVWnd_WinForm*)GetMfcWndPtr ();
    if (pwndControl->m_pEventListener == (IWinFormEventListener*)this)
        pwndControl->m_pEventListener = NULL;
}
BOOL_P CVolWinForm::IsEventAttached ()
{
    return (((CVWnd_WinForm*)GetMfcWndPtr ())->m_pEventListener != NULL);
}

void CVolWinForm::ra_CVolWinForm_JieShouDaoMingLing (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_13.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT CVolWinForm::rg_JieShouDaoMingLing (INT rg_MingLingDaiMa1)
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_13.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber, INT rg_MingLingDaiMa1))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber, rg_MingLingDaiMa1);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

void CVolWinForm::ra_CVolWinForm_MingLingBeiXuanZhong (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_14.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT CVolWinForm::rg_MingLingBeiXuanZhong (INT rg_MingLingDaiMa2)
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_14.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber, INT rg_MingLingDaiMa2))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber, rg_MingLingDaiMa2);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

void CVolWinForm::ra_CVolWinForm_KeFouBeiGuanBi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_15.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT CVolWinForm::rg_KeFouBeiGuanBi ()
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_15.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

void CVolWinForm::ra_CVolWinForm_ChuangKouKeFouBeiGuanBi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_16.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT CVolWinForm::rg_ChuangKouKeFouBeiGuanBi ()
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_16.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

void CVolWinForm::ra_CVolWinForm_ShouCiJiHuo (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_17.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT CVolWinForm::rg_ShouCiJiHuo ()
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_17.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

void CVolWinForm::ra_CVolWinForm_BeiJiHuo (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_18.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT CVolWinForm::rg_BeiJiHuo ()
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_18.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

void CVolWinForm::ra_CVolWinForm_BeiQuXiaoJiHuo (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_19.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT CVolWinForm::rg_BeiQuXiaoJiHuo ()
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_19.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

void CVolWinForm::ra_CVolWinForm_TuoPanShiJian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_20.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT CVolWinForm::rg_TuoPanShiJian (INT rg_CaoZuoLeiXing2)
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_20.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber, INT rg_CaoZuoLeiXing2))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber, rg_CaoZuoLeiXing2);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

void CVolWinForm::ra_CVolWinForm_WeiZhiXianZhi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_21.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT CVolWinForm::rg_WeiZhiXianZhi (rg_ChuangKouWeiZhiXianZhiXinXi& rg_WeiZhiXianZhiXinXi)
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_21.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber, rg_ChuangKouWeiZhiXianZhiXinXi& rg_WeiZhiXianZhiXinXi))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber, rg_WeiZhiXianZhiXinXi);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

void CVolWinForm::ra_CVolWinForm_DuiHuaKuangYiChuShiHua (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_22.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT CVolWinForm::rg_DuiHuaKuangYiChuShiHua ()
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_22.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

BOOL CVolWinForm::rg_XiaoXiGuoLu1 (INT64 rg_ChuangKouGouBing6, INT rg_XiaoXiZhi1, INT64 rg_XiaoXiCanShu2, INT64 rg_XiaoXiCanShu3, INT64 rg_XiaoXiDeZhi1)
{
    return (TRUE);
}

void CVolWinForm::rg_ChuangKouBianKuang1 (INT rg_SuoYuSheZhiDeBianKuang)
{
    ((CVWnd_WinForm*)GetMfcWndPtr ())->SetBorderType (rg_SuoYuSheZhiDeBianKuang);
}

void CVolWinForm::rg_ZuiDaHuaAnNiu1 (BOOL rg_ShiFouXianShiZuiDaHuaAnNiu)
{
    ((CVWnd_WinForm*)GetMfcWndPtr ())->SetMaxBox (rg_ShiFouXianShiZuiDaHuaAnNiu);
}

void CVolWinForm::rg_ZuiXiaoHuaAnNiu1 (BOOL rg_ShiFouXianShiZuiXiaoHuaAnNiu)
{
    ((CVWnd_WinForm*)GetMfcWndPtr ())->SetMinBox (rg_ShiFouXianShiZuiXiaoHuaAnNiu);
}

void CVolWinForm::rg_ZhiTuoPanTuBiaoDuiXiang (rg_volcano_base::rg_TuBiaoDuiXiangLei& rg_SuoYuSheZhiDeTuBiao3, CVolString& rg_DiShiXinXi4)
{
    CWnd* pWnd = GetMfcWndPtrWithValidHWnd ();
    if (pWnd != NULL)
        ((CVWnd_WinForm*)pWnd)->SetTrayIcon (::CopyIcon ((HICON)rg_SuoYuSheZhiDeTuBiao3.GetGDIHandle ()), rg_DiShiXinXi4);
}
void CVolWinForm::OnGetMinMaxInfo (MINMAXINFO* lpMMI)
{
    rg_ChuangKouWeiZhiXianZhiXinXi inf (lpMMI);
    if (rg_WeiZhiXianZhi (inf) != 0)
        inf.Out (lpMMI);
}
void CVolWinForm::OnBeforeNativeWndCreate (CVolNativeWndCreateParam* pCreateParam)
{
    BaseClass::OnBeforeNativeWndCreate (pCreateParam);
    ((CVWnd_WinForm*)GetMfcWndPtr ())->OnPrepareWindowStyle (pCreateParam);
}
void CVolWinForm::OnCalcNativeWndPos (CVolNativeWndCreateParam* pCreateParam)
{
    BaseClass::OnCalcNativeWndPos (pCreateParam);
    if (pCreateParam->m_nLeft == INT_MIN || pCreateParam->m_nTop == INT_MIN)
    {
        if ((pCreateParam->m_dwStyle & WS_CHILD) == 0)
        {
            RECT rtMonitor;
            GetMonitorRect (NULL, &rtMonitor);
            if (pCreateParam->m_nLeft == INT_MIN)
                pCreateParam->m_nLeft = (rtMonitor.left + rtMonitor.right - pCreateParam->m_nWidth) / 2;
            if (pCreateParam->m_nTop == INT_MIN)
                pCreateParam->m_nTop = (rtMonitor.top + rtMonitor.bottom - pCreateParam->m_nHeight) / 2;
        }
        else
        {
            if (pCreateParam->m_nLeft == INT_MIN)  pCreateParam->m_nLeft = 0;
            if (pCreateParam->m_nTop == INT_MIN)  pCreateParam->m_nTop = 0;
        }
    }
}
BOOL CVolWinForm::CreateVolWindowWithNewMenu (CVolWinControl* pParentControl, INT nLeft, INT nTop, INT nWidth, INT nHeight, CVolRuntimeClass* pVolMenuRuntimeClass)
{
    rg_CaiChanLei* pVolMenuObject;
    if (pVolMenuRuntimeClass != NULL)
    {
        pVolMenuObject = (rg_CaiChanLei*)pVolMenuRuntimeClass->CreateObject ();
        ASSERT (P_IS_VOL_INSTANCE_OF (pVolMenuObject, rg_CaiChanLei));
    }
    else
        pVolMenuObject = NULL;
    CVolObjectDestroyer destroyer (pVolMenuObject);
    return CreateVolWindow (pParentControl, nLeft, nTop, nWidth, nHeight, pVolMenuObject->SafeGetVolMenu ());
}
BOOL CVolWinForm::CreateVolWindow (CVolWinControl* pParentControl, INT nLeft, INT nTop, INT nWidth, INT nHeight, CRefVolMenu* pVolMenu)
{
    CWnd* pParentWnd = pParentControl->SafeGetMfcWndPtrWithValidHWnd ();
    CVolNativeWndCreateParam param (pParentWnd, nLeft, nTop, nWidth, nHeight, 0);
    if (pParentWnd != NULL)  param.m_pParentWndObject = pParentControl;
    param.m_pVolMenu = pVolMenu;
    return CreateMfcControl (&param);
}
BOOL CVolWinForm::CreateMainVolWindowWithNewMenu (INT nLeft, INT nTop, INT nWidth, INT nHeight, CVolRuntimeClass* pVolMenuRuntimeClass)
{
    if (CreateVolWindowWithNewMenu (NULL, nLeft, nTop, nWidth, nHeight, pVolMenuRuntimeClass))
    {
        if (AfxGetApp () != NULL)
            AfxGetApp ()->m_pMainWnd = GetMfcWndPtrWithValidHWnd ();
        return TRUE;
    }
    return FALSE;
}
BOOL CVolWinForm::CreateMainVolWindow (INT nLeft, INT nTop, INT nWidth, INT nHeight, CRefVolMenu* pVolMenu)
{
    if (CreateVolWindow (NULL, nLeft, nTop, nWidth, nHeight, pVolMenu))
    {
        if (AfxGetApp () != NULL)
            AfxGetApp ()->m_pMainWnd = GetMfcWndPtrWithValidHWnd ();
        return TRUE;
    }
    return FALSE;
}
INT CVolWinForm::CreateVolDialogWithNewMenu (CVolWinControl* pParentControl, INT nLeft, INT nTop, INT nWidth, INT nHeight, CVolRuntimeClass* pVolMenuRuntimeClass, BOOL blForceUseDialogStyle)
{
    rg_CaiChanLei* pVolMenuObject;
    if (pVolMenuRuntimeClass != NULL)
    {
        pVolMenuObject = (rg_CaiChanLei*)pVolMenuRuntimeClass->CreateObject ();
        ASSERT (P_IS_VOL_INSTANCE_OF (pVolMenuObject, rg_CaiChanLei));
    }
    else
        pVolMenuObject = NULL;
    CVolObjectDestroyer destroyer (pVolMenuObject);
    return CreateVolDialog (pParentControl, nLeft, nTop, nWidth, nHeight, pVolMenuObject->SafeGetVolMenu (), blForceUseDialogStyle);
}
INT CVolWinForm::CreateVolDialog (CVolWinControl* pParentControl, INT nLeft, INT nTop, INT nWidth, INT nHeight, CRefVolMenu* pVolMenu, BOOL blForceUseDialogStyle)
{
    CWnd* pParentWnd = pParentControl->SafeGetMfcWndPtrWithValidHWnd ();
    CVolNativeWndCreateParam param (pParentWnd, nLeft, nTop, nWidth, nHeight, 0xFFFF);
    if (pParentWnd != NULL)  param.m_pParentWndObject = pParentControl;
    param.m_pVolMenu = pVolMenu;
    param.m_blModalDialog = TRUE;
    param.m_blForceUseDialogStyle = blForceUseDialogStyle;
    return (CreateMfcControl (&param) == FALSE ? -1 : param.m_nDialogResult);
}
void CVolWinForm::SetWndMenuClass (CVolRuntimeClass* pVolMenuRuntimeClass)
{
    if (pVolMenuRuntimeClass != NULL)
    {
        rg_CaiChanLei* pVolMenuObject = (rg_CaiChanLei*)pVolMenuRuntimeClass->CreateObject ();
        ASSERT (P_IS_VOL_INSTANCE_OF (pVolMenuObject, rg_CaiChanLei));
        SetWndMenu (pVolMenuObject->GetVolMenu ());
        pVolMenuObject->Destroy ();
    }
}

void rg_AnNiuJiChuLei::ra_AnNiuJiChuLei_clicked2 (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_23.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT rg_AnNiuJiChuLei::rg_clicked2 ()
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_23.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}
void rg_AnNiuJiChuLei::SetButtonStyle (const DWORD dwStyle, const BOOL_P blpSet)
{
    if (blpSet)
        GetMfcWndObject ()->m_dwAttrInitialStyle |= dwStyle;
    else
        GetMfcWndObject ()->m_dwAttrInitialStyle &= ~dwStyle;
    CWnd* pWnd = GetMfcWndPtrWithValidHWnd ();
    if (pWnd != NULL)
    {
        pWnd->ModifyStyle (dwStyle, (GetMfcWndObject ()->m_dwAttrInitialStyle & dwStyle),
                (SWP_NOSIZE | SWP_NOMOVE | SWP_NOZORDER | SWP_NOACTIVATE | SWP_FRAMECHANGED | SWP_DRAWFRAME));
        pWnd->Invalidate ();
    }
}

rg_button1::rg_button1 ()
{
    _VolObjectInitMembers ();
}

void rg_button1::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

rg_button1::~rg_button1 ()
{
    OnBeforeObjectCleanup ();
    _OnCleanupExtra ();
}
void rg_button1::_OnInitExtra ()
{
    CMfcWndObject* pMfcWndObject = new CMfcWndObject (new CVWnd_Button (), FALSE);
    pMfcWndObject->m_dwAttrInitialStyle = (pMfcWndObject->m_dwAttrInitialStyle & ~(0)) | WS_TABSTOP | BS_PUSHBUTTON | BS_MULTILINE;
    pMfcWndObject->m_dwAttrInitialExStyle = (pMfcWndObject->m_dwAttrInitialExStyle & ~(0)) | 0;
    TakeOverNewRefObject (pMfcWndObject);
    _OnInitControl ();
}
BOOL rg_button1::CreateMfcControl (CVolNativeWndCreateParam* pCreateParam)
{
    ASSERT (pCreateParam != NULL);
    CVWnd_Button* pWnd = (CVWnd_Button*)GetMfcWndPtr ();
    ASSERT (pWnd != NULL);
    pWnd->m_nGroupNumber = pCreateParam->m_nGroupNumber;
    if (pWnd->m_hWnd == NULL)
    {
        OnBeforeNativeWndCreate (pCreateParam);
        OnCalcNativeWndPos (pCreateParam);
        if (pWnd->CreateControl (pCreateParam))
        {
            if (pWnd->m_hWnd != NULL)
                OnAfterNativeWndCreate (pWnd, pCreateParam);
            return TRUE;
        }
    }
    return FALSE;
}
void rg_button1::AttachEventListener ()
{
    ((CVWnd_Button*)GetMfcWndPtr ())->m_pEventListener = (IButtonEventListener*)this;
}
void rg_button1::DetachEventListener ()
{
    CVWnd_Button* pwndControl = (CVWnd_Button*)GetMfcWndPtr ();
    if (pwndControl->m_pEventListener == (IButtonEventListener*)this)
        pwndControl->m_pEventListener = NULL;
}
BOOL_P rg_button1::IsEventAttached ()
{
    return (((CVWnd_Button*)GetMfcWndPtr ())->m_pEventListener != NULL);
}

rg_label::rg_label ()
{
    _VolObjectInitMembers ();
}

void rg_label::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

rg_label::~rg_label ()
{
    OnBeforeObjectCleanup ();
    _OnCleanupExtra ();
}
void rg_label::_OnInitExtra ()
{
    CMfcWndObject* pMfcWndObject = new CMfcWndObject (new CVWnd_Label (), FALSE);
    pMfcWndObject->m_dwAttrInitialStyle = (pMfcWndObject->m_dwAttrInitialStyle & ~(WS_BORDER)) | 0;
    pMfcWndObject->m_dwAttrInitialExStyle = (pMfcWndObject->m_dwAttrInitialExStyle & ~(0)) | 0;
    TakeOverNewRefObject (pMfcWndObject);
    _OnInitControl ();
}
BOOL rg_label::CreateMfcControl (CVolNativeWndCreateParam* pCreateParam)
{
    ASSERT (pCreateParam != NULL);
    CVWnd_Label* pWnd = (CVWnd_Label*)GetMfcWndPtr ();
    ASSERT (pWnd != NULL);
    pWnd->m_nGroupNumber = pCreateParam->m_nGroupNumber;
    if (pWnd->m_hWnd == NULL)
    {
        OnBeforeNativeWndCreate (pCreateParam);
        OnCalcNativeWndPos (pCreateParam);
        if (pWnd->CreateControl (pCreateParam))
        {
            if (pWnd->m_hWnd != NULL)
                OnAfterNativeWndCreate (pWnd, pCreateParam);
            return TRUE;
        }
    }
    return FALSE;
}
void rg_label::AttachEventListener ()
{
    ((CVWnd_Label*)GetMfcWndPtr ())->m_pEventListener = (ILabelEventListener*)this;
}
void rg_label::DetachEventListener ()
{
    CVWnd_Label* pwndControl = (CVWnd_Label*)GetMfcWndPtr ();
    if (pwndControl->m_pEventListener == (ILabelEventListener*)this)
        pwndControl->m_pEventListener = NULL;
}
BOOL_P rg_label::IsEventAttached ()
{
    return (((CVWnd_Label*)GetMfcWndPtr ())->m_pEventListener != NULL);
}

void rg_label::ra_label_FanKuiShiJian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_24.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT rg_label::rg_FanKuiShiJian (INT64 rg_param26, INT64 rg_param27)
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_24.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber, INT64 rg_param26, INT64 rg_param27))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber, rg_param26, rg_param27);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

rg_edit_box1::rg_edit_box1 ()
{
    _VolObjectInitMembers ();
}

void rg_edit_box1::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

rg_edit_box1::~rg_edit_box1 ()
{
    OnBeforeObjectCleanup ();
    _OnCleanupExtra ();
}
void rg_edit_box1::_OnInitExtra ()
{
    CMfcWndObject* pMfcWndObject = new CMfcWndObject (new CVWnd_Edit (), FALSE);
    pMfcWndObject->m_dwAttrInitialStyle = (pMfcWndObject->m_dwAttrInitialStyle & ~(0)) | WS_TABSTOP;
    pMfcWndObject->m_dwAttrInitialExStyle = (pMfcWndObject->m_dwAttrInitialExStyle & ~(0)) | WS_EX_CLIENTEDGE;
    TakeOverNewRefObject (pMfcWndObject);
    _OnInitControl ();
}
BOOL rg_edit_box1::CreateMfcControl (CVolNativeWndCreateParam* pCreateParam)
{
    ASSERT (pCreateParam != NULL);
    CVWnd_Edit* pWnd = (CVWnd_Edit*)GetMfcWndPtr ();
    ASSERT (pWnd != NULL);
    pWnd->m_nGroupNumber = pCreateParam->m_nGroupNumber;
    if (pWnd->m_hWnd == NULL)
    {
        OnBeforeNativeWndCreate (pCreateParam);
        OnCalcNativeWndPos (pCreateParam);
        if (pWnd->CreateControl (pCreateParam))
        {
            if (pWnd->m_hWnd != NULL)
                OnAfterNativeWndCreate (pWnd, pCreateParam);
            return TRUE;
        }
    }
    return FALSE;
}
void rg_edit_box1::AttachEventListener ()
{
    ((CVWnd_Edit*)GetMfcWndPtr ())->m_pEventListener = (IEditEventListener*)this;
}
void rg_edit_box1::DetachEventListener ()
{
    CVWnd_Edit* pwndControl = (CVWnd_Edit*)GetMfcWndPtr ();
    if (pwndControl->m_pEventListener == (IEditEventListener*)this)
        pwndControl->m_pEventListener = NULL;
}
BOOL_P rg_edit_box1::IsEventAttached ()
{
    return (((CVWnd_Edit*)GetMfcWndPtr ())->m_pEventListener != NULL);
}

void rg_edit_box1::ra_edit_box1_NeiRongBeiGaiBian1 (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_25.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT rg_edit_box1::rg_NeiRongBeiGaiBian1 ()
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_25.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

void rg_edit_box1::ra_edit_box1_DiaoJieNiuBeiAnXia (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_26.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT rg_edit_box1::rg_DiaoJieNiuBeiAnXia (INT rg_BeiChanJiDiaoJieAnNiu)
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_26.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber, INT rg_BeiChanJiDiaoJieAnNiu))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber, rg_BeiChanJiDiaoJieAnNiu);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

CVolString rg_edit_box1::rg_NeiRong12 ()
{
    return (rg_BiaoTi15 ());
}

void rg_edit_box1::rg_NeiRong13 (CVolString& rg_SuoYuSheZhiDeNeiRong2)
{
    rg_BiaoTi16 (rg_SuoYuSheZhiDeNeiRong2);
}

rg_timer::rg_timer ()
{
    _VolObjectInitMembers ();
}

void rg_timer::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

rg_timer::~rg_timer ()
{
    OnBeforeObjectCleanup ();
    _OnCleanupExtra ();
}
void rg_timer::_OnInitExtra ()
{
    CMfcWndObject* pMfcWndObject = new CMfcWndObject (new CVWnd_Timer (), FALSE);
    pMfcWndObject->m_dwAttrInitialStyle = (pMfcWndObject->m_dwAttrInitialStyle & ~(0)) | 0;
    pMfcWndObject->m_dwAttrInitialExStyle = (pMfcWndObject->m_dwAttrInitialExStyle & ~(0)) | 0;
    TakeOverNewRefObject (pMfcWndObject);
    _OnInitControl ();
}
BOOL rg_timer::CreateMfcControl (CVolNativeWndCreateParam* pCreateParam)
{
    ASSERT (pCreateParam != NULL);
    CVWnd_Timer* pWnd = (CVWnd_Timer*)GetMfcWndPtr ();
    ASSERT (pWnd != NULL);
    pWnd->m_nGroupNumber = pCreateParam->m_nGroupNumber;
    if (pWnd->m_hWnd == NULL)
    {
        OnBeforeNativeWndCreate (pCreateParam);
        OnCalcNativeWndPos (pCreateParam);
        if (pWnd->CreateControl (pCreateParam))
        {
            if (pWnd->m_hWnd != NULL)
                OnAfterNativeWndCreate (pWnd, pCreateParam);
            return TRUE;
        }
    }
    return FALSE;
}
void rg_timer::AttachEventListener ()
{
    ((CVWnd_Timer*)GetMfcWndPtr ())->m_pEventListener = (ITimerEventListener*)this;
}
void rg_timer::DetachEventListener ()
{
    CVWnd_Timer* pwndControl = (CVWnd_Timer*)GetMfcWndPtr ();
    if (pwndControl->m_pEventListener == (ITimerEventListener*)this)
        pwndControl->m_pEventListener = NULL;
}
BOOL_P rg_timer::IsEventAttached ()
{
    return (((CVWnd_Timer*)GetMfcWndPtr ())->m_pEventListener != NULL);
}

void rg_timer::ra_timer_ZhouJiShiJian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber)
{
    rw_27.SetReceiver (fnReceiver, pEventReceiver, nTagNumber);
    _OnAfterEventAttached (fnReceiver != NULL);
}

INT rg_timer::rg_ZhouJiShiJian ()
{
    VOID_FUNC fnReceiver;
    INT nTagNumber, nEventResult = 0;
    CVolEventObjectPointer* pEventReceiver = rw_27.BeginSendEvent (&fnReceiver, &nTagNumber);
    if (pEventReceiver != NULL)
    {
        nEventResult = ((INT (*) (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber))fnReceiver) (pEventReceiver->GetVolObject (), this, nTagNumber);
        CVolEventReceiver::sEndSendEvent (pEventReceiver);
    }
    return nEventResult;
}

void rg_timer::rg_ShiZhongZhouJi1 (INT rg_SuoYuSheZhiDeShiZhongZhouJi)
{
    ((CVWnd_Timer*)GetMfcWndPtr ())->VolResetTimer (rg_SuoYuSheZhiDeShiZhongZhouJi);
}

}
