
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

namespace rg_volcano_app
{

static void _sOnClassesStaticInit ()
{
}

BOOL rg_startup_class::_IsSelfEqual (const rg_startup_class& objCompare) const
{
    if (rg_ZhuChuangKouDuiXiang != objCompare.rg_ZhuChuangKouDuiXiang)  return FALSE;
    return TRUE;
}

void rg_startup_class::_CopySelfFrom (const rg_startup_class& objCopyFrom)
{
    rg_ZhuChuangKouDuiXiang = objCopyFrom.rg_ZhuChuangKouDuiXiang;
}

void rg_startup_class::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    rg_ZhuChuangKouDuiXiang.LoadFromStream (stream);
}

void rg_startup_class::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    rg_ZhuChuangKouDuiXiang.SaveIntoStream (stream);
}

INT rg_startup_class::rg_startup_method ()
{
    _sOnClassesStaticInit ();
    rg_MCPMingLingFuWuQi::rg_JiaZaiMCPPeiZhi ();
    if (rg_MCPMingLingFuWuQi::rg_VIPShouQuanMa == _T (""))
    {
        rg_MCPMingLingFuWuQi::rg_VIPShouQuanMa = _T ("xsmzas1");
    }
    rg_LiuLanQi_VIP::rg_FBrowserVIPZhuCe::rg_VIPZhuCe_ZhiShouQuanMa (rg_MCPMingLingFuWuQi::rg_VIPShouQuanMa);
    rg_FBrowser_ShuJuLeiXing::rg_FBrowser_ChuShiHuaPeiZhi rg_SheZhi;
    rg_SheZhi.rg_MoShaXiang = TRUE;
    rg_SheZhi.rg_HuanCunMuLu = rg_volcano_base::rg_HuanJingCunQuLei::rg_QuYunHangMuLu () + _T ("\\CacheData\\GlobalData");
    rg_SheZhi.rg_BenDeHuaYuYan = _T ("zh-CN");
    rg_SheZhi.rg_JieShouYuYanQingChan = _T ("zh-CN,zh,en");
    rg_SheZhi.rg_QiYongJiTongXiaoXiXunHuan = TRUE;
    rg_SheZhi.rg_BaoLiuSession = TRUE;
    rg_SheZhi.rg_RiZhiMuLu = rg_volcano_base::rg_HuanJingCunQuLei::rg_QuYunHangMuLu () + _T ("\\log.txt");
    rg_SheZhi.rg_RiZhiMoShi = 6;
    rg_SheZhi.rg_ZhiHangJinCheng = rg_volcano_base::rg_HuanJingCunQuLei::rg_QuYunHangMuLu () + _T ("\\") + rg_volcano_base::rg_HuanJingCunQuLei::rg_QuZhiHangWenJianMing ();
    rg_FBrowser_LiuLanQi::rg_class_FBrowser_shjzhnzhzh rg_ChuShiHuaShiJian;
    rg_ChuShiHuaShiJian.m_class = static_cast<rg_class_MCP_ChuShiHuaShiJian*>(new rg_class_MCP_ChuShiHuaShiJian());
    if (rg_FBrowser_LiuLanQi::rg_FBrowserChuShiHuaKongZhi::rg_FBrowser_ChuShiHua (rg_SheZhi, rg_ChuShiHuaShiJian) == FALSE)
    {
        _DEBUG_STATMENT (DebugTrace (FALSE, 0, 0, _T ("S"), _T ("[AI浏览器] FBrowser 初始化失败")));
        return (0);
    }
    rg_ZhuChuangKouDuiXiang.CreateMainVolWindow (_VOL_INT_MIN, _VOL_INT_MIN, _VOL_INT_MIN, _VOL_INT_MIN, _NULL_VOL_OBJECT (rg_volcano_MFCJieMian_base::rg_CaiChanLei).GetVolMenuCheckNull ());
    if (rg_MCPStdioQiao::rg_ShiFouWeiStdioMoShi ())
    {
        rg_ZhuChuangKouDuiXiang.rg_XianShiYinCangChuangKou (TRUE);
    }
    return (1);
}

BOOL rg_class_MCP_ChuShiHuaShiJian::rg_JiLuYingYongJianKongShiJian (CVolString& rg_ShiJianLeiXing, CVolString& rg_ShuJuJSON)
{
    if (rg_MCPMingLingFuWuQi::rg_ShiFouJianKongYingYongShiJian)
    {
        rg_MCPMingLingFuWuQi::rg_JiLuYingYongShiJian (rg_ShiJianLeiXing, rg_ShuJuJSON);
    }
    return (rg_MCPMingLingFuWuQi::rg_ShiFouJianKongYingYongShiJian);
}

void rg_class_MCP_ChuShiHuaShiJian::rg_LiuLanQi_ChuShiHuaWanBi ()
{
    rg_MCPMingLingFuWuQi::rg_QiDongMCPFuWuQi ();
    CVolString rg_DuanKouWenBen;
    rg_DuanKouWenBen = CVolString (rg_MCPMingLingFuWuQi::rg_FuWuQiDuanKou);
    CVolString rg_BangDingDeZhi;
    rg_BangDingDeZhi = rg_MCPMingLingFuWuQi::rg_FuWuQiBangDingDeZhi;
    rg_volcano_base::rg_HuanJingCunQuLei::rg_XieHuanJingBianLiang (_CT2 (_T ("AI_BROWSER_MCP_URL")), _CT2 (_T ("ws://")) + rg_BangDingDeZhi + _T (":") + rg_DuanKouWenBen);
    rg_volcano_base::rg_HuanJingCunQuLei::rg_XieHuanJingBianLiang (_CT2 (_T ("AI_BROWSER_MCP_PORT")), rg_DuanKouWenBen);
    rg_volcano_base::rg_HuanJingCunQuLei::rg_XieHuanJingBianLiang (_CT2 (_T ("AI_BROWSER_MCP_HEALTH")), _CT2 (_T ("http://")) + rg_BangDingDeZhi + _T (":") + rg_DuanKouWenBen + _T ("/health"));
    rg_volcano_base::rg_HuanJingCunQuLei::rg_XieHuanJingBianLiang (_CT2 (_T ("AI_BROWSER_MCP_HTTP_POST")), _CT2 (_T ("http://")) + rg_BangDingDeZhi + _T (":") + rg_DuanKouWenBen + _T ("/mcp"));
    _DEBUG_STATMENT (DebugTrace (FALSE, 0, 0, _T ("S"), _T ("[AI浏览器] FBrowser 初始化完毕, MCP 服务已就绪")));
    if (rg_MCPStdioQiao::rg_ShiFouWeiStdioMoShi ())
    {
        _DEBUG_STATMENT (DebugTrace (FALSE, 0, 0, _T ("S"), _T ("[AI浏览器] 检测到 Stdio MCP 模式, 启动 stdin 并行服务")));
        rg_MCPStdioQiao::rg_QiDongBingHangStdioFuWu ();
    }
}

void rg_class_MCP_ChuShiHuaShiJian::rg_ZhiHangGuanBiWanBi (rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouJieShuChengXu)
{
    _DEBUG_STATMENT (DebugTrace (FALSE, 0, 0, _T ("S"), _T ("[AI浏览器] FBrowser 资源已释放, 结束进程")));
    rg_ShiFouJieShuChengXu.rg_value14 = TRUE;
}

void rg_class_MCP_ChuShiHuaShiJian::rg_XuanRan_JiJiangBuHuoYiChang (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia, rg_FBrowser_LiuLanQi::FBroV8Context& rg_V8HuanJing, rg_FBrowser_LiuLanQi::FBroV8Exception& rg_V8YiChang, rg_FBrowser_LiuLanQi::FBroV8StackTrace& rg_V8DuiZhanZongJi)
{
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONDuiXiangLei rg_ShuJu;
    rg_ShuJu.data().CreateFromText(_CT2 (_T ("{}")));
    rg_ShuJu.rg_JiaRuZhengShuChengYuan (_CT2 (_T ("browser_id")), rg_LiuLanQi.rg_QuID ());
    rg_ShuJu.rg_JiaRuWenBenChengYuan (_CT2 (_T ("url")), rg_KuangJia.rg_QuDeZhi ());
    if (rg_V8YiChang.rg_ShiFouWeiKong144 () == FALSE)
    {
        rg_ShuJu.rg_JiaRuWenBenChengYuan (_CT2 (_T ("message")), rg_V8YiChang.rg_QuXiaoXi ());
    }
    rg_JiLuYingYongJianKongShiJian (_CT2 (_T ("app_v8_exception")), rg_ShuJu.data().ToString(YYJSON_WRITE_NOFLAG));
}

void rg_class_MCP_ChuShiHuaShiJian::rg_XuanRan_JiaoDianJieDianGaiBian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi1, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia1, rg_FBrowser_LiuLanQi::FBroDOMNode& rg_DOMJieDian)
{
    if (rg_MCPMingLingFuWuQi::rg_ShiFouJianKongYingYongShiJian == FALSE)
    {
        return;
    }
    INT64 rg_DangQianHaoMiao;
    static INT64 rg_ShangCiHaoMiao = 0;
    rg_DangQianHaoMiao = rg_volcano_base::rg_ChangYongGongNengLei::rg_QuQiDongShiJian ();
    if (rg_DangQianHaoMiao - rg_ShangCiHaoMiao < 300)
    {
        return;
    }
    rg_ShangCiHaoMiao = rg_DangQianHaoMiao;
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONDuiXiangLei rg_ShuJu1;
    rg_ShuJu1.data().CreateFromText(_CT2 (_T ("{}")));
    rg_ShuJu1.rg_JiaRuZhengShuChengYuan (_CT2 (_T ("browser_id")), rg_LiuLanQi1.rg_QuID ());
    rg_ShuJu1.rg_JiaRuWenBenChengYuan (_CT2 (_T ("url")), rg_KuangJia1.rg_QuDeZhi ());
    if (rg_DOMJieDian.rg_ShiFouWeiKong147 () == FALSE)
    {
        rg_ShuJu1.rg_JiaRuWenBenChengYuan (_CT2 (_T ("tag")), rg_DOMJieDian.rg_QuBiaoQianMing ());
    }
    rg_JiLuYingYongJianKongShiJian (_CT2 (_T ("app_dom_focus_changed")), rg_ShuJu1.data().ToString(YYJSON_WRITE_NOFLAG));
}

void rg_class_MCP_ChuShiHuaShiJian::rg_XuanRan_JiJiangShiFangV8HuanJing (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi2, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia2, rg_FBrowser_LiuLanQi::FBroV8Context& rg_V8HuanJing1)
{
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONDuiXiangLei rg_ShuJu2;
    rg_ShuJu2.data().CreateFromText(_CT2 (_T ("{}")));
    rg_ShuJu2.rg_JiaRuZhengShuChengYuan (_CT2 (_T ("browser_id")), rg_LiuLanQi2.rg_QuID ());
    rg_ShuJu2.rg_JiaRuWenBenChengYuan (_CT2 (_T ("url")), rg_KuangJia2.rg_QuDeZhi ());
    rg_JiLuYingYongJianKongShiJian (_CT2 (_T ("app_v8_released")), rg_ShuJu2.data().ToString(YYJSON_WRITE_NOFLAG));
}

void rg_class_MCP_ChuShiHuaShiJian::rg_XuanRan_ZaiRuCuoWu (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi3, rg_FBrowser_LiuLanQi::FBroFrame& rg_KuangJia3, INT rg_CuoWuDaiMa, CVolString& rg_CuoWuWenBen, CVolString& rg_ShiBaiDeZhi)
{
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONDuiXiangLei rg_ShuJu3;
    rg_ShuJu3.data().CreateFromText(_CT2 (_T ("{}")));
    rg_ShuJu3.rg_JiaRuZhengShuChengYuan (_CT2 (_T ("browser_id")), rg_LiuLanQi3.rg_QuID ());
    rg_ShuJu3.rg_JiaRuZhengShuChengYuan (_CT2 (_T ("error_code")), rg_CuoWuDaiMa);
    rg_ShuJu3.rg_JiaRuWenBenChengYuan (_CT2 (_T ("error_text")), rg_CuoWuWenBen);
    rg_ShuJu3.rg_JiaRuWenBenChengYuan (_CT2 (_T ("failed_url")), rg_ShiBaiDeZhi);
    rg_JiLuYingYongJianKongShiJian (_CT2 (_T ("app_render_load_error")), rg_ShuJu3.data().ToString(YYJSON_WRITE_NOFLAG));
}

void rg_class_MCP_ChuShiHuaShiJian::rg_XuanRan_LiuLanQiChuangJian (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi4, rg_FBrowser_value::FBroDictionaryValue& rg_EWaiXinXi)
{
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONDuiXiangLei rg_ShuJu4;
    rg_ShuJu4.data().CreateFromText(_CT2 (_T ("{}")));
    rg_ShuJu4.rg_JiaRuZhengShuChengYuan (_CT2 (_T ("browser_id")), rg_LiuLanQi4.rg_QuID ());
    rg_JiLuYingYongJianKongShiJian (_CT2 (_T ("app_render_browser_created")), rg_ShuJu4.data().ToString(YYJSON_WRITE_NOFLAG));
}

void rg_class_MCP_ChuShiHuaShiJian::rg_XuanRan_JiJiangXiaoHuiLiuLanQi (rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi& rg_LiuLanQi5)
{
    rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONDuiXiangLei rg_ShuJu5;
    rg_ShuJu5.data().CreateFromText(_CT2 (_T ("{}")));
    rg_ShuJu5.rg_JiaRuZhengShuChengYuan (_CT2 (_T ("browser_id")), rg_LiuLanQi5.rg_QuID ());
    rg_JiLuYingYongJianKongShiJian (_CT2 (_T ("app_render_browser_destroyed")), rg_ShuJu5.data().ToString(YYJSON_WRITE_NOFLAG));
}

rg_AILiuLanQiZhuChuangKou::rg_AILiuLanQiZhuChuangKou ()
{
    _VolObjectInitMembers ();
}

void rg_AILiuLanQiZhuChuangKou::_VolObjectInitMembers ()
{
    rw_46 = new CVolEventObjectPointer (this);
    rg_DeZhiLanYouJiaoDian = FALSE;
    rg_YunXuZhenGuanBi = FALSE;
    rg_MCPJiuXuYiTongZhi = FALSE;
    rg_ZhengZaiTuiChu = FALSE;
    _VOL_THIS.rg_BiaoTi16 (_CT2 (_T ("AI浏览器-MCP")));
    _VOL_THIS.rg_ZuiDaHuaAnNiu1 (TRUE);
    _VOL_THIS.rg_ZuiXiaoHuaAnNiu1 (TRUE);
    _VOL_THIS.rg_ChuangKouBianKuang1 (rg_volcano_MFCJieMian_base::rg_ChuangKouBianKuangLeiXing::rg_PuTongKeDiaoBianKuang);
}

BOOL rg_AILiuLanQiZhuChuangKou::_IsSelfEqual (const rg_AILiuLanQiZhuChuangKou& objCompare) const
{
    if (rg_HouTuiAnNiu != objCompare.rg_HouTuiAnNiu)  return FALSE;
    if (rg_QianJinAnNiu != objCompare.rg_QianJinAnNiu)  return FALSE;
    if (rg_ShuaXinAnNiu != objCompare.rg_ShuaXinAnNiu)  return FALSE;
    if (rg_DeZhiBianJiKuang != objCompare.rg_DeZhiBianJiKuang)  return FALSE;
    if (rg_FangWenAnNiu != objCompare.rg_FangWenAnNiu)  return FALSE;
    if (rg_MCPZhuangTaiBiaoQian != objCompare.rg_MCPZhuangTaiBiaoQian)  return FALSE;
    if (rg_ZhuangTaiShiZhong != objCompare.rg_ZhuangTaiShiZhong)  return FALSE;
    if (rg_TuoPanTuBiao != objCompare.rg_TuoPanTuBiao)  return FALSE;
    if (rg_DeZhiLanYouJiaoDian != objCompare.rg_DeZhiLanYouJiaoDian)  return FALSE;
    if (rg_YunXuZhenGuanBi != objCompare.rg_YunXuZhenGuanBi)  return FALSE;
    if (rg_MCPJiuXuYiTongZhi != objCompare.rg_MCPJiuXuYiTongZhi)  return FALSE;
    if (rg_ZhengZaiTuiChu != objCompare.rg_ZhengZaiTuiChu)  return FALSE;
    return TRUE;
}

void rg_AILiuLanQiZhuChuangKou::_CopySelfFrom (const rg_AILiuLanQiZhuChuangKou& objCopyFrom)
{
    rg_HouTuiAnNiu = objCopyFrom.rg_HouTuiAnNiu;
    rg_QianJinAnNiu = objCopyFrom.rg_QianJinAnNiu;
    rg_ShuaXinAnNiu = objCopyFrom.rg_ShuaXinAnNiu;
    rg_DeZhiBianJiKuang = objCopyFrom.rg_DeZhiBianJiKuang;
    rg_FangWenAnNiu = objCopyFrom.rg_FangWenAnNiu;
    rg_MCPZhuangTaiBiaoQian = objCopyFrom.rg_MCPZhuangTaiBiaoQian;
    rg_ZhuangTaiShiZhong = objCopyFrom.rg_ZhuangTaiShiZhong;
    rg_TuoPanTuBiao = objCopyFrom.rg_TuoPanTuBiao;
    rg_DeZhiLanYouJiaoDian = objCopyFrom.rg_DeZhiLanYouJiaoDian;
    rg_YunXuZhenGuanBi = objCopyFrom.rg_YunXuZhenGuanBi;
    rg_MCPJiuXuYiTongZhi = objCopyFrom.rg_MCPJiuXuYiTongZhi;
    rg_ZhengZaiTuiChu = objCopyFrom.rg_ZhengZaiTuiChu;
}

rg_AILiuLanQiZhuChuangKou::~rg_AILiuLanQiZhuChuangKou ()
{
    OnBeforeObjectCleanup ();
    rw_46->ReleasePointer ();
}

void rg_AILiuLanQiZhuChuangKou::OnWinContainerCreated ()
{
    BaseClass::OnWinContainerCreated ();
    _VolAttachWinEvents ();
    rg_HouTuiAnNiu.rg_BiaoTi16 (_CT2 (_T ("<")));
    rg_HouTuiAnNiu.CreateVolControl (this, _DPISIZE (4), _DPISIZE (4), _DPISIZE (36), _DPISIZE (28), 101, -1);
    rg_QianJinAnNiu.rg_BiaoTi16 (_CT2 (_T (">")));
    rg_QianJinAnNiu.CreateVolControl (this, _DPISIZE (44), _DPISIZE (4), _DPISIZE (36), _DPISIZE (28), 102, -1);
    rg_ShuaXinAnNiu.rg_BiaoTi16 (_CT2 (_T ("R")));
    rg_ShuaXinAnNiu.CreateVolControl (this, _DPISIZE (84), _DPISIZE (4), _DPISIZE (36), _DPISIZE (28), 103, -1);
    rg_DeZhiBianJiKuang.CreateVolControl (this, _DPISIZE (124), _DPISIZE (4), _DPISIZE (1020), _DPISIZE (28), 104, -1);
    rg_FangWenAnNiu.rg_BiaoTi16 (_CT2 (_T ("前往")));
    rg_FangWenAnNiu.CreateVolControl (this, _DPISIZE (1148), _DPISIZE (4), _DPISIZE (48), _DPISIZE (28), 105, -1);
    rg_MCPZhuangTaiBiaoQian.rg_BiaoTi16 (_CT2 (_T ("MCP: 启动中...")));
    rg_MCPZhuangTaiBiaoQian.CreateVolControl (this, _DPISIZE (4), _DPISIZE (768), _DPISIZE (1192), _DPISIZE (24), 106, -1);
    rg_ZhuangTaiShiZhong.rg_ShiZhongZhouJi1 (800);
    rg_ZhuangTaiShiZhong.CreateVolControl (this, _DPISIZE (0), _DPISIZE (0), _DPISIZE (1), _DPISIZE (1), 107, -1);
}

void rg_AILiuLanQiZhuChuangKou::_VolAttachWinEvents ()
{
    ra_ZuJianBuJuQi_ChuangJianWanBi ((VOID_FUNC)re_AILiuLanQiZhuChuangKou_AILiuLanQiZhuChuangKou_ChuangJianWanBi, rw_46, 0);
    ra_ZuJianBuJuQi_CheCunBeiGaiBian ((VOID_FUNC)re_AILiuLanQiZhuChuangKou_AILiuLanQiZhuChuangKou_CheCunBeiGaiBian, rw_46, 0);
    ra_ZuJianBuJuQi_WeiZhiBeiGaiBian ((VOID_FUNC)re_AILiuLanQiZhuChuangKou_AILiuLanQiZhuChuangKou_WeiZhiBeiGaiBian, rw_46, 0);
    ra_CVolWinForm_KeFouBeiGuanBi ((VOID_FUNC)re_AILiuLanQiZhuChuangKou_AILiuLanQiZhuChuangKou_KeFouBeiGuanBi, rw_46, 0);
    ra_CVolWinForm_TuoPanShiJian ((VOID_FUNC)re_AILiuLanQiZhuChuangKou_AILiuLanQiZhuChuangKou_TuoPanShiJian, rw_46, 0);
    ra_ZuJianBuJuQi_YiBeiXiaoHui ((VOID_FUNC)re_AILiuLanQiZhuChuangKou_AILiuLanQiZhuChuangKou_YiBeiXiaoHui, rw_46, 0);
    rg_HouTuiAnNiu.ra_AnNiuJiChuLei_clicked2 ((VOID_FUNC)re_AILiuLanQiZhuChuangKou_button_clicked, rw_46, 0);
    rg_QianJinAnNiu.ra_AnNiuJiChuLei_clicked2 ((VOID_FUNC)re_AILiuLanQiZhuChuangKou_button_clicked, rw_46, 0);
    rg_ShuaXinAnNiu.ra_AnNiuJiChuLei_clicked2 ((VOID_FUNC)re_AILiuLanQiZhuChuangKou_button_clicked, rw_46, 0);
    rg_DeZhiBianJiKuang.ra_CVolWinControl_HuoDeJiaoDian ((VOID_FUNC)re_AILiuLanQiZhuChuangKou_edit_box_HuoDeJiaoDian, rw_46, 0);
    rg_DeZhiBianJiKuang.ra_CVolWinControl_ShiQuJiaoDian ((VOID_FUNC)re_AILiuLanQiZhuChuangKou_edit_box_ShiQuJiaoDian, rw_46, 0);
    rg_DeZhiBianJiKuang.ra_CVolWinControl_AnXiaMouJian ((VOID_FUNC)re_AILiuLanQiZhuChuangKou_edit_box_AnXiaMouJian, rw_46, 0);
    rg_FangWenAnNiu.ra_AnNiuJiChuLei_clicked2 ((VOID_FUNC)re_AILiuLanQiZhuChuangKou_button_clicked, rw_46, 0);
    rg_ZhuangTaiShiZhong.ra_timer_ZhouJiShiJian ((VOID_FUNC)re_AILiuLanQiZhuChuangKou_timer_ZhouJiShiJian, rw_46, 0);
}

void rg_AILiuLanQiZhuChuangKou::LoadFromStream (CVolBaseInputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::LoadFromStream (stream);
    rg_HouTuiAnNiu.LoadFromStream (stream);
    rg_QianJinAnNiu.LoadFromStream (stream);
    rg_ShuaXinAnNiu.LoadFromStream (stream);
    rg_DeZhiBianJiKuang.LoadFromStream (stream);
    rg_FangWenAnNiu.LoadFromStream (stream);
    rg_MCPZhuangTaiBiaoQian.LoadFromStream (stream);
    rg_ZhuangTaiShiZhong.LoadFromStream (stream);
    rg_TuoPanTuBiao.LoadFromStream (stream);
    stream.ReadExact (&rg_DeZhiLanYouJiaoDian, sizeof (BOOL));
    stream.ReadExact (&rg_YunXuZhenGuanBi, sizeof (BOOL));
    stream.ReadExact (&rg_MCPJiuXuYiTongZhi, sizeof (BOOL));
    stream.ReadExact (&rg_ZhengZaiTuiChu, sizeof (BOOL));
}

void rg_AILiuLanQiZhuChuangKou::SaveIntoStream (CVolBaseOutputStream& stream)
{
    if (stream.IsFoundError ())  return;
    BaseClass::SaveIntoStream (stream);
    rg_HouTuiAnNiu.SaveIntoStream (stream);
    rg_QianJinAnNiu.SaveIntoStream (stream);
    rg_ShuaXinAnNiu.SaveIntoStream (stream);
    rg_DeZhiBianJiKuang.SaveIntoStream (stream);
    rg_FangWenAnNiu.SaveIntoStream (stream);
    rg_MCPZhuangTaiBiaoQian.SaveIntoStream (stream);
    rg_ZhuangTaiShiZhong.SaveIntoStream (stream);
    rg_TuoPanTuBiao.SaveIntoStream (stream);
    stream.write (&rg_DeZhiLanYouJiaoDian, sizeof (BOOL));
    stream.write (&rg_YunXuZhenGuanBi, sizeof (BOOL));
    stream.write (&rg_MCPJiuXuYiTongZhi, sizeof (BOOL));
    stream.write (&rg_ZhengZaiTuiChu, sizeof (BOOL));
}

void rg_AILiuLanQiZhuChuangKou::rg_XianShiYinCangChuangKou (BOOL rg_YinCang)
{
    rg_KeShi1 (rg_YinCang == FALSE);
}

INT rg_AILiuLanQiZhuChuangKou::rg_AILiuLanQiZhuChuangKou_ChuangJianWanBi (rg_AILiuLanQiZhuChuangKou& rg_LaiYuanDuiXiang, INT rg_BiaoJiZhi)
{
    rg_LiuLanQiRongQi::rg_DeZhiBianJiKuang1 = rg_DeZhiBianJiKuang;
    rg_LiuLanQiRongQi::rg_DeZhiLanYiBangDing = TRUE;
    rg_LiuLanQiRongQi::rg_ZuiXinDeZhi = _T ("about:blank");
    rg_DeZhiBianJiKuang.rg_NeiRong13 (_CT2 (_T ("")));
    rg_TuoPanTuBiao = rg_volcano_base::rg_TuBiaoDuiXiangLei ((HICON)g_objVolApp.LoadResImageFile (VRIT_ICON, (rg_volcano_base::rg_HuanJingCunQuLei::rg_QuYunHangMuLu () + _T ("\\") + rg_volcano_base::rg_HuanJingCunQuLei::rg_QuZhiHangWenJianMing ()).GetText ()), GOADT_DESTORY_ICON);
    if ((rg_TuoPanTuBiao.GetGDIHandle () == NULL) == FALSE)
    {
        rg_ZhiTuoPanTuBiaoDuiXiang (rg_TuoPanTuBiao, _CT2 (_T ("AI浏览器-MCP | ")) + rg_MCPMingLingFuWuQi::rg_QuMCP_WSDeZhi ());
    }
    rg_ChuangJianKanRuShiLiuLanQi ();
    rg_DiaoZhengBuJu ();
    rg_ShuaXinMCPZhuangTai ();
    rg_ZhuangTaiShiZhong.rg_ShiZhongZhouJi1 (800);
    return (0);
}

void rg_AILiuLanQiZhuChuangKou::rg_ChuangJianKanRuShiLiuLanQi ()
{
    if (rg_MCPMingLingFuWuQi::rg_MCPZhengZaiGuanBi)
    {
        return;
    }
    if (rg_FBrowser_LiuLanQi::rg_FBrowserFuZhuGongNeng::rg_FBrowser_LiuLanQi_QuShuLiang () > 0)
    {
        return;
    }
    rg_FBrowser_ShuJuLeiXing::rg_FBrowser_ChuangKouXinXi rg_ChuangKouXinXi;
    rg_FBrowser_ShuJuLeiXing::rg_FBrowser_LiuLanQiPeiZhi rg_LiuLanQiPeiZhi;
    INT rg_LiuLanQiDing;
    rg_LiuLanQiDing = 36;
    rg_ChuangKouXinXi.rg_FuChuangKouGouBing8 = (INT_P)_VOL_THIS.GetMfcWndPtr ()->m_hWnd;
    rg_ChuangKouXinXi.rg_HengZuoBiao1 = 0;
    rg_ChuangKouXinXi.rg_ZongZuoBiao1 = rg_LiuLanQiDing;
    rg_ChuangKouXinXi.rg_KuanDu7 = rg_QuYongHuOuKuanDu ();
    rg_ChuangKouXinXi.rg_GaoDu7 = rg_QuYongHuOuGaoDu () - 36 - 28;
    rg_FBrowser_LiuLanQi::rg_class_FBrowser_shjzhnzhzh rg_LiuLanQiShiJian;
    rg_LiuLanQiShiJian.m_class = static_cast<rg_class_MCP_LiuLanQiShiJian*>(new rg_class_MCP_LiuLanQiShiJian());
    rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi::rg_FBrowser_ChuangJianLiuLanQi (_CT2 (_T ("about:blank")), rg_ChuangKouXinXi, rg_LiuLanQiPeiZhi, _NULL_VOL_OBJECT (rg_FBrowser_LiuLanQi::FBroRequestContext), _NULL_VOL_OBJECT (rg_FBrowser_value::FBroDictionaryValue), rg_LiuLanQiShiJian, _NULL_VOL_OBJECT (rg_FBrowser_ShuJuLeiXing::rg_FBrowser_JinYongShiJian), _CT2 (_T ("")));
    rg_LiuLanQiRongQi::rg_ZuiXinDeZhi = _T ("about:blank");
    rg_DeZhiBianJiKuang.rg_NeiRong13 (_CT2 (_T ("about:blank")));
}

void rg_AILiuLanQiZhuChuangKou::rg_HuiFuKanRuShiBuJu ()
{
    rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi rg_browser;
    rg_browser = rg_QuZhuLiuLanQiShiLi ();
    if (rg_browser.rg_ShiFouWeiKong127 () == FALSE && rg_browser.rg_ShiFouYiGuanBi () == FALSE)
    {
        rg_browser.rg_ZhiZiDongDiaoZhengDaXiao (FALSE, 0, 0, 0, 0);
        rg_browser.rg_XianShiYinCangChuangKou1 (TRUE);
        rg_browser.rg_YiDongChuangKou (0, 36, rg_QuYongHuOuKuanDu (), rg_QuYongHuOuGaoDu () - 36 - 28, TRUE);
    }
    rg_DiaoZhengBuJu ();
    rg_LiuLanQiRongQi::rg_HuiFuHuanYingYe ();
}

void rg_AILiuLanQiZhuChuangKou::rg_QueBaoZhuLiuLanQiJianKang ()
{
    if (rg_MCPMingLingFuWuQi::rg_MCPZhengZaiGuanBi)
    {
        return;
    }
    if (rg_LiuLanQiRongQi::rg_XuYaoChongJianLiuLanQi)
    {
        rg_LiuLanQiRongQi::rg_XuYaoChongJianLiuLanQi = FALSE;
        if (rg_FBrowser_LiuLanQi::rg_FBrowserFuZhuGongNeng::rg_FBrowser_LiuLanQi_QuShuLiang () == 0)
        {
            rg_ChuangJianKanRuShiLiuLanQi ();
            rg_DiaoZhengBuJu ();
        }
        else
        {
            rg_HuiFuKanRuShiBuJu ();
        }
        return;
    }
    rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi rg_browser1;
    rg_browser1 = rg_QuZhuLiuLanQiShiLi ();
    if (rg_browser1.rg_ShiFouWeiKong127 () || rg_browser1.rg_ShiFouYiGuanBi ())
    {
        if (rg_FBrowser_LiuLanQi::rg_FBrowserFuZhuGongNeng::rg_FBrowser_LiuLanQi_QuShuLiang () == 0)
        {
            rg_ChuangJianKanRuShiLiuLanQi ();
            rg_DiaoZhengBuJu ();
        }
        return;
    }
    if (rg_LiuLanQiRongQi::rg_XuYaoHuiFuBuJu)
    {
        rg_LiuLanQiRongQi::rg_XuYaoHuiFuBuJu = FALSE;
        rg_HuiFuKanRuShiBuJu ();
    }
}

rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi rg_AILiuLanQiZhuChuangKou::rg_QuZhuLiuLanQiShiLi ()
{
    rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi rg_browser2;
    rg_browser2 = rg_MCPMingLingFuWuQi::rg_QuZhuLiuLanQi ();
    return (rg_browser2);
}

void rg_AILiuLanQiZhuChuangKou::rg_DaoHangDaoDeZhiLan ()
{
    CVolString rg_ShuRuURL;
    rg_ShuRuURL = CVolString (rg_DeZhiBianJiKuang.rg_NeiRong12 ()).TrimAll ();
    if (rg_ShuRuURL == _T (""))
    {
        return;
    }
    rg_ShuRuURL = rg_MCPMingLingFuWuQi::rg_GuiFanHuaURL (rg_ShuRuURL, _CT2 (_T ("")));
    if (rg_MCPMingLingFuWuQi::rg_YanZhengURLAnQuan (rg_ShuRuURL) == FALSE)
    {
        _DEBUG_STATMENT (DebugTrace (FALSE, 0, 0, _T ("SS"), _T ("[AI浏览器] 拒绝不安全 URL:"), rg_ShuRuURL.GetText ()));
        return;
    }
    rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi rg_browser3;
    rg_browser3 = rg_QuZhuLiuLanQiShiLi ();
    if (rg_browser3.rg_ShiFouWeiKong127 () == FALSE && rg_browser3.rg_ShiFouYiGuanBi () == FALSE)
    {
        rg_FBrowser_LiuLanQi::FBroFrame rg_frame;
        rg_frame = rg_MCPMingLingFuWuQi::rg_QuAnQuanZhuKuangJia (rg_browser3);
        if (rg_frame.rg_ShiFouYouXiao ())
        {
            rg_frame.rg_ZaiRuDeZhi (rg_ShuRuURL);
            rg_LiuLanQiRongQi::rg_ZuiXinDeZhi = rg_ShuRuURL;
        }
    }
}

void rg_AILiuLanQiZhuChuangKou::rg_DiaoZhengBuJu ()
{
    INT rg_KeHuKuan;
    INT rg_KeHuGao;
    rg_KeHuKuan = rg_QuYongHuOuKuanDu ();
    rg_KeHuGao = rg_QuYongHuOuGaoDu ();
    INT rg_DeZhiKuan;
    rg_DeZhiKuan = rg_KeHuKuan - 124 - 52;
    if (rg_DeZhiKuan < 100)
    {
        rg_DeZhiKuan = 100;
    }
    rg_DeZhiBianJiKuang.rg_ZuoBian5 (124);
    rg_DeZhiBianJiKuang.rg_DingBian7 (4);
    rg_DeZhiBianJiKuang.rg_KuanDu33 (rg_DeZhiKuan);
    rg_DeZhiBianJiKuang.rg_GaoDu32 (28);
    rg_FangWenAnNiu.rg_ZuoBian5 (rg_KeHuKuan - 52);
    rg_FangWenAnNiu.rg_DingBian7 (4);
    rg_FangWenAnNiu.rg_KuanDu33 (48);
    rg_FangWenAnNiu.rg_GaoDu32 (28);
    rg_MCPZhuangTaiBiaoQian.rg_ZuoBian5 (4);
    rg_MCPZhuangTaiBiaoQian.rg_DingBian7 (rg_KeHuGao - 28);
    rg_MCPZhuangTaiBiaoQian.rg_KuanDu33 (rg_KeHuKuan - 8);
    rg_MCPZhuangTaiBiaoQian.rg_GaoDu32 (28 - 4);
    rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi rg_browser4;
    rg_browser4 = rg_QuZhuLiuLanQiShiLi ();
    if (rg_browser4.rg_ShiFouWeiKong127 () == FALSE && rg_browser4.rg_ShiFouYiGuanBi () == FALSE)
    {
        rg_browser4.rg_YiDongChuangKou (0, 36, rg_KeHuKuan, rg_KeHuGao - 36 - 28, FALSE);
    }
}

void rg_AILiuLanQiZhuChuangKou::rg_TongBuDeZhiLan ()
{
    if (rg_DeZhiLanYouJiaoDian)
    {
        return;
    }
    if (rg_LiuLanQiRongQi::rg_ZuiXinDeZhi != _T ("") && rg_LiuLanQiRongQi::rg_ZuiXinDeZhi != rg_DeZhiBianJiKuang.rg_NeiRong12 ())
    {
        rg_DeZhiBianJiKuang.rg_NeiRong13 (rg_LiuLanQiRongQi::rg_ZuiXinDeZhi);
    }
}

void rg_AILiuLanQiZhuChuangKou::rg_ShuaXinMCPZhuangTai ()
{
    CVolString rg_ZhuangTaiWenBen;
    if (rg_LiuLanQiRongQi::rg_MCPFuWuYiJiuXu)
    {
        rg_ZhuangTaiWenBen = _CT2 (_T ("MCP就绪 | POST ")) + rg_MCPMingLingFuWuQi::rg_QuMCP_HTTPDeZhi () + _T ("/mcp");
        rg_ZhuangTaiWenBen = rg_ZhuangTaiWenBen + _T (" | WS ") + rg_MCPMingLingFuWuQi::rg_QuMCP_WSDeZhi ();
    }
    else
    {
        rg_ZhuangTaiWenBen = _T ("MCP: 启动中...");
    }
    rg_ZhuangTaiWenBen = rg_ZhuangTaiWenBen + _T (" | 浏览器 ") + CVolString (rg_FBrowser_LiuLanQi::rg_FBrowserFuZhuGongNeng::rg_FBrowser_LiuLanQi_QuShuLiang ());
    rg_ZhuangTaiWenBen = rg_ZhuangTaiWenBen + _T (" | v") + rg_MCPMingLingFuWuQi::rg_MCP_BanBenHao;
    rg_MCPZhuangTaiBiaoQian.rg_BiaoTi16 (rg_ZhuangTaiWenBen);
    if (rg_LiuLanQiRongQi::rg_MCPFuWuYiJiuXu && rg_MCPJiuXuYiTongZhi == FALSE)
    {
        rg_MCPJiuXuYiTongZhi = TRUE;
        ::ShowTrayBalloonTip (_VOL_THIS.GetMfcWndHandle (), _CT2 (_T ("AI浏览器 MCP 已就绪")).GetText (), (_CT2 (_T ("POST ")) + rg_MCPMingLingFuWuQi::rg_QuMCP_HTTPDeZhi () + _T ("/mcp") + _T ("\r\n桥接: node mcp_bridge.js --check") + _T ("\r\n全量: node run_all_tests.js --quick")).GetText (), 0, 15);
    }
}

INT rg_AILiuLanQiZhuChuangKou::rg_AILiuLanQiZhuChuangKou_CheCunBeiGaiBian (rg_AILiuLanQiZhuChuangKou& rg_LaiYuanDuiXiang1, INT rg_BiaoJiZhi1)
{
    rg_DiaoZhengBuJu ();
    return (0);
}

INT rg_AILiuLanQiZhuChuangKou::rg_AILiuLanQiZhuChuangKou_WeiZhiBeiGaiBian (rg_AILiuLanQiZhuChuangKou& rg_LaiYuanDuiXiang2, INT rg_BiaoJiZhi2)
{
    rg_DiaoZhengBuJu ();
    return (0);
}

INT rg_AILiuLanQiZhuChuangKou::rg_button_clicked (rg_volcano_MFCJieMian_base::rg_button1& rg_LaiYuanDuiXiang3, INT rg_BiaoJiZhi3)
{
    rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi rg_browser5;
    rg_browser5 = rg_QuZhuLiuLanQiShiLi ();
    if (rg_LaiYuanDuiXiang3 == rg_HouTuiAnNiu)
    {
        if (rg_browser5.rg_ShiFouWeiKong127 () == FALSE && rg_browser5.rg_KeFouHouTui ())
        {
            rg_browser5.rg_HouTui ();
        }
    }
    else if (rg_LaiYuanDuiXiang3 == rg_QianJinAnNiu)
    {
        if (rg_browser5.rg_ShiFouWeiKong127 () == FALSE && rg_browser5.rg_KeFouQianJin ())
        {
            rg_browser5.rg_QianJin ();
        }
    }
    else if (rg_LaiYuanDuiXiang3 == rg_ShuaXinAnNiu)
    {
        if (rg_browser5.rg_ShiFouWeiKong127 () == FALSE)
        {
            rg_browser5.rg_ChongXinZaiRu ();
        }
    }
    else if (rg_LaiYuanDuiXiang3 == rg_FangWenAnNiu)
    {
        rg_DaoHangDaoDeZhiLan ();
    }
    return (0);
}

INT rg_AILiuLanQiZhuChuangKou::rg_edit_box_HuoDeJiaoDian (rg_volcano_MFCJieMian_base::rg_edit_box1& rg_LaiYuanDuiXiang4, INT rg_BiaoJiZhi4)
{
    if (rg_LaiYuanDuiXiang4 == rg_DeZhiBianJiKuang)
    {
        rg_DeZhiLanYouJiaoDian = TRUE;
    }
    return (0);
}

INT rg_AILiuLanQiZhuChuangKou::rg_edit_box_ShiQuJiaoDian (rg_volcano_MFCJieMian_base::rg_edit_box1& rg_LaiYuanDuiXiang5, INT rg_BiaoJiZhi5)
{
    if (rg_LaiYuanDuiXiang5 == rg_DeZhiBianJiKuang)
    {
        rg_DeZhiLanYouJiaoDian = FALSE;
        rg_TongBuDeZhiLan ();
    }
    return (0);
}

INT rg_AILiuLanQiZhuChuangKou::rg_edit_box_AnXiaMouJian (rg_volcano_MFCJieMian_base::rg_edit_box1& rg_LaiYuanDuiXiang6, INT rg_BiaoJiZhi6, INT rg_JianDaiMa, INT rg_FuZhuJianZhuangTai)
{
    if (rg_LaiYuanDuiXiang6 == rg_DeZhiBianJiKuang && rg_JianDaiMa == KYV_ENTER)
    {
        rg_DaoHangDaoDeZhiLan ();
    }
    return (0);
}

INT rg_AILiuLanQiZhuChuangKou::rg_timer_ZhouJiShiJian (rg_volcano_MFCJieMian_base::rg_timer& rg_LaiYuanDuiXiang7, INT rg_BiaoJiZhi7)
{
    if (rg_LaiYuanDuiXiang7 == rg_ZhuangTaiShiZhong)
    {
        rg_QueBaoZhuLiuLanQiJianKang ();
        rg_TongBuDeZhiLan ();
        rg_ShuaXinMCPZhuangTai ();
    }
    return (0);
}

void rg_AILiuLanQiZhuChuangKou::rg_TuiChuYingYong ()
{
    if (rg_ZhengZaiTuiChu)
    {
        return;
    }
    rg_ZhengZaiTuiChu = TRUE;
    rg_YunXuZhenGuanBi = TRUE;
    rg_ZhuangTaiShiZhong.rg_ShiZhongZhouJi1 (0);
    rg_MCPMingLingFuWuQi::rg_GuanBiMCPFuWuQi ();
    rg_FBrowser_LiuLanQi::rg_FBrowserChuShiHuaKongZhi::rg_FBrowser_GuanBi (TRUE);
}

INT rg_AILiuLanQiZhuChuangKou::rg_AILiuLanQiZhuChuangKou_KeFouBeiGuanBi (rg_AILiuLanQiZhuChuangKou& rg_LaiYuanDuiXiang8, INT rg_BiaoJiZhi8)
{
    if (rg_YunXuZhenGuanBi)
    {
        return (0);
    }
    rg_KeShi1 (FALSE);
    return (1);
}

INT rg_AILiuLanQiZhuChuangKou::rg_AILiuLanQiZhuChuangKou_TuoPanShiJian (rg_AILiuLanQiZhuChuangKou& rg_LaiYuanDuiXiang9, INT rg_BiaoJiZhi9, INT rg_CaoZuoLeiXing)
{
    if (rg_CaoZuoLeiXing == 1 || rg_CaoZuoLeiXing == 2)
    {
        rg_KeShi1 (TRUE);
        rg_ZhiWeiQianTaiChuangKou ();
    }
    else if (rg_CaoZuoLeiXing == 3)
    {
        if (rg_XunWenXinXiKuang (_CT2 (_T ("确定要退出 AI浏览器 并停止 MCP 服务吗？")), _CT2 (_T ("退出确认"))))
        {
            rg_TuiChuYingYong ();
        }
    }
    return (0);
}

INT rg_AILiuLanQiZhuChuangKou::rg_AILiuLanQiZhuChuangKou_YiBeiXiaoHui (rg_AILiuLanQiZhuChuangKou& rg_LaiYuanDuiXiang10, INT rg_BiaoJiZhi10)
{
    rg_ZhuangTaiShiZhong.rg_ShiZhongZhouJi1 (0);
    if (rg_ZhengZaiTuiChu == FALSE)
    {
        rg_MCPMingLingFuWuQi::rg_GuanBiMCPFuWuQi ();
        rg_FBrowser_LiuLanQi::rg_FBrowserChuShiHuaKongZhi::rg_FBrowser_GuanBi (TRUE);
    }
    return (0);
}

}
