
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

namespace rg_volcano_app
{

CVolString CALLBACK rg_MCP_JiTongFenPa::rg_FenLeiFenPa_JiTongCaoZuo (CVolString& rg_MingLingID26, CVolString& rg_FangFaMing10, rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONZhiDouDuiXiangLei& rg_CanShuJSON18)
{
    if (rg_FangFaMing10 == _T ("browser.create_tab") || rg_FangFaMing10 == _T ("browser_create_tab"))
    {
        return (rg_MCPMingLingFuWuQi::rg_MingLingShiBai (rg_MingLingID26, _CT2 (_T ("⛔ 远程创建标签页已禁用 | 浏览器由GUI自动管理"))));
    }
    else if (rg_FangFaMing10 == _T ("browser.task_runner_post") || rg_FangFaMing10 == _T ("browser_task_runner_post"))
    {
        INT rg_threadID;
        rg_threadID = rg_MCPMingLingFuWuQi::rg_yyjsonQuZhengShu (rg_CanShuJSON18, _CT2 (_T ("thread_id")));
        if (rg_threadID == 0)
        {
            rg_threadID = 0;
        }
        CVolString rg_RenWuDaiMa;
        rg_RenWuDaiMa = rg_MCPMingLingFuWuQi::rg_yyjsonQuWenBen (rg_CanShuJSON18, _CT2 (_T ("code")));
        CVolString rg_YiBuRenWuID2;
        rg_YiBuRenWuID2 = rg_MCPMingLingFuWuQi::rg_ShengChengYiBuRenWuID ();
        rg_FBrowser_LiuLanQi::rg_class_FBrowser_shjzhnzhzh rg_RenWuHuiDiao;
        rg_RenWuHuiDiao.m_class = static_cast<rg_class_MCP_RenWuHuiDiao*>(new rg_class_MCP_RenWuHuiDiao());
        (*static_cast<rg_class_MCP_RenWuHuiDiao *>(rg_RenWuHuiDiao.m_class.get())).rg_RenWuID5 = rg_YiBuRenWuID2;
        (*static_cast<rg_class_MCP_RenWuHuiDiao *>(rg_RenWuHuiDiao.m_class.get())).rg_ZhiHangDaiMa = rg_RenWuDaiMa;
        rg_FBrowser_LiuLanQi::rg_class_FBrowser_rwyhq::rg_FBrowser_RenWuYunHangQi_TouDiRenWu (rg_threadID, rg_RenWuHuiDiao);
        return (rg_MCPMingLingFuWuQi::rg_MingLingChengGong_YiBu (rg_MingLingID26, rg_YiBuRenWuID2, _CT2 (_T ("任务已投递到线程")) + CVolString (rg_threadID) + _T (", 通过mcp_result查询执行结果"), 0));
    }
    else if (rg_FangFaMing10 == _T ("browser.send_message") || rg_FangFaMing10 == _T ("browser_send_message"))
    {
        CVolString rg_msgName2;
        rg_msgName2 = rg_MCPMingLingFuWuQi::rg_yyjsonQuWenBen (rg_CanShuJSON18, _CT2 (_T ("name")));
        if (rg_msgName2 == _T (""))
        {
            return (rg_MCPMingLingFuWuQi::rg_MingLingShiBai (rg_MingLingID26, _CT2 (_T ("name ")) + rg_MCPMingLingFuWuQi::rg_CuoWu_QueShaoCanShu));
        }
        CVolString rg_msgData2;
        rg_msgData2 = rg_MCPMingLingFuWuQi::rg_yyjsonQuWenBen (rg_CanShuJSON18, _CT2 (_T ("data")));
        rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi rg_browser115;
        rg_browser115 = rg_MCPMingLingFuWuQi::rg_QuZhuLiuLanQi ();
        if (rg_browser115.rg_ShiFouWeiKong127 () == FALSE)
        {
            rg_browser115.rg_JinChengJianXiaoXi_FaSongShuJu_DaoZhuJinCheng (rg_msgName2, CVolMem (rg_msgData2));
            return (rg_MCPMingLingFuWuQi::rg_MingLingChengGong (rg_MingLingID26, _CT2 (_T ("已向主进程发送消息"))));
        }
        return (rg_MCPMingLingFuWuQi::rg_MingLingShiBai (rg_MingLingID26, rg_MCPMingLingFuWuQi::rg_CuoWu_MoLiuLanQi));
    }
    if (rg_FangFaMing10 == _T ("browser.get_global_cache_dir") || rg_FangFaMing10 == _T ("browser_get_global_cache_dir"))
    {
        CVolString rg_QuanJuHuanCunMuLu;
        rg_QuanJuHuanCunMuLu = rg_volcano_base::rg_HuanJingCunQuLei::rg_QuYunHangMuLu () + _T ("\\CacheData\\GlobalData");
        return (rg_MCPMingLingFuWuQi::rg_GouJianJianChanJSON (_CT2 (_T ("global_cache_dir")), rg_QuanJuHuanCunMuLu));
    }
    else if (rg_FangFaMing10 == _T ("browser.get_process_type") || rg_FangFaMing10 == _T ("browser_get_process_type"))
    {
        INT rg_JinChengLeiXingZhi;
        rg_JinChengLeiXingZhi = rg_FBrowser_LiuLanQi::rg_FBrowserChuShiHuaKongZhi::rg_FBrowser_JinCheng_QuDangQianJinChengLeiXing ();
        return (rg_MCPMingLingFuWuQi::rg_GouJianJianChanJSON (_CT2 (_T ("process_type")), CVolString (rg_JinChengLeiXingZhi)));
    }
    else if (rg_FangFaMing10 == _T ("browser.get_window_style") || rg_FangFaMing10 == _T ("browser_get_window_style"))
    {
        rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi rg_browser116;
        rg_browser116 = rg_MCPMingLingFuWuQi::rg_QuZhuLiuLanQi ();
        if (rg_browser116.rg_ShiFouWeiKong127 () == FALSE)
        {
            return (rg_MCPMingLingFuWuQi::rg_GouJianJianChanJSON (_CT2 (_T ("style")), CVolString (rg_browser116.rg_QuChuangKouShuXing (-16))));
        }
        return (rg_MCPMingLingFuWuQi::rg_MingLingShiBai (rg_MingLingID26, rg_MCPMingLingFuWuQi::rg_CuoWu_MoLiuLanQi));
    }
    else if (rg_FangFaMing10 == _T ("browser.set_window_style") || rg_FangFaMing10 == _T ("browser_set_window_style"))
    {
        rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi rg_browser117;
        rg_browser117 = rg_MCPMingLingFuWuQi::rg_QuZhuLiuLanQi ();
        if (rg_browser117.rg_ShiFouWeiKong127 () == FALSE)
        {
            rg_browser117.rg_ZhiChuangKouShuXing (rg_MCPMingLingFuWuQi::rg_yyjsonQuZhengShu (rg_CanShuJSON18, _CT2 (_T ("type"))), rg_MCPMingLingFuWuQi::rg_yyjsonQuZhengShu (rg_CanShuJSON18, _CT2 (_T ("style"))));
            return (rg_MCPMingLingFuWuQi::rg_XiangYing_XuYaoShuaXin (rg_MingLingID26, _CT2 (_T ("窗口风格已设置"))));
        }
        return (rg_MCPMingLingFuWuQi::rg_MingLingShiBai (rg_MingLingID26, rg_MCPMingLingFuWuQi::rg_CuoWu_MoLiuLanQi));
    }
    else if (rg_FangFaMing10 == _T ("browser.get_run_style") || rg_FangFaMing10 == _T ("browser_get_run_style"))
    {
        rg_FBrowser_LiuLanQi::rg_class_FBrowser_LiuLanQi rg_browser118;
        rg_browser118 = rg_MCPMingLingFuWuQi::rg_QuZhuLiuLanQi ();
        if (rg_browser118.rg_ShiFouWeiKong127 () == FALSE)
        {
            return (rg_MCPMingLingFuWuQi::rg_GouJianJianChanJSON (_CT2 (_T ("run_style")), _CT2 (_T ("暂不支持此方法工具"))));
        }
        return (rg_MCPMingLingFuWuQi::rg_MingLingShiBai (rg_MingLingID26, rg_MCPMingLingFuWuQi::rg_CuoWu_MoLiuLanQi));
    }
    else if (rg_FangFaMing10 == _T ("ping"))
    {
        rg_HuoShanShiChuang_JSONZhiChi::rg_YYJSONDuiXiangLei rg_pingJieGuo;
        rg_pingJieGuo.data().CreateFromText(_CT2 (_T ("{}")));
        rg_pingJieGuo.rg_JiaRuWenBenChengYuan (_CT2 (_T ("pong")), CVolString (rg_volcano_base::rg_ChangYongGongNengLei::rg_QuQiDongShiJian ()));
        rg_pingJieGuo.rg_JiaRuZhengShuChengYuan (_CT2 (_T ("browsers")), rg_FBrowser_LiuLanQi::rg_FBrowserFuZhuGongNeng::rg_FBrowser_LiuLanQi_QuShuLiang ());
        rg_pingJieGuo.rg_JiaRuWenBenChengYuan (_CT2 (_T ("version")), rg_MCPMingLingFuWuQi::rg_MCP_BanBenHao);
        return (rg_MCPMingLingFuWuQi::rg_MingLingChengGong_YuanShiJSON (rg_MingLingID26, rg_pingJieGuo.data().ToString(YYJSON_WRITE_NOFLAG), TRUE));
    }
    return (_T (""));
}

}
