
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_SHUZHIFANWEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_SHUZHIFANWEI_H__

namespace rg_volcano_base
{

class rg_ShuZhiFanWei : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_base, rg_ShuZhiFanWei)

public:
    inline_ rg_ShuZhiFanWei () { }
    inline_ void _VolObjectInitMembers () { }

public:
    static const INT rg_ZuiXiaoZhengShuZhi;
    static const INT rg_ZuiDaZhengShuZhi;
    static const INT64 rg_ZuiDaChangZhengShuZhi;
    static const DOUBLE rg_ZuiXiaoRiJiShiJianZhi;
    static const DOUBLE rg_ZuiDaRiJiShiJianZhi;
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_SHUZHIFANWEI_H__
