
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_APP_RG_CLASS_MCP_CUANGAIGUOLUQI_H__
#define __VCLS_RG_VOLCANO_APP_RG_CLASS_MCP_CUANGAIGUOLUQI_H__

namespace rg_volcano_app
{

class rg_class_MCP_CuanGaiGuoLuQi : public rg_FBrowser_ShiJianKongZhi::rg_class_FBrowser_zyglq
{
    DECLARE_VOL_CLASS (rg_volcano_app, rg_class_MCP_CuanGaiGuoLuQi)

public:
    virtual BOOL rg_ChuShiHuaGuoLuQi (INT64 rg_BiaoShiID7);
    virtual void rg_HuoQuShuJu (INT64 rg_BiaoShiID8, INT64 rg_ShuJuZhiZhen3, INT rg_ShuJuDaXiao3);
    virtual INT rg_XiuGaiShuJu (INT64 rg_BiaoShiID9, INT64 rg_ShuRuZhiZhen1, INT rg_ShuRuDaXiao1, rg_volcano_base::rg_ZhengShuLei& rg_ShuRuDouQuDaXiao1, INT64 rg_ShuChuZhiZhen2, INT rg_ShuChuDaXiao2, rg_volcano_base::rg_ZhengShuLei& rg_ShuChuXieRuDaXiao2);
    virtual void rg_JieShu1 (INT64 rg_BiaoShiID10);
    rg_class_MCP_CuanGaiGuoLuQi ();
    void _VolObjectInitMembers ();
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

public:
    CVolString rg_DongZuo;
    CVolString rg_SouSuoWenBen;
    CVolString rg_TiHuanWenBen;
    CVolString rg_WeiBuWenBen;
    CVolString rg_DaiShuChuWenBen;
    BOOL rg_XiuGaiYiFangQi;
    INT rg_HangTiHuanKaiShi;
    INT rg_HangTiHuanJieShu;

protected:
    BOOL rg_ShuChuDaiShuChuWenBen (INT64 rg_ShuChuZhiZhen1, INT rg_ShuChuDaXiao1, rg_volcano_base::rg_ZhengShuLei& rg_ShuChuXieRuDaXiao1);
    void rg_ZhuaiRuTouChuan (CVolString& rg_TouChuanWenBen, CVolString& rg_FangQiYuanYin);

protected:
    CVolMem rg_WeiBuZiJie;
    CVolMem rg_YuanShiShuJuHuanCun;
    INT rg_DangQianHangHao;
};

}

#endif  //__VCLS_RG_VOLCANO_APP_RG_CLASS_MCP_CUANGAIGUOLUQI_H__
