
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HUOSHANSHICHUANG_JSONZHICHI_RG_YYJSONGESHIHUAXUANXIANG_H__
#define __VCLS_RG_HUOSHANSHICHUANG_JSONZHICHI_RG_YYJSONGESHIHUAXUANXIANG_H__

namespace rg_HuoShanShiChuang_JSONZhiChi
{

class rg_YYJSONGeShiHuaXuanXiang : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_HuoShanShiChuang_JSONZhiChi, rg_YYJSONGeShiHuaXuanXiang)

public:
    inline_ rg_YYJSONGeShiHuaXuanXiang () { }
    inline_ void _VolObjectInitMembers () { }

public:
    static const INT rg_YaSu;
    static const INT rg_SuJin;
};

}

#endif  //__VCLS_RG_HUOSHANSHICHUANG_JSONZHICHI_RG_YYJSONGESHIHUAXUANXIANG_H__
