
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_APP_RG_CLASS_MCP_JSYIBUHUIDIAO_H__
#define __VCLS_RG_VOLCANO_APP_RG_CLASS_MCP_JSYIBUHUIDIAO_H__

namespace rg_volcano_app
{

class rg_class_MCP_JSYiBuHuiDiao : public rg_FBrowser_HuiDiao::rg_class_FBrowser_JSHuiDiao
{
    DECLARE_VOL_CLASS (rg_volcano_app, rg_class_MCP_JSYiBuHuiDiao)

public:
    virtual void rg_HuiDiao3 (rg_FBrowser_value::FBroListValue& rg_FanHuiJieGuo);
    inline_ rg_class_MCP_JSYiBuHuiDiao () { }
    inline_ void _VolObjectInitMembers () { }
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

public:
    CVolString rg_RenWuID;
};

}

#endif  //__VCLS_RG_VOLCANO_APP_RG_CLASS_MCP_JSYIBUHUIDIAO_H__
