
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_APP_RG_LIULANQIRONGQI_H__
#define __VCLS_RG_VOLCANO_APP_RG_LIULANQIRONGQI_H__

namespace rg_volcano_app
{

class rg_LiuLanQiRongQi : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_app, rg_LiuLanQiRongQi)

public:
    static void CALLBACK rg_ZhiJiaZaiZhuangTai (BOOL rg_value3);
    static BOOL CALLBACK rg_QuJiaZaiZhuangTai ();
    static void CALLBACK rg_ZhiZuiHouZaiRuJieShuHaoMiao (INT64 rg_value4);
    static INT64 CALLBACK rg_QuZuiHouZaiRuJieShuHaoMiao ();
    static void CALLBACK rg_ZhiZuiXinDeZhi (CVolString& rg_value5);
    static CVolString CALLBACK rg_QuZuiXinDeZhi ();
    static void CALLBACK rg_ZhiYeMianBiaoTi (CVolString& rg_value6);
    static CVolString CALLBACK rg_QuYeMianBiaoTi ();
    static void CALLBACK rg_ChongZhiHuanYingYeDaoHangZhuangTai ();
    static void CALLBACK rg_BiaoJiHuanYingYeDaoHangYiFaQi ();
    static void CALLBACK rg_BiaoJiXuYaoChongJianLiuLanQi ();
    static void CALLBACK rg_BiaoJiXuYaoHuiFuBuJu ();
    static void CALLBACK rg_HuiFuHuanYingYe ();
    static CVolString CALLBACK rg_QuHuanYingYeDeZhi ();
    static void CALLBACK rg_DaoHangHuanYingYeNeiBu ();
    static CVolString CALLBACK rg_QuHuanYingYeHTML ();
    inline_ rg_LiuLanQiRongQi () { }
    inline_ void _VolObjectInitMembers () { }

public:
    static CVolString rg_ZuiXinDeZhi;
    static CVolString rg_DangQianYeMianBiaoTi;
    static BOOL rg_YeMianJiaZaiZhong;
    static INT64 rg_ZuiHouZaiRuJieShuHaoMiao;
    static rg_volcano_base::rg_HuChiSuoLei rg_ZhuangTaiSuo;
    static CVolObjectArray rg_LiuLanQiShuZu;
    static CVolString rg_WangYeShuJu;
    static BOOL rg_MCPFuWuYiJiuXu;
    static BOOL rg_HuanYingYeYiDaoHang;
    static BOOL rg_HuanYingYeDaoHangYiFaQi;
    static INT64 rg_HuanYingYeDaoHangFaQiHaoMiao;
    static BOOL rg_XuYaoChongJianLiuLanQi;
    static BOOL rg_XuYaoHuiFuBuJu;
};

}

#endif  //__VCLS_RG_VOLCANO_APP_RG_LIULANQIRONGQI_H__
