
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_APP_RG_MCP_FUWUQIGONGJU_H__
#define __VCLS_RG_VOLCANO_APP_RG_MCP_FUWUQIGONGJU_H__

namespace rg_volcano_app
{

class rg_MCP_FuWuQiGongJu : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_app, rg_MCP_FuWuQiGongJu)

public:
    static INT CALLBACK rg_ZhengShuDaoTLSBanBen (INT rg_ZhengShuZhi);
    inline_ rg_MCP_FuWuQiGongJu () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_APP_RG_MCP_FUWUQIGONGJU_H__
