
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_LIULANQI_FBROIMAGE_H__
#define __VCLS_RG_FBROWSER_LIULANQI_FBROIMAGE_H__

namespace rg_FBrowser_LiuLanQi
{

class FBroImage : public CVolObject
{
    DECLARE_VOL_CLASS (rg_FBrowser_LiuLanQi, FBroImage)

public:
    CefRefPtr<CefImage> m_class;
    inline_ FBroImage (CefRefPtr<CefImage> object) : FBroImage () { m_class = object; }
    inline_ void _CopySelfFromExtra (const FBroImage& objCopyFrom) { m_class = objCopyFrom.m_class; }
    inline_ BOOL _IsSelfEqualExtra (const FBroImage& objCompare) const { return (m_class.get () == objCompare.m_class.get ()); }
    inline_ BOOL IsEmpty () const { return m_class.get () == nullptr; }
    inline_ void Set (CefRefPtr<CefImage> object) { m_class = object; }
    ~FBroImage(){};

public:
    BOOL rg_ShiFouWeiKong131 ();
    BOOL rg_QuTuPianXinXi (DOUBLE rg_BiLiYinZi, rg_volcano_base::rg_XiaoShuLei& rg_ShiJiBiLi1, rg_volcano_base::rg_ZhengShuLei& rg_KuanDu15, rg_volcano_base::rg_ZhengShuLei& rg_GaoDu15);
    rg_FBrowser_value::FBroBinaryValue rg_QuTuPianShuJu_PNG (DOUBLE rg_BiLiYinZi3, INT rg_TouMing, rg_volcano_base::rg_ZhengShuLei& rg_KuanDu18, rg_volcano_base::rg_ZhengShuLei& rg_GaoDu18);
    inline_ FBroImage () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_FBROWSER_LIULANQI_FBROIMAGE_H__
