
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_APP_RG_MCPFUWUCHUANGKOU_H__
#define __VCLS_RG_VOLCANO_APP_RG_MCPFUWUCHUANGKOU_H__

namespace rg_volcano_app
{

class rg_MCPFuWuChuangKou : public rg_volcano_MFCJieMian_base::CVolWinForm
{
    DECLARE_VOL_CLASS (rg_volcano_app, rg_MCPFuWuChuangKou)

public:

    virtual INT GetDesignClientWidth () const override  {  return _DPISIZE (280);  }
    virtual INT GetDesignClientHeight () const override  {  return _DPISIZE (60);  }

    static void CALLBACK rg_ZhiHangGuanBiXuLie ();
    rg_MCPFuWuChuangKou ();
    void _VolObjectInitMembers ();
    virtual ~rg_MCPFuWuChuangKou ();
    virtual void OnWinContainerCreated () override;
    virtual void _VolAttachWinEvents ();
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

public:
    static INT re_MCPFuWuChuangKou_timer_ZhouJiShiJian (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber)
    {
        return ((rg_MCPFuWuChuangKou*)pobjEventReceiver)->rg_timer_ZhouJiShiJian ((rg_volcano_MFCJieMian_base::rg_timer&)*pobjEventSource, nTagNumber);
    }
    static INT re_MCPFuWuChuangKou_MCPFuWuChuangKou_ChuangJianWanBi (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber)
    {
        return ((rg_MCPFuWuChuangKou*)pobjEventReceiver)->rg_MCPFuWuChuangKou_ChuangJianWanBi ((rg_MCPFuWuChuangKou&)*pobjEventSource, nTagNumber);
    }
    static INT re_MCPFuWuChuangKou_MCPFuWuChuangKou_JiangBeiXiaoHui (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber)
    {
        return ((rg_MCPFuWuChuangKou*)pobjEventReceiver)->rg_MCPFuWuChuangKou_JiangBeiXiaoHui ((rg_MCPFuWuChuangKou&)*pobjEventSource, nTagNumber);
    }

protected:
    INT rg_MCPFuWuChuangKou_ChuangJianWanBi (rg_MCPFuWuChuangKou& rg_LaiYuanDuiXiang, INT rg_BiaoJiZhi);
    INT rg_timer_ZhouJiShiJian (rg_volcano_MFCJieMian_base::rg_timer& rg_LaiYuanDuiXiang1, INT rg_BiaoJiZhi1);
    INT rg_MCPFuWuChuangKou_JiangBeiXiaoHui (rg_MCPFuWuChuangKou& rg_LaiYuanDuiXiang2, INT rg_BiaoJiZhi2);

protected:
    rg_volcano_MFCJieMian_base::rg_label rg_ZhuangTaiBiaoQian;
    rg_volcano_MFCJieMian_base::rg_timer rg_WeiHuShiZhong;
    static BOOL rg_ZhengZaiTuiChu;
    CVolEventObjectPointer* rw_43;
};

}

#endif  //__VCLS_RG_VOLCANO_APP_RG_MCPFUWUCHUANGKOU_H__
