
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_LIULANQI_RG_CLASS_FBROWSER_SHJZHNZHZH_H__
#define __VCLS_RG_FBROWSER_LIULANQI_RG_CLASS_FBROWSER_SHJZHNZHZH_H__

namespace rg_FBrowser_LiuLanQi
{

class rg_class_FBrowser_shjzhnzhzh : public CVolObject
{
    DECLARE_VOL_CLASS (rg_FBrowser_LiuLanQi, rg_class_FBrowser_shjzhnzhzh)

public:
CefRefPtr<FBroBaseEvent> m_class = nullptr;
inline_ rg_class_FBrowser_shjzhnzhzh (CefRefPtr<FBroBaseEvent> object) : rg_class_FBrowser_shjzhnzhzh () { m_class = object; }
inline_ void _CopySelfFromExtra (const rg_class_FBrowser_shjzhnzhzh& objCopyFrom) { m_class = objCopyFrom.m_class; }
inline_ BOOL _IsSelfEqualExtra (const rg_class_FBrowser_shjzhnzhzh& objCompare) const { return (m_class.get () == objCompare.m_class.get ()); }
FBroBaseEvent* GetPtr(){return m_class.get();};

public:
    inline_ rg_class_FBrowser_shjzhnzhzh () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_FBROWSER_LIULANQI_RG_CLASS_FBROWSER_SHJZHNZHZH_H__
