
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_FBROWSER_SHUJULEIXING_RG_FBROWSER_ANJIANSHIJIAN_H__
#define __VCLS_RG_FBROWSER_SHUJULEIXING_RG_FBROWSER_ANJIANSHIJIAN_H__

namespace rg_FBrowser_ShuJuLeiXing
{

class rg_FBrowser_AnJianShiJian : public CVolObject
{
    DECLARE_VOL_CLASS (rg_FBrowser_ShuJuLeiXing, rg_FBrowser_AnJianShiJian)

public:
    ~rg_FBrowser_AnJianShiJian(){}
    rg_FBrowser_AnJianShiJian (E_KEYEVENT data) : rg_FBrowser_AnJianShiJian () {
      m_data = data;
      ToHsData();
    }
    PTELIB_KEYEVENT ToFBroData();
    void ToHsData();
    E_KEYEVENT m_data;

public:
    rg_FBrowser_AnJianShiJian ();
    void _VolObjectInitMembers ();
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

public:
    INT rg_LeiXing2;
    INT rg_XiuShiWei1;
    INT rg_JiTongAnJian;
    INT rg_JiQiAnJian;
    INT rg_ShiFouJiTongAnJian;
    TCHAR rg_ZiFuZhi;
    TCHAR rg_XiuGaiZiFu;
    INT rg_ShiFouKeBianJi;
};

}

#endif  //__VCLS_RG_FBROWSER_SHUJULEIXING_RG_FBROWSER_ANJIANSHIJIAN_H__
