
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

namespace rg_volcano_app
{

CVolString CALLBACK rg_MCPStdioQiao::rg_DouQuYiHang (INT64 rg_XianChengGouBing)
{
    CVolMem rg_HangZiJieJi;
    *(volatile BOOL*)&rg_ShangCiDouQuWeiDuanKai = FALSE;
    HANDLE hStdin = GetStdHandle(STD_INPUT_HANDLE);
    if (hStdin == INVALID_HANDLE_VALUE || hStdin == NULL) { *(volatile BOOL*)&rg_ShangCiDouQuWeiDuanKai = TRUE; return CVolString(); }
    const bool isPipe = (GetFileType(hStdin) == FILE_TYPE_PIPE);
    DWORD emptyPolls = 0;
    std::string headLine;
    for (;;) {
        if (*(volatile BOOL*)&rg_StdioYingTuiChu) return CVolString();
        if (rg_XianChengGouBing != 0 && g_objVolApp.GetThreadPool().IsThreadNeedBreak((HVOLTHREAD)rg_XianChengGouBing, 0))
            return CVolString();
        DWORD avail = 0;
        if (isPipe) { if (!PeekNamedPipe(hStdin, NULL, 0, NULL, &avail, NULL)) { *(volatile BOOL*)&rg_ShangCiDouQuWeiDuanKai = TRUE; break; } }
        else { avail = 1; }
        if (isPipe && avail == 0) { Sleep(50); continue; }
        emptyPolls = 0;
        DWORD headLen = 0;
        bool gotNewline = false;
        bool headFailed = false;
        DWORD headEmptyPolls = 0;
        while (headLen < 1048576) {
            if (*(volatile BOOL*)&rg_StdioYingTuiChu) return CVolString();
            if (rg_XianChengGouBing != 0 && g_objVolApp.GetThreadPool().IsThreadNeedBreak((HVOLTHREAD)rg_XianChengGouBing, 0))
                return CVolString();
            DWORD availH = 0;
            if (isPipe) { if (!PeekNamedPipe(hStdin, NULL, 0, NULL, &availH, NULL)) { headFailed = true; *(volatile BOOL*)&rg_ShangCiDouQuWeiDuanKai = TRUE; break; } }
            else { availH = 1; }
            if (isPipe && availH == 0) { if (++headEmptyPolls > 1200) { headFailed = true; break; } Sleep(50); continue; }
            headEmptyPolls = 0;
            char c; DWORD n = 0;
            if (!ReadFile(hStdin, &c, 1, &n, NULL) || n == 0) { headFailed = true; *(volatile BOOL*)&rg_ShangCiDouQuWeiDuanKai = TRUE; break; }
            if (c == '\n') { gotNewline = true; break; }
            if (c != '\r') headLine += c;
            headLen++;
        }
        if (headFailed) break;
        if (headLine.empty()) { Sleep(50); continue; }
        long contentLen = -1;
        if (strncmp(headLine.c_str(), "Content-Length:", 15) == 0)
            contentLen = atol(headLine.c_str() + 15);
        if (contentLen > 67108864) {
            fprintf(stderr, "[MCP-Stdio] Content-Length %ld 超过64MB上限, 拒绝并排空该帧\n", contentLen);
            long toDiscard = contentLen;
            if (toDiscard > 67108864) toDiscard = 67108864;
            while (toDiscard > 0) {
                if (*(volatile BOOL*)&rg_StdioYingTuiChu) return CVolString();
                DWORD avail5 = 0;
                if (isPipe) { if (!PeekNamedPipe(hStdin, NULL, 0, NULL, &avail5, NULL)) break; }
                else { avail5 = 1; }
                if (isPipe && avail5 == 0) { if (++emptyPolls > 600) break; Sleep(20); continue; }
                emptyPolls = 0;
                char tmpD[4096];
                DWORD n5 = 0;
                DWORD toRead = (DWORD)(toDiscard > 4096 ? 4096 : toDiscard);
                if (!ReadFile(hStdin, tmpD, toRead, &n5, NULL) || n5 == 0) break;
                toDiscard -= n5;
            }
            break;
        }
        if (contentLen < 0) {
            rg_HangZiJieJi.CopyFrom(headLine.data(), (INT_P)headLine.size());
            break;
        }
        std::string body;
        body.reserve((size_t)contentLen);
        if (gotNewline) {
            bool sepDone = false;
            while (!sepDone) {
                if (*(volatile BOOL*)&rg_StdioYingTuiChu) return CVolString();
                if (rg_XianChengGouBing != 0 && g_objVolApp.GetThreadPool().IsThreadNeedBreak((HVOLTHREAD)rg_XianChengGouBing, 0))
                    return CVolString();
                DWORD avail2 = 0;
                if (isPipe) { if (!PeekNamedPipe(hStdin, NULL, 0, NULL, &avail2, NULL)) { *(volatile BOOL*)&rg_ShangCiDouQuWeiDuanKai = TRUE; sepDone = true; break; } }
                else { avail2 = 1; }
                if (isPipe && avail2 == 0) { if (++headEmptyPolls > 1200) { sepDone = true; break; } Sleep(50); continue; }
                headEmptyPolls = 0;
                char c0; DWORD n0 = 0;
                if (!ReadFile(hStdin, &c0, 1, &n0, NULL) || n0 == 0) { *(volatile BOOL*)&rg_ShangCiDouQuWeiDuanKai = TRUE; sepDone = true; break; }
                if (c0 == '\r') {
                    bool c1Done = false;
                    while (!c1Done) {
                        if (*(volatile BOOL*)&rg_StdioYingTuiChu) return CVolString();
                        if (rg_XianChengGouBing != 0 && g_objVolApp.GetThreadPool().IsThreadNeedBreak((HVOLTHREAD)rg_XianChengGouBing, 0))
                            return CVolString();
                        DWORD avail2b = 0;
                        if (isPipe) { if (!PeekNamedPipe(hStdin, NULL, 0, NULL, &avail2b, NULL)) { *(volatile BOOL*)&rg_ShangCiDouQuWeiDuanKai = TRUE; body += c0; c1Done = true; break; } }
                        else { avail2b = 1; }
                        if (isPipe && avail2b == 0) { if (++headEmptyPolls > 1200) { body += c0; c1Done = true; break; } Sleep(50); continue; }
                        headEmptyPolls = 0;
                        char c1; DWORD n1 = 0;
                        if (!ReadFile(hStdin, &c1, 1, &n1, NULL) || n1 == 0) { *(volatile BOOL*)&rg_ShangCiDouQuWeiDuanKai = TRUE; body += c0; c1Done = true; break; }
                        if (c1 == '\n') { sepDone = true; c1Done = true; }
                        else { body += c0; body += c1; sepDone = true; c1Done = true; }
                    }
                } else if (c0 == '\n') {
                    sepDone = true;
                } else {
                    body += c0; sepDone = true;
                }
            }
        }
        while ((long)body.size() < contentLen) {
            if (*(volatile BOOL*)&rg_StdioYingTuiChu) return CVolString();
            if (rg_XianChengGouBing != 0 && g_objVolApp.GetThreadPool().IsThreadNeedBreak((HVOLTHREAD)rg_XianChengGouBing, 0))
                return CVolString();
            DWORD avail3 = 0;
            if (isPipe) { if (!PeekNamedPipe(hStdin, NULL, 0, NULL, &avail3, NULL)) break; }
            else { avail3 = 1; }
            if (isPipe && avail3 == 0) { if (++emptyPolls > 600) break; Sleep(20); continue; }
            emptyPolls = 0;
            char tmpB[4096];
            DWORD n3 = 0;
            DWORD toRead = (DWORD)min((size_t)(contentLen - (long)body.size()), (size_t)4096);
            if (!ReadFile(hStdin, tmpB, toRead, &n3, NULL) || n3 == 0) break;
            body.append(tmpB, n3);
        }
        if ((long)body.size() < contentLen) {
            fprintf(stderr, "[MCP-Stdio] 帧体不完整(已读%ld/%ld字节), 丢弃本帧\n", (long)body.size(), contentLen);
            break;
        }
        rg_HangZiJieJi.CopyFrom(body.data(), (INT_P)body.size());
        break;
    }
    if ((INT)rg_HangZiJieJi.GetSize () == 0)
    {
        return (_T (""));
    }
    return (rg_volcano_base::rg_WenBenLei::rg_UTF8DaoWenBen (rg_HangZiJieJi));
}

void CALLBACK rg_MCPStdioQiao::rg_XieRuYiHang (CVolString& rg_string4)
{
    std::string utf8 = CU8String(rg_string4.GetText()).GetText();
    DWORD contentLen = (DWORD)utf8.size();
    char header[128];
    int headerLen = snprintf(header, sizeof(header), "Content-Length: %lu\r\n\r\n", (unsigned long)contentLen);
    std::string frame(header, headerLen);
    frame += utf8;
    HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);
    if (hOut == INVALID_HANDLE_VALUE || hOut == NULL) return;
    const char* wp = frame.c_str();
    DWORD wleft = (DWORD)frame.size();
    while (wleft > 0) {
        DWORD written = 0;
        if (!WriteFile(hOut, wp, wleft, &written, NULL)) {
            *(volatile BOOL*)&rg_StdioYingTuiChu = TRUE;
            HANDLE hErr = GetStdHandle(STD_ERROR_HANDLE);
            if (hErr != INVALID_HANDLE_VALUE && hErr != NULL)
            {
                const char* err = "[MCP-Stdio] stdout写入失败, 服务即将退出\n";
                DWORD ew = 0;
                WriteFile(hErr, err, (DWORD)strlen(err), &ew, NULL);
            }
            break;
        }
        if (written == 0) break;
        wp += written;
        wleft -= written;
    }
}

void CALLBACK rg_MCPStdioQiao::rg_XieRiZhi (CVolString& rg_string5)
{
    std::string msg = "[MCP-Stdio] ";
    msg += CU8String(rg_string5.GetText()).GetText();
    msg += "\n";
    HANDLE hErr = GetStdHandle(STD_ERROR_HANDLE);
    if (hErr == INVALID_HANDLE_VALUE || hErr == NULL) return;
    DWORD written = 0;
    WriteFile(hErr, msg.c_str(), (DWORD)msg.size(), &written, NULL);
}

BOOL CALLBACK rg_MCPStdioQiao::rg_ShiFouWeiStdioMoShi ()
{
    rg_volcano_base::rg_WenBenShuZuLei rg_MingLingHangShuZu;
    GetCommandLineArray (rg_MingLingHangShuZu.data ());
    INT rg_count5;
    rg_count5 = (INT)rg_MingLingHangShuZu.data ().GetCount ();
    for (INT_P __vol_counter_index = 0; __vol_counter_index < rg_count5; __vol_counter_index++)
    {
        CVolString rg_arg;
        rg_arg = CVolString (rg_MingLingHangShuZu.data ().GetAt ((INT)__vol_counter_index));
        if (rg_arg == _T ("--mcp-stdio") || rg_arg == _T ("--stdio") || rg_arg == _T ("--headless"))
        {
            return (TRUE);
        }
    }
    return (FALSE);
}

void CALLBACK rg_MCPStdioQiao::rg_YunHangStdioZhuXunHuan (INT64 rg_XianChengGouBing1)
{
    rg_XieRiZhi (_CT2 (_T ("============================================")));
    rg_XieRiZhi (_CT2 (_T ("AI浏览器 MCP Stdio Server 启动")));
    rg_XieRiZhi (_CT2 (_T ("协议: JSON-RPC 2.0 over stdin/stdout (Content-Length 帧格式)")));
    rg_XieRiZhi (_CT2 (_T ("直连: Claude Desktop / Cursor / Trace 等任意AI工具")));
    rg_XieRiZhi (_CT2 (_T ("============================================")));
    INT rg_KongDouCiShu = 0;
    do
    {
        if (rg_StdioYingTuiChu)
        {
            break;
        }
        if (rg_XianChengGouBing1 != 0 && (BOOL)g_objVolApp.GetThreadPool ().IsThreadNeedBreak (rg_XianChengGouBing1, 10))
        {
            break;
        }
        CVolString rg_QingQiuJSON2;
        rg_QingQiuJSON2 = rg_DouQuYiHang (rg_XianChengGouBing1);
        if (rg_QingQiuJSON2 == _T (""))
        {
            if (rg_StdioYingTuiChu || rg_XianChengGouBing1 != 0 && (BOOL)g_objVolApp.GetThreadPool ().IsThreadNeedBreak (rg_XianChengGouBing1, 10))
            {
                break;
            }
            if (rg_ShangCiDouQuWeiDuanKai)
            {
                rg_KongDouCiShu = rg_KongDouCiShu + 1;
            }
            if (rg_KongDouCiShu >= 3)
            {
                rg_XieRiZhi (_CT2 (_T ("stdin已断开(父进程退出), stdio服务自动停止")));
                rg_StdioYingTuiChu = TRUE;
                break;
            }
            continue;
        }
        rg_KongDouCiShu = 0;
        if ((INT)rg_QingQiuJSON2.GetLength () > 200)
        {
            rg_XieRiZhi (_CT2 (_T ("收到命令: ")) + rg_QingQiuJSON2.Left (200) + _T ("...(") + CVolString ((INT)rg_QingQiuJSON2.GetLength ()) + _T ("字符)"));
        }
        else
        {
            rg_XieRiZhi (_CT2 (_T ("收到命令: ")) + rg_QingQiuJSON2);
        }
        CVolString rg_XiangYingJSON5;
        rg_XiangYingJSON5 = rg_MCPMingLingFuWuQi::rg_ChuLiMCPQingQiu (rg_QingQiuJSON2, _CT2 (_T ("stdio")));
        if (rg_XiangYingJSON5 != _T (""))
        {
            rg_XieRuYiHang (rg_XiangYingJSON5);
        }
    }
    while (TRUE);
    rg_XieRiZhi (_CT2 (_T ("MCP Stdio Server 停止")));
}

void CALLBACK rg_MCPStdioQiao::rg_QiDongBingHangStdioFuWu ()
{
    if ((BOOL)g_objVolApp.GetThreadPool ().IsThreadRunning (rg_StdioXianChengShiLi.data ().m_hThreadHandle) || rg_MCPMingLingFuWuQi::rg_MCPZhengZaiGuanBi)
    {
        return;
    }
    rg_StdioYingTuiChu = FALSE;
    rg_StdioXianChengShiLi.rg_QiDong2 (0);
}

void CALLBACK rg_MCPStdioQiao::rg_TingZhiStdioFuWu ()
{
    rg_StdioYingTuiChu = TRUE;
    if ((BOOL)g_objVolApp.GetThreadPool ().IsThreadRunning (rg_StdioXianChengShiLi.data ().m_hThreadHandle))
    {
        INT rg_TingZhiLunXunCiShu = 0;
        while ((BOOL)g_objVolApp.GetThreadPool ().IsThreadRunning (rg_StdioXianChengShiLi.data ().m_hThreadHandle) && rg_TingZhiLunXunCiShu < 30)
        {
            rg_TingZhiLunXunCiShu = rg_TingZhiLunXunCiShu + 1;
            Sleep(100);
        }
        if ((BOOL)g_objVolApp.GetThreadPool ().IsThreadRunning (rg_StdioXianChengShiLi.data ().m_hThreadHandle))
        {
            rg_XieRiZhi (_CT2 (_T ("停止超时(线程可能卡在长调用), 放弃等待, 由进程退出强制终止")));
        }
    }
}

rg_class_MCP_StdioFuWuXianCheng::rg_class_MCP_StdioFuWuXianCheng ()
{
    _VolObjectInitMembers ();
}

void rg_class_MCP_StdioFuWuXianCheng::_VolObjectInitMembers ()
{
    rw_2 = new CVolEventObjectPointer (this);
    ra_HuanCunXianChengLei_XianChengYunHang1 ((VOID_FUNC)re_class_MCP_StdioFuWuXianCheng_HuanCunXianChengLei_XianChengYunHang, rw_2, 0);
}

rg_class_MCP_StdioFuWuXianCheng::~rg_class_MCP_StdioFuWuXianCheng ()
{
    OnBeforeObjectCleanup ();
    rw_2->ReleasePointer ();
}

INT rg_class_MCP_StdioFuWuXianCheng::rg_HuanCunXianChengLei_XianChengYunHang (rg_volcano_base::rg_HuanCunXianChengLei& rg_LaiYuanDuiXiang, INT rg_BiaoJiZhi, INT64 rg_XianChengGouBing2, INT64 rg_YongHuCanShu, INT64 rg_TuiChuShiJian)
{
    rg_MCPStdioQiao::rg_YunHangStdioZhuXunHuan (rg_XianChengGouBing2);
    return (0);
}

}
