
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

namespace rg_volcano_base
{

CVolMem CALLBACK rg_WenBenLei::rg_WenBenDaoUTF (CVolString& rg_SuoYuCaoZuoDeWenBen5, BOOL rg_ShiFouBaoGuaJieShuLingZiFu)
{
    CU8String u8str (rg_SuoYuCaoZuoDeWenBen5.GetText ());
    const U8CHAR* ps = u8str.GetText ();
    return CVolMem (ps, (strlen (ps) + (rg_ShiFouBaoGuaJieShuLingZiFu ? 1 : 0)) * sizeof (CHAR));
}

CVolString CALLBACK rg_WenBenLei::rg_UTF8DaoWenBen (CVolMem& rg_SuoYuZhuaiHuanDeUTF8WenBenShuJu)
{
    CVolMem memBuf (rg_SuoYuZhuaiHuanDeUTF8WenBenShuJu);
    memBuf.AddDWord (0);
    return CVolString ((const CHAR*)memBuf.GetPtr ());
}

CVolString CALLBACK rg_WenBenLei::rg_ZiJieJiDaoWenBen (CVolMem& rg_SuoYuZhuaiHuanDeWenBenShuJu1)
{
    CVolMem memBuf (rg_SuoYuZhuaiHuanDeWenBenShuJu1);
    memBuf.AddDWord (0);
    return CVolString (memBuf.GetTextPtr ());
}

}
