#pragma once
#ifndef FBROWSER_HOOKEVENT_H_
#define FBROWSER_HOOKEVENT_H_

#ifdef _FBROELIB

extern FinishShutdown_Callback pfnFinishShutdown;
extern OnClearData_callback pfnOnClearData;
extern OnContextInitialized_callback pfnOnContextInitialized;
extern OnBeforeCommandLineProcessing_callback pfnOnBeforeCommandLineProcessing;

//浏览器进程中执行
extern OnAfterCreated_callback pfnOnAfterCreated;
extern OnBeforeBrowse_callback pfnOnBeforeBrowse;
extern OnBeforeClose_callback pfnOnBeforeClose;
extern OnAddressChange_callback pfnOnAddressChange;
extern OnTitleChange_callback pfnOnTitleChange;
extern OnTooltip_callback pfnOnTooltip;
extern OnStatusMessage_callback pfnOnStatusMessage;
extern OnFaviconURLChange_callback pfnOnFaviconURLChange;
extern OnFullscreenModeChange_callback pfnOnFullscreenModeChange;
extern OnBeforePopup_callback pfnOnBeforePopup;
extern DoClose_callback pfnDoClose;
extern OnConsoleMessage_callback pfnOnConsoleMessage;
extern OnAutoResize_callback pfnOnAutoResize;
extern OnLoadingProgressChange_callback pfnOnLoadingProgressChange;
extern OnBeforeResourceLoad_callback pfnOnBeforeResourceLoad;
extern OnResourceRedirect_callback pfnOnResourceRedirect;
extern OnResourceResponse_callback pfnOnResourceResponse;
extern OnResourceLoadComplete_callback pfnOnResourceLoadComplete;
extern OnProtocolExecution_callback pfnOnProtocolExecution;
extern OnOpenURLFromTab_callback pfnOnOpenURLFromTab;//从标签打开URL
extern OnQuotaRequest_callback pfnOnQuotaRequest;//JS请求存储配额
extern OnCertificateError_callback pfnOnCertificateError;//证书错误

extern OnPluginCrashed_callback  pfnOnPluginCrashed; //插件意外崩溃  
extern OnRenderViewReady_callback pfnOnRenderViewReady;//渲染视图 
extern OnRenderProcessTerminated_callback pfnOnRenderProcessTerminated;

extern OnLoadingStateChange_callback pfnOnLoadingStateChange; //读取状态改变
extern OnLoadStart_callback pfnOnLoadStart;              //开始读取
extern OnLoadEnd_callback pfnOnLoadEnd;             //读取完毕
extern OnLoadError_callback pfnOnLoadError;    //读取错误

extern OnProcessMessageReceived_callback pfnOnProcessMessageReceived;

extern OnBeforeContextMenu_callback pfnOnBeforeContextMenu;
extern RunContextMenu_callback pfnRunContextMenu;
extern OnContextMenuCommand_callback pfnOnContextMenuCommand;
extern OnContextMenuDismissed_callback pfnOnContextMenuDismissed;


extern OnBeforeDownload_callback pfnOnBeforeDownload;
extern OnDownloadUpdated_callback pfnOnDownloadUpdated;

extern OnPreKeyEvent_callback pfnOnPreKeyEvent;
extern OnKeyEvent_callback pfnOnKeyEvent;
extern OnFileDialog_callback pfnOnFileDialog;

extern OnJSDialog_callback pfnOnJSDialog;
extern OnBeforeUnloadDialog_callback pfnOnBeforeUnloadDialog;
extern OnResetDialogState_callback pfnOnResetDialogState;
extern OnDialogClosed_callback pfnOnDialogClosed;
extern OnTakeFocus_callback pfnOnTakeFocus;
extern OnSetFocus_callback pfnOnSetFocus;
extern OnGotFocus_callback pfnOnGotFocus;
extern OnFindResult_callback pfnOnFindResult;
extern GetAuthCredentials_callback pfnGetAuthCredentials;
extern OnDragEnter_callback pfnOnDragEnter;
extern OnDraggableRegionsChanged_callback pfnOnDraggableRegionsChanged;
extern GetResourceResponseFilter_callback pfnGetResourceResponseFilter;

//渲染进程中执行
extern OnBrowserCreated_callback pfnOnBrowserCreated;  //浏览器创建,渲染进程中执行
extern FBroApp_OnProcessMessageReceived_callback pfnFBroApp_OnProcessMessageReceived;  //收到消息

//离屏渲染事件
extern GetRootScreenRect_callback pfnGetRootScreenRect;
extern GetViewRect_callback pfnGetViewRect;
extern GetScreenPoint_callback pfnGetScreenPoint;
extern GetScreenInfo_callback pfnGetScreenInfo;
extern OnPopupShow_callback pfnOnPopupShow;
extern OnPopupSize_callback pfnOnPopupSize;
extern OnPaint_callback pfnOnPaint;
extern OnAcceleratedPaint_callback pfnOnAcceleratedPaint;
extern OnCursorChange_callback pfnOnCursorChange;
extern StartDragging_callback pfnStartDragging;
extern UpdateDragCursor_callback pfnUpdateDragCursor;
extern OnScrollOffsetChanged_callback pfnOnScrollOffsetChanged;
extern OnImeCompositionRangeChanged_callback pfnOnImeCompositionRangeChanged;
extern OnTextSelectionChanged_callback pfnOnTextSelectionChanged;
extern OnVirtualKeyboardRequested_callback pfnOnVirtualKeyboardRequested;


extern GetResourceHandler_callback pfnGetResourceHandler;
extern ResourceHandler_Open_callback pfnResourceHandler_Open;
extern ResourceHandler_ProcessRequest_callback pfnResourceHandler_ProcessRequest;
extern ResourceHandler_GetResponseHeaders_callback pfnResourceHandler_GetResponseHeaders;
extern ResourceHandler_Skip_callback pfnResourceHandler_Skip;
extern ResourceHandler_Read_callback pfnResourceHandler_Read;
extern ResourceHandler_Cancel_callback pfnResourceHandler_Cancel;


extern OnRegisterCustomSchemes_callback pfnOnRegisterCustomSchemes;
extern OnBeforeChildProcessLaunch_callback pfnOnBeforeChildProcessLaunch;
extern OnRenderProcessThreadCreated_callback pfnOnRenderProcessThreadCreated;
extern OnScheduleMessagePumpWork_callback pfnOnScheduleMessagePumpWork;
extern OnRenderThreadCreated_callback pfnOnRenderThreadCreated;
extern OnWebKitInitialized_callback pfnOnWebKitInitialized;
extern OnBrowserDestroyed_callback pfnOnBrowserDestroyed;
extern OnContextCreated_callback pfnOnContextCreated;
extern OnContextReleased_callback pfnOnContextReleased;
extern OnUncaughtException_callback pfnOnUncaughtException;
extern OnFocusedNodeChanged_callback pfnOnFocusedNodeChanged;


extern Render_OnLoadingStateChange_callback Render_pfnOnLoadingStateChange;
extern Render_OnLoadStart_callback Render_pfnOnLoadStart;
extern Render_OnLoadEnd_callback Render_pfnOnLoadEnd;
extern Render_OnLoadError_callback Render_pfnOnLoadError;

extern Extension_OnExtensionLoadFailedMessage_callback Extension_pfnOnExtensionLoadFailedMessage;
extern Extension_OnExtensionLoadFailed_callback Extension_pfnOnExtensionLoadFailed;
extern Extension_OnExtensionLoaded_callback Extension_pfnOnExtensionLoaded;
extern Extension_OnExtensionUnloaded_callback Extension_pfnOnExtensionUnloaded;
extern Extension_OnBeforeBackgroundBrowser_callback Extension_pfnOnBeforeBackgroundBrowser;
extern Extension_OnBeforeBrowser_callback Extension_pfnOnBeforeBrowser;
extern Extension_GetActiveBrowser_callback Extension_pfnGetActiveBrowser;
extern Extension_CanAccessBrowser_callback Extension_pfnCanAccessBrowser;
extern Extension_GetExtensionResource_callback Extension_pfnGetExtensionResource;

extern Extension_GetDefaultTabBrowser_callback Extension_pfnGetDefaultTabBrowser;

extern ExtensionClient_OnConsoleMessage_callback ExtensionClient_pfnOnConsoleMessage;
extern ExtensionClient_OnAfterCreated_callback ExtensionClient_pfnOnAfterCreated;
extern ExtensionClient_OnBeforePopup_callback ExtensionClient_pfnOnBeforePopup;
extern ExtensionClient_DoClose_callback ExtensionClient_pfnDoClose;
extern ExtensionClient_OnBeforeClose_callback ExtensionClient_pfnOnBeforeClose;

extern Render_OnWebSocketCreate_callback Render_pfnOnWebSocketCreate;
extern Render_OnWebSocketClose_callback Render_pfnOnWebSocketClose;
extern Render_OnWebSocketConnect_callback Render_pfnOnWebSocketConnect;
extern Render_OnWebSocketSendText_callback Render_pfnOnWebSocketSendText;
extern Render_OnWebSocketSendData_callback Render_pfnOnWebSocketSendData;
extern Render_OnWebSocketMessage_callback Render_pfnOnWebSocketMessage;


extern Message_ReceiveRenderProcessMessage Message_pfnReceiveRenderProcessMessage;
extern Message_ReceiveMainProcessMessage Message_pfnReceiveMainProcessMessage;


//20220825新内核增加事件
extern OnDocumentAvailableInMainFrame_callback pfnOnDocumentAvailableInMainFrame;
extern OnMediaAccessChange_callback pfnOnMediaAccessChange;
extern RunQuickMenu_callback pfnRunQuickMenu;
extern OnQuickMenuCommand_callback pfnOnQuickMenuCommand;
extern OnQuickMenuDismissed_callback pfnOnQuickMenuDismissed;
extern CanDownload_callback pfnCanDownload;
extern GetAudioParameters_callback pfnGetAudioParameters;
extern OnAudioStreamStarted_callback pfnOnAudioStreamStarted;
extern OnAudioStreamPacket_callback pfnOnAudioStreamPacket;
extern OnAudioStreamStopped_callback pfnOnAudioStreamStopped;
extern OnAudioStreamError_callback pfnOnAudioStreamError;
extern OnChromeCommand_callback pfnOnChromeCommand;
extern OnFrameCreated_callback pfnOnFrameCreated;
extern OnFrameAttached_callback pfnOnFrameAttached;
extern OnFrameDetached_callback pfnOnFrameDetached;
extern OnMainFrameChanged_callback pfnOnMainFrameChanged;
extern OnRequestMediaAccessPermission_callback pfnOnRequestMediaAccessPermission;
extern OnShowPermissionPrompt_callback pfnOnShowPermissionPrompt;
extern OnDismissPermissionPrompt_callback pfnOnDismissPermissionPrompt;



extern URLRequest_Start_callback pfnURLRequestStart;
extern URLRequest_End_callback pfnURLRequestEnd;
extern URLRequest_OnRequestComplete_callback pfnURLRequestOnRequestComplete;
extern URLRequest_OnUploadProgress_callback pfnURLRequestOnUploadProgress;
extern URLRequest_OnDownloadProgress_callback pfnURLRequestOnDownloadProgress;
extern URLRequest_OnDownloadData_callback pfnURLRequestOnDownloadData;
extern URLRequest_GetAuthCredentials_callback pfnURLRequestGetAuthCredentials;



// 135内核后新加的APP事件
extern OnGetDefaultClient_callback pfnOnGetDefaultClient;

extern OnBeforePopupAborted_callback pfnOnBeforePopupAborted;
extern OnBeforeDevToolsPopup_callback pfnOnBeforeDevToolsPopup;

// my add 20260512 插件创建成功的事件
extern OnCreateExtension_Callback pfnOnCreateExtension;

// my add 20260512 插件创建失败的事件
extern OnCreateExtensionError_Callback pfnOnCreateExtensionError;

// my add 20260512 添加插件
extern OnAddExtension_Callback pfnOnAddExtension;

// my add 20260512 移除插件
extern OnRemoveExtension_Callback pfnOnRemoveExtension;


// 135内核后新加APP事件
extern OnRequestContextInitialized_Callback pfnOnRequestContextInitialized;

#endif

#endif